// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: mail

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilMail = (*Mail)(nil)

var (
	_ bun.BeforeInsertHook = (*Mail)(nil)
	_ bun.BeforeUpdateHook = (*Mail)(nil)
)

const MailTableName = "mail"

var MailTableNameIdent  = bun.Ident("mail")

const (
	MailID                  = "id"
	MailUID                 = "uid"
	MailSubject             = "subject"
	MailContent             = "content"
	MailStatus              = "status"
	MailCustomHasAttachment = "has_attachment"
	MailCreatedAt           = "created_at"
	MailUpdatedAt           = "updated_at"
)

const (
	MailRelationAttachments = "Attachments"
)

var (
	MailIDIdent                  = bun.Ident("id")
	MailUIDIdent                 = bun.Ident("uid")
	MailSubjectIdent             = bun.Ident("subject")
	MailContentIdent             = bun.Ident("content")
	MailStatusIdent              = bun.Ident("status")
	MailCustomHasAttachmentIdent = bun.Ident("has_attachment")
	MailCreatedAtIdent           = bun.Ident("created_at")
	MailUpdatedAtIdent           = bun.Ident("updated_at")
)

const (
	MailIDEq                  = "id = ?"
	MailUIDEq                 = "uid = ?"
	MailSubjectEq             = "subject = ?"
	MailContentEq             = "content = ?"
	MailStatusEq              = "status = ?"
	MailCustomHasAttachmentEq = "has_attachment = ?"
	MailCreatedAtEq           = "created_at = ?"
	MailUpdatedAtEq           = "updated_at = ?"
)

const (
	MailIDNeq                  = "id <> ?"
	MailUIDNeq                 = "uid <> ?"
	MailSubjectNeq             = "subject <> ?"
	MailContentNeq             = "content <> ?"
	MailStatusNeq              = "status <> ?"
	MailCustomHasAttachmentNeq = "has_attachment <> ?"
	MailCreatedAtNeq           = "created_at <> ?"
	MailUpdatedAtNeq           = "updated_at <> ?"
)

const (
	MailIDGt                  = "id > ?"
	MailUIDGt                 = "uid > ?"
	MailStatusGt              = "status > ?"
	MailCustomHasAttachmentGt = "has_attachment > ?"
	MailCreatedAtGt           = "created_at > ?"
	MailUpdatedAtGt           = "updated_at > ?"
)

const (
	MailIDGte                  = "id >= ?"
	MailUIDGte                 = "uid >= ?"
	MailStatusGte              = "status >= ?"
	MailCustomHasAttachmentGte = "has_attachment >= ?"
	MailCreatedAtGte           = "created_at >= ?"
	MailUpdatedAtGte           = "updated_at >= ?"
)

const (
	MailIDLt                  = "id < ?"
	MailUIDLt                 = "uid < ?"
	MailStatusLt              = "status < ?"
	MailCustomHasAttachmentLt = "has_attachment < ?"
	MailCreatedAtLt           = "created_at < ?"
	MailUpdatedAtLt           = "updated_at < ?"
)

const (
	MailIDLte                  = "id <= ?"
	MailUIDLte                 = "uid <= ?"
	MailStatusLte              = "status <= ?"
	MailCustomHasAttachmentLte = "has_attachment <= ?"
	MailCreatedAtLte           = "created_at <= ?"
	MailUpdatedAtLte           = "updated_at <= ?"
)

const (
	MailSubjectLike = "subject LIKE ?"
	MailContentLike = "content LIKE ?"
)

const (
	MailSubjectLikePrefix = "subject LIKE ?%"
	MailContentLikePrefix = "content LIKE ?%"
)

const (
	MailSubjectLikeSuffix = "subject LIKE %?"
	MailContentLikeSuffix = "content LIKE %?"
)

const (
	MailSubjectLikeContain = "subject LIKE %?%"
	MailContentLikeContain = "content LIKE %?%"
)

const (
	MailSubjectConcatExpr = "subject = CONCAT(subject, ?)"
	MailContentConcatExpr = "content = CONCAT(content, ?)"
)

const (
	MailUIDSUMExpr                 = "SUM(uid)"
	MailStatusSUMExpr              = "SUM(status)"
	MailCustomHasAttachmentSUMExpr = "SUM(has_attachment)"
)

const (
	MailUIDAVGExpr                 = "AVG(uid)"
	MailStatusAVGExpr              = "AVG(status)"
	MailCustomHasAttachmentAVGExpr = "AVG(has_attachment)"
)

const (
	MailIDMINExpr                  = "MIN(id)"
	MailUIDMINExpr                 = "MIN(uid)"
	MailStatusMINExpr              = "MIN(status)"
	MailCustomHasAttachmentMINExpr = "MIN(has_attachment)"
	MailCreatedAtMINExpr           = "MIN(created_at)"
	MailUpdatedAtMINExpr           = "MIN(updated_at)"
)

const (
	MailIDMAXExpr                  = "MAX(id)"
	MailUIDMAXExpr                 = "MAX(uid)"
	MailStatusMAXExpr              = "MAX(status)"
	MailCustomHasAttachmentMAXExpr = "MAX(has_attachment)"
	MailCreatedAtMAXExpr           = "MAX(created_at)"
	MailUpdatedAtMAXExpr           = "MAX(updated_at)"
)

const (
	MailUIDAddExpr                 = "uid = uid + ?"
	MailStatusAddExpr              = "status = status + ?"
	MailCustomHasAttachmentAddExpr = "has_attachment = has_attachment + ?"
)

const (
	MailUIDSubExpr                 = "uid = uid - ?"
	MailStatusSubExpr              = "status = status - ?"
	MailCustomHasAttachmentSubExpr = "has_attachment = has_attachment - ?"
)

const (
	MailUIDAddLeastExpr                 = "uid = LEAST(uid + ?, ?)"
	MailStatusAddLeastExpr              = "status = LEAST(status + ?, ?)"
	MailCustomHasAttachmentAddLeastExpr = "has_attachment = LEAST(has_attachment + ?, ?)"
)

const (
	MailUIDSubGreatestExpr                 = "uid = GREATEST(uid - ?, ?)"
	MailStatusSubGreatestExpr              = "status = GREATEST(status - ?, ?)"
	MailCustomHasAttachmentSubGreatestExpr = "has_attachment = GREATEST(has_attachment - ?, ?)"
)

const (
	MailUIDClampExpr                 = "uid = LEAST(GREATEST(uid + ?, ?), ?)"
	MailStatusClampExpr              = "status = LEAST(GREATEST(status + ?, ?), ?)"
	MailCustomHasAttachmentClampExpr = "has_attachment = LEAST(GREATEST(has_attachment + ?, ?), ?)"
)

const (
	MailIDDistinctExpr                  = "DISTINCT id"
	MailUIDDistinctExpr                 = "DISTINCT uid"
	MailSubjectDistinctExpr             = "DISTINCT subject"
	MailContentDistinctExpr             = "DISTINCT content"
	MailStatusDistinctExpr              = "DISTINCT status"
	MailCustomHasAttachmentDistinctExpr = "DISTINCT has_attachment"
	MailCreatedAtDistinctExpr           = "DISTINCT created_at"
	MailUpdatedAtDistinctExpr           = "DISTINCT updated_at"
)

const (
	MailIDCountDistinctExpr                  = "COUNT(DISTINCT id)"
	MailUIDCountDistinctExpr                 = "COUNT(DISTINCT uid)"
	MailSubjectCountDistinctExpr             = "COUNT(DISTINCT subject)"
	MailContentCountDistinctExpr             = "COUNT(DISTINCT content)"
	MailStatusCountDistinctExpr              = "COUNT(DISTINCT status)"
	MailCustomHasAttachmentCountDistinctExpr = "COUNT(DISTINCT has_attachment)"
	MailCreatedAtCountDistinctExpr           = "COUNT(DISTINCT created_at)"
	MailUpdatedAtCountDistinctExpr           = "COUNT(DISTINCT updated_at)"
)

const (
	MailIDIn                  = "id IN (?)"
	MailUIDIn                 = "uid IN (?)"
	MailSubjectIn             = "subject IN (?)"
	MailContentIn             = "content IN (?)"
	MailStatusIn              = "status IN (?)"
	MailCustomHasAttachmentIn = "has_attachment IN (?)"
	MailCreatedAtIn           = "created_at IN (?)"
	MailUpdatedAtIn           = "updated_at IN (?)"
)

const (
	MailIDNotIn                  = "id NOT IN (?)"
	MailUIDNotIn                 = "uid NOT IN (?)"
	MailSubjectNotIn             = "subject NOT IN (?)"
	MailContentNotIn             = "content NOT IN (?)"
	MailStatusNotIn              = "status NOT IN (?)"
	MailCustomHasAttachmentNotIn = "has_attachment NOT IN (?)"
	MailCreatedAtNotIn           = "created_at NOT IN (?)"
	MailUpdatedAtNotIn           = "updated_at NOT IN (?)"
)

const (
	MailIDBetween                  = "id BETWEEN ? AND ?"
	MailUIDBetween                 = "uid BETWEEN ? AND ?"
	MailStatusBetween              = "status BETWEEN ? AND ?"
	MailCustomHasAttachmentBetween = "has_attachment BETWEEN ? AND ?"
	MailCreatedAtBetween           = "created_at BETWEEN ? AND ?"
	MailUpdatedAtBetween           = "updated_at BETWEEN ? AND ?"
)

const (
	MailIDNotBetween                  = "id NOT BETWEEN ? AND ?"
	MailUIDNotBetween                 = "uid NOT BETWEEN ? AND ?"
	MailStatusNotBetween              = "status NOT BETWEEN ? AND ?"
	MailCustomHasAttachmentNotBetween = "has_attachment NOT BETWEEN ? AND ?"
	MailCreatedAtNotBetween           = "created_at NOT BETWEEN ? AND ?"
	MailUpdatedAtNotBetween           = "updated_at NOT BETWEEN ? AND ?"
)

const (
	MailCreatedAtDateExpr = "DATE(created_at)"
	MailUpdatedAtDateExpr = "DATE(updated_at)"
)

const (
	MailCreatedAtYearExpr = "EXTRACT(YEAR FROM created_at)"
	MailUpdatedAtYearExpr = "EXTRACT(YEAR FROM updated_at)"
)

const (
	MailCreatedAtMonthExpr = "EXTRACT(MONTH FROM created_at)"
	MailUpdatedAtMonthExpr = "EXTRACT(MONTH FROM updated_at)"
)

const (
	MailCreatedAtDayExpr = "EXTRACT(DAY FROM created_at)"
	MailUpdatedAtDayExpr = "EXTRACT(DAY FROM updated_at)"
)

const (
	MailCreatedAtHourExpr = "EXTRACT(HOUR FROM created_at)"
	MailUpdatedAtHourExpr = "EXTRACT(HOUR FROM updated_at)"
)

const (
	MailCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM created_at)"
	MailUpdatedAtMinuteExpr = "EXTRACT(MINUTE FROM updated_at)"
)

const (
	MailCreatedAtSecondExpr = "EXTRACT(SECOND FROM created_at)"
	MailUpdatedAtSecondExpr = "EXTRACT(SECOND FROM updated_at)"
)

const (
	MailIDAsc                  = "id ASC"
	MailUIDAsc                 = "uid ASC"
	MailSubjectAsc             = "subject ASC"
	MailContentAsc             = "content ASC"
	MailStatusAsc              = "status ASC"
	MailCustomHasAttachmentAsc = "has_attachment ASC"
	MailCreatedAtAsc           = "created_at ASC"
	MailUpdatedAtAsc           = "updated_at ASC"
)

const (
	MailIDDesc                  = "id DESC"
	MailUIDDesc                 = "uid DESC"
	MailSubjectDesc             = "subject DESC"
	MailContentDesc             = "content DESC"
	MailStatusDesc              = "status DESC"
	MailCustomHasAttachmentDesc = "has_attachment DESC"
	MailCreatedAtDesc           = "created_at DESC"
	MailUpdatedAtDesc           = "updated_at DESC"
)

// Mail generates a model for the "mail" table.
type Mail struct {
	bun.BaseModel `bun:"table:mail,alias:mail_alias"`

	ID                  int64             `bun:"id,pk,unique,autoincrement,notnull" form:"id" json:"id,omitempty"`                           //
	UID                 int64             `bun:"uid,notnull" form:"uid" json:"uid,omitempty"`                                                //
	Subject             string            `bun:"subject,notnull" form:"subject" json:"subject,omitempty"`                                    //
	Content             string            `bun:"content,notnull" form:"content" json:"content,omitempty"`                                    //
	Status              int16             `bun:"status,notnull,default:'0'" form:"status" json:"status,omitempty"`                           //
	CustomHasAttachment int16             `bun:"has_attachment,notnull,default:'0'" form:"has_attachment" json:"#has_attachment,omitempty"`  //
	CreatedAt           time.Time         `bun:"created_at,notnull,default:current_timestamp" form:"created_at" json:"created_at,omitempty"` //
	UpdatedAt           time.Time         `bun:"updated_at,notnull,default:current_timestamp" form:"updated_at" json:"updated_at,omitempty"` //
	Attachments         []*MailAttachment `bun:"attachments,rel:has-many,join:id=mail_id" form:"attachments" json:"attachments,omitempty"`   // email attachments
}

func (m *Mail) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	now := time.Now()
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}
	return nil
}
func (m *Mail) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	now := time.Now()
	m.UpdatedAt = now
	return nil
}
