// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: mail_attachment

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilMailAttachment = (*MailAttachment)(nil)

var (
	_ bun.BeforeInsertHook = (*MailAttachment)(nil)
	_ bun.BeforeUpdateHook = (*MailAttachment)(nil)
)

const MailAttachmentTableName = "mail_attachment"

var MailAttachmentTableNameIdent  = bun.Ident("mail_attachment")

const (
	MailAttachmentID          = "id"
	MailAttachmentMailID      = "mail_id"
	MailAttachmentKind        = "kind"
	MailAttachmentRewardID    = "reward_id"
	MailAttachmentRewardCount = "reward_count"
	MailAttachmentCreatedAt   = "created_at"
	MailAttachmentUpdatedAt   = "updated_at"
)

var (
	MailAttachmentIDIdent          = bun.Ident("id")
	MailAttachmentMailIDIdent      = bun.Ident("mail_id")
	MailAttachmentKindIdent        = bun.Ident("kind")
	MailAttachmentRewardIDIdent    = bun.Ident("reward_id")
	MailAttachmentRewardCountIdent = bun.Ident("reward_count")
	MailAttachmentCreatedAtIdent   = bun.Ident("created_at")
	MailAttachmentUpdatedAtIdent   = bun.Ident("updated_at")
)

const (
	MailAttachmentIDEq          = "id = ?"
	MailAttachmentMailIDEq      = "mail_id = ?"
	MailAttachmentKindEq        = "kind = ?"
	MailAttachmentRewardIDEq    = "reward_id = ?"
	MailAttachmentRewardCountEq = "reward_count = ?"
	MailAttachmentCreatedAtEq   = "created_at = ?"
	MailAttachmentUpdatedAtEq   = "updated_at = ?"
)

const (
	MailAttachmentIDNeq          = "id <> ?"
	MailAttachmentMailIDNeq      = "mail_id <> ?"
	MailAttachmentKindNeq        = "kind <> ?"
	MailAttachmentRewardIDNeq    = "reward_id <> ?"
	MailAttachmentRewardCountNeq = "reward_count <> ?"
	MailAttachmentCreatedAtNeq   = "created_at <> ?"
	MailAttachmentUpdatedAtNeq   = "updated_at <> ?"
)

const (
	MailAttachmentIDGt          = "id > ?"
	MailAttachmentMailIDGt      = "mail_id > ?"
	MailAttachmentKindGt        = "kind > ?"
	MailAttachmentRewardIDGt    = "reward_id > ?"
	MailAttachmentRewardCountGt = "reward_count > ?"
	MailAttachmentCreatedAtGt   = "created_at > ?"
	MailAttachmentUpdatedAtGt   = "updated_at > ?"
)

const (
	MailAttachmentIDGte          = "id >= ?"
	MailAttachmentMailIDGte      = "mail_id >= ?"
	MailAttachmentKindGte        = "kind >= ?"
	MailAttachmentRewardIDGte    = "reward_id >= ?"
	MailAttachmentRewardCountGte = "reward_count >= ?"
	MailAttachmentCreatedAtGte   = "created_at >= ?"
	MailAttachmentUpdatedAtGte   = "updated_at >= ?"
)

const (
	MailAttachmentIDLt          = "id < ?"
	MailAttachmentMailIDLt      = "mail_id < ?"
	MailAttachmentKindLt        = "kind < ?"
	MailAttachmentRewardIDLt    = "reward_id < ?"
	MailAttachmentRewardCountLt = "reward_count < ?"
	MailAttachmentCreatedAtLt   = "created_at < ?"
	MailAttachmentUpdatedAtLt   = "updated_at < ?"
)

const (
	MailAttachmentIDLte          = "id <= ?"
	MailAttachmentMailIDLte      = "mail_id <= ?"
	MailAttachmentKindLte        = "kind <= ?"
	MailAttachmentRewardIDLte    = "reward_id <= ?"
	MailAttachmentRewardCountLte = "reward_count <= ?"
	MailAttachmentCreatedAtLte   = "created_at <= ?"
	MailAttachmentUpdatedAtLte   = "updated_at <= ?"
)

const (
	MailAttachmentMailIDSUMExpr      = "SUM(mail_id)"
	MailAttachmentKindSUMExpr        = "SUM(kind)"
	MailAttachmentRewardIDSUMExpr    = "SUM(reward_id)"
	MailAttachmentRewardCountSUMExpr = "SUM(reward_count)"
	MailAttachmentCreatedAtSUMExpr   = "SUM(created_at)"
	MailAttachmentUpdatedAtSUMExpr   = "SUM(updated_at)"
)

const (
	MailAttachmentMailIDAVGExpr      = "AVG(mail_id)"
	MailAttachmentKindAVGExpr        = "AVG(kind)"
	MailAttachmentRewardIDAVGExpr    = "AVG(reward_id)"
	MailAttachmentRewardCountAVGExpr = "AVG(reward_count)"
	MailAttachmentCreatedAtAVGExpr   = "AVG(created_at)"
	MailAttachmentUpdatedAtAVGExpr   = "AVG(updated_at)"
)

const (
	MailAttachmentIDMINExpr          = "MIN(id)"
	MailAttachmentMailIDMINExpr      = "MIN(mail_id)"
	MailAttachmentKindMINExpr        = "MIN(kind)"
	MailAttachmentRewardIDMINExpr    = "MIN(reward_id)"
	MailAttachmentRewardCountMINExpr = "MIN(reward_count)"
	MailAttachmentCreatedAtMINExpr   = "MIN(created_at)"
	MailAttachmentUpdatedAtMINExpr   = "MIN(updated_at)"
)

const (
	MailAttachmentIDMAXExpr          = "MAX(id)"
	MailAttachmentMailIDMAXExpr      = "MAX(mail_id)"
	MailAttachmentKindMAXExpr        = "MAX(kind)"
	MailAttachmentRewardIDMAXExpr    = "MAX(reward_id)"
	MailAttachmentRewardCountMAXExpr = "MAX(reward_count)"
	MailAttachmentCreatedAtMAXExpr   = "MAX(created_at)"
	MailAttachmentUpdatedAtMAXExpr   = "MAX(updated_at)"
)

const (
	MailAttachmentMailIDAddExpr      = "mail_id = mail_id + ?"
	MailAttachmentKindAddExpr        = "kind = kind + ?"
	MailAttachmentRewardIDAddExpr    = "reward_id = reward_id + ?"
	MailAttachmentRewardCountAddExpr = "reward_count = reward_count + ?"
	MailAttachmentCreatedAtAddExpr   = "created_at = created_at + ?"
	MailAttachmentUpdatedAtAddExpr   = "updated_at = updated_at + ?"
)

const (
	MailAttachmentMailIDSubExpr      = "mail_id = mail_id - ?"
	MailAttachmentKindSubExpr        = "kind = kind - ?"
	MailAttachmentRewardIDSubExpr    = "reward_id = reward_id - ?"
	MailAttachmentRewardCountSubExpr = "reward_count = reward_count - ?"
	MailAttachmentCreatedAtSubExpr   = "created_at = created_at - ?"
	MailAttachmentUpdatedAtSubExpr   = "updated_at = updated_at - ?"
)

const (
	MailAttachmentMailIDAddLeastExpr      = "mail_id = LEAST(mail_id + ?, ?)"
	MailAttachmentKindAddLeastExpr        = "kind = LEAST(kind + ?, ?)"
	MailAttachmentRewardIDAddLeastExpr    = "reward_id = LEAST(reward_id + ?, ?)"
	MailAttachmentRewardCountAddLeastExpr = "reward_count = LEAST(reward_count + ?, ?)"
	MailAttachmentCreatedAtAddLeastExpr   = "created_at = LEAST(created_at + ?, ?)"
	MailAttachmentUpdatedAtAddLeastExpr   = "updated_at = LEAST(updated_at + ?, ?)"
)

const (
	MailAttachmentMailIDSubGreatestExpr      = "mail_id = GREATEST(mail_id - ?, ?)"
	MailAttachmentKindSubGreatestExpr        = "kind = GREATEST(kind - ?, ?)"
	MailAttachmentRewardIDSubGreatestExpr    = "reward_id = GREATEST(reward_id - ?, ?)"
	MailAttachmentRewardCountSubGreatestExpr = "reward_count = GREATEST(reward_count - ?, ?)"
	MailAttachmentCreatedAtSubGreatestExpr   = "created_at = GREATEST(created_at - ?, ?)"
	MailAttachmentUpdatedAtSubGreatestExpr   = "updated_at = GREATEST(updated_at - ?, ?)"
)

const (
	MailAttachmentMailIDClampExpr      = "mail_id = LEAST(GREATEST(mail_id + ?, ?), ?)"
	MailAttachmentKindClampExpr        = "kind = LEAST(GREATEST(kind + ?, ?), ?)"
	MailAttachmentRewardIDClampExpr    = "reward_id = LEAST(GREATEST(reward_id + ?, ?), ?)"
	MailAttachmentRewardCountClampExpr = "reward_count = LEAST(GREATEST(reward_count + ?, ?), ?)"
	MailAttachmentCreatedAtClampExpr   = "created_at = LEAST(GREATEST(created_at + ?, ?), ?)"
	MailAttachmentUpdatedAtClampExpr   = "updated_at = LEAST(GREATEST(updated_at + ?, ?), ?)"
)

const (
	MailAttachmentIDDistinctExpr          = "DISTINCT id"
	MailAttachmentMailIDDistinctExpr      = "DISTINCT mail_id"
	MailAttachmentKindDistinctExpr        = "DISTINCT kind"
	MailAttachmentRewardIDDistinctExpr    = "DISTINCT reward_id"
	MailAttachmentRewardCountDistinctExpr = "DISTINCT reward_count"
	MailAttachmentCreatedAtDistinctExpr   = "DISTINCT created_at"
	MailAttachmentUpdatedAtDistinctExpr   = "DISTINCT updated_at"
)

const (
	MailAttachmentIDCountDistinctExpr          = "COUNT(DISTINCT id)"
	MailAttachmentMailIDCountDistinctExpr      = "COUNT(DISTINCT mail_id)"
	MailAttachmentKindCountDistinctExpr        = "COUNT(DISTINCT kind)"
	MailAttachmentRewardIDCountDistinctExpr    = "COUNT(DISTINCT reward_id)"
	MailAttachmentRewardCountCountDistinctExpr = "COUNT(DISTINCT reward_count)"
	MailAttachmentCreatedAtCountDistinctExpr   = "COUNT(DISTINCT created_at)"
	MailAttachmentUpdatedAtCountDistinctExpr   = "COUNT(DISTINCT updated_at)"
)

const (
	MailAttachmentIDIn          = "id IN (?)"
	MailAttachmentMailIDIn      = "mail_id IN (?)"
	MailAttachmentKindIn        = "kind IN (?)"
	MailAttachmentRewardIDIn    = "reward_id IN (?)"
	MailAttachmentRewardCountIn = "reward_count IN (?)"
	MailAttachmentCreatedAtIn   = "created_at IN (?)"
	MailAttachmentUpdatedAtIn   = "updated_at IN (?)"
)

const (
	MailAttachmentIDNotIn          = "id NOT IN (?)"
	MailAttachmentMailIDNotIn      = "mail_id NOT IN (?)"
	MailAttachmentKindNotIn        = "kind NOT IN (?)"
	MailAttachmentRewardIDNotIn    = "reward_id NOT IN (?)"
	MailAttachmentRewardCountNotIn = "reward_count NOT IN (?)"
	MailAttachmentCreatedAtNotIn   = "created_at NOT IN (?)"
	MailAttachmentUpdatedAtNotIn   = "updated_at NOT IN (?)"
)

const (
	MailAttachmentIDBetween          = "id BETWEEN ? AND ?"
	MailAttachmentMailIDBetween      = "mail_id BETWEEN ? AND ?"
	MailAttachmentKindBetween        = "kind BETWEEN ? AND ?"
	MailAttachmentRewardIDBetween    = "reward_id BETWEEN ? AND ?"
	MailAttachmentRewardCountBetween = "reward_count BETWEEN ? AND ?"
	MailAttachmentCreatedAtBetween   = "created_at BETWEEN ? AND ?"
	MailAttachmentUpdatedAtBetween   = "updated_at BETWEEN ? AND ?"
)

const (
	MailAttachmentIDNotBetween          = "id NOT BETWEEN ? AND ?"
	MailAttachmentMailIDNotBetween      = "mail_id NOT BETWEEN ? AND ?"
	MailAttachmentKindNotBetween        = "kind NOT BETWEEN ? AND ?"
	MailAttachmentRewardIDNotBetween    = "reward_id NOT BETWEEN ? AND ?"
	MailAttachmentRewardCountNotBetween = "reward_count NOT BETWEEN ? AND ?"
	MailAttachmentCreatedAtNotBetween   = "created_at NOT BETWEEN ? AND ?"
	MailAttachmentUpdatedAtNotBetween   = "updated_at NOT BETWEEN ? AND ?"
)

const (
	MailAttachmentIDAsc          = "id ASC"
	MailAttachmentMailIDAsc      = "mail_id ASC"
	MailAttachmentKindAsc        = "kind ASC"
	MailAttachmentRewardIDAsc    = "reward_id ASC"
	MailAttachmentRewardCountAsc = "reward_count ASC"
	MailAttachmentCreatedAtAsc   = "created_at ASC"
	MailAttachmentUpdatedAtAsc   = "updated_at ASC"
)

const (
	MailAttachmentIDDesc          = "id DESC"
	MailAttachmentMailIDDesc      = "mail_id DESC"
	MailAttachmentKindDesc        = "kind DESC"
	MailAttachmentRewardIDDesc    = "reward_id DESC"
	MailAttachmentRewardCountDesc = "reward_count DESC"
	MailAttachmentCreatedAtDesc   = "created_at DESC"
	MailAttachmentUpdatedAtDesc   = "updated_at DESC"
)

// MailAttachment generates a model for the "mail_attachment" table.
type MailAttachment struct {
	bun.BaseModel `bun:"table:mail_attachment,alias:mail_attachment_alias"`

	ID          int64 `bun:"id,pk,unique,autoincrement,notnull" json:"id,omitempty"`     //
	MailID      int64 `bun:"mail_id,notnull" json:"mail_id,omitempty"`                   //
	Kind        int16 `bun:"kind,notnull,default:'0'" json:"kind,omitempty"`             //
	RewardID    int64 `bun:"reward_id,notnull" json:"reward_id,omitempty"`               //
	RewardCount int32 `bun:"reward_count,notnull" json:"reward_count,omitempty"`         //
	CreatedAt   int64 `bun:"created_at,notnull,default:'0'" json:"created_at,omitempty"` //
	UpdatedAt   int64 `bun:"updated_at,notnull" json:"updated_at,omitempty"`             //
}

func (m *MailAttachment) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	now := time.Now()
	if m.CreatedAt == 0 {
		m.CreatedAt = now.UnixMilli()
	}
	if m.UpdatedAt == 0 {
		m.UpdatedAt = now.UnixMilli()
	}
	return nil
}
func (m *MailAttachment) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	now := time.Now()
	m.UpdatedAt = now.UnixMilli()
	return nil
}
