// Code generated by bake. DO NOT EDIT.
// version: v0.1.0
// source: posts

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilPost = (*Post)(nil)

var (
	_ bun.BeforeInsertHook = (*Post)(nil)
	_ bun.BeforeUpdateHook = (*Post)(nil)
)

const (
	PostTableName  = "posts"
	PostTableAlias = "posts_alias"
)

var (
	PostTableNameIdent  = bun.Ident("posts")
	PostTableAliasIdent = bun.Ident("posts_alias")
)

const (
	InnerJoinPostAsAlias = "INNER JOIN posts AS posts_alias" // same as JOIN
	LeftJoinPostAsAlias  = "LEFT JOIN posts AS posts_alias"  // same as LEFT OUTER JOIN
	RightJoinPostAsAlias = "RIGHT JOIN posts AS posts_alias" // same as RIGHT OUTER JOIN
	FullJoinPostAsAlias  = "FULL JOIN posts AS posts_alias"  // same as FULL OUTER JOIN
)

const (
	PostID        = "id"
	PostUserID    = "user_id"
	PostTitle     = "title"
	PostContent   = "content"
	PostStatus    = "status"
	PostCreatedAt = "created_at"
	PostUpdatedAt = "updated_at"
)

const (
	PostRelationUser = "User"
)

const (
	PostAliasID        = "posts_alias.id"
	PostAliasUserID    = "posts_alias.user_id"
	PostAliasTitle     = "posts_alias.title"
	PostAliasContent   = "posts_alias.content"
	PostAliasStatus    = "posts_alias.status"
	PostAliasCreatedAt = "posts_alias.created_at"
	PostAliasUpdatedAt = "posts_alias.updated_at"
)

var (
	PostIDIdent        = bun.Ident("id")
	PostUserIDIdent    = bun.Ident("user_id")
	PostTitleIdent     = bun.Ident("title")
	PostContentIdent   = bun.Ident("content")
	PostStatusIdent    = bun.Ident("status")
	PostCreatedAtIdent = bun.Ident("created_at")
	PostUpdatedAtIdent = bun.Ident("updated_at")
)

const (
	PostIDEq        = "id = ?"
	PostUserIDEq    = "user_id = ?"
	PostTitleEq     = "title = ?"
	PostContentEq   = "content = ?"
	PostStatusEq    = "status = ?"
	PostCreatedAtEq = "created_at = ?"
	PostUpdatedAtEq = "updated_at = ?"
)

const (
	PostAliasIDEq        = "posts_alias.id = ?"
	PostAliasUserIDEq    = "posts_alias.user_id = ?"
	PostAliasTitleEq     = "posts_alias.title = ?"
	PostAliasContentEq   = "posts_alias.content = ?"
	PostAliasStatusEq    = "posts_alias.status = ?"
	PostAliasCreatedAtEq = "posts_alias.created_at = ?"
	PostAliasUpdatedAtEq = "posts_alias.updated_at = ?"
)

const (
	PostIDNeq        = "id <> ?"
	PostUserIDNeq    = "user_id <> ?"
	PostTitleNeq     = "title <> ?"
	PostContentNeq   = "content <> ?"
	PostStatusNeq    = "status <> ?"
	PostCreatedAtNeq = "created_at <> ?"
	PostUpdatedAtNeq = "updated_at <> ?"
)

const (
	PostAliasIDNeq        = "posts_alias.id <> ?"
	PostAliasUserIDNeq    = "posts_alias.user_id <> ?"
	PostAliasTitleNeq     = "posts_alias.title <> ?"
	PostAliasContentNeq   = "posts_alias.content <> ?"
	PostAliasStatusNeq    = "posts_alias.status <> ?"
	PostAliasCreatedAtNeq = "posts_alias.created_at <> ?"
	PostAliasUpdatedAtNeq = "posts_alias.updated_at <> ?"
)

const (
	PostIDGt        = "id > ?"
	PostUserIDGt    = "user_id > ?"
	PostStatusGt    = "status > ?"
	PostCreatedAtGt = "created_at > ?"
	PostUpdatedAtGt = "updated_at > ?"
)

const (
	PostAliasIDGt        = "posts_alias.id > ?"
	PostAliasUserIDGt    = "posts_alias.user_id > ?"
	PostAliasStatusGt    = "posts_alias.status > ?"
	PostAliasCreatedAtGt = "posts_alias.created_at > ?"
	PostAliasUpdatedAtGt = "posts_alias.updated_at > ?"
)

const (
	PostIDGte        = "id >= ?"
	PostUserIDGte    = "user_id >= ?"
	PostStatusGte    = "status >= ?"
	PostCreatedAtGte = "created_at >= ?"
	PostUpdatedAtGte = "updated_at >= ?"
)

const (
	PostAliasIDGte        = "posts_alias.id >= ?"
	PostAliasUserIDGte    = "posts_alias.user_id >= ?"
	PostAliasStatusGte    = "posts_alias.status >= ?"
	PostAliasCreatedAtGte = "posts_alias.created_at >= ?"
	PostAliasUpdatedAtGte = "posts_alias.updated_at >= ?"
)

const (
	PostIDLt        = "id < ?"
	PostUserIDLt    = "user_id < ?"
	PostStatusLt    = "status < ?"
	PostCreatedAtLt = "created_at < ?"
	PostUpdatedAtLt = "updated_at < ?"
)

const (
	PostAliasIDLt        = "posts_alias.id < ?"
	PostAliasUserIDLt    = "posts_alias.user_id < ?"
	PostAliasStatusLt    = "posts_alias.status < ?"
	PostAliasCreatedAtLt = "posts_alias.created_at < ?"
	PostAliasUpdatedAtLt = "posts_alias.updated_at < ?"
)

const (
	PostIDLte        = "id <= ?"
	PostUserIDLte    = "user_id <= ?"
	PostStatusLte    = "status <= ?"
	PostCreatedAtLte = "created_at <= ?"
	PostUpdatedAtLte = "updated_at <= ?"
)

const (
	PostAliasIDLte        = "posts_alias.id <= ?"
	PostAliasUserIDLte    = "posts_alias.user_id <= ?"
	PostAliasStatusLte    = "posts_alias.status <= ?"
	PostAliasCreatedAtLte = "posts_alias.created_at <= ?"
	PostAliasUpdatedAtLte = "posts_alias.updated_at <= ?"
)

const (
	PostTitleLike   = "title LIKE ?"
	PostContentLike = "content LIKE ?"
)

const (
	PostAliasTitleLike   = "posts_alias.title LIKE ?"
	PostAliasContentLike = "posts_alias.content LIKE ?"
)

const (
	PostTitleLikePrefix   = "title LIKE ?%"
	PostContentLikePrefix = "content LIKE ?%"
)

const (
	PostAliasTitleLikePrefix   = "posts_alias.title LIKE ?%"
	PostAliasContentLikePrefix = "posts_alias.content LIKE ?%"
)

const (
	PostTitleLikeSuffix   = "title LIKE %?"
	PostContentLikeSuffix = "content LIKE %?"
)

const (
	PostAliasTitleLikeSuffix   = "posts_alias.title LIKE %?"
	PostAliasContentLikeSuffix = "posts_alias.content LIKE %?"
)

const (
	PostTitleLikeContain   = "title LIKE %?%"
	PostContentLikeContain = "content LIKE %?%"
)

const (
	PostAliasTitleLikeContain   = "posts_alias.title LIKE %?%"
	PostAliasContentLikeContain = "posts_alias.content LIKE %?%"
)

const (
	PostUserIDSUMExpr = "SUM(user_id)"
	PostStatusSUMExpr = "SUM(status)"
)

const (
	PostAliasUserIDSUMExpr = "SUM(posts_alias.user_id)"
	PostAliasStatusSUMExpr = "SUM(posts_alias.status)"
)

const (
	PostUserIDAVGExpr = "AVG(user_id)"
	PostStatusAVGExpr = "AVG(status)"
)

const (
	PostAliasUserIDAVGExpr = "AVG(posts_alias.user_id)"
	PostAliasStatusAVGExpr = "AVG(posts_alias.status)"
)

const (
	PostIDMINExpr        = "MIN(id)"
	PostUserIDMINExpr    = "MIN(user_id)"
	PostStatusMINExpr    = "MIN(status)"
	PostCreatedAtMINExpr = "MIN(created_at)"
	PostUpdatedAtMINExpr = "MIN(updated_at)"
)

const (
	PostAliasIDMINExpr        = "MIN(posts_alias.id)"
	PostAliasUserIDMINExpr    = "MIN(posts_alias.user_id)"
	PostAliasStatusMINExpr    = "MIN(posts_alias.status)"
	PostAliasCreatedAtMINExpr = "MIN(posts_alias.created_at)"
	PostAliasUpdatedAtMINExpr = "MIN(posts_alias.updated_at)"
)

const (
	PostIDMAXExpr        = "MAX(id)"
	PostUserIDMAXExpr    = "MAX(user_id)"
	PostStatusMAXExpr    = "MAX(status)"
	PostCreatedAtMAXExpr = "MAX(created_at)"
	PostUpdatedAtMAXExpr = "MAX(updated_at)"
)

const (
	PostAliasIDMAXExpr        = "MAX(posts_alias.id)"
	PostAliasUserIDMAXExpr    = "MAX(posts_alias.user_id)"
	PostAliasStatusMAXExpr    = "MAX(posts_alias.status)"
	PostAliasCreatedAtMAXExpr = "MAX(posts_alias.created_at)"
	PostAliasUpdatedAtMAXExpr = "MAX(posts_alias.updated_at)"
)

const (
	PostUserIDAddExpr = "user_id = user_id + ?"
	PostStatusAddExpr = "status = status + ?"
)

const (
	PostAliasUserIDAddExpr = "posts_alias.user_id = posts_alias.user_id + ?"
	PostAliasStatusAddExpr = "posts_alias.status = posts_alias.status + ?"
)

const (
	PostUserIDSubExpr = "user_id = user_id - ?"
	PostStatusSubExpr = "status = status - ?"
)

const (
	PostAliasUserIDSubExpr = "posts_alias.user_id = posts_alias.user_id - ?"
	PostAliasStatusSubExpr = "posts_alias.status = posts_alias.status - ?"
)

const (
	PostUserIDAddLeastExpr = "user_id = LEAST(user_id + ?, ?)"
	PostStatusAddLeastExpr = "status = LEAST(status + ?, ?)"
)

const (
	PostAliasUserIDAddLeastExpr = "posts_alias.user_id = LEAST(posts_alias.user_id + ?, ?)"
	PostAliasStatusAddLeastExpr = "posts_alias.status = LEAST(posts_alias.status + ?, ?)"
)

const (
	PostUserIDSubGreatestExpr = "user_id = GREATEST(user_id - ?, ?)"
	PostStatusSubGreatestExpr = "status = GREATEST(status - ?, ?)"
)

const (
	PostAliasUserIDSubGreatestExpr = "posts_alias.user_id = GREATEST(posts_alias.user_id - ?, ?)"
	PostAliasStatusSubGreatestExpr = "posts_alias.status = GREATEST(posts_alias.status - ?, ?)"
)

const (
	PostUserIDClampExpr = "user_id = LEAST(GREATEST(user_id + ?, ?), ?)"
	PostStatusClampExpr = "status = LEAST(GREATEST(status + ?, ?), ?)"
)

const (
	PostAliasUserIDClampExpr = "posts_alias.user_id = LEAST(GREATEST(posts_alias.user_id + ?, ?), ?)"
	PostAliasStatusClampExpr = "posts_alias.status = LEAST(GREATEST(posts_alias.status + ?, ?), ?)"
)

const (
	PostIDIn        = "id IN (?)"
	PostUserIDIn    = "user_id IN (?)"
	PostTitleIn     = "title IN (?)"
	PostContentIn   = "content IN (?)"
	PostStatusIn    = "status IN (?)"
	PostCreatedAtIn = "created_at IN (?)"
	PostUpdatedAtIn = "updated_at IN (?)"
)

const (
	PostAliasIDIn        = "posts_alias.id IN (?)"
	PostAliasUserIDIn    = "posts_alias.user_id IN (?)"
	PostAliasTitleIn     = "posts_alias.title IN (?)"
	PostAliasContentIn   = "posts_alias.content IN (?)"
	PostAliasStatusIn    = "posts_alias.status IN (?)"
	PostAliasCreatedAtIn = "posts_alias.created_at IN (?)"
	PostAliasUpdatedAtIn = "posts_alias.updated_at IN (?)"
)

const (
	PostIDNotIn        = "id NOT IN (?)"
	PostUserIDNotIn    = "user_id NOT IN (?)"
	PostTitleNotIn     = "title NOT IN (?)"
	PostContentNotIn   = "content NOT IN (?)"
	PostStatusNotIn    = "status NOT IN (?)"
	PostCreatedAtNotIn = "created_at NOT IN (?)"
	PostUpdatedAtNotIn = "updated_at NOT IN (?)"
)

const (
	PostAliasIDNotIn        = "posts_alias.id NOT IN (?)"
	PostAliasUserIDNotIn    = "posts_alias.user_id NOT IN (?)"
	PostAliasTitleNotIn     = "posts_alias.title NOT IN (?)"
	PostAliasContentNotIn   = "posts_alias.content NOT IN (?)"
	PostAliasStatusNotIn    = "posts_alias.status NOT IN (?)"
	PostAliasCreatedAtNotIn = "posts_alias.created_at NOT IN (?)"
	PostAliasUpdatedAtNotIn = "posts_alias.updated_at NOT IN (?)"
)

const (
	PostContentIsNull = "content IS NULL"
)

const (
	PostAliasContentIsNull = "posts_alias.content IS NULL"
)

const (
	PostContentIsNotNull = "content IS NOT NULL"
)

const (
	PostAliasContentIsNotNull = "posts_alias.content IS NOT NULL"
)

// COALESCE expressions (COALESCE(column, ?))
const (
	PostContentCoalesceExpr = "COALESCE(content, ?)"
)

const (
	PostAliasContentCoalesceExpr = "COALESCE(posts_alias.content, ?)"
)

const (
	PostIDBetween        = "id BETWEEN ? AND ?"
	PostUserIDBetween    = "user_id BETWEEN ? AND ?"
	PostStatusBetween    = "status BETWEEN ? AND ?"
	PostCreatedAtBetween = "created_at BETWEEN ? AND ?"
	PostUpdatedAtBetween = "updated_at BETWEEN ? AND ?"
)

const (
	PostAliasIDBetween        = "posts_alias.id BETWEEN ? AND ?"
	PostAliasUserIDBetween    = "posts_alias.user_id BETWEEN ? AND ?"
	PostAliasStatusBetween    = "posts_alias.status BETWEEN ? AND ?"
	PostAliasCreatedAtBetween = "posts_alias.created_at BETWEEN ? AND ?"
	PostAliasUpdatedAtBetween = "posts_alias.updated_at BETWEEN ? AND ?"
)

const (
	PostIDNotBetween        = "id NOT BETWEEN ? AND ?"
	PostUserIDNotBetween    = "user_id NOT BETWEEN ? AND ?"
	PostStatusNotBetween    = "status NOT BETWEEN ? AND ?"
	PostCreatedAtNotBetween = "created_at NOT BETWEEN ? AND ?"
	PostUpdatedAtNotBetween = "updated_at NOT BETWEEN ? AND ?"
)

const (
	PostAliasIDNotBetween        = "posts_alias.id NOT BETWEEN ? AND ?"
	PostAliasUserIDNotBetween    = "posts_alias.user_id NOT BETWEEN ? AND ?"
	PostAliasStatusNotBetween    = "posts_alias.status NOT BETWEEN ? AND ?"
	PostAliasCreatedAtNotBetween = "posts_alias.created_at NOT BETWEEN ? AND ?"
	PostAliasUpdatedAtNotBetween = "posts_alias.updated_at NOT BETWEEN ? AND ?"
)

const (
	PostCreatedAtDateExpr = "DATE(created_at)"
	PostUpdatedAtDateExpr = "DATE(updated_at)"
)

const (
	PostAliasCreatedAtDateExpr = "DATE(posts_alias.created_at)"
	PostAliasUpdatedAtDateExpr = "DATE(posts_alias.updated_at)"
)

const (
	PostCreatedAtYearExpr = "EXTRACT(YEAR FROM created_at)"
	PostUpdatedAtYearExpr = "EXTRACT(YEAR FROM updated_at)"
)

const (
	PostAliasCreatedAtYearExpr = "EXTRACT(YEAR FROM posts_alias.created_at)"
	PostAliasUpdatedAtYearExpr = "EXTRACT(YEAR FROM posts_alias.updated_at)"
)

const (
	PostCreatedAtMonthExpr = "EXTRACT(MONTH FROM created_at)"
	PostUpdatedAtMonthExpr = "EXTRACT(MONTH FROM updated_at)"
)

const (
	PostAliasCreatedAtMonthExpr = "EXTRACT(MONTH FROM posts_alias.created_at)"
	PostAliasUpdatedAtMonthExpr = "EXTRACT(MONTH FROM posts_alias.updated_at)"
)

const (
	PostCreatedAtDayExpr = "EXTRACT(DAY FROM created_at)"
	PostUpdatedAtDayExpr = "EXTRACT(DAY FROM updated_at)"
)

const (
	PostAliasCreatedAtDayExpr = "EXTRACT(DAY FROM posts_alias.created_at)"
	PostAliasUpdatedAtDayExpr = "EXTRACT(DAY FROM posts_alias.updated_at)"
)

const (
	PostCreatedAtHourExpr = "EXTRACT(HOUR FROM created_at)"
	PostUpdatedAtHourExpr = "EXTRACT(HOUR FROM updated_at)"
)

const (
	PostAliasCreatedAtHourExpr = "EXTRACT(HOUR FROM posts_alias.created_at)"
	PostAliasUpdatedAtHourExpr = "EXTRACT(HOUR FROM posts_alias.updated_at)"
)

const (
	PostCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM created_at)"
	PostUpdatedAtMinuteExpr = "EXTRACT(MINUTE FROM updated_at)"
)

const (
	PostAliasCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM posts_alias.created_at)"
	PostAliasUpdatedAtMinuteExpr = "EXTRACT(MINUTE FROM posts_alias.updated_at)"
)

const (
	PostCreatedAtSecondExpr = "EXTRACT(SECOND FROM created_at)"
	PostUpdatedAtSecondExpr = "EXTRACT(SECOND FROM updated_at)"
)

const (
	PostAliasCreatedAtSecondExpr = "EXTRACT(SECOND FROM posts_alias.created_at)"
	PostAliasUpdatedAtSecondExpr = "EXTRACT(SECOND FROM posts_alias.updated_at)"
)

const (
	PostIDAsc        = "id ASC"
	PostUserIDAsc    = "user_id ASC"
	PostTitleAsc     = "title ASC"
	PostContentAsc   = "content ASC"
	PostStatusAsc    = "status ASC"
	PostCreatedAtAsc = "created_at ASC"
	PostUpdatedAtAsc = "updated_at ASC"
)

const (
	PostAliasIDAsc        = "posts_alias.id ASC"
	PostAliasUserIDAsc    = "posts_alias.user_id ASC"
	PostAliasTitleAsc     = "posts_alias.title ASC"
	PostAliasContentAsc   = "posts_alias.content ASC"
	PostAliasStatusAsc    = "posts_alias.status ASC"
	PostAliasCreatedAtAsc = "posts_alias.created_at ASC"
	PostAliasUpdatedAtAsc = "posts_alias.updated_at ASC"
)

const (
	PostIDDesc        = "id DESC"
	PostUserIDDesc    = "user_id DESC"
	PostTitleDesc     = "title DESC"
	PostContentDesc   = "content DESC"
	PostStatusDesc    = "status DESC"
	PostCreatedAtDesc = "created_at DESC"
	PostUpdatedAtDesc = "updated_at DESC"
)

const (
	PostAliasIDDesc        = "posts_alias.id DESC"
	PostAliasUserIDDesc    = "posts_alias.user_id DESC"
	PostAliasTitleDesc     = "posts_alias.title DESC"
	PostAliasContentDesc   = "posts_alias.content DESC"
	PostAliasStatusDesc    = "posts_alias.status DESC"
	PostAliasCreatedAtDesc = "posts_alias.created_at DESC"
	PostAliasUpdatedAtDesc = "posts_alias.updated_at DESC"
)

// Post generates a model for the "posts" table.
type Post struct {
	bun.BaseModel `bun:"table:posts,alias:posts_alias"`

	ID        int64     `bun:"id,pk,notnull" json:"id,omitempty" xml:"id"`                                                //
	UserID    int64     `bun:"user_id,notnull" json:"user_id,omitempty" xml:"user_id"`                                    //
	Title     string    `bun:"title,notnull" json:"title,omitempty" xml:"title"`                                          //
	Content   *string   `bun:"content,notnull" json:"content,omitempty" xml:"content"`                                    //
	Status    int16     `bun:"status,notnull,default:'0'" json:"status,omitempty" xml:"status"`                           //
	CreatedAt time.Time `bun:"created_at,notnull,default:current_timestamp" json:"created_at,omitempty" xml:"created_at"` //
	UpdatedAt time.Time `bun:"updated_at,notnull,default:current_timestamp" json:"updated_at,omitempty" xml:"updated_at"` //
	User      *User     `bun:"User,join:user_id=id,rel:belongs-to" json:"user,omitempty" xml:"user"`                      //
}

func (m *Post) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	now := time.Now()
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}
	return nil
}

func (m *Post) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	now := time.Now()
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}
	return nil
}
