// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: test_multi_index

// Package model defines database models generated from schema.
package model

import (
	"github.com/uptrace/bun"
)

const TestMultiIndexTableAlias = "test_multi_index_alias"

const TestMultiIndexTableNameAsAlias = "test_multi_index AS test_multi_index_alias"

var TestMultiIndexTableAliasIdent = bun.Ident("test_multi_index_alias")

const (
	InnerJoinTestMultiIndexAsAlias = "INNER JOIN test_multi_index AS test_multi_index_alias" // same as JOIN
	LeftJoinTestMultiIndexAsAlias  = "LEFT JOIN test_multi_index AS test_multi_index_alias"  // same as LEFT OUTER JOIN
	RightJoinTestMultiIndexAsAlias = "RIGHT JOIN test_multi_index AS test_multi_index_alias" // same as RIGHT OUTER JOIN
	FullJoinTestMultiIndexAsAlias  = "FULL JOIN test_multi_index AS test_multi_index_alias"  // same as FULL OUTER JOIN
)

const (
	TestMultiIndexAliasID      = "test_multi_index_alias.id"
	TestMultiIndexAliasStartAt = "test_multi_index_alias.start_at"
	TestMultiIndexAliasEndAt   = "test_multi_index_alias.end_at"
	TestMultiIndexAliasSeq     = "test_multi_index_alias.seq"
)

var (
	TestMultiIndexIDAliasIdent      = bun.Ident("test_multi_index_alias.id")
	TestMultiIndexStartAtAliasIdent = bun.Ident("test_multi_index_alias.start_at")
	TestMultiIndexEndAtAliasIdent   = bun.Ident("test_multi_index_alias.end_at")
	TestMultiIndexSeqAliasIdent     = bun.Ident("test_multi_index_alias.seq")
)

const (
	TestMultiIndexAliasIDEq      = "test_multi_index_alias.id = ?"
	TestMultiIndexAliasStartAtEq = "test_multi_index_alias.start_at = ?"
	TestMultiIndexAliasEndAtEq   = "test_multi_index_alias.end_at = ?"
	TestMultiIndexAliasSeqEq     = "test_multi_index_alias.seq = ?"
)

const (
	TestMultiIndexAliasIDNeq      = "test_multi_index_alias.id <> ?"
	TestMultiIndexAliasStartAtNeq = "test_multi_index_alias.start_at <> ?"
	TestMultiIndexAliasEndAtNeq   = "test_multi_index_alias.end_at <> ?"
	TestMultiIndexAliasSeqNeq     = "test_multi_index_alias.seq <> ?"
)

const (
	TestMultiIndexAliasIDGt      = "test_multi_index_alias.id > ?"
	TestMultiIndexAliasStartAtGt = "test_multi_index_alias.start_at > ?"
	TestMultiIndexAliasEndAtGt   = "test_multi_index_alias.end_at > ?"
	TestMultiIndexAliasSeqGt     = "test_multi_index_alias.seq > ?"
)

const (
	TestMultiIndexAliasIDGte      = "test_multi_index_alias.id >= ?"
	TestMultiIndexAliasStartAtGte = "test_multi_index_alias.start_at >= ?"
	TestMultiIndexAliasEndAtGte   = "test_multi_index_alias.end_at >= ?"
	TestMultiIndexAliasSeqGte     = "test_multi_index_alias.seq >= ?"
)

const (
	TestMultiIndexAliasIDLt      = "test_multi_index_alias.id < ?"
	TestMultiIndexAliasStartAtLt = "test_multi_index_alias.start_at < ?"
	TestMultiIndexAliasEndAtLt   = "test_multi_index_alias.end_at < ?"
	TestMultiIndexAliasSeqLt     = "test_multi_index_alias.seq < ?"
)

const (
	TestMultiIndexAliasIDLte      = "test_multi_index_alias.id <= ?"
	TestMultiIndexAliasStartAtLte = "test_multi_index_alias.start_at <= ?"
	TestMultiIndexAliasEndAtLte   = "test_multi_index_alias.end_at <= ?"
	TestMultiIndexAliasSeqLte     = "test_multi_index_alias.seq <= ?"
)

const (
	TestMultiIndexAliasSeqSUMExpr = "SUM(test_multi_index_alias.seq)"
)

const (
	TestMultiIndexAliasSeqAVGExpr = "AVG(test_multi_index_alias.seq)"
)

const (
	TestMultiIndexAliasIDMINExpr      = "MIN(test_multi_index_alias.id)"
	TestMultiIndexAliasStartAtMINExpr = "MIN(test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtMINExpr   = "MIN(test_multi_index_alias.end_at)"
	TestMultiIndexAliasSeqMINExpr     = "MIN(test_multi_index_alias.seq)"
)

const (
	TestMultiIndexAliasIDMAXExpr      = "MAX(test_multi_index_alias.id)"
	TestMultiIndexAliasStartAtMAXExpr = "MAX(test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtMAXExpr   = "MAX(test_multi_index_alias.end_at)"
	TestMultiIndexAliasSeqMAXExpr     = "MAX(test_multi_index_alias.seq)"
)

const (
	TestMultiIndexAliasSeqAddExpr = "test_multi_index_alias.seq = test_multi_index_alias.seq + ?"
)

const (
	TestMultiIndexAliasSeqSubExpr = "test_multi_index_alias.seq = test_multi_index_alias.seq - ?"
)

const (
	TestMultiIndexAliasSeqAddLeastExpr = "test_multi_index_alias.seq = LEAST(test_multi_index_alias.seq + ?, ?)"
)

const (
	TestMultiIndexAliasSeqSubGreatestExpr = "test_multi_index_alias.seq = GREATEST(test_multi_index_alias.seq - ?, ?)"
)

const (
	TestMultiIndexAliasSeqClampExpr = "test_multi_index_alias.seq = LEAST(GREATEST(test_multi_index_alias.seq + ?, ?), ?)"
)

const (
	TestMultiIndexAliasIDDistinctExpr      = "DISTINCT test_multi_index_alias.id"
	TestMultiIndexAliasStartAtDistinctExpr = "DISTINCT test_multi_index_alias.start_at"
	TestMultiIndexAliasEndAtDistinctExpr   = "DISTINCT test_multi_index_alias.end_at"
	TestMultiIndexAliasSeqDistinctExpr     = "DISTINCT test_multi_index_alias.seq"
)

const (
	TestMultiIndexAliasIDCountDistinctExpr      = "COUNT(DISTINCT test_multi_index_alias.id)"
	TestMultiIndexAliasStartAtCountDistinctExpr = "COUNT(DISTINCT test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtCountDistinctExpr   = "COUNT(DISTINCT test_multi_index_alias.end_at)"
	TestMultiIndexAliasSeqCountDistinctExpr     = "COUNT(DISTINCT test_multi_index_alias.seq)"
)

const (
	TestMultiIndexAliasIDIn      = "test_multi_index_alias.id IN (?)"
	TestMultiIndexAliasStartAtIn = "test_multi_index_alias.start_at IN (?)"
	TestMultiIndexAliasEndAtIn   = "test_multi_index_alias.end_at IN (?)"
	TestMultiIndexAliasSeqIn     = "test_multi_index_alias.seq IN (?)"
)

const (
	TestMultiIndexAliasIDNotIn      = "test_multi_index_alias.id NOT IN (?)"
	TestMultiIndexAliasStartAtNotIn = "test_multi_index_alias.start_at NOT IN (?)"
	TestMultiIndexAliasEndAtNotIn   = "test_multi_index_alias.end_at NOT IN (?)"
	TestMultiIndexAliasSeqNotIn     = "test_multi_index_alias.seq NOT IN (?)"
)

const (
	TestMultiIndexAliasIDBetween      = "test_multi_index_alias.id BETWEEN ? AND ?"
	TestMultiIndexAliasStartAtBetween = "test_multi_index_alias.start_at BETWEEN ? AND ?"
	TestMultiIndexAliasEndAtBetween   = "test_multi_index_alias.end_at BETWEEN ? AND ?"
	TestMultiIndexAliasSeqBetween     = "test_multi_index_alias.seq BETWEEN ? AND ?"
)

const (
	TestMultiIndexAliasIDNotBetween      = "test_multi_index_alias.id NOT BETWEEN ? AND ?"
	TestMultiIndexAliasStartAtNotBetween = "test_multi_index_alias.start_at NOT BETWEEN ? AND ?"
	TestMultiIndexAliasEndAtNotBetween   = "test_multi_index_alias.end_at NOT BETWEEN ? AND ?"
	TestMultiIndexAliasSeqNotBetween     = "test_multi_index_alias.seq NOT BETWEEN ? AND ?"
)

const (
	TestMultiIndexAliasStartAtDateExpr = "DATE(test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtDateExpr   = "DATE(test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexAliasStartAtYearExpr = "EXTRACT(YEAR FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtYearExpr   = "EXTRACT(YEAR FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexAliasStartAtMonthExpr = "EXTRACT(MONTH FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtMonthExpr   = "EXTRACT(MONTH FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexAliasStartAtDayExpr = "EXTRACT(DAY FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtDayExpr   = "EXTRACT(DAY FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexAliasStartAtHourExpr = "EXTRACT(HOUR FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtHourExpr   = "EXTRACT(HOUR FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexAliasStartAtMinuteExpr = "EXTRACT(MINUTE FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtMinuteExpr   = "EXTRACT(MINUTE FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexAliasStartAtSecondExpr = "EXTRACT(SECOND FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtSecondExpr   = "EXTRACT(SECOND FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexAliasIDAsc      = "test_multi_index_alias.id ASC"
	TestMultiIndexAliasStartAtAsc = "test_multi_index_alias.start_at ASC"
	TestMultiIndexAliasEndAtAsc   = "test_multi_index_alias.end_at ASC"
	TestMultiIndexAliasSeqAsc     = "test_multi_index_alias.seq ASC"
)

const (
	TestMultiIndexAliasIDDesc      = "test_multi_index_alias.id DESC"
	TestMultiIndexAliasStartAtDesc = "test_multi_index_alias.start_at DESC"
	TestMultiIndexAliasEndAtDesc   = "test_multi_index_alias.end_at DESC"
	TestMultiIndexAliasSeqDesc     = "test_multi_index_alias.seq DESC"
)
