// Code generated by bake. DO NOT EDIT.
// version: v0.2.1
// source: test_multi_index

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilTestMultiIndex = (*TestMultiIndex)(nil)

var (
	_ bun.BeforeInsertHook = (*TestMultiIndex)(nil)
	_ bun.BeforeUpdateHook = (*TestMultiIndex)(nil)
)

const (
	TestMultiIndexTableName  = "test_multi_index"
	TestMultiIndexTableAlias = "test_multi_index_alias"
)

const TestMultiIndexTableNameAsAlias = "test_multi_index AS test_multi_index_alias"

var (
	TestMultiIndexTableNameIdent  = bun.Ident("test_multi_index")
	TestMultiIndexTableAliasIdent = bun.Ident("test_multi_index_alias")
)

const (
	InnerJoinTestMultiIndexAsAlias = "INNER JOIN test_multi_index AS test_multi_index_alias" // same as JOIN
	LeftJoinTestMultiIndexAsAlias  = "LEFT JOIN test_multi_index AS test_multi_index_alias"  // same as LEFT OUTER JOIN
	RightJoinTestMultiIndexAsAlias = "RIGHT JOIN test_multi_index AS test_multi_index_alias" // same as RIGHT OUTER JOIN
	FullJoinTestMultiIndexAsAlias  = "FULL JOIN test_multi_index AS test_multi_index_alias"  // same as FULL OUTER JOIN
)

const (
	TestMultiIndexID      = "id"
	TestMultiIndexStartAt = "start_at"
	TestMultiIndexEndAt   = "end_at"
	TestMultiIndexSeq     = "seq"
)

const (
	TestMultiIndexAliasID      = "test_multi_index_alias.id"
	TestMultiIndexAliasStartAt = "test_multi_index_alias.start_at"
	TestMultiIndexAliasEndAt   = "test_multi_index_alias.end_at"
	TestMultiIndexAliasSeq     = "test_multi_index_alias.seq"
)

var (
	TestMultiIndexIDIdent      = bun.Ident("id")
	TestMultiIndexStartAtIdent = bun.Ident("start_at")
	TestMultiIndexEndAtIdent   = bun.Ident("end_at")
	TestMultiIndexSeqIdent     = bun.Ident("seq")
)

var (
	TestMultiIndexIDAliasIdent      = bun.Ident("test_multi_index_alias.id")
	TestMultiIndexStartAtAliasIdent = bun.Ident("test_multi_index_alias.start_at")
	TestMultiIndexEndAtAliasIdent   = bun.Ident("test_multi_index_alias.end_at")
	TestMultiIndexSeqAliasIdent     = bun.Ident("test_multi_index_alias.seq")
)

const (
	TestMultiIndexIDEq      = "id = ?"
	TestMultiIndexStartAtEq = "start_at = ?"
	TestMultiIndexEndAtEq   = "end_at = ?"
	TestMultiIndexSeqEq     = "seq = ?"
)

const (
	TestMultiIndexAliasIDEq      = "test_multi_index_alias.id = ?"
	TestMultiIndexAliasStartAtEq = "test_multi_index_alias.start_at = ?"
	TestMultiIndexAliasEndAtEq   = "test_multi_index_alias.end_at = ?"
	TestMultiIndexAliasSeqEq     = "test_multi_index_alias.seq = ?"
)

const (
	TestMultiIndexIDNeq      = "id <> ?"
	TestMultiIndexStartAtNeq = "start_at <> ?"
	TestMultiIndexEndAtNeq   = "end_at <> ?"
	TestMultiIndexSeqNeq     = "seq <> ?"
)

const (
	TestMultiIndexAliasIDNeq      = "test_multi_index_alias.id <> ?"
	TestMultiIndexAliasStartAtNeq = "test_multi_index_alias.start_at <> ?"
	TestMultiIndexAliasEndAtNeq   = "test_multi_index_alias.end_at <> ?"
	TestMultiIndexAliasSeqNeq     = "test_multi_index_alias.seq <> ?"
)

const (
	TestMultiIndexIDGt      = "id > ?"
	TestMultiIndexStartAtGt = "start_at > ?"
	TestMultiIndexEndAtGt   = "end_at > ?"
	TestMultiIndexSeqGt     = "seq > ?"
)

const (
	TestMultiIndexAliasIDGt      = "test_multi_index_alias.id > ?"
	TestMultiIndexAliasStartAtGt = "test_multi_index_alias.start_at > ?"
	TestMultiIndexAliasEndAtGt   = "test_multi_index_alias.end_at > ?"
	TestMultiIndexAliasSeqGt     = "test_multi_index_alias.seq > ?"
)

const (
	TestMultiIndexIDGte      = "id >= ?"
	TestMultiIndexStartAtGte = "start_at >= ?"
	TestMultiIndexEndAtGte   = "end_at >= ?"
	TestMultiIndexSeqGte     = "seq >= ?"
)

const (
	TestMultiIndexAliasIDGte      = "test_multi_index_alias.id >= ?"
	TestMultiIndexAliasStartAtGte = "test_multi_index_alias.start_at >= ?"
	TestMultiIndexAliasEndAtGte   = "test_multi_index_alias.end_at >= ?"
	TestMultiIndexAliasSeqGte     = "test_multi_index_alias.seq >= ?"
)

const (
	TestMultiIndexIDLt      = "id < ?"
	TestMultiIndexStartAtLt = "start_at < ?"
	TestMultiIndexEndAtLt   = "end_at < ?"
	TestMultiIndexSeqLt     = "seq < ?"
)

const (
	TestMultiIndexAliasIDLt      = "test_multi_index_alias.id < ?"
	TestMultiIndexAliasStartAtLt = "test_multi_index_alias.start_at < ?"
	TestMultiIndexAliasEndAtLt   = "test_multi_index_alias.end_at < ?"
	TestMultiIndexAliasSeqLt     = "test_multi_index_alias.seq < ?"
)

const (
	TestMultiIndexIDLte      = "id <= ?"
	TestMultiIndexStartAtLte = "start_at <= ?"
	TestMultiIndexEndAtLte   = "end_at <= ?"
	TestMultiIndexSeqLte     = "seq <= ?"
)

const (
	TestMultiIndexAliasIDLte      = "test_multi_index_alias.id <= ?"
	TestMultiIndexAliasStartAtLte = "test_multi_index_alias.start_at <= ?"
	TestMultiIndexAliasEndAtLte   = "test_multi_index_alias.end_at <= ?"
	TestMultiIndexAliasSeqLte     = "test_multi_index_alias.seq <= ?"
)

const (
	TestMultiIndexSeqSUMExpr = "SUM(seq)"
)

const (
	TestMultiIndexAliasSeqSUMExpr = "SUM(test_multi_index_alias.seq)"
)

const (
	TestMultiIndexSeqAVGExpr = "AVG(seq)"
)

const (
	TestMultiIndexAliasSeqAVGExpr = "AVG(test_multi_index_alias.seq)"
)

const (
	TestMultiIndexIDMINExpr      = "MIN(id)"
	TestMultiIndexStartAtMINExpr = "MIN(start_at)"
	TestMultiIndexEndAtMINExpr   = "MIN(end_at)"
	TestMultiIndexSeqMINExpr     = "MIN(seq)"
)

const (
	TestMultiIndexAliasIDMINExpr      = "MIN(test_multi_index_alias.id)"
	TestMultiIndexAliasStartAtMINExpr = "MIN(test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtMINExpr   = "MIN(test_multi_index_alias.end_at)"
	TestMultiIndexAliasSeqMINExpr     = "MIN(test_multi_index_alias.seq)"
)

const (
	TestMultiIndexIDMAXExpr      = "MAX(id)"
	TestMultiIndexStartAtMAXExpr = "MAX(start_at)"
	TestMultiIndexEndAtMAXExpr   = "MAX(end_at)"
	TestMultiIndexSeqMAXExpr     = "MAX(seq)"
)

const (
	TestMultiIndexAliasIDMAXExpr      = "MAX(test_multi_index_alias.id)"
	TestMultiIndexAliasStartAtMAXExpr = "MAX(test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtMAXExpr   = "MAX(test_multi_index_alias.end_at)"
	TestMultiIndexAliasSeqMAXExpr     = "MAX(test_multi_index_alias.seq)"
)

const (
	TestMultiIndexSeqAddExpr = "seq = seq + ?"
)

const (
	TestMultiIndexAliasSeqAddExpr = "test_multi_index_alias.seq = test_multi_index_alias.seq + ?"
)

const (
	TestMultiIndexSeqSubExpr = "seq = seq - ?"
)

const (
	TestMultiIndexAliasSeqSubExpr = "test_multi_index_alias.seq = test_multi_index_alias.seq - ?"
)

const (
	TestMultiIndexSeqAddLeastExpr = "seq = LEAST(seq + ?, ?)"
)

const (
	TestMultiIndexAliasSeqAddLeastExpr = "test_multi_index_alias.seq = LEAST(test_multi_index_alias.seq + ?, ?)"
)

const (
	TestMultiIndexSeqSubGreatestExpr = "seq = GREATEST(seq - ?, ?)"
)

const (
	TestMultiIndexAliasSeqSubGreatestExpr = "test_multi_index_alias.seq = GREATEST(test_multi_index_alias.seq - ?, ?)"
)

const (
	TestMultiIndexSeqClampExpr = "seq = LEAST(GREATEST(seq + ?, ?), ?)"
)

const (
	TestMultiIndexAliasSeqClampExpr = "test_multi_index_alias.seq = LEAST(GREATEST(test_multi_index_alias.seq + ?, ?), ?)"
)

const (
	TestMultiIndexIDDistinctExpr      = "DISTINCT id"
	TestMultiIndexStartAtDistinctExpr = "DISTINCT start_at"
	TestMultiIndexEndAtDistinctExpr   = "DISTINCT end_at"
	TestMultiIndexSeqDistinctExpr     = "DISTINCT seq"
)

const (
	TestMultiIndexAliasIDDistinctExpr      = "DISTINCT test_multi_index_alias.id"
	TestMultiIndexAliasStartAtDistinctExpr = "DISTINCT test_multi_index_alias.start_at"
	TestMultiIndexAliasEndAtDistinctExpr   = "DISTINCT test_multi_index_alias.end_at"
	TestMultiIndexAliasSeqDistinctExpr     = "DISTINCT test_multi_index_alias.seq"
)

// COUNT(DISTINCT ...) expressions
const (
	TestMultiIndexIDCountDistinctExpr      = "COUNT(DISTINCT id)"
	TestMultiIndexStartAtCountDistinctExpr = "COUNT(DISTINCT start_at)"
	TestMultiIndexEndAtCountDistinctExpr   = "COUNT(DISTINCT end_at)"
	TestMultiIndexSeqCountDistinctExpr     = "COUNT(DISTINCT seq)"
)

const (
	TestMultiIndexAliasIDCountDistinctExpr      = "COUNT(DISTINCT test_multi_index_alias.id)"
	TestMultiIndexAliasStartAtCountDistinctExpr = "COUNT(DISTINCT test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtCountDistinctExpr   = "COUNT(DISTINCT test_multi_index_alias.end_at)"
	TestMultiIndexAliasSeqCountDistinctExpr     = "COUNT(DISTINCT test_multi_index_alias.seq)"
)

const (
	TestMultiIndexIDIn      = "id IN (?)"
	TestMultiIndexStartAtIn = "start_at IN (?)"
	TestMultiIndexEndAtIn   = "end_at IN (?)"
	TestMultiIndexSeqIn     = "seq IN (?)"
)

const (
	TestMultiIndexAliasIDIn      = "test_multi_index_alias.id IN (?)"
	TestMultiIndexAliasStartAtIn = "test_multi_index_alias.start_at IN (?)"
	TestMultiIndexAliasEndAtIn   = "test_multi_index_alias.end_at IN (?)"
	TestMultiIndexAliasSeqIn     = "test_multi_index_alias.seq IN (?)"
)

const (
	TestMultiIndexIDNotIn      = "id NOT IN (?)"
	TestMultiIndexStartAtNotIn = "start_at NOT IN (?)"
	TestMultiIndexEndAtNotIn   = "end_at NOT IN (?)"
	TestMultiIndexSeqNotIn     = "seq NOT IN (?)"
)

const (
	TestMultiIndexAliasIDNotIn      = "test_multi_index_alias.id NOT IN (?)"
	TestMultiIndexAliasStartAtNotIn = "test_multi_index_alias.start_at NOT IN (?)"
	TestMultiIndexAliasEndAtNotIn   = "test_multi_index_alias.end_at NOT IN (?)"
	TestMultiIndexAliasSeqNotIn     = "test_multi_index_alias.seq NOT IN (?)"
)

const (
	TestMultiIndexIDBetween      = "id BETWEEN ? AND ?"
	TestMultiIndexStartAtBetween = "start_at BETWEEN ? AND ?"
	TestMultiIndexEndAtBetween   = "end_at BETWEEN ? AND ?"
	TestMultiIndexSeqBetween     = "seq BETWEEN ? AND ?"
)

const (
	TestMultiIndexAliasIDBetween      = "test_multi_index_alias.id BETWEEN ? AND ?"
	TestMultiIndexAliasStartAtBetween = "test_multi_index_alias.start_at BETWEEN ? AND ?"
	TestMultiIndexAliasEndAtBetween   = "test_multi_index_alias.end_at BETWEEN ? AND ?"
	TestMultiIndexAliasSeqBetween     = "test_multi_index_alias.seq BETWEEN ? AND ?"
)

const (
	TestMultiIndexIDNotBetween      = "id NOT BETWEEN ? AND ?"
	TestMultiIndexStartAtNotBetween = "start_at NOT BETWEEN ? AND ?"
	TestMultiIndexEndAtNotBetween   = "end_at NOT BETWEEN ? AND ?"
	TestMultiIndexSeqNotBetween     = "seq NOT BETWEEN ? AND ?"
)

const (
	TestMultiIndexAliasIDNotBetween      = "test_multi_index_alias.id NOT BETWEEN ? AND ?"
	TestMultiIndexAliasStartAtNotBetween = "test_multi_index_alias.start_at NOT BETWEEN ? AND ?"
	TestMultiIndexAliasEndAtNotBetween   = "test_multi_index_alias.end_at NOT BETWEEN ? AND ?"
	TestMultiIndexAliasSeqNotBetween     = "test_multi_index_alias.seq NOT BETWEEN ? AND ?"
)

const (
	TestMultiIndexStartAtDateExpr = "DATE(start_at)"
	TestMultiIndexEndAtDateExpr   = "DATE(end_at)"
)

const (
	TestMultiIndexAliasStartAtDateExpr = "DATE(test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtDateExpr   = "DATE(test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexStartAtYearExpr = "EXTRACT(YEAR FROM start_at)"
	TestMultiIndexEndAtYearExpr   = "EXTRACT(YEAR FROM end_at)"
)

const (
	TestMultiIndexAliasStartAtYearExpr = "EXTRACT(YEAR FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtYearExpr   = "EXTRACT(YEAR FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexStartAtMonthExpr = "EXTRACT(MONTH FROM start_at)"
	TestMultiIndexEndAtMonthExpr   = "EXTRACT(MONTH FROM end_at)"
)

const (
	TestMultiIndexAliasStartAtMonthExpr = "EXTRACT(MONTH FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtMonthExpr   = "EXTRACT(MONTH FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexStartAtDayExpr = "EXTRACT(DAY FROM start_at)"
	TestMultiIndexEndAtDayExpr   = "EXTRACT(DAY FROM end_at)"
)

const (
	TestMultiIndexAliasStartAtDayExpr = "EXTRACT(DAY FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtDayExpr   = "EXTRACT(DAY FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexStartAtHourExpr = "EXTRACT(HOUR FROM start_at)"
	TestMultiIndexEndAtHourExpr   = "EXTRACT(HOUR FROM end_at)"
)

const (
	TestMultiIndexAliasStartAtHourExpr = "EXTRACT(HOUR FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtHourExpr   = "EXTRACT(HOUR FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexStartAtMinuteExpr = "EXTRACT(MINUTE FROM start_at)"
	TestMultiIndexEndAtMinuteExpr   = "EXTRACT(MINUTE FROM end_at)"
)

const (
	TestMultiIndexAliasStartAtMinuteExpr = "EXTRACT(MINUTE FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtMinuteExpr   = "EXTRACT(MINUTE FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexStartAtSecondExpr = "EXTRACT(SECOND FROM start_at)"
	TestMultiIndexEndAtSecondExpr   = "EXTRACT(SECOND FROM end_at)"
)

const (
	TestMultiIndexAliasStartAtSecondExpr = "EXTRACT(SECOND FROM test_multi_index_alias.start_at)"
	TestMultiIndexAliasEndAtSecondExpr   = "EXTRACT(SECOND FROM test_multi_index_alias.end_at)"
)

const (
	TestMultiIndexIDAsc      = "id ASC"
	TestMultiIndexStartAtAsc = "start_at ASC"
	TestMultiIndexEndAtAsc   = "end_at ASC"
	TestMultiIndexSeqAsc     = "seq ASC"
)

const (
	TestMultiIndexAliasIDAsc      = "test_multi_index_alias.id ASC"
	TestMultiIndexAliasStartAtAsc = "test_multi_index_alias.start_at ASC"
	TestMultiIndexAliasEndAtAsc   = "test_multi_index_alias.end_at ASC"
	TestMultiIndexAliasSeqAsc     = "test_multi_index_alias.seq ASC"
)

const (
	TestMultiIndexIDDesc      = "id DESC"
	TestMultiIndexStartAtDesc = "start_at DESC"
	TestMultiIndexEndAtDesc   = "end_at DESC"
	TestMultiIndexSeqDesc     = "seq DESC"
)

const (
	TestMultiIndexAliasIDDesc      = "test_multi_index_alias.id DESC"
	TestMultiIndexAliasStartAtDesc = "test_multi_index_alias.start_at DESC"
	TestMultiIndexAliasEndAtDesc   = "test_multi_index_alias.end_at DESC"
	TestMultiIndexAliasSeqDesc     = "test_multi_index_alias.seq DESC"
)

// TestMultiIndex generates a model for the "test_multi_index" table.
type TestMultiIndex struct {
	bun.BaseModel `bun:"table:test_multi_index,alias:test_multi_index_alias"`

	ID      int32     `bun:"id,pk,unique,autoincrement,notnull" json:"id,omitempty"`                           //
	StartAt time.Time `bun:"start_at,unique:test_multi_index_start_end_key,notnull" json:"start_at,omitempty"` //
	EndAt   time.Time `bun:"end_at,unique:test_multi_index_start_end_key,notnull" json:"end_at,omitempty"`     //
	Seq     int64     `bun:"seq,notnull" json:"seq,omitempty"`                                                 //
}

func (m *TestMultiIndex) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	return nil
}

func (m *TestMultiIndex) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	return nil
}
