// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: test_multi_index

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilTestMultiIndex = (*TestMultiIndex)(nil)

var (
	_ bun.BeforeInsertHook = (*TestMultiIndex)(nil)
	_ bun.BeforeUpdateHook = (*TestMultiIndex)(nil)
)

const TestMultiIndexTableName = "test_multi_index"

var TestMultiIndexTableNameIdent  = bun.Ident("test_multi_index")

const (
	TestMultiIndexID      = "id"
	TestMultiIndexStartAt = "start_at"
	TestMultiIndexEndAt   = "end_at"
	TestMultiIndexSeq     = "seq"
)

var (
	TestMultiIndexIDIdent      = bun.Ident("id")
	TestMultiIndexStartAtIdent = bun.Ident("start_at")
	TestMultiIndexEndAtIdent   = bun.Ident("end_at")
	TestMultiIndexSeqIdent     = bun.Ident("seq")
)

const (
	TestMultiIndexIDEq      = "id = ?"
	TestMultiIndexStartAtEq = "start_at = ?"
	TestMultiIndexEndAtEq   = "end_at = ?"
	TestMultiIndexSeqEq     = "seq = ?"
)

const (
	TestMultiIndexIDNeq      = "id <> ?"
	TestMultiIndexStartAtNeq = "start_at <> ?"
	TestMultiIndexEndAtNeq   = "end_at <> ?"
	TestMultiIndexSeqNeq     = "seq <> ?"
)

const (
	TestMultiIndexIDGt      = "id > ?"
	TestMultiIndexStartAtGt = "start_at > ?"
	TestMultiIndexEndAtGt   = "end_at > ?"
	TestMultiIndexSeqGt     = "seq > ?"
)

const (
	TestMultiIndexIDGte      = "id >= ?"
	TestMultiIndexStartAtGte = "start_at >= ?"
	TestMultiIndexEndAtGte   = "end_at >= ?"
	TestMultiIndexSeqGte     = "seq >= ?"
)

const (
	TestMultiIndexIDLt      = "id < ?"
	TestMultiIndexStartAtLt = "start_at < ?"
	TestMultiIndexEndAtLt   = "end_at < ?"
	TestMultiIndexSeqLt     = "seq < ?"
)

const (
	TestMultiIndexIDLte      = "id <= ?"
	TestMultiIndexStartAtLte = "start_at <= ?"
	TestMultiIndexEndAtLte   = "end_at <= ?"
	TestMultiIndexSeqLte     = "seq <= ?"
)

const (
	TestMultiIndexSeqSUMExpr = "SUM(seq)"
)

const (
	TestMultiIndexSeqAVGExpr = "AVG(seq)"
)

const (
	TestMultiIndexIDMINExpr      = "MIN(id)"
	TestMultiIndexStartAtMINExpr = "MIN(start_at)"
	TestMultiIndexEndAtMINExpr   = "MIN(end_at)"
	TestMultiIndexSeqMINExpr     = "MIN(seq)"
)

const (
	TestMultiIndexIDMAXExpr      = "MAX(id)"
	TestMultiIndexStartAtMAXExpr = "MAX(start_at)"
	TestMultiIndexEndAtMAXExpr   = "MAX(end_at)"
	TestMultiIndexSeqMAXExpr     = "MAX(seq)"
)

const (
	TestMultiIndexSeqAddExpr = "seq = seq + ?"
)

const (
	TestMultiIndexSeqSubExpr = "seq = seq - ?"
)

const (
	TestMultiIndexSeqAddLeastExpr = "seq = LEAST(seq + ?, ?)"
)

const (
	TestMultiIndexSeqSubGreatestExpr = "seq = GREATEST(seq - ?, ?)"
)

const (
	TestMultiIndexSeqClampExpr = "seq = LEAST(GREATEST(seq + ?, ?), ?)"
)

const (
	TestMultiIndexIDDistinctExpr      = "DISTINCT id"
	TestMultiIndexStartAtDistinctExpr = "DISTINCT start_at"
	TestMultiIndexEndAtDistinctExpr   = "DISTINCT end_at"
	TestMultiIndexSeqDistinctExpr     = "DISTINCT seq"
)

const (
	TestMultiIndexIDCountDistinctExpr      = "COUNT(DISTINCT id)"
	TestMultiIndexStartAtCountDistinctExpr = "COUNT(DISTINCT start_at)"
	TestMultiIndexEndAtCountDistinctExpr   = "COUNT(DISTINCT end_at)"
	TestMultiIndexSeqCountDistinctExpr     = "COUNT(DISTINCT seq)"
)

const (
	TestMultiIndexIDIn      = "id IN (?)"
	TestMultiIndexStartAtIn = "start_at IN (?)"
	TestMultiIndexEndAtIn   = "end_at IN (?)"
	TestMultiIndexSeqIn     = "seq IN (?)"
)

const (
	TestMultiIndexIDNotIn      = "id NOT IN (?)"
	TestMultiIndexStartAtNotIn = "start_at NOT IN (?)"
	TestMultiIndexEndAtNotIn   = "end_at NOT IN (?)"
	TestMultiIndexSeqNotIn     = "seq NOT IN (?)"
)

const (
	TestMultiIndexIDBetween      = "id BETWEEN ? AND ?"
	TestMultiIndexStartAtBetween = "start_at BETWEEN ? AND ?"
	TestMultiIndexEndAtBetween   = "end_at BETWEEN ? AND ?"
	TestMultiIndexSeqBetween     = "seq BETWEEN ? AND ?"
)

const (
	TestMultiIndexIDNotBetween      = "id NOT BETWEEN ? AND ?"
	TestMultiIndexStartAtNotBetween = "start_at NOT BETWEEN ? AND ?"
	TestMultiIndexEndAtNotBetween   = "end_at NOT BETWEEN ? AND ?"
	TestMultiIndexSeqNotBetween     = "seq NOT BETWEEN ? AND ?"
)

const (
	TestMultiIndexStartAtDateExpr = "DATE(start_at)"
	TestMultiIndexEndAtDateExpr   = "DATE(end_at)"
)

const (
	TestMultiIndexStartAtYearExpr = "EXTRACT(YEAR FROM start_at)"
	TestMultiIndexEndAtYearExpr   = "EXTRACT(YEAR FROM end_at)"
)

const (
	TestMultiIndexStartAtMonthExpr = "EXTRACT(MONTH FROM start_at)"
	TestMultiIndexEndAtMonthExpr   = "EXTRACT(MONTH FROM end_at)"
)

const (
	TestMultiIndexStartAtDayExpr = "EXTRACT(DAY FROM start_at)"
	TestMultiIndexEndAtDayExpr   = "EXTRACT(DAY FROM end_at)"
)

const (
	TestMultiIndexStartAtHourExpr = "EXTRACT(HOUR FROM start_at)"
	TestMultiIndexEndAtHourExpr   = "EXTRACT(HOUR FROM end_at)"
)

const (
	TestMultiIndexStartAtMinuteExpr = "EXTRACT(MINUTE FROM start_at)"
	TestMultiIndexEndAtMinuteExpr   = "EXTRACT(MINUTE FROM end_at)"
)

const (
	TestMultiIndexStartAtSecondExpr = "EXTRACT(SECOND FROM start_at)"
	TestMultiIndexEndAtSecondExpr   = "EXTRACT(SECOND FROM end_at)"
)

const (
	TestMultiIndexIDAsc      = "id ASC"
	TestMultiIndexStartAtAsc = "start_at ASC"
	TestMultiIndexEndAtAsc   = "end_at ASC"
	TestMultiIndexSeqAsc     = "seq ASC"
)

const (
	TestMultiIndexIDDesc      = "id DESC"
	TestMultiIndexStartAtDesc = "start_at DESC"
	TestMultiIndexEndAtDesc   = "end_at DESC"
	TestMultiIndexSeqDesc     = "seq DESC"
)

// TestMultiIndex generates a model for the "test_multi_index" table.
type TestMultiIndex struct {
	bun.BaseModel `bun:"table:test_multi_index,alias:test_multi_index_alias"`

	ID      int32     `bun:"id,pk,unique,autoincrement,notnull" json:"id,omitempty"`                           //
	StartAt time.Time `bun:"start_at,unique:test_multi_index_start_end_key,notnull" json:"start_at,omitempty"` //
	EndAt   time.Time `bun:"end_at,unique:test_multi_index_start_end_key,notnull" json:"end_at,omitempty"`     //
	Seq     int64     `bun:"seq,notnull" json:"seq,omitempty"`                                                 //
}

func (m *TestMultiIndex) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	return nil
}
func (m *TestMultiIndex) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	return nil
}
