// Code generated by bake. DO NOT EDIT.
// version: v0.2.1
// source: test_index

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilTestIndex = (*TestIndex)(nil)

var (
	_ bun.BeforeInsertHook = (*TestIndex)(nil)
	_ bun.BeforeUpdateHook = (*TestIndex)(nil)
)

const (
	TestIndexTableName  = "test_index"
	TestIndexTableAlias = "test_index_alias"
)

const TestIndexTableNameAsAlias = "test_index AS test_index_alias"

var (
	TestIndexTableNameIdent  = bun.Ident("test_index")
	TestIndexTableAliasIdent = bun.Ident("test_index_alias")
)

const (
	InnerJoinTestIndexAsAlias = "INNER JOIN test_index AS test_index_alias" // same as JOIN
	LeftJoinTestIndexAsAlias  = "LEFT JOIN test_index AS test_index_alias"  // same as LEFT OUTER JOIN
	RightJoinTestIndexAsAlias = "RIGHT JOIN test_index AS test_index_alias" // same as RIGHT OUTER JOIN
	FullJoinTestIndexAsAlias  = "FULL JOIN test_index AS test_index_alias"  // same as FULL OUTER JOIN
)

const (
	TestIndexID      = "id"
	TestIndexStartAt = "start_at"
	TestIndexEndAt   = "end_at"
	TestIndexSeq     = "seq"
)

const (
	TestIndexAliasID      = "test_index_alias.id"
	TestIndexAliasStartAt = "test_index_alias.start_at"
	TestIndexAliasEndAt   = "test_index_alias.end_at"
	TestIndexAliasSeq     = "test_index_alias.seq"
)

var (
	TestIndexIDIdent      = bun.Ident("id")
	TestIndexStartAtIdent = bun.Ident("start_at")
	TestIndexEndAtIdent   = bun.Ident("end_at")
	TestIndexSeqIdent     = bun.Ident("seq")
)

var (
	TestIndexIDAliasIdent      = bun.Ident("test_index_alias.id")
	TestIndexStartAtAliasIdent = bun.Ident("test_index_alias.start_at")
	TestIndexEndAtAliasIdent   = bun.Ident("test_index_alias.end_at")
	TestIndexSeqAliasIdent     = bun.Ident("test_index_alias.seq")
)

const (
	TestIndexIDEq      = "id = ?"
	TestIndexStartAtEq = "start_at = ?"
	TestIndexEndAtEq   = "end_at = ?"
	TestIndexSeqEq     = "seq = ?"
)

const (
	TestIndexAliasIDEq      = "test_index_alias.id = ?"
	TestIndexAliasStartAtEq = "test_index_alias.start_at = ?"
	TestIndexAliasEndAtEq   = "test_index_alias.end_at = ?"
	TestIndexAliasSeqEq     = "test_index_alias.seq = ?"
)

const (
	TestIndexIDNeq      = "id <> ?"
	TestIndexStartAtNeq = "start_at <> ?"
	TestIndexEndAtNeq   = "end_at <> ?"
	TestIndexSeqNeq     = "seq <> ?"
)

const (
	TestIndexAliasIDNeq      = "test_index_alias.id <> ?"
	TestIndexAliasStartAtNeq = "test_index_alias.start_at <> ?"
	TestIndexAliasEndAtNeq   = "test_index_alias.end_at <> ?"
	TestIndexAliasSeqNeq     = "test_index_alias.seq <> ?"
)

const (
	TestIndexIDGt      = "id > ?"
	TestIndexStartAtGt = "start_at > ?"
	TestIndexEndAtGt   = "end_at > ?"
	TestIndexSeqGt     = "seq > ?"
)

const (
	TestIndexAliasIDGt      = "test_index_alias.id > ?"
	TestIndexAliasStartAtGt = "test_index_alias.start_at > ?"
	TestIndexAliasEndAtGt   = "test_index_alias.end_at > ?"
	TestIndexAliasSeqGt     = "test_index_alias.seq > ?"
)

const (
	TestIndexIDGte      = "id >= ?"
	TestIndexStartAtGte = "start_at >= ?"
	TestIndexEndAtGte   = "end_at >= ?"
	TestIndexSeqGte     = "seq >= ?"
)

const (
	TestIndexAliasIDGte      = "test_index_alias.id >= ?"
	TestIndexAliasStartAtGte = "test_index_alias.start_at >= ?"
	TestIndexAliasEndAtGte   = "test_index_alias.end_at >= ?"
	TestIndexAliasSeqGte     = "test_index_alias.seq >= ?"
)

const (
	TestIndexIDLt      = "id < ?"
	TestIndexStartAtLt = "start_at < ?"
	TestIndexEndAtLt   = "end_at < ?"
	TestIndexSeqLt     = "seq < ?"
)

const (
	TestIndexAliasIDLt      = "test_index_alias.id < ?"
	TestIndexAliasStartAtLt = "test_index_alias.start_at < ?"
	TestIndexAliasEndAtLt   = "test_index_alias.end_at < ?"
	TestIndexAliasSeqLt     = "test_index_alias.seq < ?"
)

const (
	TestIndexIDLte      = "id <= ?"
	TestIndexStartAtLte = "start_at <= ?"
	TestIndexEndAtLte   = "end_at <= ?"
	TestIndexSeqLte     = "seq <= ?"
)

const (
	TestIndexAliasIDLte      = "test_index_alias.id <= ?"
	TestIndexAliasStartAtLte = "test_index_alias.start_at <= ?"
	TestIndexAliasEndAtLte   = "test_index_alias.end_at <= ?"
	TestIndexAliasSeqLte     = "test_index_alias.seq <= ?"
)

const (
	TestIndexSeqSUMExpr = "SUM(seq)"
)

const (
	TestIndexAliasSeqSUMExpr = "SUM(test_index_alias.seq)"
)

const (
	TestIndexSeqAVGExpr = "AVG(seq)"
)

const (
	TestIndexAliasSeqAVGExpr = "AVG(test_index_alias.seq)"
)

const (
	TestIndexIDMINExpr      = "MIN(id)"
	TestIndexStartAtMINExpr = "MIN(start_at)"
	TestIndexEndAtMINExpr   = "MIN(end_at)"
	TestIndexSeqMINExpr     = "MIN(seq)"
)

const (
	TestIndexAliasIDMINExpr      = "MIN(test_index_alias.id)"
	TestIndexAliasStartAtMINExpr = "MIN(test_index_alias.start_at)"
	TestIndexAliasEndAtMINExpr   = "MIN(test_index_alias.end_at)"
	TestIndexAliasSeqMINExpr     = "MIN(test_index_alias.seq)"
)

const (
	TestIndexIDMAXExpr      = "MAX(id)"
	TestIndexStartAtMAXExpr = "MAX(start_at)"
	TestIndexEndAtMAXExpr   = "MAX(end_at)"
	TestIndexSeqMAXExpr     = "MAX(seq)"
)

const (
	TestIndexAliasIDMAXExpr      = "MAX(test_index_alias.id)"
	TestIndexAliasStartAtMAXExpr = "MAX(test_index_alias.start_at)"
	TestIndexAliasEndAtMAXExpr   = "MAX(test_index_alias.end_at)"
	TestIndexAliasSeqMAXExpr     = "MAX(test_index_alias.seq)"
)

const (
	TestIndexSeqAddExpr = "seq = seq + ?"
)

const (
	TestIndexAliasSeqAddExpr = "test_index_alias.seq = test_index_alias.seq + ?"
)

const (
	TestIndexSeqSubExpr = "seq = seq - ?"
)

const (
	TestIndexAliasSeqSubExpr = "test_index_alias.seq = test_index_alias.seq - ?"
)

const (
	TestIndexSeqAddLeastExpr = "seq = LEAST(seq + ?, ?)"
)

const (
	TestIndexAliasSeqAddLeastExpr = "test_index_alias.seq = LEAST(test_index_alias.seq + ?, ?)"
)

const (
	TestIndexSeqSubGreatestExpr = "seq = GREATEST(seq - ?, ?)"
)

const (
	TestIndexAliasSeqSubGreatestExpr = "test_index_alias.seq = GREATEST(test_index_alias.seq - ?, ?)"
)

const (
	TestIndexSeqClampExpr = "seq = LEAST(GREATEST(seq + ?, ?), ?)"
)

const (
	TestIndexAliasSeqClampExpr = "test_index_alias.seq = LEAST(GREATEST(test_index_alias.seq + ?, ?), ?)"
)

const (
	TestIndexIDDistinctExpr      = "DISTINCT id"
	TestIndexStartAtDistinctExpr = "DISTINCT start_at"
	TestIndexEndAtDistinctExpr   = "DISTINCT end_at"
	TestIndexSeqDistinctExpr     = "DISTINCT seq"
)

const (
	TestIndexAliasIDDistinctExpr      = "DISTINCT test_index_alias.id"
	TestIndexAliasStartAtDistinctExpr = "DISTINCT test_index_alias.start_at"
	TestIndexAliasEndAtDistinctExpr   = "DISTINCT test_index_alias.end_at"
	TestIndexAliasSeqDistinctExpr     = "DISTINCT test_index_alias.seq"
)

// COUNT(DISTINCT ...) expressions
const (
	TestIndexIDCountDistinctExpr      = "COUNT(DISTINCT id)"
	TestIndexStartAtCountDistinctExpr = "COUNT(DISTINCT start_at)"
	TestIndexEndAtCountDistinctExpr   = "COUNT(DISTINCT end_at)"
	TestIndexSeqCountDistinctExpr     = "COUNT(DISTINCT seq)"
)

const (
	TestIndexAliasIDCountDistinctExpr      = "COUNT(DISTINCT test_index_alias.id)"
	TestIndexAliasStartAtCountDistinctExpr = "COUNT(DISTINCT test_index_alias.start_at)"
	TestIndexAliasEndAtCountDistinctExpr   = "COUNT(DISTINCT test_index_alias.end_at)"
	TestIndexAliasSeqCountDistinctExpr     = "COUNT(DISTINCT test_index_alias.seq)"
)

const (
	TestIndexIDIn      = "id IN (?)"
	TestIndexStartAtIn = "start_at IN (?)"
	TestIndexEndAtIn   = "end_at IN (?)"
	TestIndexSeqIn     = "seq IN (?)"
)

const (
	TestIndexAliasIDIn      = "test_index_alias.id IN (?)"
	TestIndexAliasStartAtIn = "test_index_alias.start_at IN (?)"
	TestIndexAliasEndAtIn   = "test_index_alias.end_at IN (?)"
	TestIndexAliasSeqIn     = "test_index_alias.seq IN (?)"
)

const (
	TestIndexIDNotIn      = "id NOT IN (?)"
	TestIndexStartAtNotIn = "start_at NOT IN (?)"
	TestIndexEndAtNotIn   = "end_at NOT IN (?)"
	TestIndexSeqNotIn     = "seq NOT IN (?)"
)

const (
	TestIndexAliasIDNotIn      = "test_index_alias.id NOT IN (?)"
	TestIndexAliasStartAtNotIn = "test_index_alias.start_at NOT IN (?)"
	TestIndexAliasEndAtNotIn   = "test_index_alias.end_at NOT IN (?)"
	TestIndexAliasSeqNotIn     = "test_index_alias.seq NOT IN (?)"
)

const (
	TestIndexIDBetween      = "id BETWEEN ? AND ?"
	TestIndexStartAtBetween = "start_at BETWEEN ? AND ?"
	TestIndexEndAtBetween   = "end_at BETWEEN ? AND ?"
	TestIndexSeqBetween     = "seq BETWEEN ? AND ?"
)

const (
	TestIndexAliasIDBetween      = "test_index_alias.id BETWEEN ? AND ?"
	TestIndexAliasStartAtBetween = "test_index_alias.start_at BETWEEN ? AND ?"
	TestIndexAliasEndAtBetween   = "test_index_alias.end_at BETWEEN ? AND ?"
	TestIndexAliasSeqBetween     = "test_index_alias.seq BETWEEN ? AND ?"
)

const (
	TestIndexIDNotBetween      = "id NOT BETWEEN ? AND ?"
	TestIndexStartAtNotBetween = "start_at NOT BETWEEN ? AND ?"
	TestIndexEndAtNotBetween   = "end_at NOT BETWEEN ? AND ?"
	TestIndexSeqNotBetween     = "seq NOT BETWEEN ? AND ?"
)

const (
	TestIndexAliasIDNotBetween      = "test_index_alias.id NOT BETWEEN ? AND ?"
	TestIndexAliasStartAtNotBetween = "test_index_alias.start_at NOT BETWEEN ? AND ?"
	TestIndexAliasEndAtNotBetween   = "test_index_alias.end_at NOT BETWEEN ? AND ?"
	TestIndexAliasSeqNotBetween     = "test_index_alias.seq NOT BETWEEN ? AND ?"
)

const (
	TestIndexStartAtDateExpr = "DATE(start_at)"
	TestIndexEndAtDateExpr   = "DATE(end_at)"
)

const (
	TestIndexAliasStartAtDateExpr = "DATE(test_index_alias.start_at)"
	TestIndexAliasEndAtDateExpr   = "DATE(test_index_alias.end_at)"
)

const (
	TestIndexStartAtYearExpr = "EXTRACT(YEAR FROM start_at)"
	TestIndexEndAtYearExpr   = "EXTRACT(YEAR FROM end_at)"
)

const (
	TestIndexAliasStartAtYearExpr = "EXTRACT(YEAR FROM test_index_alias.start_at)"
	TestIndexAliasEndAtYearExpr   = "EXTRACT(YEAR FROM test_index_alias.end_at)"
)

const (
	TestIndexStartAtMonthExpr = "EXTRACT(MONTH FROM start_at)"
	TestIndexEndAtMonthExpr   = "EXTRACT(MONTH FROM end_at)"
)

const (
	TestIndexAliasStartAtMonthExpr = "EXTRACT(MONTH FROM test_index_alias.start_at)"
	TestIndexAliasEndAtMonthExpr   = "EXTRACT(MONTH FROM test_index_alias.end_at)"
)

const (
	TestIndexStartAtDayExpr = "EXTRACT(DAY FROM start_at)"
	TestIndexEndAtDayExpr   = "EXTRACT(DAY FROM end_at)"
)

const (
	TestIndexAliasStartAtDayExpr = "EXTRACT(DAY FROM test_index_alias.start_at)"
	TestIndexAliasEndAtDayExpr   = "EXTRACT(DAY FROM test_index_alias.end_at)"
)

const (
	TestIndexStartAtHourExpr = "EXTRACT(HOUR FROM start_at)"
	TestIndexEndAtHourExpr   = "EXTRACT(HOUR FROM end_at)"
)

const (
	TestIndexAliasStartAtHourExpr = "EXTRACT(HOUR FROM test_index_alias.start_at)"
	TestIndexAliasEndAtHourExpr   = "EXTRACT(HOUR FROM test_index_alias.end_at)"
)

const (
	TestIndexStartAtMinuteExpr = "EXTRACT(MINUTE FROM start_at)"
	TestIndexEndAtMinuteExpr   = "EXTRACT(MINUTE FROM end_at)"
)

const (
	TestIndexAliasStartAtMinuteExpr = "EXTRACT(MINUTE FROM test_index_alias.start_at)"
	TestIndexAliasEndAtMinuteExpr   = "EXTRACT(MINUTE FROM test_index_alias.end_at)"
)

const (
	TestIndexStartAtSecondExpr = "EXTRACT(SECOND FROM start_at)"
	TestIndexEndAtSecondExpr   = "EXTRACT(SECOND FROM end_at)"
)

const (
	TestIndexAliasStartAtSecondExpr = "EXTRACT(SECOND FROM test_index_alias.start_at)"
	TestIndexAliasEndAtSecondExpr   = "EXTRACT(SECOND FROM test_index_alias.end_at)"
)

const (
	TestIndexIDAsc      = "id ASC"
	TestIndexStartAtAsc = "start_at ASC"
	TestIndexEndAtAsc   = "end_at ASC"
	TestIndexSeqAsc     = "seq ASC"
)

const (
	TestIndexAliasIDAsc      = "test_index_alias.id ASC"
	TestIndexAliasStartAtAsc = "test_index_alias.start_at ASC"
	TestIndexAliasEndAtAsc   = "test_index_alias.end_at ASC"
	TestIndexAliasSeqAsc     = "test_index_alias.seq ASC"
)

const (
	TestIndexIDDesc      = "id DESC"
	TestIndexStartAtDesc = "start_at DESC"
	TestIndexEndAtDesc   = "end_at DESC"
	TestIndexSeqDesc     = "seq DESC"
)

const (
	TestIndexAliasIDDesc      = "test_index_alias.id DESC"
	TestIndexAliasStartAtDesc = "test_index_alias.start_at DESC"
	TestIndexAliasEndAtDesc   = "test_index_alias.end_at DESC"
	TestIndexAliasSeqDesc     = "test_index_alias.seq DESC"
)

// TestIndex generates a model for the "test_index" table.
type TestIndex struct {
	bun.BaseModel `bun:"table:test_index,alias:test_index_alias"`

	ID      int32     `bun:"id,pk,unique,autoincrement,notnull" json:"id,omitempty"` //
	StartAt time.Time `bun:"start_at,notnull" json:"start_at,omitempty"`             //
	EndAt   time.Time `bun:"end_at,notnull" json:"end_at,omitempty"`                 //
	Seq     int64     `bun:"seq,unique,notnull" json:"seq,omitempty"`                //
}

func (m *TestIndex) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	return nil
}

func (m *TestIndex) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	return nil
}
