// Code generated by bake. DO NOT EDIT.
// version: v0.0.1
// source: users

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilUser = (*User)(nil)

var (
	_ bun.BeforeInsertHook = (*User)(nil)
	_ bun.BeforeUpdateHook = (*User)(nil)
)

const (
	UserTableName  = "users"
	UserTableAlias = "users_alias"
)

var (
	UserTableNameIdent  = bun.Ident("users")
	UserTableAliasIdent = bun.Ident("users_alias")
)

const (
	InnerJoinUserAsAlias = "INNER JOIN users AS users_alias" // same as JOIN
	LeftJoinUserAsAlias  = "LEFT JOIN users AS users_alias"  // same as LEFT OUTER JOIN
	RightJoinUserAsAlias = "RIGHT JOIN users AS users_alias" // same as RIGHT OUTER JOIN
	FullJoinUserAsAlias  = "FULL JOIN users AS users_alias"  // same as FULL OUTER JOIN
)

const (
	UserID        = "id"
	UserUsername  = "username"
	UserEmail     = "email"
	UserAge       = "age"
	UserStatus    = "status"
	UserCreatedAt = "created_at"
	UserUpdatedAt = "updated_at"
)

const (
	UserAliasID        = "users_alias.id"
	UserAliasUsername  = "users_alias.username"
	UserAliasEmail     = "users_alias.email"
	UserAliasAge       = "users_alias.age"
	UserAliasStatus    = "users_alias.status"
	UserAliasCreatedAt = "users_alias.created_at"
	UserAliasUpdatedAt = "users_alias.updated_at"
)

var (
	UserIDIdent        = bun.Ident("id")
	UserUsernameIdent  = bun.Ident("username")
	UserEmailIdent     = bun.Ident("email")
	UserAgeIdent       = bun.Ident("age")
	UserStatusIdent    = bun.Ident("status")
	UserCreatedAtIdent = bun.Ident("created_at")
	UserUpdatedAtIdent = bun.Ident("updated_at")
)

const (
	UserIDEq        = "id = ?"
	UserUsernameEq  = "username = ?"
	UserEmailEq     = "email = ?"
	UserAgeEq       = "age = ?"
	UserStatusEq    = "status = ?"
	UserCreatedAtEq = "created_at = ?"
	UserUpdatedAtEq = "updated_at = ?"
)

const (
	UserAliasIDEq        = "users_alias.id = ?"
	UserAliasUsernameEq  = "users_alias.username = ?"
	UserAliasEmailEq     = "users_alias.email = ?"
	UserAliasAgeEq       = "users_alias.age = ?"
	UserAliasStatusEq    = "users_alias.status = ?"
	UserAliasCreatedAtEq = "users_alias.created_at = ?"
	UserAliasUpdatedAtEq = "users_alias.updated_at = ?"
)

const (
	UserIDNeq        = "id <> ?"
	UserUsernameNeq  = "username <> ?"
	UserEmailNeq     = "email <> ?"
	UserAgeNeq       = "age <> ?"
	UserStatusNeq    = "status <> ?"
	UserCreatedAtNeq = "created_at <> ?"
	UserUpdatedAtNeq = "updated_at <> ?"
)

const (
	UserAliasIDNeq        = "users_alias.id <> ?"
	UserAliasUsernameNeq  = "users_alias.username <> ?"
	UserAliasEmailNeq     = "users_alias.email <> ?"
	UserAliasAgeNeq       = "users_alias.age <> ?"
	UserAliasStatusNeq    = "users_alias.status <> ?"
	UserAliasCreatedAtNeq = "users_alias.created_at <> ?"
	UserAliasUpdatedAtNeq = "users_alias.updated_at <> ?"
)

const (
	UserIDGt        = "id > ?"
	UserAgeGt       = "age > ?"
	UserStatusGt    = "status > ?"
	UserCreatedAtGt = "created_at > ?"
	UserUpdatedAtGt = "updated_at > ?"
)

const (
	UserAliasIDGt        = "users_alias.id > ?"
	UserAliasAgeGt       = "users_alias.age > ?"
	UserAliasStatusGt    = "users_alias.status > ?"
	UserAliasCreatedAtGt = "users_alias.created_at > ?"
	UserAliasUpdatedAtGt = "users_alias.updated_at > ?"
)

const (
	UserIDGte        = "id >= ?"
	UserAgeGte       = "age >= ?"
	UserStatusGte    = "status >= ?"
	UserCreatedAtGte = "created_at >= ?"
	UserUpdatedAtGte = "updated_at >= ?"
)

const (
	UserAliasIDGte        = "users_alias.id >= ?"
	UserAliasAgeGte       = "users_alias.age >= ?"
	UserAliasStatusGte    = "users_alias.status >= ?"
	UserAliasCreatedAtGte = "users_alias.created_at >= ?"
	UserAliasUpdatedAtGte = "users_alias.updated_at >= ?"
)

const (
	UserIDLt        = "id < ?"
	UserAgeLt       = "age < ?"
	UserStatusLt    = "status < ?"
	UserCreatedAtLt = "created_at < ?"
	UserUpdatedAtLt = "updated_at < ?"
)

const (
	UserAliasIDLt        = "users_alias.id < ?"
	UserAliasAgeLt       = "users_alias.age < ?"
	UserAliasStatusLt    = "users_alias.status < ?"
	UserAliasCreatedAtLt = "users_alias.created_at < ?"
	UserAliasUpdatedAtLt = "users_alias.updated_at < ?"
)

const (
	UserIDLte        = "id <= ?"
	UserAgeLte       = "age <= ?"
	UserStatusLte    = "status <= ?"
	UserCreatedAtLte = "created_at <= ?"
	UserUpdatedAtLte = "updated_at <= ?"
)

const (
	UserAliasIDLte        = "users_alias.id <= ?"
	UserAliasAgeLte       = "users_alias.age <= ?"
	UserAliasStatusLte    = "users_alias.status <= ?"
	UserAliasCreatedAtLte = "users_alias.created_at <= ?"
	UserAliasUpdatedAtLte = "users_alias.updated_at <= ?"
)

const (
	UserUsernameLike = "username LIKE ?"
	UserEmailLike    = "email LIKE ?"
)

const (
	UserAliasUsernameLike = "users_alias.username LIKE ?"
	UserAliasEmailLike    = "users_alias.email LIKE ?"
)

const (
	UserUsernameLikePrefix = "username LIKE ?%"
	UserEmailLikePrefix    = "email LIKE ?%"
)

const (
	UserAliasUsernameLikePrefix = "users_alias.username LIKE ?%"
	UserAliasEmailLikePrefix    = "users_alias.email LIKE ?%"
)

const (
	UserUsernameLikeSuffix = "username LIKE %?"
	UserEmailLikeSuffix    = "email LIKE %?"
)

const (
	UserAliasUsernameLikeSuffix = "users_alias.username LIKE ?%"
	UserAliasEmailLikeSuffix    = "users_alias.email LIKE ?%"
)

const (
	UserUsernameLikeContain = "username LIKE %?%"
	UserEmailLikeContain    = "email LIKE %?%"
)

const (
	UserAliasUsernameLikeContain = "users_alias.username LIKE %?%"
	UserAliasEmailLikeContain    = "users_alias.email LIKE %?%"
)

const (
	UserIDSUMExpr     = "SUM(id)"
	UserAgeSUMExpr    = "SUM(age)"
	UserStatusSUMExpr = "SUM(status)"
)

const (
	UserAliasIDSUMExpr     = "SUM(id)"
	UserAliasAgeSUMExpr    = "SUM(age)"
	UserAliasStatusSUMExpr = "SUM(status)"
)

const (
	UserIDAddExpr     = "id = id + ?"
	UserAgeAddExpr    = "age = age + ?"
	UserStatusAddExpr = "status = status + ?"
)

const (
	UserAliasIDAddExpr     = "id = id + ?"
	UserAliasAgeAddExpr    = "age = age + ?"
	UserAliasStatusAddExpr = "status = status + ?"
)

const (
	UserIDSubExpr     = "id = id - ?"
	UserAgeSubExpr    = "age = age - ?"
	UserStatusSubExpr = "status = status - ?"
)

const (
	UserAliasIDSubExpr     = "id = id - ?"
	UserAliasAgeSubExpr    = "age = age - ?"
	UserAliasStatusSubExpr = "status = status - ?"
)

const (
	UserIDAddLeastExpr     = "id = LEAST(id + ?, ?)"
	UserAgeAddLeastExpr    = "age = LEAST(age + ?, ?)"
	UserStatusAddLeastExpr = "status = LEAST(status + ?, ?)"
)

const (
	UserAliasIDAddLeastExpr     = "id = LEAST(id + ?, ?)"
	UserAliasAgeAddLeastExpr    = "age = LEAST(age + ?, ?)"
	UserAliasStatusAddLeastExpr = "status = LEAST(status + ?, ?)"
)

const (
	UserIDSubGreatestExpr     = "id = GREATEST(id - ?, ?)"
	UserAgeSubGreatestExpr    = "age = GREATEST(age - ?, ?)"
	UserStatusSubGreatestExpr = "status = GREATEST(status - ?, ?)"
)

const (
	UserAliasIDSubGreatestExpr     = "id = GREATEST(id - ?, ?)"
	UserAliasAgeSubGreatestExpr    = "age = GREATEST(age - ?, ?)"
	UserAliasStatusSubGreatestExpr = "status = GREATEST(status - ?, ?)"
)

const (
	UserIDClampExpr     = "id = LEAST(GREATEST(id + ?, ?), ?)"
	UserAgeClampExpr    = "age = LEAST(GREATEST(age + ?, ?), ?)"
	UserStatusClampExpr = "status = LEAST(GREATEST(status + ?, ?), ?)"
)

const (
	UserAliasIDClampExpr     = "id = LEAST(GREATEST(id + ?, ?), ?)"
	UserAliasAgeClampExpr    = "age = LEAST(GREATEST(age + ?, ?), ?)"
	UserAliasStatusClampExpr = "status = LEAST(GREATEST(status + ?, ?), ?)"
)

const (
	UserIDIn        = "id IN (?)"
	UserUsernameIn  = "username IN (?)"
	UserEmailIn     = "email IN (?)"
	UserAgeIn       = "age IN (?)"
	UserStatusIn    = "status IN (?)"
	UserCreatedAtIn = "created_at IN (?)"
	UserUpdatedAtIn = "updated_at IN (?)"
)

const (
	UserAliasIDIn        = "users_alias.id IN (?)"
	UserAliasUsernameIn  = "users_alias.username IN (?)"
	UserAliasEmailIn     = "users_alias.email IN (?)"
	UserAliasAgeIn       = "users_alias.age IN (?)"
	UserAliasStatusIn    = "users_alias.status IN (?)"
	UserAliasCreatedAtIn = "users_alias.created_at IN (?)"
	UserAliasUpdatedAtIn = "users_alias.updated_at IN (?)"
)

const (
	UserIDNotIn        = "id NOT IN (?)"
	UserUsernameNotIn  = "username NOT IN (?)"
	UserEmailNotIn     = "email NOT IN (?)"
	UserAgeNotIn       = "age NOT IN (?)"
	UserStatusNotIn    = "status NOT IN (?)"
	UserCreatedAtNotIn = "created_at NOT IN (?)"
	UserUpdatedAtNotIn = "updated_at NOT IN (?)"
)

const (
	UserAliasIDNotIn        = "users_alias.id NOT IN (?)"
	UserAliasUsernameNotIn  = "users_alias.username NOT IN (?)"
	UserAliasEmailNotIn     = "users_alias.email NOT IN (?)"
	UserAliasAgeNotIn       = "users_alias.age NOT IN (?)"
	UserAliasStatusNotIn    = "users_alias.status NOT IN (?)"
	UserAliasCreatedAtNotIn = "users_alias.created_at NOT IN (?)"
	UserAliasUpdatedAtNotIn = "users_alias.updated_at NOT IN (?)"
)

const (
	UserAgeIsNull       = "age IS NULL"
	UserUpdatedAtIsNull = "updated_at IS NULL"
)

const (
	UserAliasAgeIsNull       = "users_alias.age IS NULL"
	UserAliasUpdatedAtIsNull = "users_alias.updated_at IS NULL"
)

const (
	UserAgeIsNotNull       = "age IS NOT NULL"
	UserUpdatedAtIsNotNull = "updated_at IS NOT NULL"
)

const (
	UserAliasAgeIsNotNull       = "users_alias.age IS NOT NULL"
	UserAliasUpdatedAtIsNotNull = "users_alias.updated_at IS NOT NULL"
)

const (
	UserIDBetween        = "id BETWEEN ? AND ?"
	UserAgeBetween       = "age BETWEEN ? AND ?"
	UserStatusBetween    = "status BETWEEN ? AND ?"
	UserCreatedAtBetween = "created_at BETWEEN ? AND ?"
	UserUpdatedAtBetween = "updated_at BETWEEN ? AND ?"
)

const (
	UserAliasIDBetween        = "users_alias.id BETWEEN ? AND ?"
	UserAliasAgeBetween       = "users_alias.age BETWEEN ? AND ?"
	UserAliasStatusBetween    = "users_alias.status BETWEEN ? AND ?"
	UserAliasCreatedAtBetween = "users_alias.created_at BETWEEN ? AND ?"
	UserAliasUpdatedAtBetween = "users_alias.updated_at BETWEEN ? AND ?"
)

const (
	UserIDNotBetween        = "id NOT BETWEEN ? AND ?"
	UserAgeNotBetween       = "age NOT BETWEEN ? AND ?"
	UserStatusNotBetween    = "status NOT BETWEEN ? AND ?"
	UserCreatedAtNotBetween = "created_at NOT BETWEEN ? AND ?"
	UserUpdatedAtNotBetween = "updated_at NOT BETWEEN ? AND ?"
)

const (
	UserAliasIDNotBetween        = "users_alias.id NOT BETWEEN ? AND ?"
	UserAliasAgeNotBetween       = "users_alias.age NOT BETWEEN ? AND ?"
	UserAliasStatusNotBetween    = "users_alias.status NOT BETWEEN ? AND ?"
	UserAliasCreatedAtNotBetween = "users_alias.created_at NOT BETWEEN ? AND ?"
	UserAliasUpdatedAtNotBetween = "users_alias.updated_at NOT BETWEEN ? AND ?"
)

const (
	UserIDAsc        = "id ASC"
	UserUsernameAsc  = "username ASC"
	UserEmailAsc     = "email ASC"
	UserAgeAsc       = "age ASC"
	UserStatusAsc    = "status ASC"
	UserCreatedAtAsc = "created_at ASC"
	UserUpdatedAtAsc = "updated_at ASC"
)

const (
	UserAliasIDAsc        = "users_alias.id ASC"
	UserAliasUsernameAsc  = "users_alias.username ASC"
	UserAliasEmailAsc     = "users_alias.email ASC"
	UserAliasAgeAsc       = "users_alias.age ASC"
	UserAliasStatusAsc    = "users_alias.status ASC"
	UserAliasCreatedAtAsc = "users_alias.created_at ASC"
	UserAliasUpdatedAtAsc = "users_alias.updated_at ASC"
)

const (
	UserIDDesc        = "id DESC"
	UserUsernameDesc  = "username DESC"
	UserEmailDesc     = "email DESC"
	UserAgeDesc       = "age DESC"
	UserStatusDesc    = "status DESC"
	UserCreatedAtDesc = "created_at DESC"
	UserUpdatedAtDesc = "updated_at DESC"
)

const (
	UserAliasIDDesc        = "users_alias.id DESC"
	UserAliasUsernameDesc  = "users_alias.username DESC"
	UserAliasEmailDesc     = "users_alias.email DESC"
	UserAliasAgeDesc       = "users_alias.age DESC"
	UserAliasStatusDesc    = "users_alias.status DESC"
	UserAliasCreatedAtDesc = "users_alias.created_at DESC"
	UserAliasUpdatedAtDesc = "users_alias.updated_at DESC"
)

// User generates a model for the "users" table.
// user table
type User struct {
	bun.BaseModel `bun:"table:users,alias:users_alias"`
	ID            int64      `bun:"id,pk,notnull,default:'nextval('users_id_seq'::regclass)'" json:"id,omitempty"` // primary id
	Username      string     `bun:"username,notnull" json:"username,omitempty"`                                    // login username
	Email         string     `bun:"email,notnull" json:"email,omitempty"`                                          // email address
	Age           *int32     `bun:"age,notnull,default:'0'" json:"age,omitempty"`                                  // user age
	Status        int16      `bun:"status,notnull,default:'1'" json:"status,omitempty"`                            // user status
	CreatedAt     time.Time  `bun:"created_at,notnull,default:current_timestamp" json:"created_at,omitempty"`      // create time
	UpdatedAt     *time.Time `bun:"updated_at,notnull" json:"updated_at,omitempty"`                                // update time
}

func (m *User) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	now := time.Now()
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	if m.UpdatedAt == nil {
		m.UpdatedAt = &now
	}

	return nil
}

func (m *User) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	now := time.Now()
	if m.UpdatedAt == nil {
		m.UpdatedAt = &now
	}

	return nil
}
