// Code generated by bake. DO NOT EDIT.
// version: v0.2.1

package model
import (
	"database/sql/driver"
	"encoding/json"
	"errors"
)
// Address value object stored as JSONB
type Address struct {
	City string `json:"city,omitempty"` //
	// GPS coordinates
	// (latitude, longitude)
	Coordinates []float64 `json:"coordinates,omitempty"`
	Country     string    `json:"country,omitempty"`  // Country code (ISO 3166-1 alpha-2)
	Street      string    `json:"street,omitempty"`   //
	ZipCode     string    `json:"zip_code,omitempty"` // Postal code
}

func (o *Address) Scan(src any) error {
	if src == nil {
		return nil
	}
	switch v := src.(type) {
	case []byte:
		return json.Unmarshal(v, o)
	case string:
		return json.Unmarshal([]byte(v), o)
	default:
		return errors.New("unsupported type")
	}
}

func (o Address) Value() (driver.Value, error) {
	return json.Marshal(o)
}
