// Code generated by bake. DO NOT EDIT.
// version: v0.2.1

package model
import (
	"database/sql/driver"
	"encoding/json"
	"errors"
)
// Application configuration stored as JSONB
type Config struct {
	// A detailed description
	// of the configuration
	// with multiple lines
	Description     string `json:"description,omitempty"`
	Locale          string `json:"locale,omitempty"`           // User locale
	Notifications   bool   `json:"notifications,omitempty"`    // Enable push notifications
	RefreshInterval int    `json:"refresh_interval,omitempty"` // Auto-refresh interval in seconds
	Theme           string `json:"theme,omitempty"`            // UI theme (light/dark)
}

func (o *Config) Scan(src any) error {
	if src == nil {
		return nil
	}
	switch v := src.(type) {
	case []byte:
		return json.Unmarshal(v, o)
	case string:
		return json.Unmarshal([]byte(v), o)
	default:
		return errors.New("unsupported type")
	}
}

func (o Config) Value() (driver.Value, error) {
	return json.Marshal(o)
}
