// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: mail

// Package model defines database models generated from schema.
package model

import (
	"github.com/uptrace/bun"
)

const MailTableAlias = "mail_alias"

const MailTableNameAsAlias = "mail AS mail_alias"

var MailTableAliasIdent = bun.Ident("mail_alias")

const (
	InnerJoinMailAsAlias = "INNER JOIN mail AS mail_alias" // same as JOIN
	LeftJoinMailAsAlias  = "LEFT JOIN mail AS mail_alias"  // same as LEFT OUTER JOIN
	RightJoinMailAsAlias = "RIGHT JOIN mail AS mail_alias" // same as RIGHT OUTER JOIN
)

const (
	MailAliasID                  = "mail_alias.id"
	MailAliasUID                 = "mail_alias.uid"
	MailAliasSubject             = "mail_alias.subject"
	MailAliasContent             = "mail_alias.content"
	MailAliasStatus              = "mail_alias.status"
	MailAliasCustomHasAttachment = "mail_alias.has_attachment"
	MailAliasCreatedAt           = "mail_alias.created_at"
	MailAliasUpdatedAt           = "mail_alias.updated_at"
)

var (
	MailIDAliasIdent                  = bun.Ident("mail_alias.id")
	MailUIDAliasIdent                 = bun.Ident("mail_alias.uid")
	MailSubjectAliasIdent             = bun.Ident("mail_alias.subject")
	MailContentAliasIdent             = bun.Ident("mail_alias.content")
	MailStatusAliasIdent              = bun.Ident("mail_alias.status")
	MailCustomHasAttachmentAliasIdent = bun.Ident("mail_alias.has_attachment")
	MailCreatedAtAliasIdent           = bun.Ident("mail_alias.created_at")
	MailUpdatedAtAliasIdent           = bun.Ident("mail_alias.updated_at")
)

const (
	MailAliasIDEq                  = "mail_alias.id = ?"
	MailAliasUIDEq                 = "mail_alias.uid = ?"
	MailAliasSubjectEq             = "mail_alias.subject = ?"
	MailAliasContentEq             = "mail_alias.content = ?"
	MailAliasStatusEq              = "mail_alias.status = ?"
	MailAliasCustomHasAttachmentEq = "mail_alias.has_attachment = ?"
	MailAliasCreatedAtEq           = "mail_alias.created_at = ?"
	MailAliasUpdatedAtEq           = "mail_alias.updated_at = ?"
)

const (
	MailAliasIDNeq                  = "mail_alias.id <> ?"
	MailAliasUIDNeq                 = "mail_alias.uid <> ?"
	MailAliasSubjectNeq             = "mail_alias.subject <> ?"
	MailAliasContentNeq             = "mail_alias.content <> ?"
	MailAliasStatusNeq              = "mail_alias.status <> ?"
	MailAliasCustomHasAttachmentNeq = "mail_alias.has_attachment <> ?"
	MailAliasCreatedAtNeq           = "mail_alias.created_at <> ?"
	MailAliasUpdatedAtNeq           = "mail_alias.updated_at <> ?"
)

const (
	MailAliasIDGt                  = "mail_alias.id > ?"
	MailAliasUIDGt                 = "mail_alias.uid > ?"
	MailAliasStatusGt              = "mail_alias.status > ?"
	MailAliasCustomHasAttachmentGt = "mail_alias.has_attachment > ?"
	MailAliasCreatedAtGt           = "mail_alias.created_at > ?"
	MailAliasUpdatedAtGt           = "mail_alias.updated_at > ?"
)

const (
	MailAliasIDGte                  = "mail_alias.id >= ?"
	MailAliasUIDGte                 = "mail_alias.uid >= ?"
	MailAliasStatusGte              = "mail_alias.status >= ?"
	MailAliasCustomHasAttachmentGte = "mail_alias.has_attachment >= ?"
	MailAliasCreatedAtGte           = "mail_alias.created_at >= ?"
	MailAliasUpdatedAtGte           = "mail_alias.updated_at >= ?"
)

const (
	MailAliasIDLt                  = "mail_alias.id < ?"
	MailAliasUIDLt                 = "mail_alias.uid < ?"
	MailAliasStatusLt              = "mail_alias.status < ?"
	MailAliasCustomHasAttachmentLt = "mail_alias.has_attachment < ?"
	MailAliasCreatedAtLt           = "mail_alias.created_at < ?"
	MailAliasUpdatedAtLt           = "mail_alias.updated_at < ?"
)

const (
	MailAliasIDLte                  = "mail_alias.id <= ?"
	MailAliasUIDLte                 = "mail_alias.uid <= ?"
	MailAliasStatusLte              = "mail_alias.status <= ?"
	MailAliasCustomHasAttachmentLte = "mail_alias.has_attachment <= ?"
	MailAliasCreatedAtLte           = "mail_alias.created_at <= ?"
	MailAliasUpdatedAtLte           = "mail_alias.updated_at <= ?"
)

const (
	MailAliasSubjectLike = "mail_alias.subject LIKE ?"
	MailAliasContentLike = "mail_alias.content LIKE ?"
)

const (
	MailAliasSubjectLikePrefix = "mail_alias.subject LIKE ?%"
	MailAliasContentLikePrefix = "mail_alias.content LIKE ?%"
)

const (
	MailAliasSubjectLikeSuffix = "mail_alias.subject LIKE %?"
	MailAliasContentLikeSuffix = "mail_alias.content LIKE %?"
)

const (
	MailAliasSubjectLikeContain = "mail_alias.subject LIKE %?%"
	MailAliasContentLikeContain = "mail_alias.content LIKE %?%"
)

const (
	MailAliasSubjectConcatExpr = "mail_alias.subject = CONCAT(mail_alias.subject, ?)"
	MailAliasContentConcatExpr = "mail_alias.content = CONCAT(mail_alias.content, ?)"
)

const (
	MailAliasUIDSUMExpr                 = "SUM(mail_alias.uid)"
	MailAliasStatusSUMExpr              = "SUM(mail_alias.status)"
	MailAliasCustomHasAttachmentSUMExpr = "SUM(mail_alias.has_attachment)"
)

const (
	MailAliasUIDAVGExpr                 = "AVG(mail_alias.uid)"
	MailAliasStatusAVGExpr              = "AVG(mail_alias.status)"
	MailAliasCustomHasAttachmentAVGExpr = "AVG(mail_alias.has_attachment)"
)

const (
	MailAliasIDMINExpr                  = "MIN(mail_alias.id)"
	MailAliasUIDMINExpr                 = "MIN(mail_alias.uid)"
	MailAliasStatusMINExpr              = "MIN(mail_alias.status)"
	MailAliasCustomHasAttachmentMINExpr = "MIN(mail_alias.has_attachment)"
	MailAliasCreatedAtMINExpr           = "MIN(mail_alias.created_at)"
	MailAliasUpdatedAtMINExpr           = "MIN(mail_alias.updated_at)"
)

const (
	MailAliasIDMAXExpr                  = "MAX(mail_alias.id)"
	MailAliasUIDMAXExpr                 = "MAX(mail_alias.uid)"
	MailAliasStatusMAXExpr              = "MAX(mail_alias.status)"
	MailAliasCustomHasAttachmentMAXExpr = "MAX(mail_alias.has_attachment)"
	MailAliasCreatedAtMAXExpr           = "MAX(mail_alias.created_at)"
	MailAliasUpdatedAtMAXExpr           = "MAX(mail_alias.updated_at)"
)

const (
	MailAliasUIDAddExpr                 = "mail_alias.uid = mail_alias.uid + ?"
	MailAliasStatusAddExpr              = "mail_alias.status = mail_alias.status + ?"
	MailAliasCustomHasAttachmentAddExpr = "mail_alias.has_attachment = mail_alias.has_attachment + ?"
)

const (
	MailAliasUIDSubExpr                 = "mail_alias.uid = mail_alias.uid - ?"
	MailAliasStatusSubExpr              = "mail_alias.status = mail_alias.status - ?"
	MailAliasCustomHasAttachmentSubExpr = "mail_alias.has_attachment = mail_alias.has_attachment - ?"
)

const (
	MailAliasUIDAddLeastExpr                 = "mail_alias.uid = LEAST(mail_alias.uid + ?, ?)"
	MailAliasStatusAddLeastExpr              = "mail_alias.status = LEAST(mail_alias.status + ?, ?)"
	MailAliasCustomHasAttachmentAddLeastExpr = "mail_alias.has_attachment = LEAST(mail_alias.has_attachment + ?, ?)"
)

const (
	MailAliasUIDSubGreatestExpr                 = "mail_alias.uid = GREATEST(mail_alias.uid - ?, ?)"
	MailAliasStatusSubGreatestExpr              = "mail_alias.status = GREATEST(mail_alias.status - ?, ?)"
	MailAliasCustomHasAttachmentSubGreatestExpr = "mail_alias.has_attachment = GREATEST(mail_alias.has_attachment - ?, ?)"
)

const (
	MailAliasUIDClampExpr                 = "mail_alias.uid = LEAST(GREATEST(mail_alias.uid + ?, ?), ?)"
	MailAliasStatusClampExpr              = "mail_alias.status = LEAST(GREATEST(mail_alias.status + ?, ?), ?)"
	MailAliasCustomHasAttachmentClampExpr = "mail_alias.has_attachment = LEAST(GREATEST(mail_alias.has_attachment + ?, ?), ?)"
)

const (
	MailAliasIDDistinctExpr                  = "DISTINCT mail_alias.id"
	MailAliasUIDDistinctExpr                 = "DISTINCT mail_alias.uid"
	MailAliasSubjectDistinctExpr             = "DISTINCT mail_alias.subject"
	MailAliasContentDistinctExpr             = "DISTINCT mail_alias.content"
	MailAliasStatusDistinctExpr              = "DISTINCT mail_alias.status"
	MailAliasCustomHasAttachmentDistinctExpr = "DISTINCT mail_alias.has_attachment"
	MailAliasCreatedAtDistinctExpr           = "DISTINCT mail_alias.created_at"
	MailAliasUpdatedAtDistinctExpr           = "DISTINCT mail_alias.updated_at"
)

const (
	MailAliasIDCountDistinctExpr                  = "COUNT(DISTINCT mail_alias.id)"
	MailAliasUIDCountDistinctExpr                 = "COUNT(DISTINCT mail_alias.uid)"
	MailAliasSubjectCountDistinctExpr             = "COUNT(DISTINCT mail_alias.subject)"
	MailAliasContentCountDistinctExpr             = "COUNT(DISTINCT mail_alias.content)"
	MailAliasStatusCountDistinctExpr              = "COUNT(DISTINCT mail_alias.status)"
	MailAliasCustomHasAttachmentCountDistinctExpr = "COUNT(DISTINCT mail_alias.has_attachment)"
	MailAliasCreatedAtCountDistinctExpr           = "COUNT(DISTINCT mail_alias.created_at)"
	MailAliasUpdatedAtCountDistinctExpr           = "COUNT(DISTINCT mail_alias.updated_at)"
)

const (
	MailAliasIDIn                  = "mail_alias.id IN (?)"
	MailAliasUIDIn                 = "mail_alias.uid IN (?)"
	MailAliasSubjectIn             = "mail_alias.subject IN (?)"
	MailAliasContentIn             = "mail_alias.content IN (?)"
	MailAliasStatusIn              = "mail_alias.status IN (?)"
	MailAliasCustomHasAttachmentIn = "mail_alias.has_attachment IN (?)"
	MailAliasCreatedAtIn           = "mail_alias.created_at IN (?)"
	MailAliasUpdatedAtIn           = "mail_alias.updated_at IN (?)"
)

const (
	MailAliasIDNotIn                  = "mail_alias.id NOT IN (?)"
	MailAliasUIDNotIn                 = "mail_alias.uid NOT IN (?)"
	MailAliasSubjectNotIn             = "mail_alias.subject NOT IN (?)"
	MailAliasContentNotIn             = "mail_alias.content NOT IN (?)"
	MailAliasStatusNotIn              = "mail_alias.status NOT IN (?)"
	MailAliasCustomHasAttachmentNotIn = "mail_alias.has_attachment NOT IN (?)"
	MailAliasCreatedAtNotIn           = "mail_alias.created_at NOT IN (?)"
	MailAliasUpdatedAtNotIn           = "mail_alias.updated_at NOT IN (?)"
)

const (
	MailAliasIDBetween                  = "mail_alias.id BETWEEN ? AND ?"
	MailAliasUIDBetween                 = "mail_alias.uid BETWEEN ? AND ?"
	MailAliasStatusBetween              = "mail_alias.status BETWEEN ? AND ?"
	MailAliasCustomHasAttachmentBetween = "mail_alias.has_attachment BETWEEN ? AND ?"
	MailAliasCreatedAtBetween           = "mail_alias.created_at BETWEEN ? AND ?"
	MailAliasUpdatedAtBetween           = "mail_alias.updated_at BETWEEN ? AND ?"
)

const (
	MailAliasIDNotBetween                  = "mail_alias.id NOT BETWEEN ? AND ?"
	MailAliasUIDNotBetween                 = "mail_alias.uid NOT BETWEEN ? AND ?"
	MailAliasStatusNotBetween              = "mail_alias.status NOT BETWEEN ? AND ?"
	MailAliasCustomHasAttachmentNotBetween = "mail_alias.has_attachment NOT BETWEEN ? AND ?"
	MailAliasCreatedAtNotBetween           = "mail_alias.created_at NOT BETWEEN ? AND ?"
	MailAliasUpdatedAtNotBetween           = "mail_alias.updated_at NOT BETWEEN ? AND ?"
)

const (
	MailAliasCreatedAtDateExpr = "DATE(mail_alias.created_at)"
	MailAliasUpdatedAtDateExpr = "DATE(mail_alias.updated_at)"
)

const (
	MailAliasCreatedAtYearExpr = "EXTRACT(YEAR FROM mail_alias.created_at)"
	MailAliasUpdatedAtYearExpr = "EXTRACT(YEAR FROM mail_alias.updated_at)"
)

const (
	MailAliasCreatedAtMonthExpr = "EXTRACT(MONTH FROM mail_alias.created_at)"
	MailAliasUpdatedAtMonthExpr = "EXTRACT(MONTH FROM mail_alias.updated_at)"
)

const (
	MailAliasCreatedAtDayExpr = "EXTRACT(DAY FROM mail_alias.created_at)"
	MailAliasUpdatedAtDayExpr = "EXTRACT(DAY FROM mail_alias.updated_at)"
)

const (
	MailAliasCreatedAtHourExpr = "EXTRACT(HOUR FROM mail_alias.created_at)"
	MailAliasUpdatedAtHourExpr = "EXTRACT(HOUR FROM mail_alias.updated_at)"
)

const (
	MailAliasCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM mail_alias.created_at)"
	MailAliasUpdatedAtMinuteExpr = "EXTRACT(MINUTE FROM mail_alias.updated_at)"
)

const (
	MailAliasCreatedAtSecondExpr = "EXTRACT(SECOND FROM mail_alias.created_at)"
	MailAliasUpdatedAtSecondExpr = "EXTRACT(SECOND FROM mail_alias.updated_at)"
)

const (
	MailAliasIDAsc                  = "mail_alias.id ASC"
	MailAliasUIDAsc                 = "mail_alias.uid ASC"
	MailAliasSubjectAsc             = "mail_alias.subject ASC"
	MailAliasContentAsc             = "mail_alias.content ASC"
	MailAliasStatusAsc              = "mail_alias.status ASC"
	MailAliasCustomHasAttachmentAsc = "mail_alias.has_attachment ASC"
	MailAliasCreatedAtAsc           = "mail_alias.created_at ASC"
	MailAliasUpdatedAtAsc           = "mail_alias.updated_at ASC"
)

const (
	MailAliasIDDesc                  = "mail_alias.id DESC"
	MailAliasUIDDesc                 = "mail_alias.uid DESC"
	MailAliasSubjectDesc             = "mail_alias.subject DESC"
	MailAliasContentDesc             = "mail_alias.content DESC"
	MailAliasStatusDesc              = "mail_alias.status DESC"
	MailAliasCustomHasAttachmentDesc = "mail_alias.has_attachment DESC"
	MailAliasCreatedAtDesc           = "mail_alias.created_at DESC"
	MailAliasUpdatedAtDesc           = "mail_alias.updated_at DESC"
)
