// Code generated by bake. DO NOT EDIT.
// version: v0.1.0
// source: mail

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilMail = (*Mail)(nil)

var (
	_ bun.BeforeInsertHook = (*Mail)(nil)
	_ bun.BeforeUpdateHook = (*Mail)(nil)
)

const (
	MailTableName  = "mail"
	MailTableAlias = "mail_alias"
)

var (
	MailTableNameIdent  = bun.Ident("mail")
	MailTableAliasIdent = bun.Ident("mail_alias")
)

const (
	InnerJoinMailAsAlias = "INNER JOIN mail AS mail_alias" // same as JOIN
	LeftJoinMailAsAlias  = "LEFT JOIN mail AS mail_alias"  // same as LEFT OUTER JOIN
	RightJoinMailAsAlias = "RIGHT JOIN mail AS mail_alias" // same as RIGHT OUTER JOIN
	FullJoinMailAsAlias  = "FULL JOIN mail AS mail_alias"  // same as FULL OUTER JOIN
)

const (
	MailID                  = "id"
	MailUID                 = "uid"
	MailSubject             = "subject"
	MailContent             = "content"
	MailStatus              = "status"
	MailCustomHasAttachment = "has_attachment"
	MailCreatedAt           = "created_at"
	MailUpdatedAt           = "updated_at"
)

const (
	MailRelationAttachments = "Attachments"
)

const (
	MailAliasID                  = "mail_alias.id"
	MailAliasUID                 = "mail_alias.uid"
	MailAliasSubject             = "mail_alias.subject"
	MailAliasContent             = "mail_alias.content"
	MailAliasStatus              = "mail_alias.status"
	MailAliasCustomHasAttachment = "mail_alias.has_attachment"
	MailAliasCreatedAt           = "mail_alias.created_at"
	MailAliasUpdatedAt           = "mail_alias.updated_at"
)

var (
	MailIDIdent                  = bun.Ident("id")
	MailUIDIdent                 = bun.Ident("uid")
	MailSubjectIdent             = bun.Ident("subject")
	MailContentIdent             = bun.Ident("content")
	MailStatusIdent              = bun.Ident("status")
	MailCustomHasAttachmentIdent = bun.Ident("has_attachment")
	MailCreatedAtIdent           = bun.Ident("created_at")
	MailUpdatedAtIdent           = bun.Ident("updated_at")
)

const (
	MailIDEq                  = "id = ?"
	MailUIDEq                 = "uid = ?"
	MailSubjectEq             = "subject = ?"
	MailContentEq             = "content = ?"
	MailStatusEq              = "status = ?"
	MailCustomHasAttachmentEq = "has_attachment = ?"
	MailCreatedAtEq           = "created_at = ?"
	MailUpdatedAtEq           = "updated_at = ?"
)

const (
	MailAliasIDEq                  = "mail_alias.id = ?"
	MailAliasUIDEq                 = "mail_alias.uid = ?"
	MailAliasSubjectEq             = "mail_alias.subject = ?"
	MailAliasContentEq             = "mail_alias.content = ?"
	MailAliasStatusEq              = "mail_alias.status = ?"
	MailAliasCustomHasAttachmentEq = "mail_alias.has_attachment = ?"
	MailAliasCreatedAtEq           = "mail_alias.created_at = ?"
	MailAliasUpdatedAtEq           = "mail_alias.updated_at = ?"
)

const (
	MailIDNeq                  = "id <> ?"
	MailUIDNeq                 = "uid <> ?"
	MailSubjectNeq             = "subject <> ?"
	MailContentNeq             = "content <> ?"
	MailStatusNeq              = "status <> ?"
	MailCustomHasAttachmentNeq = "has_attachment <> ?"
	MailCreatedAtNeq           = "created_at <> ?"
	MailUpdatedAtNeq           = "updated_at <> ?"
)

const (
	MailAliasIDNeq                  = "mail_alias.id <> ?"
	MailAliasUIDNeq                 = "mail_alias.uid <> ?"
	MailAliasSubjectNeq             = "mail_alias.subject <> ?"
	MailAliasContentNeq             = "mail_alias.content <> ?"
	MailAliasStatusNeq              = "mail_alias.status <> ?"
	MailAliasCustomHasAttachmentNeq = "mail_alias.has_attachment <> ?"
	MailAliasCreatedAtNeq           = "mail_alias.created_at <> ?"
	MailAliasUpdatedAtNeq           = "mail_alias.updated_at <> ?"
)

const (
	MailIDGt                  = "id > ?"
	MailUIDGt                 = "uid > ?"
	MailStatusGt              = "status > ?"
	MailCustomHasAttachmentGt = "has_attachment > ?"
	MailCreatedAtGt           = "created_at > ?"
	MailUpdatedAtGt           = "updated_at > ?"
)

const (
	MailAliasIDGt                  = "mail_alias.id > ?"
	MailAliasUIDGt                 = "mail_alias.uid > ?"
	MailAliasStatusGt              = "mail_alias.status > ?"
	MailAliasCustomHasAttachmentGt = "mail_alias.has_attachment > ?"
	MailAliasCreatedAtGt           = "mail_alias.created_at > ?"
	MailAliasUpdatedAtGt           = "mail_alias.updated_at > ?"
)

const (
	MailIDGte                  = "id >= ?"
	MailUIDGte                 = "uid >= ?"
	MailStatusGte              = "status >= ?"
	MailCustomHasAttachmentGte = "has_attachment >= ?"
	MailCreatedAtGte           = "created_at >= ?"
	MailUpdatedAtGte           = "updated_at >= ?"
)

const (
	MailAliasIDGte                  = "mail_alias.id >= ?"
	MailAliasUIDGte                 = "mail_alias.uid >= ?"
	MailAliasStatusGte              = "mail_alias.status >= ?"
	MailAliasCustomHasAttachmentGte = "mail_alias.has_attachment >= ?"
	MailAliasCreatedAtGte           = "mail_alias.created_at >= ?"
	MailAliasUpdatedAtGte           = "mail_alias.updated_at >= ?"
)

const (
	MailIDLt                  = "id < ?"
	MailUIDLt                 = "uid < ?"
	MailStatusLt              = "status < ?"
	MailCustomHasAttachmentLt = "has_attachment < ?"
	MailCreatedAtLt           = "created_at < ?"
	MailUpdatedAtLt           = "updated_at < ?"
)

const (
	MailAliasIDLt                  = "mail_alias.id < ?"
	MailAliasUIDLt                 = "mail_alias.uid < ?"
	MailAliasStatusLt              = "mail_alias.status < ?"
	MailAliasCustomHasAttachmentLt = "mail_alias.has_attachment < ?"
	MailAliasCreatedAtLt           = "mail_alias.created_at < ?"
	MailAliasUpdatedAtLt           = "mail_alias.updated_at < ?"
)

const (
	MailIDLte                  = "id <= ?"
	MailUIDLte                 = "uid <= ?"
	MailStatusLte              = "status <= ?"
	MailCustomHasAttachmentLte = "has_attachment <= ?"
	MailCreatedAtLte           = "created_at <= ?"
	MailUpdatedAtLte           = "updated_at <= ?"
)

const (
	MailAliasIDLte                  = "mail_alias.id <= ?"
	MailAliasUIDLte                 = "mail_alias.uid <= ?"
	MailAliasStatusLte              = "mail_alias.status <= ?"
	MailAliasCustomHasAttachmentLte = "mail_alias.has_attachment <= ?"
	MailAliasCreatedAtLte           = "mail_alias.created_at <= ?"
	MailAliasUpdatedAtLte           = "mail_alias.updated_at <= ?"
)

const (
	MailSubjectLike = "subject LIKE ?"
	MailContentLike = "content LIKE ?"
)

const (
	MailAliasSubjectLike = "mail_alias.subject LIKE ?"
	MailAliasContentLike = "mail_alias.content LIKE ?"
)

const (
	MailSubjectLikePrefix = "subject LIKE ?%"
	MailContentLikePrefix = "content LIKE ?%"
)

const (
	MailAliasSubjectLikePrefix = "mail_alias.subject LIKE ?%"
	MailAliasContentLikePrefix = "mail_alias.content LIKE ?%"
)

const (
	MailSubjectLikeSuffix = "subject LIKE %?"
	MailContentLikeSuffix = "content LIKE %?"
)

const (
	MailAliasSubjectLikeSuffix = "mail_alias.subject LIKE %?"
	MailAliasContentLikeSuffix = "mail_alias.content LIKE %?"
)

const (
	MailSubjectLikeContain = "subject LIKE %?%"
	MailContentLikeContain = "content LIKE %?%"
)

const (
	MailAliasSubjectLikeContain = "mail_alias.subject LIKE %?%"
	MailAliasContentLikeContain = "mail_alias.content LIKE %?%"
)

const (
	MailUIDSUMExpr                 = "SUM(uid)"
	MailStatusSUMExpr              = "SUM(status)"
	MailCustomHasAttachmentSUMExpr = "SUM(has_attachment)"
)

const (
	MailAliasUIDSUMExpr                 = "SUM(mail_alias.uid)"
	MailAliasStatusSUMExpr              = "SUM(mail_alias.status)"
	MailAliasCustomHasAttachmentSUMExpr = "SUM(mail_alias.has_attachment)"
)

const (
	MailUIDAVGExpr                 = "AVG(uid)"
	MailStatusAVGExpr              = "AVG(status)"
	MailCustomHasAttachmentAVGExpr = "AVG(has_attachment)"
)

const (
	MailAliasUIDAVGExpr                 = "AVG(mail_alias.uid)"
	MailAliasStatusAVGExpr              = "AVG(mail_alias.status)"
	MailAliasCustomHasAttachmentAVGExpr = "AVG(mail_alias.has_attachment)"
)

const (
	MailIDMINExpr                  = "MIN(id)"
	MailUIDMINExpr                 = "MIN(uid)"
	MailStatusMINExpr              = "MIN(status)"
	MailCustomHasAttachmentMINExpr = "MIN(has_attachment)"
	MailCreatedAtMINExpr           = "MIN(created_at)"
	MailUpdatedAtMINExpr           = "MIN(updated_at)"
)

const (
	MailAliasIDMINExpr                  = "MIN(mail_alias.id)"
	MailAliasUIDMINExpr                 = "MIN(mail_alias.uid)"
	MailAliasStatusMINExpr              = "MIN(mail_alias.status)"
	MailAliasCustomHasAttachmentMINExpr = "MIN(mail_alias.has_attachment)"
	MailAliasCreatedAtMINExpr           = "MIN(mail_alias.created_at)"
	MailAliasUpdatedAtMINExpr           = "MIN(mail_alias.updated_at)"
)

const (
	MailIDMAXExpr                  = "MAX(id)"
	MailUIDMAXExpr                 = "MAX(uid)"
	MailStatusMAXExpr              = "MAX(status)"
	MailCustomHasAttachmentMAXExpr = "MAX(has_attachment)"
	MailCreatedAtMAXExpr           = "MAX(created_at)"
	MailUpdatedAtMAXExpr           = "MAX(updated_at)"
)

const (
	MailAliasIDMAXExpr                  = "MAX(mail_alias.id)"
	MailAliasUIDMAXExpr                 = "MAX(mail_alias.uid)"
	MailAliasStatusMAXExpr              = "MAX(mail_alias.status)"
	MailAliasCustomHasAttachmentMAXExpr = "MAX(mail_alias.has_attachment)"
	MailAliasCreatedAtMAXExpr           = "MAX(mail_alias.created_at)"
	MailAliasUpdatedAtMAXExpr           = "MAX(mail_alias.updated_at)"
)

const (
	MailUIDAddExpr                 = "uid = uid + ?"
	MailStatusAddExpr              = "status = status + ?"
	MailCustomHasAttachmentAddExpr = "has_attachment = has_attachment + ?"
)

const (
	MailAliasUIDAddExpr                 = "mail_alias.uid = mail_alias.uid + ?"
	MailAliasStatusAddExpr              = "mail_alias.status = mail_alias.status + ?"
	MailAliasCustomHasAttachmentAddExpr = "mail_alias.has_attachment = mail_alias.has_attachment + ?"
)

const (
	MailUIDSubExpr                 = "uid = uid - ?"
	MailStatusSubExpr              = "status = status - ?"
	MailCustomHasAttachmentSubExpr = "has_attachment = has_attachment - ?"
)

const (
	MailAliasUIDSubExpr                 = "mail_alias.uid = mail_alias.uid - ?"
	MailAliasStatusSubExpr              = "mail_alias.status = mail_alias.status - ?"
	MailAliasCustomHasAttachmentSubExpr = "mail_alias.has_attachment = mail_alias.has_attachment - ?"
)

const (
	MailUIDAddLeastExpr                 = "uid = LEAST(uid + ?, ?)"
	MailStatusAddLeastExpr              = "status = LEAST(status + ?, ?)"
	MailCustomHasAttachmentAddLeastExpr = "has_attachment = LEAST(has_attachment + ?, ?)"
)

const (
	MailAliasUIDAddLeastExpr                 = "mail_alias.uid = LEAST(mail_alias.uid + ?, ?)"
	MailAliasStatusAddLeastExpr              = "mail_alias.status = LEAST(mail_alias.status + ?, ?)"
	MailAliasCustomHasAttachmentAddLeastExpr = "mail_alias.has_attachment = LEAST(mail_alias.has_attachment + ?, ?)"
)

const (
	MailUIDSubGreatestExpr                 = "uid = GREATEST(uid - ?, ?)"
	MailStatusSubGreatestExpr              = "status = GREATEST(status - ?, ?)"
	MailCustomHasAttachmentSubGreatestExpr = "has_attachment = GREATEST(has_attachment - ?, ?)"
)

const (
	MailAliasUIDSubGreatestExpr                 = "mail_alias.uid = GREATEST(mail_alias.uid - ?, ?)"
	MailAliasStatusSubGreatestExpr              = "mail_alias.status = GREATEST(mail_alias.status - ?, ?)"
	MailAliasCustomHasAttachmentSubGreatestExpr = "mail_alias.has_attachment = GREATEST(mail_alias.has_attachment - ?, ?)"
)

const (
	MailUIDClampExpr                 = "uid = LEAST(GREATEST(uid + ?, ?), ?)"
	MailStatusClampExpr              = "status = LEAST(GREATEST(status + ?, ?), ?)"
	MailCustomHasAttachmentClampExpr = "has_attachment = LEAST(GREATEST(has_attachment + ?, ?), ?)"
)

const (
	MailAliasUIDClampExpr                 = "mail_alias.uid = LEAST(GREATEST(mail_alias.uid + ?, ?), ?)"
	MailAliasStatusClampExpr              = "mail_alias.status = LEAST(GREATEST(mail_alias.status + ?, ?), ?)"
	MailAliasCustomHasAttachmentClampExpr = "mail_alias.has_attachment = LEAST(GREATEST(mail_alias.has_attachment + ?, ?), ?)"
)

const (
	MailIDIn                  = "id IN (?)"
	MailUIDIn                 = "uid IN (?)"
	MailSubjectIn             = "subject IN (?)"
	MailContentIn             = "content IN (?)"
	MailStatusIn              = "status IN (?)"
	MailCustomHasAttachmentIn = "has_attachment IN (?)"
	MailCreatedAtIn           = "created_at IN (?)"
	MailUpdatedAtIn           = "updated_at IN (?)"
)

const (
	MailAliasIDIn                  = "mail_alias.id IN (?)"
	MailAliasUIDIn                 = "mail_alias.uid IN (?)"
	MailAliasSubjectIn             = "mail_alias.subject IN (?)"
	MailAliasContentIn             = "mail_alias.content IN (?)"
	MailAliasStatusIn              = "mail_alias.status IN (?)"
	MailAliasCustomHasAttachmentIn = "mail_alias.has_attachment IN (?)"
	MailAliasCreatedAtIn           = "mail_alias.created_at IN (?)"
	MailAliasUpdatedAtIn           = "mail_alias.updated_at IN (?)"
)

const (
	MailIDNotIn                  = "id NOT IN (?)"
	MailUIDNotIn                 = "uid NOT IN (?)"
	MailSubjectNotIn             = "subject NOT IN (?)"
	MailContentNotIn             = "content NOT IN (?)"
	MailStatusNotIn              = "status NOT IN (?)"
	MailCustomHasAttachmentNotIn = "has_attachment NOT IN (?)"
	MailCreatedAtNotIn           = "created_at NOT IN (?)"
	MailUpdatedAtNotIn           = "updated_at NOT IN (?)"
)

const (
	MailAliasIDNotIn                  = "mail_alias.id NOT IN (?)"
	MailAliasUIDNotIn                 = "mail_alias.uid NOT IN (?)"
	MailAliasSubjectNotIn             = "mail_alias.subject NOT IN (?)"
	MailAliasContentNotIn             = "mail_alias.content NOT IN (?)"
	MailAliasStatusNotIn              = "mail_alias.status NOT IN (?)"
	MailAliasCustomHasAttachmentNotIn = "mail_alias.has_attachment NOT IN (?)"
	MailAliasCreatedAtNotIn           = "mail_alias.created_at NOT IN (?)"
	MailAliasUpdatedAtNotIn           = "mail_alias.updated_at NOT IN (?)"
)

const (
	MailIDBetween                  = "id BETWEEN ? AND ?"
	MailUIDBetween                 = "uid BETWEEN ? AND ?"
	MailStatusBetween              = "status BETWEEN ? AND ?"
	MailCustomHasAttachmentBetween = "has_attachment BETWEEN ? AND ?"
	MailCreatedAtBetween           = "created_at BETWEEN ? AND ?"
	MailUpdatedAtBetween           = "updated_at BETWEEN ? AND ?"
)

const (
	MailAliasIDBetween                  = "mail_alias.id BETWEEN ? AND ?"
	MailAliasUIDBetween                 = "mail_alias.uid BETWEEN ? AND ?"
	MailAliasStatusBetween              = "mail_alias.status BETWEEN ? AND ?"
	MailAliasCustomHasAttachmentBetween = "mail_alias.has_attachment BETWEEN ? AND ?"
	MailAliasCreatedAtBetween           = "mail_alias.created_at BETWEEN ? AND ?"
	MailAliasUpdatedAtBetween           = "mail_alias.updated_at BETWEEN ? AND ?"
)

const (
	MailIDNotBetween                  = "id NOT BETWEEN ? AND ?"
	MailUIDNotBetween                 = "uid NOT BETWEEN ? AND ?"
	MailStatusNotBetween              = "status NOT BETWEEN ? AND ?"
	MailCustomHasAttachmentNotBetween = "has_attachment NOT BETWEEN ? AND ?"
	MailCreatedAtNotBetween           = "created_at NOT BETWEEN ? AND ?"
	MailUpdatedAtNotBetween           = "updated_at NOT BETWEEN ? AND ?"
)

const (
	MailAliasIDNotBetween                  = "mail_alias.id NOT BETWEEN ? AND ?"
	MailAliasUIDNotBetween                 = "mail_alias.uid NOT BETWEEN ? AND ?"
	MailAliasStatusNotBetween              = "mail_alias.status NOT BETWEEN ? AND ?"
	MailAliasCustomHasAttachmentNotBetween = "mail_alias.has_attachment NOT BETWEEN ? AND ?"
	MailAliasCreatedAtNotBetween           = "mail_alias.created_at NOT BETWEEN ? AND ?"
	MailAliasUpdatedAtNotBetween           = "mail_alias.updated_at NOT BETWEEN ? AND ?"
)

const (
	MailCreatedAtDateExpr = "DATE(created_at)"
	MailUpdatedAtDateExpr = "DATE(updated_at)"
)

const (
	MailAliasCreatedAtDateExpr = "DATE(mail_alias.created_at)"
	MailAliasUpdatedAtDateExpr = "DATE(mail_alias.updated_at)"
)

const (
	MailCreatedAtYearExpr = "EXTRACT(YEAR FROM created_at)"
	MailUpdatedAtYearExpr = "EXTRACT(YEAR FROM updated_at)"
)

const (
	MailAliasCreatedAtYearExpr = "EXTRACT(YEAR FROM mail_alias.created_at)"
	MailAliasUpdatedAtYearExpr = "EXTRACT(YEAR FROM mail_alias.updated_at)"
)

const (
	MailCreatedAtMonthExpr = "EXTRACT(MONTH FROM created_at)"
	MailUpdatedAtMonthExpr = "EXTRACT(MONTH FROM updated_at)"
)

const (
	MailAliasCreatedAtMonthExpr = "EXTRACT(MONTH FROM mail_alias.created_at)"
	MailAliasUpdatedAtMonthExpr = "EXTRACT(MONTH FROM mail_alias.updated_at)"
)

const (
	MailCreatedAtDayExpr = "EXTRACT(DAY FROM created_at)"
	MailUpdatedAtDayExpr = "EXTRACT(DAY FROM updated_at)"
)

const (
	MailAliasCreatedAtDayExpr = "EXTRACT(DAY FROM mail_alias.created_at)"
	MailAliasUpdatedAtDayExpr = "EXTRACT(DAY FROM mail_alias.updated_at)"
)

const (
	MailCreatedAtHourExpr = "EXTRACT(HOUR FROM created_at)"
	MailUpdatedAtHourExpr = "EXTRACT(HOUR FROM updated_at)"
)

const (
	MailAliasCreatedAtHourExpr = "EXTRACT(HOUR FROM mail_alias.created_at)"
	MailAliasUpdatedAtHourExpr = "EXTRACT(HOUR FROM mail_alias.updated_at)"
)

const (
	MailCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM created_at)"
	MailUpdatedAtMinuteExpr = "EXTRACT(MINUTE FROM updated_at)"
)

const (
	MailAliasCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM mail_alias.created_at)"
	MailAliasUpdatedAtMinuteExpr = "EXTRACT(MINUTE FROM mail_alias.updated_at)"
)

const (
	MailCreatedAtSecondExpr = "EXTRACT(SECOND FROM created_at)"
	MailUpdatedAtSecondExpr = "EXTRACT(SECOND FROM updated_at)"
)

const (
	MailAliasCreatedAtSecondExpr = "EXTRACT(SECOND FROM mail_alias.created_at)"
	MailAliasUpdatedAtSecondExpr = "EXTRACT(SECOND FROM mail_alias.updated_at)"
)

const (
	MailIDAsc                  = "id ASC"
	MailUIDAsc                 = "uid ASC"
	MailSubjectAsc             = "subject ASC"
	MailContentAsc             = "content ASC"
	MailStatusAsc              = "status ASC"
	MailCustomHasAttachmentAsc = "has_attachment ASC"
	MailCreatedAtAsc           = "created_at ASC"
	MailUpdatedAtAsc           = "updated_at ASC"
)

const (
	MailAliasIDAsc                  = "mail_alias.id ASC"
	MailAliasUIDAsc                 = "mail_alias.uid ASC"
	MailAliasSubjectAsc             = "mail_alias.subject ASC"
	MailAliasContentAsc             = "mail_alias.content ASC"
	MailAliasStatusAsc              = "mail_alias.status ASC"
	MailAliasCustomHasAttachmentAsc = "mail_alias.has_attachment ASC"
	MailAliasCreatedAtAsc           = "mail_alias.created_at ASC"
	MailAliasUpdatedAtAsc           = "mail_alias.updated_at ASC"
)

const (
	MailIDDesc                  = "id DESC"
	MailUIDDesc                 = "uid DESC"
	MailSubjectDesc             = "subject DESC"
	MailContentDesc             = "content DESC"
	MailStatusDesc              = "status DESC"
	MailCustomHasAttachmentDesc = "has_attachment DESC"
	MailCreatedAtDesc           = "created_at DESC"
	MailUpdatedAtDesc           = "updated_at DESC"
)

const (
	MailAliasIDDesc                  = "mail_alias.id DESC"
	MailAliasUIDDesc                 = "mail_alias.uid DESC"
	MailAliasSubjectDesc             = "mail_alias.subject DESC"
	MailAliasContentDesc             = "mail_alias.content DESC"
	MailAliasStatusDesc              = "mail_alias.status DESC"
	MailAliasCustomHasAttachmentDesc = "mail_alias.has_attachment DESC"
	MailAliasCreatedAtDesc           = "mail_alias.created_at DESC"
	MailAliasUpdatedAtDesc           = "mail_alias.updated_at DESC"
)

// Mail generates a model for the "mail" table.
// user email
type Mail struct {
	bun.BaseModel `bun:"table:mail,alias:mail_alias"`

	ID                  int64             `bun:"id,pk,autoincrement,notnull" form:"id" json:"id,omitempty"`                                     // pk
	UID                 int64             `bun:"uid,notnull" form:"uid" json:"uid,omitempty"`                                                   // user id
	Subject             string            `bun:"subject,notnull" form:"subject" json:"subject,omitempty"`                                       // email subject
	Content             string            `bun:"content,notnull" form:"content" json:"content,omitempty"`                                       // email content
	Status              int8              `bun:"status,notnull,default:'0'" form:"status" json:"status,omitempty"`                              // 0: unread, 1: read, 2: collected
	CustomHasAttachment int8              `bun:"has_attachment,notnull,default:'0'" form:"has_attachment" json:"has_attachment,omitempty"`      // has attachment: 0: no, 1: yes
	CreatedAt           time.Time         `bun:"created_at,notnull,default:current_timestamp(3)" form:"created_at" json:"created_at,omitempty"` // created at
	UpdatedAt           time.Time         `bun:"updated_at,notnull,default:current_timestamp(3)" form:"updated_at" json:"updated_at,omitempty"` // updated at
	Attachments         []*MailAttachment `bun:"attachments,rel:has-many,join:id=mail_id" form:"attachments" json:"attachments,omitempty"`      // email attachments
}

func (m *Mail) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	now := time.Now()
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}
	return nil
}

func (m *Mail) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	now := time.Now()
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}
	return nil
}
