// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: mail_attachment

// Package model defines database models generated from schema.
package model

import (
	"github.com/uptrace/bun"
)

const MailAttachmentTableAlias = "mail_attachment_alias"

const MailAttachmentTableNameAsAlias = "mail_attachment AS mail_attachment_alias"

var MailAttachmentTableAliasIdent = bun.Ident("mail_attachment_alias")

const (
	InnerJoinMailAttachmentAsAlias = "INNER JOIN mail_attachment AS mail_attachment_alias" // same as JOIN
	LeftJoinMailAttachmentAsAlias  = "LEFT JOIN mail_attachment AS mail_attachment_alias"  // same as LEFT OUTER JOIN
	RightJoinMailAttachmentAsAlias = "RIGHT JOIN mail_attachment AS mail_attachment_alias" // same as RIGHT OUTER JOIN
)

const (
	MailAttachmentAliasID          = "mail_attachment_alias.id"
	MailAttachmentAliasMailID      = "mail_attachment_alias.mail_id"
	MailAttachmentAliasKind        = "mail_attachment_alias.kind"
	MailAttachmentAliasRewardID    = "mail_attachment_alias.reward_id"
	MailAttachmentAliasRewardCount = "mail_attachment_alias.reward_count"
	MailAttachmentAliasCreatedAt   = "mail_attachment_alias.created_at"
	MailAttachmentAliasUpdatedAt   = "mail_attachment_alias.updated_at"
)

var (
	MailAttachmentIDAliasIdent          = bun.Ident("mail_attachment_alias.id")
	MailAttachmentMailIDAliasIdent      = bun.Ident("mail_attachment_alias.mail_id")
	MailAttachmentKindAliasIdent        = bun.Ident("mail_attachment_alias.kind")
	MailAttachmentRewardIDAliasIdent    = bun.Ident("mail_attachment_alias.reward_id")
	MailAttachmentRewardCountAliasIdent = bun.Ident("mail_attachment_alias.reward_count")
	MailAttachmentCreatedAtAliasIdent   = bun.Ident("mail_attachment_alias.created_at")
	MailAttachmentUpdatedAtAliasIdent   = bun.Ident("mail_attachment_alias.updated_at")
)

const (
	MailAttachmentAliasIDEq          = "mail_attachment_alias.id = ?"
	MailAttachmentAliasMailIDEq      = "mail_attachment_alias.mail_id = ?"
	MailAttachmentAliasKindEq        = "mail_attachment_alias.kind = ?"
	MailAttachmentAliasRewardIDEq    = "mail_attachment_alias.reward_id = ?"
	MailAttachmentAliasRewardCountEq = "mail_attachment_alias.reward_count = ?"
	MailAttachmentAliasCreatedAtEq   = "mail_attachment_alias.created_at = ?"
	MailAttachmentAliasUpdatedAtEq   = "mail_attachment_alias.updated_at = ?"
)

const (
	MailAttachmentAliasIDNeq          = "mail_attachment_alias.id <> ?"
	MailAttachmentAliasMailIDNeq      = "mail_attachment_alias.mail_id <> ?"
	MailAttachmentAliasKindNeq        = "mail_attachment_alias.kind <> ?"
	MailAttachmentAliasRewardIDNeq    = "mail_attachment_alias.reward_id <> ?"
	MailAttachmentAliasRewardCountNeq = "mail_attachment_alias.reward_count <> ?"
	MailAttachmentAliasCreatedAtNeq   = "mail_attachment_alias.created_at <> ?"
	MailAttachmentAliasUpdatedAtNeq   = "mail_attachment_alias.updated_at <> ?"
)

const (
	MailAttachmentAliasIDGt          = "mail_attachment_alias.id > ?"
	MailAttachmentAliasMailIDGt      = "mail_attachment_alias.mail_id > ?"
	MailAttachmentAliasKindGt        = "mail_attachment_alias.kind > ?"
	MailAttachmentAliasRewardIDGt    = "mail_attachment_alias.reward_id > ?"
	MailAttachmentAliasRewardCountGt = "mail_attachment_alias.reward_count > ?"
	MailAttachmentAliasCreatedAtGt   = "mail_attachment_alias.created_at > ?"
	MailAttachmentAliasUpdatedAtGt   = "mail_attachment_alias.updated_at > ?"
)

const (
	MailAttachmentAliasIDGte          = "mail_attachment_alias.id >= ?"
	MailAttachmentAliasMailIDGte      = "mail_attachment_alias.mail_id >= ?"
	MailAttachmentAliasKindGte        = "mail_attachment_alias.kind >= ?"
	MailAttachmentAliasRewardIDGte    = "mail_attachment_alias.reward_id >= ?"
	MailAttachmentAliasRewardCountGte = "mail_attachment_alias.reward_count >= ?"
	MailAttachmentAliasCreatedAtGte   = "mail_attachment_alias.created_at >= ?"
	MailAttachmentAliasUpdatedAtGte   = "mail_attachment_alias.updated_at >= ?"
)

const (
	MailAttachmentAliasIDLt          = "mail_attachment_alias.id < ?"
	MailAttachmentAliasMailIDLt      = "mail_attachment_alias.mail_id < ?"
	MailAttachmentAliasKindLt        = "mail_attachment_alias.kind < ?"
	MailAttachmentAliasRewardIDLt    = "mail_attachment_alias.reward_id < ?"
	MailAttachmentAliasRewardCountLt = "mail_attachment_alias.reward_count < ?"
	MailAttachmentAliasCreatedAtLt   = "mail_attachment_alias.created_at < ?"
	MailAttachmentAliasUpdatedAtLt   = "mail_attachment_alias.updated_at < ?"
)

const (
	MailAttachmentAliasIDLte          = "mail_attachment_alias.id <= ?"
	MailAttachmentAliasMailIDLte      = "mail_attachment_alias.mail_id <= ?"
	MailAttachmentAliasKindLte        = "mail_attachment_alias.kind <= ?"
	MailAttachmentAliasRewardIDLte    = "mail_attachment_alias.reward_id <= ?"
	MailAttachmentAliasRewardCountLte = "mail_attachment_alias.reward_count <= ?"
	MailAttachmentAliasCreatedAtLte   = "mail_attachment_alias.created_at <= ?"
	MailAttachmentAliasUpdatedAtLte   = "mail_attachment_alias.updated_at <= ?"
)

const (
	MailAttachmentAliasMailIDSUMExpr      = "SUM(mail_attachment_alias.mail_id)"
	MailAttachmentAliasKindSUMExpr        = "SUM(mail_attachment_alias.kind)"
	MailAttachmentAliasRewardIDSUMExpr    = "SUM(mail_attachment_alias.reward_id)"
	MailAttachmentAliasRewardCountSUMExpr = "SUM(mail_attachment_alias.reward_count)"
	MailAttachmentAliasCreatedAtSUMExpr   = "SUM(mail_attachment_alias.created_at)"
	MailAttachmentAliasUpdatedAtSUMExpr   = "SUM(mail_attachment_alias.updated_at)"
)

const (
	MailAttachmentAliasMailIDAVGExpr      = "AVG(mail_attachment_alias.mail_id)"
	MailAttachmentAliasKindAVGExpr        = "AVG(mail_attachment_alias.kind)"
	MailAttachmentAliasRewardIDAVGExpr    = "AVG(mail_attachment_alias.reward_id)"
	MailAttachmentAliasRewardCountAVGExpr = "AVG(mail_attachment_alias.reward_count)"
	MailAttachmentAliasCreatedAtAVGExpr   = "AVG(mail_attachment_alias.created_at)"
	MailAttachmentAliasUpdatedAtAVGExpr   = "AVG(mail_attachment_alias.updated_at)"
)

const (
	MailAttachmentAliasIDMINExpr          = "MIN(mail_attachment_alias.id)"
	MailAttachmentAliasMailIDMINExpr      = "MIN(mail_attachment_alias.mail_id)"
	MailAttachmentAliasKindMINExpr        = "MIN(mail_attachment_alias.kind)"
	MailAttachmentAliasRewardIDMINExpr    = "MIN(mail_attachment_alias.reward_id)"
	MailAttachmentAliasRewardCountMINExpr = "MIN(mail_attachment_alias.reward_count)"
	MailAttachmentAliasCreatedAtMINExpr   = "MIN(mail_attachment_alias.created_at)"
	MailAttachmentAliasUpdatedAtMINExpr   = "MIN(mail_attachment_alias.updated_at)"
)

const (
	MailAttachmentAliasIDMAXExpr          = "MAX(mail_attachment_alias.id)"
	MailAttachmentAliasMailIDMAXExpr      = "MAX(mail_attachment_alias.mail_id)"
	MailAttachmentAliasKindMAXExpr        = "MAX(mail_attachment_alias.kind)"
	MailAttachmentAliasRewardIDMAXExpr    = "MAX(mail_attachment_alias.reward_id)"
	MailAttachmentAliasRewardCountMAXExpr = "MAX(mail_attachment_alias.reward_count)"
	MailAttachmentAliasCreatedAtMAXExpr   = "MAX(mail_attachment_alias.created_at)"
	MailAttachmentAliasUpdatedAtMAXExpr   = "MAX(mail_attachment_alias.updated_at)"
)

const (
	MailAttachmentAliasMailIDAddExpr      = "mail_attachment_alias.mail_id = mail_attachment_alias.mail_id + ?"
	MailAttachmentAliasKindAddExpr        = "mail_attachment_alias.kind = mail_attachment_alias.kind + ?"
	MailAttachmentAliasRewardIDAddExpr    = "mail_attachment_alias.reward_id = mail_attachment_alias.reward_id + ?"
	MailAttachmentAliasRewardCountAddExpr = "mail_attachment_alias.reward_count = mail_attachment_alias.reward_count + ?"
	MailAttachmentAliasCreatedAtAddExpr   = "mail_attachment_alias.created_at = mail_attachment_alias.created_at + ?"
	MailAttachmentAliasUpdatedAtAddExpr   = "mail_attachment_alias.updated_at = mail_attachment_alias.updated_at + ?"
)

const (
	MailAttachmentAliasMailIDSubExpr      = "mail_attachment_alias.mail_id = mail_attachment_alias.mail_id - ?"
	MailAttachmentAliasKindSubExpr        = "mail_attachment_alias.kind = mail_attachment_alias.kind - ?"
	MailAttachmentAliasRewardIDSubExpr    = "mail_attachment_alias.reward_id = mail_attachment_alias.reward_id - ?"
	MailAttachmentAliasRewardCountSubExpr = "mail_attachment_alias.reward_count = mail_attachment_alias.reward_count - ?"
	MailAttachmentAliasCreatedAtSubExpr   = "mail_attachment_alias.created_at = mail_attachment_alias.created_at - ?"
	MailAttachmentAliasUpdatedAtSubExpr   = "mail_attachment_alias.updated_at = mail_attachment_alias.updated_at - ?"
)

const (
	MailAttachmentAliasMailIDAddLeastExpr      = "mail_attachment_alias.mail_id = LEAST(mail_attachment_alias.mail_id + ?, ?)"
	MailAttachmentAliasKindAddLeastExpr        = "mail_attachment_alias.kind = LEAST(mail_attachment_alias.kind + ?, ?)"
	MailAttachmentAliasRewardIDAddLeastExpr    = "mail_attachment_alias.reward_id = LEAST(mail_attachment_alias.reward_id + ?, ?)"
	MailAttachmentAliasRewardCountAddLeastExpr = "mail_attachment_alias.reward_count = LEAST(mail_attachment_alias.reward_count + ?, ?)"
	MailAttachmentAliasCreatedAtAddLeastExpr   = "mail_attachment_alias.created_at = LEAST(mail_attachment_alias.created_at + ?, ?)"
	MailAttachmentAliasUpdatedAtAddLeastExpr   = "mail_attachment_alias.updated_at = LEAST(mail_attachment_alias.updated_at + ?, ?)"
)

const (
	MailAttachmentAliasMailIDSubGreatestExpr      = "mail_attachment_alias.mail_id = GREATEST(mail_attachment_alias.mail_id - ?, ?)"
	MailAttachmentAliasKindSubGreatestExpr        = "mail_attachment_alias.kind = GREATEST(mail_attachment_alias.kind - ?, ?)"
	MailAttachmentAliasRewardIDSubGreatestExpr    = "mail_attachment_alias.reward_id = GREATEST(mail_attachment_alias.reward_id - ?, ?)"
	MailAttachmentAliasRewardCountSubGreatestExpr = "mail_attachment_alias.reward_count = GREATEST(mail_attachment_alias.reward_count - ?, ?)"
	MailAttachmentAliasCreatedAtSubGreatestExpr   = "mail_attachment_alias.created_at = GREATEST(mail_attachment_alias.created_at - ?, ?)"
	MailAttachmentAliasUpdatedAtSubGreatestExpr   = "mail_attachment_alias.updated_at = GREATEST(mail_attachment_alias.updated_at - ?, ?)"
)

const (
	MailAttachmentAliasMailIDClampExpr      = "mail_attachment_alias.mail_id = LEAST(GREATEST(mail_attachment_alias.mail_id + ?, ?), ?)"
	MailAttachmentAliasKindClampExpr        = "mail_attachment_alias.kind = LEAST(GREATEST(mail_attachment_alias.kind + ?, ?), ?)"
	MailAttachmentAliasRewardIDClampExpr    = "mail_attachment_alias.reward_id = LEAST(GREATEST(mail_attachment_alias.reward_id + ?, ?), ?)"
	MailAttachmentAliasRewardCountClampExpr = "mail_attachment_alias.reward_count = LEAST(GREATEST(mail_attachment_alias.reward_count + ?, ?), ?)"
	MailAttachmentAliasCreatedAtClampExpr   = "mail_attachment_alias.created_at = LEAST(GREATEST(mail_attachment_alias.created_at + ?, ?), ?)"
	MailAttachmentAliasUpdatedAtClampExpr   = "mail_attachment_alias.updated_at = LEAST(GREATEST(mail_attachment_alias.updated_at + ?, ?), ?)"
)

const (
	MailAttachmentAliasIDDistinctExpr          = "DISTINCT mail_attachment_alias.id"
	MailAttachmentAliasMailIDDistinctExpr      = "DISTINCT mail_attachment_alias.mail_id"
	MailAttachmentAliasKindDistinctExpr        = "DISTINCT mail_attachment_alias.kind"
	MailAttachmentAliasRewardIDDistinctExpr    = "DISTINCT mail_attachment_alias.reward_id"
	MailAttachmentAliasRewardCountDistinctExpr = "DISTINCT mail_attachment_alias.reward_count"
	MailAttachmentAliasCreatedAtDistinctExpr   = "DISTINCT mail_attachment_alias.created_at"
	MailAttachmentAliasUpdatedAtDistinctExpr   = "DISTINCT mail_attachment_alias.updated_at"
)

const (
	MailAttachmentAliasIDCountDistinctExpr          = "COUNT(DISTINCT mail_attachment_alias.id)"
	MailAttachmentAliasMailIDCountDistinctExpr      = "COUNT(DISTINCT mail_attachment_alias.mail_id)"
	MailAttachmentAliasKindCountDistinctExpr        = "COUNT(DISTINCT mail_attachment_alias.kind)"
	MailAttachmentAliasRewardIDCountDistinctExpr    = "COUNT(DISTINCT mail_attachment_alias.reward_id)"
	MailAttachmentAliasRewardCountCountDistinctExpr = "COUNT(DISTINCT mail_attachment_alias.reward_count)"
	MailAttachmentAliasCreatedAtCountDistinctExpr   = "COUNT(DISTINCT mail_attachment_alias.created_at)"
	MailAttachmentAliasUpdatedAtCountDistinctExpr   = "COUNT(DISTINCT mail_attachment_alias.updated_at)"
)

const (
	MailAttachmentAliasIDIn          = "mail_attachment_alias.id IN (?)"
	MailAttachmentAliasMailIDIn      = "mail_attachment_alias.mail_id IN (?)"
	MailAttachmentAliasKindIn        = "mail_attachment_alias.kind IN (?)"
	MailAttachmentAliasRewardIDIn    = "mail_attachment_alias.reward_id IN (?)"
	MailAttachmentAliasRewardCountIn = "mail_attachment_alias.reward_count IN (?)"
	MailAttachmentAliasCreatedAtIn   = "mail_attachment_alias.created_at IN (?)"
	MailAttachmentAliasUpdatedAtIn   = "mail_attachment_alias.updated_at IN (?)"
)

const (
	MailAttachmentAliasIDNotIn          = "mail_attachment_alias.id NOT IN (?)"
	MailAttachmentAliasMailIDNotIn      = "mail_attachment_alias.mail_id NOT IN (?)"
	MailAttachmentAliasKindNotIn        = "mail_attachment_alias.kind NOT IN (?)"
	MailAttachmentAliasRewardIDNotIn    = "mail_attachment_alias.reward_id NOT IN (?)"
	MailAttachmentAliasRewardCountNotIn = "mail_attachment_alias.reward_count NOT IN (?)"
	MailAttachmentAliasCreatedAtNotIn   = "mail_attachment_alias.created_at NOT IN (?)"
	MailAttachmentAliasUpdatedAtNotIn   = "mail_attachment_alias.updated_at NOT IN (?)"
)

const (
	MailAttachmentAliasIDBetween          = "mail_attachment_alias.id BETWEEN ? AND ?"
	MailAttachmentAliasMailIDBetween      = "mail_attachment_alias.mail_id BETWEEN ? AND ?"
	MailAttachmentAliasKindBetween        = "mail_attachment_alias.kind BETWEEN ? AND ?"
	MailAttachmentAliasRewardIDBetween    = "mail_attachment_alias.reward_id BETWEEN ? AND ?"
	MailAttachmentAliasRewardCountBetween = "mail_attachment_alias.reward_count BETWEEN ? AND ?"
	MailAttachmentAliasCreatedAtBetween   = "mail_attachment_alias.created_at BETWEEN ? AND ?"
	MailAttachmentAliasUpdatedAtBetween   = "mail_attachment_alias.updated_at BETWEEN ? AND ?"
)

const (
	MailAttachmentAliasIDNotBetween          = "mail_attachment_alias.id NOT BETWEEN ? AND ?"
	MailAttachmentAliasMailIDNotBetween      = "mail_attachment_alias.mail_id NOT BETWEEN ? AND ?"
	MailAttachmentAliasKindNotBetween        = "mail_attachment_alias.kind NOT BETWEEN ? AND ?"
	MailAttachmentAliasRewardIDNotBetween    = "mail_attachment_alias.reward_id NOT BETWEEN ? AND ?"
	MailAttachmentAliasRewardCountNotBetween = "mail_attachment_alias.reward_count NOT BETWEEN ? AND ?"
	MailAttachmentAliasCreatedAtNotBetween   = "mail_attachment_alias.created_at NOT BETWEEN ? AND ?"
	MailAttachmentAliasUpdatedAtNotBetween   = "mail_attachment_alias.updated_at NOT BETWEEN ? AND ?"
)

const (
	MailAttachmentAliasIDAsc          = "mail_attachment_alias.id ASC"
	MailAttachmentAliasMailIDAsc      = "mail_attachment_alias.mail_id ASC"
	MailAttachmentAliasKindAsc        = "mail_attachment_alias.kind ASC"
	MailAttachmentAliasRewardIDAsc    = "mail_attachment_alias.reward_id ASC"
	MailAttachmentAliasRewardCountAsc = "mail_attachment_alias.reward_count ASC"
	MailAttachmentAliasCreatedAtAsc   = "mail_attachment_alias.created_at ASC"
	MailAttachmentAliasUpdatedAtAsc   = "mail_attachment_alias.updated_at ASC"
)

const (
	MailAttachmentAliasIDDesc          = "mail_attachment_alias.id DESC"
	MailAttachmentAliasMailIDDesc      = "mail_attachment_alias.mail_id DESC"
	MailAttachmentAliasKindDesc        = "mail_attachment_alias.kind DESC"
	MailAttachmentAliasRewardIDDesc    = "mail_attachment_alias.reward_id DESC"
	MailAttachmentAliasRewardCountDesc = "mail_attachment_alias.reward_count DESC"
	MailAttachmentAliasCreatedAtDesc   = "mail_attachment_alias.created_at DESC"
	MailAttachmentAliasUpdatedAtDesc   = "mail_attachment_alias.updated_at DESC"
)
