// Code generated by bake. DO NOT EDIT.
// version: v0.1.1
// source: mail_attachment

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilMailAttachment = (*MailAttachment)(nil)

var (
	_ bun.BeforeInsertHook = (*MailAttachment)(nil)
	_ bun.BeforeUpdateHook = (*MailAttachment)(nil)
)

const (
	MailAttachmentTableName  = "mail_attachment"
	MailAttachmentTableAlias = "mail_attachment_alias"
)

var (
	MailAttachmentTableNameIdent  = bun.Ident("mail_attachment")
	MailAttachmentTableAliasIdent = bun.Ident("mail_attachment_alias")
)

const (
	InnerJoinMailAttachmentAsAlias = "INNER JOIN mail_attachment AS mail_attachment_alias" // same as JOIN
	LeftJoinMailAttachmentAsAlias  = "LEFT JOIN mail_attachment AS mail_attachment_alias"  // same as LEFT OUTER JOIN
	RightJoinMailAttachmentAsAlias = "RIGHT JOIN mail_attachment AS mail_attachment_alias" // same as RIGHT OUTER JOIN
	FullJoinMailAttachmentAsAlias  = "FULL JOIN mail_attachment AS mail_attachment_alias"  // same as FULL OUTER JOIN
)

const (
	MailAttachmentID          = "id"
	MailAttachmentMailID      = "mail_id"
	MailAttachmentKind        = "kind"
	MailAttachmentRewardID    = "reward_id"
	MailAttachmentRewardCount = "reward_count"
	MailAttachmentCreatedAt   = "created_at"
	MailAttachmentUpdatedAt   = "updated_at"
)

const (
	MailAttachmentAliasID          = "mail_attachment_alias.id"
	MailAttachmentAliasMailID      = "mail_attachment_alias.mail_id"
	MailAttachmentAliasKind        = "mail_attachment_alias.kind"
	MailAttachmentAliasRewardID    = "mail_attachment_alias.reward_id"
	MailAttachmentAliasRewardCount = "mail_attachment_alias.reward_count"
	MailAttachmentAliasCreatedAt   = "mail_attachment_alias.created_at"
	MailAttachmentAliasUpdatedAt   = "mail_attachment_alias.updated_at"
)

var (
	MailAttachmentIDIdent          = bun.Ident("id")
	MailAttachmentMailIDIdent      = bun.Ident("mail_id")
	MailAttachmentKindIdent        = bun.Ident("kind")
	MailAttachmentRewardIDIdent    = bun.Ident("reward_id")
	MailAttachmentRewardCountIdent = bun.Ident("reward_count")
	MailAttachmentCreatedAtIdent   = bun.Ident("created_at")
	MailAttachmentUpdatedAtIdent   = bun.Ident("updated_at")
)

const (
	MailAttachmentIDEq          = "id = ?"
	MailAttachmentMailIDEq      = "mail_id = ?"
	MailAttachmentKindEq        = "kind = ?"
	MailAttachmentRewardIDEq    = "reward_id = ?"
	MailAttachmentRewardCountEq = "reward_count = ?"
	MailAttachmentCreatedAtEq   = "created_at = ?"
	MailAttachmentUpdatedAtEq   = "updated_at = ?"
)

const (
	MailAttachmentAliasIDEq          = "mail_attachment_alias.id = ?"
	MailAttachmentAliasMailIDEq      = "mail_attachment_alias.mail_id = ?"
	MailAttachmentAliasKindEq        = "mail_attachment_alias.kind = ?"
	MailAttachmentAliasRewardIDEq    = "mail_attachment_alias.reward_id = ?"
	MailAttachmentAliasRewardCountEq = "mail_attachment_alias.reward_count = ?"
	MailAttachmentAliasCreatedAtEq   = "mail_attachment_alias.created_at = ?"
	MailAttachmentAliasUpdatedAtEq   = "mail_attachment_alias.updated_at = ?"
)

const (
	MailAttachmentIDNeq          = "id <> ?"
	MailAttachmentMailIDNeq      = "mail_id <> ?"
	MailAttachmentKindNeq        = "kind <> ?"
	MailAttachmentRewardIDNeq    = "reward_id <> ?"
	MailAttachmentRewardCountNeq = "reward_count <> ?"
	MailAttachmentCreatedAtNeq   = "created_at <> ?"
	MailAttachmentUpdatedAtNeq   = "updated_at <> ?"
)

const (
	MailAttachmentAliasIDNeq          = "mail_attachment_alias.id <> ?"
	MailAttachmentAliasMailIDNeq      = "mail_attachment_alias.mail_id <> ?"
	MailAttachmentAliasKindNeq        = "mail_attachment_alias.kind <> ?"
	MailAttachmentAliasRewardIDNeq    = "mail_attachment_alias.reward_id <> ?"
	MailAttachmentAliasRewardCountNeq = "mail_attachment_alias.reward_count <> ?"
	MailAttachmentAliasCreatedAtNeq   = "mail_attachment_alias.created_at <> ?"
	MailAttachmentAliasUpdatedAtNeq   = "mail_attachment_alias.updated_at <> ?"
)

const (
	MailAttachmentIDGt          = "id > ?"
	MailAttachmentMailIDGt      = "mail_id > ?"
	MailAttachmentKindGt        = "kind > ?"
	MailAttachmentRewardIDGt    = "reward_id > ?"
	MailAttachmentRewardCountGt = "reward_count > ?"
	MailAttachmentCreatedAtGt   = "created_at > ?"
	MailAttachmentUpdatedAtGt   = "updated_at > ?"
)

const (
	MailAttachmentAliasIDGt          = "mail_attachment_alias.id > ?"
	MailAttachmentAliasMailIDGt      = "mail_attachment_alias.mail_id > ?"
	MailAttachmentAliasKindGt        = "mail_attachment_alias.kind > ?"
	MailAttachmentAliasRewardIDGt    = "mail_attachment_alias.reward_id > ?"
	MailAttachmentAliasRewardCountGt = "mail_attachment_alias.reward_count > ?"
	MailAttachmentAliasCreatedAtGt   = "mail_attachment_alias.created_at > ?"
	MailAttachmentAliasUpdatedAtGt   = "mail_attachment_alias.updated_at > ?"
)

const (
	MailAttachmentIDGte          = "id >= ?"
	MailAttachmentMailIDGte      = "mail_id >= ?"
	MailAttachmentKindGte        = "kind >= ?"
	MailAttachmentRewardIDGte    = "reward_id >= ?"
	MailAttachmentRewardCountGte = "reward_count >= ?"
	MailAttachmentCreatedAtGte   = "created_at >= ?"
	MailAttachmentUpdatedAtGte   = "updated_at >= ?"
)

const (
	MailAttachmentAliasIDGte          = "mail_attachment_alias.id >= ?"
	MailAttachmentAliasMailIDGte      = "mail_attachment_alias.mail_id >= ?"
	MailAttachmentAliasKindGte        = "mail_attachment_alias.kind >= ?"
	MailAttachmentAliasRewardIDGte    = "mail_attachment_alias.reward_id >= ?"
	MailAttachmentAliasRewardCountGte = "mail_attachment_alias.reward_count >= ?"
	MailAttachmentAliasCreatedAtGte   = "mail_attachment_alias.created_at >= ?"
	MailAttachmentAliasUpdatedAtGte   = "mail_attachment_alias.updated_at >= ?"
)

const (
	MailAttachmentIDLt          = "id < ?"
	MailAttachmentMailIDLt      = "mail_id < ?"
	MailAttachmentKindLt        = "kind < ?"
	MailAttachmentRewardIDLt    = "reward_id < ?"
	MailAttachmentRewardCountLt = "reward_count < ?"
	MailAttachmentCreatedAtLt   = "created_at < ?"
	MailAttachmentUpdatedAtLt   = "updated_at < ?"
)

const (
	MailAttachmentAliasIDLt          = "mail_attachment_alias.id < ?"
	MailAttachmentAliasMailIDLt      = "mail_attachment_alias.mail_id < ?"
	MailAttachmentAliasKindLt        = "mail_attachment_alias.kind < ?"
	MailAttachmentAliasRewardIDLt    = "mail_attachment_alias.reward_id < ?"
	MailAttachmentAliasRewardCountLt = "mail_attachment_alias.reward_count < ?"
	MailAttachmentAliasCreatedAtLt   = "mail_attachment_alias.created_at < ?"
	MailAttachmentAliasUpdatedAtLt   = "mail_attachment_alias.updated_at < ?"
)

const (
	MailAttachmentIDLte          = "id <= ?"
	MailAttachmentMailIDLte      = "mail_id <= ?"
	MailAttachmentKindLte        = "kind <= ?"
	MailAttachmentRewardIDLte    = "reward_id <= ?"
	MailAttachmentRewardCountLte = "reward_count <= ?"
	MailAttachmentCreatedAtLte   = "created_at <= ?"
	MailAttachmentUpdatedAtLte   = "updated_at <= ?"
)

const (
	MailAttachmentAliasIDLte          = "mail_attachment_alias.id <= ?"
	MailAttachmentAliasMailIDLte      = "mail_attachment_alias.mail_id <= ?"
	MailAttachmentAliasKindLte        = "mail_attachment_alias.kind <= ?"
	MailAttachmentAliasRewardIDLte    = "mail_attachment_alias.reward_id <= ?"
	MailAttachmentAliasRewardCountLte = "mail_attachment_alias.reward_count <= ?"
	MailAttachmentAliasCreatedAtLte   = "mail_attachment_alias.created_at <= ?"
	MailAttachmentAliasUpdatedAtLte   = "mail_attachment_alias.updated_at <= ?"
)

const (
	MailAttachmentMailIDSUMExpr      = "SUM(mail_id)"
	MailAttachmentKindSUMExpr        = "SUM(kind)"
	MailAttachmentRewardIDSUMExpr    = "SUM(reward_id)"
	MailAttachmentRewardCountSUMExpr = "SUM(reward_count)"
	MailAttachmentCreatedAtSUMExpr   = "SUM(created_at)"
	MailAttachmentUpdatedAtSUMExpr   = "SUM(updated_at)"
)

const (
	MailAttachmentAliasMailIDSUMExpr      = "SUM(mail_attachment_alias.mail_id)"
	MailAttachmentAliasKindSUMExpr        = "SUM(mail_attachment_alias.kind)"
	MailAttachmentAliasRewardIDSUMExpr    = "SUM(mail_attachment_alias.reward_id)"
	MailAttachmentAliasRewardCountSUMExpr = "SUM(mail_attachment_alias.reward_count)"
	MailAttachmentAliasCreatedAtSUMExpr   = "SUM(mail_attachment_alias.created_at)"
	MailAttachmentAliasUpdatedAtSUMExpr   = "SUM(mail_attachment_alias.updated_at)"
)

const (
	MailAttachmentMailIDAVGExpr      = "AVG(mail_id)"
	MailAttachmentKindAVGExpr        = "AVG(kind)"
	MailAttachmentRewardIDAVGExpr    = "AVG(reward_id)"
	MailAttachmentRewardCountAVGExpr = "AVG(reward_count)"
	MailAttachmentCreatedAtAVGExpr   = "AVG(created_at)"
	MailAttachmentUpdatedAtAVGExpr   = "AVG(updated_at)"
)

const (
	MailAttachmentAliasMailIDAVGExpr      = "AVG(mail_attachment_alias.mail_id)"
	MailAttachmentAliasKindAVGExpr        = "AVG(mail_attachment_alias.kind)"
	MailAttachmentAliasRewardIDAVGExpr    = "AVG(mail_attachment_alias.reward_id)"
	MailAttachmentAliasRewardCountAVGExpr = "AVG(mail_attachment_alias.reward_count)"
	MailAttachmentAliasCreatedAtAVGExpr   = "AVG(mail_attachment_alias.created_at)"
	MailAttachmentAliasUpdatedAtAVGExpr   = "AVG(mail_attachment_alias.updated_at)"
)

const (
	MailAttachmentIDMINExpr          = "MIN(id)"
	MailAttachmentMailIDMINExpr      = "MIN(mail_id)"
	MailAttachmentKindMINExpr        = "MIN(kind)"
	MailAttachmentRewardIDMINExpr    = "MIN(reward_id)"
	MailAttachmentRewardCountMINExpr = "MIN(reward_count)"
	MailAttachmentCreatedAtMINExpr   = "MIN(created_at)"
	MailAttachmentUpdatedAtMINExpr   = "MIN(updated_at)"
)

const (
	MailAttachmentAliasIDMINExpr          = "MIN(mail_attachment_alias.id)"
	MailAttachmentAliasMailIDMINExpr      = "MIN(mail_attachment_alias.mail_id)"
	MailAttachmentAliasKindMINExpr        = "MIN(mail_attachment_alias.kind)"
	MailAttachmentAliasRewardIDMINExpr    = "MIN(mail_attachment_alias.reward_id)"
	MailAttachmentAliasRewardCountMINExpr = "MIN(mail_attachment_alias.reward_count)"
	MailAttachmentAliasCreatedAtMINExpr   = "MIN(mail_attachment_alias.created_at)"
	MailAttachmentAliasUpdatedAtMINExpr   = "MIN(mail_attachment_alias.updated_at)"
)

const (
	MailAttachmentIDMAXExpr          = "MAX(id)"
	MailAttachmentMailIDMAXExpr      = "MAX(mail_id)"
	MailAttachmentKindMAXExpr        = "MAX(kind)"
	MailAttachmentRewardIDMAXExpr    = "MAX(reward_id)"
	MailAttachmentRewardCountMAXExpr = "MAX(reward_count)"
	MailAttachmentCreatedAtMAXExpr   = "MAX(created_at)"
	MailAttachmentUpdatedAtMAXExpr   = "MAX(updated_at)"
)

const (
	MailAttachmentAliasIDMAXExpr          = "MAX(mail_attachment_alias.id)"
	MailAttachmentAliasMailIDMAXExpr      = "MAX(mail_attachment_alias.mail_id)"
	MailAttachmentAliasKindMAXExpr        = "MAX(mail_attachment_alias.kind)"
	MailAttachmentAliasRewardIDMAXExpr    = "MAX(mail_attachment_alias.reward_id)"
	MailAttachmentAliasRewardCountMAXExpr = "MAX(mail_attachment_alias.reward_count)"
	MailAttachmentAliasCreatedAtMAXExpr   = "MAX(mail_attachment_alias.created_at)"
	MailAttachmentAliasUpdatedAtMAXExpr   = "MAX(mail_attachment_alias.updated_at)"
)

const (
	MailAttachmentMailIDAddExpr      = "mail_id = mail_id + ?"
	MailAttachmentKindAddExpr        = "kind = kind + ?"
	MailAttachmentRewardIDAddExpr    = "reward_id = reward_id + ?"
	MailAttachmentRewardCountAddExpr = "reward_count = reward_count + ?"
	MailAttachmentCreatedAtAddExpr   = "created_at = created_at + ?"
	MailAttachmentUpdatedAtAddExpr   = "updated_at = updated_at + ?"
)

const (
	MailAttachmentAliasMailIDAddExpr      = "mail_attachment_alias.mail_id = mail_attachment_alias.mail_id + ?"
	MailAttachmentAliasKindAddExpr        = "mail_attachment_alias.kind = mail_attachment_alias.kind + ?"
	MailAttachmentAliasRewardIDAddExpr    = "mail_attachment_alias.reward_id = mail_attachment_alias.reward_id + ?"
	MailAttachmentAliasRewardCountAddExpr = "mail_attachment_alias.reward_count = mail_attachment_alias.reward_count + ?"
	MailAttachmentAliasCreatedAtAddExpr   = "mail_attachment_alias.created_at = mail_attachment_alias.created_at + ?"
	MailAttachmentAliasUpdatedAtAddExpr   = "mail_attachment_alias.updated_at = mail_attachment_alias.updated_at + ?"
)

const (
	MailAttachmentMailIDSubExpr      = "mail_id = mail_id - ?"
	MailAttachmentKindSubExpr        = "kind = kind - ?"
	MailAttachmentRewardIDSubExpr    = "reward_id = reward_id - ?"
	MailAttachmentRewardCountSubExpr = "reward_count = reward_count - ?"
	MailAttachmentCreatedAtSubExpr   = "created_at = created_at - ?"
	MailAttachmentUpdatedAtSubExpr   = "updated_at = updated_at - ?"
)

const (
	MailAttachmentAliasMailIDSubExpr      = "mail_attachment_alias.mail_id = mail_attachment_alias.mail_id - ?"
	MailAttachmentAliasKindSubExpr        = "mail_attachment_alias.kind = mail_attachment_alias.kind - ?"
	MailAttachmentAliasRewardIDSubExpr    = "mail_attachment_alias.reward_id = mail_attachment_alias.reward_id - ?"
	MailAttachmentAliasRewardCountSubExpr = "mail_attachment_alias.reward_count = mail_attachment_alias.reward_count - ?"
	MailAttachmentAliasCreatedAtSubExpr   = "mail_attachment_alias.created_at = mail_attachment_alias.created_at - ?"
	MailAttachmentAliasUpdatedAtSubExpr   = "mail_attachment_alias.updated_at = mail_attachment_alias.updated_at - ?"
)

const (
	MailAttachmentMailIDAddLeastExpr      = "mail_id = LEAST(mail_id + ?, ?)"
	MailAttachmentKindAddLeastExpr        = "kind = LEAST(kind + ?, ?)"
	MailAttachmentRewardIDAddLeastExpr    = "reward_id = LEAST(reward_id + ?, ?)"
	MailAttachmentRewardCountAddLeastExpr = "reward_count = LEAST(reward_count + ?, ?)"
	MailAttachmentCreatedAtAddLeastExpr   = "created_at = LEAST(created_at + ?, ?)"
	MailAttachmentUpdatedAtAddLeastExpr   = "updated_at = LEAST(updated_at + ?, ?)"
)

const (
	MailAttachmentAliasMailIDAddLeastExpr      = "mail_attachment_alias.mail_id = LEAST(mail_attachment_alias.mail_id + ?, ?)"
	MailAttachmentAliasKindAddLeastExpr        = "mail_attachment_alias.kind = LEAST(mail_attachment_alias.kind + ?, ?)"
	MailAttachmentAliasRewardIDAddLeastExpr    = "mail_attachment_alias.reward_id = LEAST(mail_attachment_alias.reward_id + ?, ?)"
	MailAttachmentAliasRewardCountAddLeastExpr = "mail_attachment_alias.reward_count = LEAST(mail_attachment_alias.reward_count + ?, ?)"
	MailAttachmentAliasCreatedAtAddLeastExpr   = "mail_attachment_alias.created_at = LEAST(mail_attachment_alias.created_at + ?, ?)"
	MailAttachmentAliasUpdatedAtAddLeastExpr   = "mail_attachment_alias.updated_at = LEAST(mail_attachment_alias.updated_at + ?, ?)"
)

const (
	MailAttachmentMailIDSubGreatestExpr      = "mail_id = GREATEST(mail_id - ?, ?)"
	MailAttachmentKindSubGreatestExpr        = "kind = GREATEST(kind - ?, ?)"
	MailAttachmentRewardIDSubGreatestExpr    = "reward_id = GREATEST(reward_id - ?, ?)"
	MailAttachmentRewardCountSubGreatestExpr = "reward_count = GREATEST(reward_count - ?, ?)"
	MailAttachmentCreatedAtSubGreatestExpr   = "created_at = GREATEST(created_at - ?, ?)"
	MailAttachmentUpdatedAtSubGreatestExpr   = "updated_at = GREATEST(updated_at - ?, ?)"
)

const (
	MailAttachmentAliasMailIDSubGreatestExpr      = "mail_attachment_alias.mail_id = GREATEST(mail_attachment_alias.mail_id - ?, ?)"
	MailAttachmentAliasKindSubGreatestExpr        = "mail_attachment_alias.kind = GREATEST(mail_attachment_alias.kind - ?, ?)"
	MailAttachmentAliasRewardIDSubGreatestExpr    = "mail_attachment_alias.reward_id = GREATEST(mail_attachment_alias.reward_id - ?, ?)"
	MailAttachmentAliasRewardCountSubGreatestExpr = "mail_attachment_alias.reward_count = GREATEST(mail_attachment_alias.reward_count - ?, ?)"
	MailAttachmentAliasCreatedAtSubGreatestExpr   = "mail_attachment_alias.created_at = GREATEST(mail_attachment_alias.created_at - ?, ?)"
	MailAttachmentAliasUpdatedAtSubGreatestExpr   = "mail_attachment_alias.updated_at = GREATEST(mail_attachment_alias.updated_at - ?, ?)"
)

const (
	MailAttachmentMailIDClampExpr      = "mail_id = LEAST(GREATEST(mail_id + ?, ?), ?)"
	MailAttachmentKindClampExpr        = "kind = LEAST(GREATEST(kind + ?, ?), ?)"
	MailAttachmentRewardIDClampExpr    = "reward_id = LEAST(GREATEST(reward_id + ?, ?), ?)"
	MailAttachmentRewardCountClampExpr = "reward_count = LEAST(GREATEST(reward_count + ?, ?), ?)"
	MailAttachmentCreatedAtClampExpr   = "created_at = LEAST(GREATEST(created_at + ?, ?), ?)"
	MailAttachmentUpdatedAtClampExpr   = "updated_at = LEAST(GREATEST(updated_at + ?, ?), ?)"
)

const (
	MailAttachmentAliasMailIDClampExpr      = "mail_attachment_alias.mail_id = LEAST(GREATEST(mail_attachment_alias.mail_id + ?, ?), ?)"
	MailAttachmentAliasKindClampExpr        = "mail_attachment_alias.kind = LEAST(GREATEST(mail_attachment_alias.kind + ?, ?), ?)"
	MailAttachmentAliasRewardIDClampExpr    = "mail_attachment_alias.reward_id = LEAST(GREATEST(mail_attachment_alias.reward_id + ?, ?), ?)"
	MailAttachmentAliasRewardCountClampExpr = "mail_attachment_alias.reward_count = LEAST(GREATEST(mail_attachment_alias.reward_count + ?, ?), ?)"
	MailAttachmentAliasCreatedAtClampExpr   = "mail_attachment_alias.created_at = LEAST(GREATEST(mail_attachment_alias.created_at + ?, ?), ?)"
	MailAttachmentAliasUpdatedAtClampExpr   = "mail_attachment_alias.updated_at = LEAST(GREATEST(mail_attachment_alias.updated_at + ?, ?), ?)"
)

const (
	MailAttachmentIDIn          = "id IN (?)"
	MailAttachmentMailIDIn      = "mail_id IN (?)"
	MailAttachmentKindIn        = "kind IN (?)"
	MailAttachmentRewardIDIn    = "reward_id IN (?)"
	MailAttachmentRewardCountIn = "reward_count IN (?)"
	MailAttachmentCreatedAtIn   = "created_at IN (?)"
	MailAttachmentUpdatedAtIn   = "updated_at IN (?)"
)

const (
	MailAttachmentAliasIDIn          = "mail_attachment_alias.id IN (?)"
	MailAttachmentAliasMailIDIn      = "mail_attachment_alias.mail_id IN (?)"
	MailAttachmentAliasKindIn        = "mail_attachment_alias.kind IN (?)"
	MailAttachmentAliasRewardIDIn    = "mail_attachment_alias.reward_id IN (?)"
	MailAttachmentAliasRewardCountIn = "mail_attachment_alias.reward_count IN (?)"
	MailAttachmentAliasCreatedAtIn   = "mail_attachment_alias.created_at IN (?)"
	MailAttachmentAliasUpdatedAtIn   = "mail_attachment_alias.updated_at IN (?)"
)

const (
	MailAttachmentIDNotIn          = "id NOT IN (?)"
	MailAttachmentMailIDNotIn      = "mail_id NOT IN (?)"
	MailAttachmentKindNotIn        = "kind NOT IN (?)"
	MailAttachmentRewardIDNotIn    = "reward_id NOT IN (?)"
	MailAttachmentRewardCountNotIn = "reward_count NOT IN (?)"
	MailAttachmentCreatedAtNotIn   = "created_at NOT IN (?)"
	MailAttachmentUpdatedAtNotIn   = "updated_at NOT IN (?)"
)

const (
	MailAttachmentAliasIDNotIn          = "mail_attachment_alias.id NOT IN (?)"
	MailAttachmentAliasMailIDNotIn      = "mail_attachment_alias.mail_id NOT IN (?)"
	MailAttachmentAliasKindNotIn        = "mail_attachment_alias.kind NOT IN (?)"
	MailAttachmentAliasRewardIDNotIn    = "mail_attachment_alias.reward_id NOT IN (?)"
	MailAttachmentAliasRewardCountNotIn = "mail_attachment_alias.reward_count NOT IN (?)"
	MailAttachmentAliasCreatedAtNotIn   = "mail_attachment_alias.created_at NOT IN (?)"
	MailAttachmentAliasUpdatedAtNotIn   = "mail_attachment_alias.updated_at NOT IN (?)"
)

const (
	MailAttachmentIDBetween          = "id BETWEEN ? AND ?"
	MailAttachmentMailIDBetween      = "mail_id BETWEEN ? AND ?"
	MailAttachmentKindBetween        = "kind BETWEEN ? AND ?"
	MailAttachmentRewardIDBetween    = "reward_id BETWEEN ? AND ?"
	MailAttachmentRewardCountBetween = "reward_count BETWEEN ? AND ?"
	MailAttachmentCreatedAtBetween   = "created_at BETWEEN ? AND ?"
	MailAttachmentUpdatedAtBetween   = "updated_at BETWEEN ? AND ?"
)

const (
	MailAttachmentAliasIDBetween          = "mail_attachment_alias.id BETWEEN ? AND ?"
	MailAttachmentAliasMailIDBetween      = "mail_attachment_alias.mail_id BETWEEN ? AND ?"
	MailAttachmentAliasKindBetween        = "mail_attachment_alias.kind BETWEEN ? AND ?"
	MailAttachmentAliasRewardIDBetween    = "mail_attachment_alias.reward_id BETWEEN ? AND ?"
	MailAttachmentAliasRewardCountBetween = "mail_attachment_alias.reward_count BETWEEN ? AND ?"
	MailAttachmentAliasCreatedAtBetween   = "mail_attachment_alias.created_at BETWEEN ? AND ?"
	MailAttachmentAliasUpdatedAtBetween   = "mail_attachment_alias.updated_at BETWEEN ? AND ?"
)

const (
	MailAttachmentIDNotBetween          = "id NOT BETWEEN ? AND ?"
	MailAttachmentMailIDNotBetween      = "mail_id NOT BETWEEN ? AND ?"
	MailAttachmentKindNotBetween        = "kind NOT BETWEEN ? AND ?"
	MailAttachmentRewardIDNotBetween    = "reward_id NOT BETWEEN ? AND ?"
	MailAttachmentRewardCountNotBetween = "reward_count NOT BETWEEN ? AND ?"
	MailAttachmentCreatedAtNotBetween   = "created_at NOT BETWEEN ? AND ?"
	MailAttachmentUpdatedAtNotBetween   = "updated_at NOT BETWEEN ? AND ?"
)

const (
	MailAttachmentAliasIDNotBetween          = "mail_attachment_alias.id NOT BETWEEN ? AND ?"
	MailAttachmentAliasMailIDNotBetween      = "mail_attachment_alias.mail_id NOT BETWEEN ? AND ?"
	MailAttachmentAliasKindNotBetween        = "mail_attachment_alias.kind NOT BETWEEN ? AND ?"
	MailAttachmentAliasRewardIDNotBetween    = "mail_attachment_alias.reward_id NOT BETWEEN ? AND ?"
	MailAttachmentAliasRewardCountNotBetween = "mail_attachment_alias.reward_count NOT BETWEEN ? AND ?"
	MailAttachmentAliasCreatedAtNotBetween   = "mail_attachment_alias.created_at NOT BETWEEN ? AND ?"
	MailAttachmentAliasUpdatedAtNotBetween   = "mail_attachment_alias.updated_at NOT BETWEEN ? AND ?"
)

const (
	MailAttachmentIDAsc          = "id ASC"
	MailAttachmentMailIDAsc      = "mail_id ASC"
	MailAttachmentKindAsc        = "kind ASC"
	MailAttachmentRewardIDAsc    = "reward_id ASC"
	MailAttachmentRewardCountAsc = "reward_count ASC"
	MailAttachmentCreatedAtAsc   = "created_at ASC"
	MailAttachmentUpdatedAtAsc   = "updated_at ASC"
)

const (
	MailAttachmentAliasIDAsc          = "mail_attachment_alias.id ASC"
	MailAttachmentAliasMailIDAsc      = "mail_attachment_alias.mail_id ASC"
	MailAttachmentAliasKindAsc        = "mail_attachment_alias.kind ASC"
	MailAttachmentAliasRewardIDAsc    = "mail_attachment_alias.reward_id ASC"
	MailAttachmentAliasRewardCountAsc = "mail_attachment_alias.reward_count ASC"
	MailAttachmentAliasCreatedAtAsc   = "mail_attachment_alias.created_at ASC"
	MailAttachmentAliasUpdatedAtAsc   = "mail_attachment_alias.updated_at ASC"
)

const (
	MailAttachmentIDDesc          = "id DESC"
	MailAttachmentMailIDDesc      = "mail_id DESC"
	MailAttachmentKindDesc        = "kind DESC"
	MailAttachmentRewardIDDesc    = "reward_id DESC"
	MailAttachmentRewardCountDesc = "reward_count DESC"
	MailAttachmentCreatedAtDesc   = "created_at DESC"
	MailAttachmentUpdatedAtDesc   = "updated_at DESC"
)

const (
	MailAttachmentAliasIDDesc          = "mail_attachment_alias.id DESC"
	MailAttachmentAliasMailIDDesc      = "mail_attachment_alias.mail_id DESC"
	MailAttachmentAliasKindDesc        = "mail_attachment_alias.kind DESC"
	MailAttachmentAliasRewardIDDesc    = "mail_attachment_alias.reward_id DESC"
	MailAttachmentAliasRewardCountDesc = "mail_attachment_alias.reward_count DESC"
	MailAttachmentAliasCreatedAtDesc   = "mail_attachment_alias.created_at DESC"
	MailAttachmentAliasUpdatedAtDesc   = "mail_attachment_alias.updated_at DESC"
)

// MailAttachment generates a model for the "mail_attachment" table.
// user email attachment
type MailAttachment struct {
	bun.BaseModel `bun:"table:mail_attachment,alias:mail_attachment_alias"`

	ID          int64  `bun:"id,pk,autoincrement,notnull" json:"id,omitempty"`    // pk
	MailID      int64  `bun:"mail_id,notnull" json:"mail_id,omitempty"`           // email id
	Kind        int8   `bun:"kind,notnull,default:'0'" json:"kind,omitempty"`     // attachment kind
	RewardID    int64  `bun:"reward_id,notnull" json:"reward_id,omitempty"`       // attachment reward id
	RewardCount uint32 `bun:"reward_count,notnull" json:"reward_count,omitempty"` // attachment reward count (must > 0)
	CreatedAt   int64  `bun:"created_at,notnull" json:"created_at,omitempty"`     // created at
	UpdatedAt   int64  `bun:"updated_at,notnull" json:"updated_at,omitempty"`     // updated at
}

func (m *MailAttachment) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	now := time.Now()
	if m.CreatedAt == 0 {
		m.CreatedAt = now.UnixMilli()
	}
	if m.UpdatedAt == 0 {
		m.UpdatedAt = now.UnixMilli()
	}
	return nil
}

func (m *MailAttachment) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	now := time.Now()
	if m.UpdatedAt == 0 {
		m.UpdatedAt = now.UnixMilli()
	}
	return nil
}
