// Code generated by bake. DO NOT EDIT.
// version: v0.2.1

package model
import (
	"database/sql/driver"
	"encoding/json"
	"errors"
)
// Resource metadata stored as JSON column
type Metadata struct {
	Owner      string   `json:"owner,omitempty"`      // Resource owner UID
	Tags       []string `json:"tags,omitempty"`       // Resource tags
	Version    int64    `json:"version,omitempty"`    // Resource version number
	Visibility string   `json:"visibility,omitempty"` //
}

func (o *Metadata) Scan(src any) error {
	if src == nil {
		return nil
	}
	switch v := src.(type) {
	case []byte:
		return json.Unmarshal(v, o)
	case string:
		return json.Unmarshal([]byte(v), o)
	default:
		return errors.New("unsupported type")
	}
}

func (o Metadata) Value() (driver.Value, error) {
	return json.Marshal(o)
}
