// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: posts

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilPost = (*Post)(nil)

var (
	_ bun.BeforeInsertHook = (*Post)(nil)
	_ bun.BeforeUpdateHook = (*Post)(nil)
)

const PostTableName = "posts"

var PostTableNameIdent  = bun.Ident("posts")

const (
	PostID        = "id"
	PostUserID    = "user_id"
	PostTitle     = "title"
	PostContent   = "content"
	PostStatus    = "status"
	PostCreatedAt = "created_at"
	PostUpdatedAt = "updated_at"
)

const (
	PostRelationUser = "User"
)

var (
	PostIDIdent        = bun.Ident("id")
	PostUserIDIdent    = bun.Ident("user_id")
	PostTitleIdent     = bun.Ident("title")
	PostContentIdent   = bun.Ident("content")
	PostStatusIdent    = bun.Ident("status")
	PostCreatedAtIdent = bun.Ident("created_at")
	PostUpdatedAtIdent = bun.Ident("updated_at")
)

const (
	PostIDEq        = "id = ?"
	PostUserIDEq    = "user_id = ?"
	PostTitleEq     = "title = ?"
	PostContentEq   = "content = ?"
	PostStatusEq    = "status = ?"
	PostCreatedAtEq = "created_at = ?"
	PostUpdatedAtEq = "updated_at = ?"
)

const (
	PostIDNeq        = "id <> ?"
	PostUserIDNeq    = "user_id <> ?"
	PostTitleNeq     = "title <> ?"
	PostContentNeq   = "content <> ?"
	PostStatusNeq    = "status <> ?"
	PostCreatedAtNeq = "created_at <> ?"
	PostUpdatedAtNeq = "updated_at <> ?"
)

const (
	PostIDGt        = "id > ?"
	PostUserIDGt    = "user_id > ?"
	PostStatusGt    = "status > ?"
	PostCreatedAtGt = "created_at > ?"
	PostUpdatedAtGt = "updated_at > ?"
)

const (
	PostIDGte        = "id >= ?"
	PostUserIDGte    = "user_id >= ?"
	PostStatusGte    = "status >= ?"
	PostCreatedAtGte = "created_at >= ?"
	PostUpdatedAtGte = "updated_at >= ?"
)

const (
	PostIDLt        = "id < ?"
	PostUserIDLt    = "user_id < ?"
	PostStatusLt    = "status < ?"
	PostCreatedAtLt = "created_at < ?"
	PostUpdatedAtLt = "updated_at < ?"
)

const (
	PostIDLte        = "id <= ?"
	PostUserIDLte    = "user_id <= ?"
	PostStatusLte    = "status <= ?"
	PostCreatedAtLte = "created_at <= ?"
	PostUpdatedAtLte = "updated_at <= ?"
)

const (
	PostTitleLike   = "title LIKE ?"
	PostContentLike = "content LIKE ?"
)

const (
	PostTitleLikePrefix   = "title LIKE ?%"
	PostContentLikePrefix = "content LIKE ?%"
)

const (
	PostTitleLikeSuffix   = "title LIKE %?"
	PostContentLikeSuffix = "content LIKE %?"
)

const (
	PostTitleLikeContain   = "title LIKE %?%"
	PostContentLikeContain = "content LIKE %?%"
)

const (
	PostTitleConcatExpr   = "title = CONCAT(title, ?)"
	PostContentConcatExpr = "content = CONCAT(content, ?)"
)

const (
	PostUserIDSUMExpr = "SUM(user_id)"
	PostStatusSUMExpr = "SUM(status)"
)

const (
	PostUserIDAVGExpr = "AVG(user_id)"
	PostStatusAVGExpr = "AVG(status)"
)

const (
	PostIDMINExpr        = "MIN(id)"
	PostUserIDMINExpr    = "MIN(user_id)"
	PostStatusMINExpr    = "MIN(status)"
	PostCreatedAtMINExpr = "MIN(created_at)"
	PostUpdatedAtMINExpr = "MIN(updated_at)"
)

const (
	PostIDMAXExpr        = "MAX(id)"
	PostUserIDMAXExpr    = "MAX(user_id)"
	PostStatusMAXExpr    = "MAX(status)"
	PostCreatedAtMAXExpr = "MAX(created_at)"
	PostUpdatedAtMAXExpr = "MAX(updated_at)"
)

const (
	PostUserIDAddExpr = "user_id = user_id + ?"
	PostStatusAddExpr = "status = status + ?"
)

const (
	PostUserIDSubExpr = "user_id = user_id - ?"
	PostStatusSubExpr = "status = status - ?"
)

const (
	PostUserIDAddLeastExpr = "user_id = LEAST(user_id + ?, ?)"
	PostStatusAddLeastExpr = "status = LEAST(status + ?, ?)"
)

const (
	PostUserIDSubGreatestExpr = "user_id = GREATEST(user_id - ?, ?)"
	PostStatusSubGreatestExpr = "status = GREATEST(status - ?, ?)"
)

const (
	PostUserIDClampExpr = "user_id = LEAST(GREATEST(user_id + ?, ?), ?)"
	PostStatusClampExpr = "status = LEAST(GREATEST(status + ?, ?), ?)"
)

const (
	PostIDDistinctExpr        = "DISTINCT id"
	PostUserIDDistinctExpr    = "DISTINCT user_id"
	PostTitleDistinctExpr     = "DISTINCT title"
	PostContentDistinctExpr   = "DISTINCT content"
	PostStatusDistinctExpr    = "DISTINCT status"
	PostCreatedAtDistinctExpr = "DISTINCT created_at"
	PostUpdatedAtDistinctExpr = "DISTINCT updated_at"
)

const (
	PostIDCountDistinctExpr        = "COUNT(DISTINCT id)"
	PostUserIDCountDistinctExpr    = "COUNT(DISTINCT user_id)"
	PostTitleCountDistinctExpr     = "COUNT(DISTINCT title)"
	PostContentCountDistinctExpr   = "COUNT(DISTINCT content)"
	PostStatusCountDistinctExpr    = "COUNT(DISTINCT status)"
	PostCreatedAtCountDistinctExpr = "COUNT(DISTINCT created_at)"
	PostUpdatedAtCountDistinctExpr = "COUNT(DISTINCT updated_at)"
)

const (
	PostIDIn        = "id IN (?)"
	PostUserIDIn    = "user_id IN (?)"
	PostTitleIn     = "title IN (?)"
	PostContentIn   = "content IN (?)"
	PostStatusIn    = "status IN (?)"
	PostCreatedAtIn = "created_at IN (?)"
	PostUpdatedAtIn = "updated_at IN (?)"
)

const (
	PostIDNotIn        = "id NOT IN (?)"
	PostUserIDNotIn    = "user_id NOT IN (?)"
	PostTitleNotIn     = "title NOT IN (?)"
	PostContentNotIn   = "content NOT IN (?)"
	PostStatusNotIn    = "status NOT IN (?)"
	PostCreatedAtNotIn = "created_at NOT IN (?)"
	PostUpdatedAtNotIn = "updated_at NOT IN (?)"
)

const (
	PostContentIsNull = "content IS NULL"
)

const (
	PostContentIsNotNull = "content IS NOT NULL"
)

// COALESCE expressions (COALESCE(column, ?))
const (
	PostContentCoalesceExpr = "COALESCE(content, ?)"
)

const (
	PostIDBetween        = "id BETWEEN ? AND ?"
	PostUserIDBetween    = "user_id BETWEEN ? AND ?"
	PostStatusBetween    = "status BETWEEN ? AND ?"
	PostCreatedAtBetween = "created_at BETWEEN ? AND ?"
	PostUpdatedAtBetween = "updated_at BETWEEN ? AND ?"
)

const (
	PostIDNotBetween        = "id NOT BETWEEN ? AND ?"
	PostUserIDNotBetween    = "user_id NOT BETWEEN ? AND ?"
	PostStatusNotBetween    = "status NOT BETWEEN ? AND ?"
	PostCreatedAtNotBetween = "created_at NOT BETWEEN ? AND ?"
	PostUpdatedAtNotBetween = "updated_at NOT BETWEEN ? AND ?"
)

const (
	PostCreatedAtDateExpr = "DATE(created_at)"
	PostUpdatedAtDateExpr = "DATE(updated_at)"
)

const (
	PostCreatedAtYearExpr = "EXTRACT(YEAR FROM created_at)"
	PostUpdatedAtYearExpr = "EXTRACT(YEAR FROM updated_at)"
)

const (
	PostCreatedAtMonthExpr = "EXTRACT(MONTH FROM created_at)"
	PostUpdatedAtMonthExpr = "EXTRACT(MONTH FROM updated_at)"
)

const (
	PostCreatedAtDayExpr = "EXTRACT(DAY FROM created_at)"
	PostUpdatedAtDayExpr = "EXTRACT(DAY FROM updated_at)"
)

const (
	PostCreatedAtHourExpr = "EXTRACT(HOUR FROM created_at)"
	PostUpdatedAtHourExpr = "EXTRACT(HOUR FROM updated_at)"
)

const (
	PostCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM created_at)"
	PostUpdatedAtMinuteExpr = "EXTRACT(MINUTE FROM updated_at)"
)

const (
	PostCreatedAtSecondExpr = "EXTRACT(SECOND FROM created_at)"
	PostUpdatedAtSecondExpr = "EXTRACT(SECOND FROM updated_at)"
)

const (
	PostIDAsc        = "id ASC"
	PostUserIDAsc    = "user_id ASC"
	PostTitleAsc     = "title ASC"
	PostContentAsc   = "content ASC"
	PostStatusAsc    = "status ASC"
	PostCreatedAtAsc = "created_at ASC"
	PostUpdatedAtAsc = "updated_at ASC"
)

const (
	PostIDDesc        = "id DESC"
	PostUserIDDesc    = "user_id DESC"
	PostTitleDesc     = "title DESC"
	PostContentDesc   = "content DESC"
	PostStatusDesc    = "status DESC"
	PostCreatedAtDesc = "created_at DESC"
	PostUpdatedAtDesc = "updated_at DESC"
)

// Post generates a model for the "posts" table.
// 文章表
type Post struct {
	bun.BaseModel `bun:"table:posts,alias:posts_alias"`

	ID        int64     `bun:"id,pk,autoincrement,notnull" json:"id,omitempty" xml:"id"`                                     //
	UserID    int64     `bun:"user_id,notnull" json:"user_id,omitempty" xml:"user_id"`                                       // 用户ID
	Title     string    `bun:"title,notnull" json:"title,omitempty" xml:"title"`                                             // 标题
	Content   *string   `bun:"content,nullzero" json:"content,omitempty" xml:"content"`                                      // 内容
	Status    int8      `bun:"status,notnull,default:'0'" json:"status,omitempty" xml:"status"`                              // 状态: 0=草稿, 1=发布
	CreatedAt time.Time `bun:"created_at,notnull,default:current_timestamp(3)" json:"created_at,omitempty" xml:"created_at"` // 创建时间
	UpdatedAt time.Time `bun:"updated_at,notnull,default:current_timestamp(3)" json:"updated_at,omitempty" xml:"updated_at"` // 更新时间
	User      *User     `bun:"user,join:user_id=id,rel:belongs-to" json:"user,omitempty" xml:"user"`                         //
}

func (m *Post) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	now := time.Now().UTC()
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}
	return nil
}
func (m *Post) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	now := time.Now().UTC()
	m.UpdatedAt = now
	return nil
}
