// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: posts

// Package model defines database models generated from schema.
package model

import (
	"github.com/uptrace/bun"
)

const PostTableAlias = "posts_alias"

const PostTableNameAsAlias = "posts AS posts_alias"

var PostTableAliasIdent = bun.Ident("posts_alias")

const (
	InnerJoinPostAsAlias = "INNER JOIN posts AS posts_alias" // same as JOIN
	LeftJoinPostAsAlias  = "LEFT JOIN posts AS posts_alias"  // same as LEFT OUTER JOIN
	RightJoinPostAsAlias = "RIGHT JOIN posts AS posts_alias" // same as RIGHT OUTER JOIN
)

const (
	PostAliasID        = "posts_alias.id"
	PostAliasUserID    = "posts_alias.user_id"
	PostAliasTitle     = "posts_alias.title"
	PostAliasContent   = "posts_alias.content"
	PostAliasStatus    = "posts_alias.status"
	PostAliasCreatedAt = "posts_alias.created_at"
	PostAliasUpdatedAt = "posts_alias.updated_at"
)

var (
	PostIDAliasIdent        = bun.Ident("posts_alias.id")
	PostUserIDAliasIdent    = bun.Ident("posts_alias.user_id")
	PostTitleAliasIdent     = bun.Ident("posts_alias.title")
	PostContentAliasIdent   = bun.Ident("posts_alias.content")
	PostStatusAliasIdent    = bun.Ident("posts_alias.status")
	PostCreatedAtAliasIdent = bun.Ident("posts_alias.created_at")
	PostUpdatedAtAliasIdent = bun.Ident("posts_alias.updated_at")
)

const (
	PostAliasIDEq        = "posts_alias.id = ?"
	PostAliasUserIDEq    = "posts_alias.user_id = ?"
	PostAliasTitleEq     = "posts_alias.title = ?"
	PostAliasContentEq   = "posts_alias.content = ?"
	PostAliasStatusEq    = "posts_alias.status = ?"
	PostAliasCreatedAtEq = "posts_alias.created_at = ?"
	PostAliasUpdatedAtEq = "posts_alias.updated_at = ?"
)

const (
	PostAliasIDNeq        = "posts_alias.id <> ?"
	PostAliasUserIDNeq    = "posts_alias.user_id <> ?"
	PostAliasTitleNeq     = "posts_alias.title <> ?"
	PostAliasContentNeq   = "posts_alias.content <> ?"
	PostAliasStatusNeq    = "posts_alias.status <> ?"
	PostAliasCreatedAtNeq = "posts_alias.created_at <> ?"
	PostAliasUpdatedAtNeq = "posts_alias.updated_at <> ?"
)

const (
	PostAliasIDGt        = "posts_alias.id > ?"
	PostAliasUserIDGt    = "posts_alias.user_id > ?"
	PostAliasStatusGt    = "posts_alias.status > ?"
	PostAliasCreatedAtGt = "posts_alias.created_at > ?"
	PostAliasUpdatedAtGt = "posts_alias.updated_at > ?"
)

const (
	PostAliasIDGte        = "posts_alias.id >= ?"
	PostAliasUserIDGte    = "posts_alias.user_id >= ?"
	PostAliasStatusGte    = "posts_alias.status >= ?"
	PostAliasCreatedAtGte = "posts_alias.created_at >= ?"
	PostAliasUpdatedAtGte = "posts_alias.updated_at >= ?"
)

const (
	PostAliasIDLt        = "posts_alias.id < ?"
	PostAliasUserIDLt    = "posts_alias.user_id < ?"
	PostAliasStatusLt    = "posts_alias.status < ?"
	PostAliasCreatedAtLt = "posts_alias.created_at < ?"
	PostAliasUpdatedAtLt = "posts_alias.updated_at < ?"
)

const (
	PostAliasIDLte        = "posts_alias.id <= ?"
	PostAliasUserIDLte    = "posts_alias.user_id <= ?"
	PostAliasStatusLte    = "posts_alias.status <= ?"
	PostAliasCreatedAtLte = "posts_alias.created_at <= ?"
	PostAliasUpdatedAtLte = "posts_alias.updated_at <= ?"
)

const (
	PostAliasTitleLike   = "posts_alias.title LIKE ?"
	PostAliasContentLike = "posts_alias.content LIKE ?"
)

const (
	PostAliasTitleLikePrefix   = "posts_alias.title LIKE ?%"
	PostAliasContentLikePrefix = "posts_alias.content LIKE ?%"
)

const (
	PostAliasTitleLikeSuffix   = "posts_alias.title LIKE %?"
	PostAliasContentLikeSuffix = "posts_alias.content LIKE %?"
)

const (
	PostAliasTitleLikeContain   = "posts_alias.title LIKE %?%"
	PostAliasContentLikeContain = "posts_alias.content LIKE %?%"
)

const (
	PostAliasTitleConcatExpr   = "posts_alias.title = CONCAT(posts_alias.title, ?)"
	PostAliasContentConcatExpr = "posts_alias.content = CONCAT(posts_alias.content, ?)"
)

const (
	PostAliasUserIDSUMExpr = "SUM(posts_alias.user_id)"
	PostAliasStatusSUMExpr = "SUM(posts_alias.status)"
)

const (
	PostAliasUserIDAVGExpr = "AVG(posts_alias.user_id)"
	PostAliasStatusAVGExpr = "AVG(posts_alias.status)"
)

const (
	PostAliasIDMINExpr        = "MIN(posts_alias.id)"
	PostAliasUserIDMINExpr    = "MIN(posts_alias.user_id)"
	PostAliasStatusMINExpr    = "MIN(posts_alias.status)"
	PostAliasCreatedAtMINExpr = "MIN(posts_alias.created_at)"
	PostAliasUpdatedAtMINExpr = "MIN(posts_alias.updated_at)"
)

const (
	PostAliasIDMAXExpr        = "MAX(posts_alias.id)"
	PostAliasUserIDMAXExpr    = "MAX(posts_alias.user_id)"
	PostAliasStatusMAXExpr    = "MAX(posts_alias.status)"
	PostAliasCreatedAtMAXExpr = "MAX(posts_alias.created_at)"
	PostAliasUpdatedAtMAXExpr = "MAX(posts_alias.updated_at)"
)

const (
	PostAliasUserIDAddExpr = "posts_alias.user_id = posts_alias.user_id + ?"
	PostAliasStatusAddExpr = "posts_alias.status = posts_alias.status + ?"
)

const (
	PostAliasUserIDSubExpr = "posts_alias.user_id = posts_alias.user_id - ?"
	PostAliasStatusSubExpr = "posts_alias.status = posts_alias.status - ?"
)

const (
	PostAliasUserIDAddLeastExpr = "posts_alias.user_id = LEAST(posts_alias.user_id + ?, ?)"
	PostAliasStatusAddLeastExpr = "posts_alias.status = LEAST(posts_alias.status + ?, ?)"
)

const (
	PostAliasUserIDSubGreatestExpr = "posts_alias.user_id = GREATEST(posts_alias.user_id - ?, ?)"
	PostAliasStatusSubGreatestExpr = "posts_alias.status = GREATEST(posts_alias.status - ?, ?)"
)

const (
	PostAliasUserIDClampExpr = "posts_alias.user_id = LEAST(GREATEST(posts_alias.user_id + ?, ?), ?)"
	PostAliasStatusClampExpr = "posts_alias.status = LEAST(GREATEST(posts_alias.status + ?, ?), ?)"
)

const (
	PostAliasIDDistinctExpr        = "DISTINCT posts_alias.id"
	PostAliasUserIDDistinctExpr    = "DISTINCT posts_alias.user_id"
	PostAliasTitleDistinctExpr     = "DISTINCT posts_alias.title"
	PostAliasContentDistinctExpr   = "DISTINCT posts_alias.content"
	PostAliasStatusDistinctExpr    = "DISTINCT posts_alias.status"
	PostAliasCreatedAtDistinctExpr = "DISTINCT posts_alias.created_at"
	PostAliasUpdatedAtDistinctExpr = "DISTINCT posts_alias.updated_at"
)

const (
	PostAliasIDCountDistinctExpr        = "COUNT(DISTINCT posts_alias.id)"
	PostAliasUserIDCountDistinctExpr    = "COUNT(DISTINCT posts_alias.user_id)"
	PostAliasTitleCountDistinctExpr     = "COUNT(DISTINCT posts_alias.title)"
	PostAliasContentCountDistinctExpr   = "COUNT(DISTINCT posts_alias.content)"
	PostAliasStatusCountDistinctExpr    = "COUNT(DISTINCT posts_alias.status)"
	PostAliasCreatedAtCountDistinctExpr = "COUNT(DISTINCT posts_alias.created_at)"
	PostAliasUpdatedAtCountDistinctExpr = "COUNT(DISTINCT posts_alias.updated_at)"
)

const (
	PostAliasIDIn        = "posts_alias.id IN (?)"
	PostAliasUserIDIn    = "posts_alias.user_id IN (?)"
	PostAliasTitleIn     = "posts_alias.title IN (?)"
	PostAliasContentIn   = "posts_alias.content IN (?)"
	PostAliasStatusIn    = "posts_alias.status IN (?)"
	PostAliasCreatedAtIn = "posts_alias.created_at IN (?)"
	PostAliasUpdatedAtIn = "posts_alias.updated_at IN (?)"
)

const (
	PostAliasIDNotIn        = "posts_alias.id NOT IN (?)"
	PostAliasUserIDNotIn    = "posts_alias.user_id NOT IN (?)"
	PostAliasTitleNotIn     = "posts_alias.title NOT IN (?)"
	PostAliasContentNotIn   = "posts_alias.content NOT IN (?)"
	PostAliasStatusNotIn    = "posts_alias.status NOT IN (?)"
	PostAliasCreatedAtNotIn = "posts_alias.created_at NOT IN (?)"
	PostAliasUpdatedAtNotIn = "posts_alias.updated_at NOT IN (?)"
)

const (
	PostAliasContentIsNull = "posts_alias.content IS NULL"
)

const (
	PostAliasContentIsNotNull = "posts_alias.content IS NOT NULL"
)

const (
	PostAliasContentCoalesceExpr = "COALESCE(posts_alias.content, ?)"
)

const (
	PostAliasIDBetween        = "posts_alias.id BETWEEN ? AND ?"
	PostAliasUserIDBetween    = "posts_alias.user_id BETWEEN ? AND ?"
	PostAliasStatusBetween    = "posts_alias.status BETWEEN ? AND ?"
	PostAliasCreatedAtBetween = "posts_alias.created_at BETWEEN ? AND ?"
	PostAliasUpdatedAtBetween = "posts_alias.updated_at BETWEEN ? AND ?"
)

const (
	PostAliasIDNotBetween        = "posts_alias.id NOT BETWEEN ? AND ?"
	PostAliasUserIDNotBetween    = "posts_alias.user_id NOT BETWEEN ? AND ?"
	PostAliasStatusNotBetween    = "posts_alias.status NOT BETWEEN ? AND ?"
	PostAliasCreatedAtNotBetween = "posts_alias.created_at NOT BETWEEN ? AND ?"
	PostAliasUpdatedAtNotBetween = "posts_alias.updated_at NOT BETWEEN ? AND ?"
)

const (
	PostAliasCreatedAtDateExpr = "DATE(posts_alias.created_at)"
	PostAliasUpdatedAtDateExpr = "DATE(posts_alias.updated_at)"
)

const (
	PostAliasCreatedAtYearExpr = "EXTRACT(YEAR FROM posts_alias.created_at)"
	PostAliasUpdatedAtYearExpr = "EXTRACT(YEAR FROM posts_alias.updated_at)"
)

const (
	PostAliasCreatedAtMonthExpr = "EXTRACT(MONTH FROM posts_alias.created_at)"
	PostAliasUpdatedAtMonthExpr = "EXTRACT(MONTH FROM posts_alias.updated_at)"
)

const (
	PostAliasCreatedAtDayExpr = "EXTRACT(DAY FROM posts_alias.created_at)"
	PostAliasUpdatedAtDayExpr = "EXTRACT(DAY FROM posts_alias.updated_at)"
)

const (
	PostAliasCreatedAtHourExpr = "EXTRACT(HOUR FROM posts_alias.created_at)"
	PostAliasUpdatedAtHourExpr = "EXTRACT(HOUR FROM posts_alias.updated_at)"
)

const (
	PostAliasCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM posts_alias.created_at)"
	PostAliasUpdatedAtMinuteExpr = "EXTRACT(MINUTE FROM posts_alias.updated_at)"
)

const (
	PostAliasCreatedAtSecondExpr = "EXTRACT(SECOND FROM posts_alias.created_at)"
	PostAliasUpdatedAtSecondExpr = "EXTRACT(SECOND FROM posts_alias.updated_at)"
)

const (
	PostAliasIDAsc        = "posts_alias.id ASC"
	PostAliasUserIDAsc    = "posts_alias.user_id ASC"
	PostAliasTitleAsc     = "posts_alias.title ASC"
	PostAliasContentAsc   = "posts_alias.content ASC"
	PostAliasStatusAsc    = "posts_alias.status ASC"
	PostAliasCreatedAtAsc = "posts_alias.created_at ASC"
	PostAliasUpdatedAtAsc = "posts_alias.updated_at ASC"
)

const (
	PostAliasIDDesc        = "posts_alias.id DESC"
	PostAliasUserIDDesc    = "posts_alias.user_id DESC"
	PostAliasTitleDesc     = "posts_alias.title DESC"
	PostAliasContentDesc   = "posts_alias.content DESC"
	PostAliasStatusDesc    = "posts_alias.status DESC"
	PostAliasCreatedAtDesc = "posts_alias.created_at DESC"
	PostAliasUpdatedAtDesc = "posts_alias.updated_at DESC"
)
