// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: test_index

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilTestIndex = (*TestIndex)(nil)

var (
	_ bun.BeforeInsertHook = (*TestIndex)(nil)
	_ bun.BeforeUpdateHook = (*TestIndex)(nil)
)

const TestIndexTableName = "test_index"

var TestIndexTableNameIdent  = bun.Ident("test_index")

const (
	TestIndexID      = "id"
	TestIndexStartAt = "start_at"
	TestIndexEndAt   = "end_at"
	TestIndexSeq     = "seq"
)

var (
	TestIndexIDIdent      = bun.Ident("id")
	TestIndexStartAtIdent = bun.Ident("start_at")
	TestIndexEndAtIdent   = bun.Ident("end_at")
	TestIndexSeqIdent     = bun.Ident("seq")
)

const (
	TestIndexIDEq      = "id = ?"
	TestIndexStartAtEq = "start_at = ?"
	TestIndexEndAtEq   = "end_at = ?"
	TestIndexSeqEq     = "seq = ?"
)

const (
	TestIndexIDNeq      = "id <> ?"
	TestIndexStartAtNeq = "start_at <> ?"
	TestIndexEndAtNeq   = "end_at <> ?"
	TestIndexSeqNeq     = "seq <> ?"
)

const (
	TestIndexIDGt      = "id > ?"
	TestIndexStartAtGt = "start_at > ?"
	TestIndexEndAtGt   = "end_at > ?"
	TestIndexSeqGt     = "seq > ?"
)

const (
	TestIndexIDGte      = "id >= ?"
	TestIndexStartAtGte = "start_at >= ?"
	TestIndexEndAtGte   = "end_at >= ?"
	TestIndexSeqGte     = "seq >= ?"
)

const (
	TestIndexIDLt      = "id < ?"
	TestIndexStartAtLt = "start_at < ?"
	TestIndexEndAtLt   = "end_at < ?"
	TestIndexSeqLt     = "seq < ?"
)

const (
	TestIndexIDLte      = "id <= ?"
	TestIndexStartAtLte = "start_at <= ?"
	TestIndexEndAtLte   = "end_at <= ?"
	TestIndexSeqLte     = "seq <= ?"
)

const (
	TestIndexSeqSUMExpr = "SUM(seq)"
)

const (
	TestIndexSeqAVGExpr = "AVG(seq)"
)

const (
	TestIndexIDMINExpr      = "MIN(id)"
	TestIndexStartAtMINExpr = "MIN(start_at)"
	TestIndexEndAtMINExpr   = "MIN(end_at)"
	TestIndexSeqMINExpr     = "MIN(seq)"
)

const (
	TestIndexIDMAXExpr      = "MAX(id)"
	TestIndexStartAtMAXExpr = "MAX(start_at)"
	TestIndexEndAtMAXExpr   = "MAX(end_at)"
	TestIndexSeqMAXExpr     = "MAX(seq)"
)

const (
	TestIndexSeqAddExpr = "seq = seq + ?"
)

const (
	TestIndexSeqSubExpr = "seq = seq - ?"
)

const (
	TestIndexSeqAddLeastExpr = "seq = LEAST(seq + ?, ?)"
)

const (
	TestIndexSeqSubGreatestExpr = "seq = GREATEST(seq - ?, ?)"
)

const (
	TestIndexSeqClampExpr = "seq = LEAST(GREATEST(seq + ?, ?), ?)"
)

const (
	TestIndexIDDistinctExpr      = "DISTINCT id"
	TestIndexStartAtDistinctExpr = "DISTINCT start_at"
	TestIndexEndAtDistinctExpr   = "DISTINCT end_at"
	TestIndexSeqDistinctExpr     = "DISTINCT seq"
)

const (
	TestIndexIDCountDistinctExpr      = "COUNT(DISTINCT id)"
	TestIndexStartAtCountDistinctExpr = "COUNT(DISTINCT start_at)"
	TestIndexEndAtCountDistinctExpr   = "COUNT(DISTINCT end_at)"
	TestIndexSeqCountDistinctExpr     = "COUNT(DISTINCT seq)"
)

const (
	TestIndexIDIn      = "id IN (?)"
	TestIndexStartAtIn = "start_at IN (?)"
	TestIndexEndAtIn   = "end_at IN (?)"
	TestIndexSeqIn     = "seq IN (?)"
)

const (
	TestIndexIDNotIn      = "id NOT IN (?)"
	TestIndexStartAtNotIn = "start_at NOT IN (?)"
	TestIndexEndAtNotIn   = "end_at NOT IN (?)"
	TestIndexSeqNotIn     = "seq NOT IN (?)"
)

const (
	TestIndexIDBetween      = "id BETWEEN ? AND ?"
	TestIndexStartAtBetween = "start_at BETWEEN ? AND ?"
	TestIndexEndAtBetween   = "end_at BETWEEN ? AND ?"
	TestIndexSeqBetween     = "seq BETWEEN ? AND ?"
)

const (
	TestIndexIDNotBetween      = "id NOT BETWEEN ? AND ?"
	TestIndexStartAtNotBetween = "start_at NOT BETWEEN ? AND ?"
	TestIndexEndAtNotBetween   = "end_at NOT BETWEEN ? AND ?"
	TestIndexSeqNotBetween     = "seq NOT BETWEEN ? AND ?"
)

const (
	TestIndexStartAtDateExpr = "DATE(start_at)"
	TestIndexEndAtDateExpr   = "DATE(end_at)"
)

const (
	TestIndexStartAtYearExpr = "EXTRACT(YEAR FROM start_at)"
	TestIndexEndAtYearExpr   = "EXTRACT(YEAR FROM end_at)"
)

const (
	TestIndexStartAtMonthExpr = "EXTRACT(MONTH FROM start_at)"
	TestIndexEndAtMonthExpr   = "EXTRACT(MONTH FROM end_at)"
)

const (
	TestIndexStartAtDayExpr = "EXTRACT(DAY FROM start_at)"
	TestIndexEndAtDayExpr   = "EXTRACT(DAY FROM end_at)"
)

const (
	TestIndexStartAtHourExpr = "EXTRACT(HOUR FROM start_at)"
	TestIndexEndAtHourExpr   = "EXTRACT(HOUR FROM end_at)"
)

const (
	TestIndexStartAtMinuteExpr = "EXTRACT(MINUTE FROM start_at)"
	TestIndexEndAtMinuteExpr   = "EXTRACT(MINUTE FROM end_at)"
)

const (
	TestIndexStartAtSecondExpr = "EXTRACT(SECOND FROM start_at)"
	TestIndexEndAtSecondExpr   = "EXTRACT(SECOND FROM end_at)"
)

const (
	TestIndexIDAsc      = "id ASC"
	TestIndexStartAtAsc = "start_at ASC"
	TestIndexEndAtAsc   = "end_at ASC"
	TestIndexSeqAsc     = "seq ASC"
)

const (
	TestIndexIDDesc      = "id DESC"
	TestIndexStartAtDesc = "start_at DESC"
	TestIndexEndAtDesc   = "end_at DESC"
	TestIndexSeqDesc     = "seq DESC"
)

// TestIndex generates a model for the "test_index" table.
type TestIndex struct {
	bun.BaseModel `bun:"table:test_index,alias:test_index_alias"`

	ID      int32     `bun:"id,pk,autoincrement,notnull" json:"id,omitempty"` //
	StartAt time.Time `bun:"start_at,notnull" json:"start_at,omitempty"`      //
	EndAt   time.Time `bun:"end_at,notnull" json:"end_at,omitempty"`          //
	Seq     int64     `bun:"seq,unique,notnull" json:"seq,omitempty"`         //
}

func (m *TestIndex) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	return nil
}
func (m *TestIndex) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	return nil
}
