// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: test_all_types

// Package model defines database models generated from schema.
package model

import (
	"context"
	"encoding/json"
	"time"

	"github.com/shopspring/decimal"
	"github.com/uptrace/bun"
)

var NilTestAllType = (*TestAllType)(nil)

var (
	_ bun.BeforeInsertHook = (*TestAllType)(nil)
	_ bun.BeforeUpdateHook = (*TestAllType)(nil)
)

const TestAllTypeTableName = "test_all_types"

var TestAllTypeTableNameIdent  = bun.Ident("test_all_types")

const (
	TestAllTypeID             = "id"
	TestAllTypeTinyIntVal     = "tiny_int_val"
	TestAllTypeSmallIntVal    = "small_int_val"
	TestAllTypeMediumIntVal   = "medium_int_val"
	TestAllTypeIntVal         = "int_val"
	TestAllTypeBigIntVal      = "big_int_val"
	TestAllTypeDecimalVal     = "decimal_val"
	TestAllTypeFloatVal       = "float_val"
	TestAllTypeDoubleVal      = "double_val"
	TestAllTypeCharVal        = "char_val"
	TestAllTypeVarcharVal     = "varchar_val"
	TestAllTypeTextVal        = "text_val"
	TestAllTypeMediumtextVal  = "mediumtext_val"
	TestAllTypeLongtextVal    = "longtext_val"
	TestAllTypeDateVal        = "date_val"
	TestAllTypeTimeVal        = "time_val"
	TestAllTypeDatetimeVal    = "datetime_val"
	TestAllTypeTimestampVal   = "timestamp_val"
	TestAllTypeYearVal        = "year_val"
	TestAllTypeBoolVal        = "bool_val"
	TestAllTypeEnumVal        = "enum_val"
	TestAllTypeSetVal         = "set_val"
	TestAllTypeBinaryVal      = "binary_val"
	TestAllTypeVarbinaryVal   = "varbinary_val"
	TestAllTypeBlobVal        = "blob_val"
	TestAllTypeMediumblobVal  = "mediumblob_val"
	TestAllTypeLongblobVal    = "longblob_val"
	TestAllTypeJsonVal        = "json_val"
	TestAllTypeBitVal         = "bit_val"
	TestAllTypeNullableIntVal = "nullable_int_val"
	TestAllTypeIgnoreVal      = "ignore_val"
	TestAllTypeCreatedAt      = "created_at"
	TestAllTypeUpdatedAt      = "updated_at"
	TestAllTypeDeletedAt      = "deleted_at"
)

var (
	TestAllTypeIDIdent             = bun.Ident("id")
	TestAllTypeTinyIntValIdent     = bun.Ident("tiny_int_val")
	TestAllTypeSmallIntValIdent    = bun.Ident("small_int_val")
	TestAllTypeMediumIntValIdent   = bun.Ident("medium_int_val")
	TestAllTypeIntValIdent         = bun.Ident("int_val")
	TestAllTypeBigIntValIdent      = bun.Ident("big_int_val")
	TestAllTypeDecimalValIdent     = bun.Ident("decimal_val")
	TestAllTypeFloatValIdent       = bun.Ident("float_val")
	TestAllTypeDoubleValIdent      = bun.Ident("double_val")
	TestAllTypeCharValIdent        = bun.Ident("char_val")
	TestAllTypeVarcharValIdent     = bun.Ident("varchar_val")
	TestAllTypeTextValIdent        = bun.Ident("text_val")
	TestAllTypeMediumtextValIdent  = bun.Ident("mediumtext_val")
	TestAllTypeLongtextValIdent    = bun.Ident("longtext_val")
	TestAllTypeDateValIdent        = bun.Ident("date_val")
	TestAllTypeTimeValIdent        = bun.Ident("time_val")
	TestAllTypeDatetimeValIdent    = bun.Ident("datetime_val")
	TestAllTypeTimestampValIdent   = bun.Ident("timestamp_val")
	TestAllTypeYearValIdent        = bun.Ident("year_val")
	TestAllTypeBoolValIdent        = bun.Ident("bool_val")
	TestAllTypeEnumValIdent        = bun.Ident("enum_val")
	TestAllTypeSetValIdent         = bun.Ident("set_val")
	TestAllTypeBinaryValIdent      = bun.Ident("binary_val")
	TestAllTypeVarbinaryValIdent   = bun.Ident("varbinary_val")
	TestAllTypeBlobValIdent        = bun.Ident("blob_val")
	TestAllTypeMediumblobValIdent  = bun.Ident("mediumblob_val")
	TestAllTypeLongblobValIdent    = bun.Ident("longblob_val")
	TestAllTypeJsonValIdent        = bun.Ident("json_val")
	TestAllTypeBitValIdent         = bun.Ident("bit_val")
	TestAllTypeNullableIntValIdent = bun.Ident("nullable_int_val")
	TestAllTypeIgnoreValIdent      = bun.Ident("ignore_val")
	TestAllTypeCreatedAtIdent      = bun.Ident("created_at")
	TestAllTypeUpdatedAtIdent      = bun.Ident("updated_at")
	TestAllTypeDeletedAtIdent      = bun.Ident("deleted_at")
)

const (
	TestAllTypeIDEq             = "id = ?"
	TestAllTypeTinyIntValEq     = "tiny_int_val = ?"
	TestAllTypeSmallIntValEq    = "small_int_val = ?"
	TestAllTypeMediumIntValEq   = "medium_int_val = ?"
	TestAllTypeIntValEq         = "int_val = ?"
	TestAllTypeBigIntValEq      = "big_int_val = ?"
	TestAllTypeDecimalValEq     = "decimal_val = ?"
	TestAllTypeFloatValEq       = "float_val = ?"
	TestAllTypeDoubleValEq      = "double_val = ?"
	TestAllTypeCharValEq        = "char_val = ?"
	TestAllTypeVarcharValEq     = "varchar_val = ?"
	TestAllTypeTextValEq        = "text_val = ?"
	TestAllTypeMediumtextValEq  = "mediumtext_val = ?"
	TestAllTypeLongtextValEq    = "longtext_val = ?"
	TestAllTypeDateValEq        = "date_val = ?"
	TestAllTypeTimeValEq        = "time_val = ?"
	TestAllTypeDatetimeValEq    = "datetime_val = ?"
	TestAllTypeTimestampValEq   = "timestamp_val = ?"
	TestAllTypeYearValEq        = "year_val = ?"
	TestAllTypeBoolValEq        = "bool_val = ?"
	TestAllTypeEnumValEq        = "enum_val = ?"
	TestAllTypeSetValEq         = "set_val = ?"
	TestAllTypeBinaryValEq      = "binary_val = ?"
	TestAllTypeVarbinaryValEq   = "varbinary_val = ?"
	TestAllTypeBlobValEq        = "blob_val = ?"
	TestAllTypeMediumblobValEq  = "mediumblob_val = ?"
	TestAllTypeLongblobValEq    = "longblob_val = ?"
	TestAllTypeJsonValEq        = "json_val = ?"
	TestAllTypeBitValEq         = "bit_val = ?"
	TestAllTypeNullableIntValEq = "nullable_int_val = ?"
	TestAllTypeIgnoreValEq      = "ignore_val = ?"
	TestAllTypeCreatedAtEq      = "created_at = ?"
	TestAllTypeUpdatedAtEq      = "updated_at = ?"
	TestAllTypeDeletedAtEq      = "deleted_at = ?"
)

const (
	TestAllTypeIDNeq             = "id <> ?"
	TestAllTypeTinyIntValNeq     = "tiny_int_val <> ?"
	TestAllTypeSmallIntValNeq    = "small_int_val <> ?"
	TestAllTypeMediumIntValNeq   = "medium_int_val <> ?"
	TestAllTypeIntValNeq         = "int_val <> ?"
	TestAllTypeBigIntValNeq      = "big_int_val <> ?"
	TestAllTypeDecimalValNeq     = "decimal_val <> ?"
	TestAllTypeFloatValNeq       = "float_val <> ?"
	TestAllTypeDoubleValNeq      = "double_val <> ?"
	TestAllTypeCharValNeq        = "char_val <> ?"
	TestAllTypeVarcharValNeq     = "varchar_val <> ?"
	TestAllTypeTextValNeq        = "text_val <> ?"
	TestAllTypeMediumtextValNeq  = "mediumtext_val <> ?"
	TestAllTypeLongtextValNeq    = "longtext_val <> ?"
	TestAllTypeDateValNeq        = "date_val <> ?"
	TestAllTypeTimeValNeq        = "time_val <> ?"
	TestAllTypeDatetimeValNeq    = "datetime_val <> ?"
	TestAllTypeTimestampValNeq   = "timestamp_val <> ?"
	TestAllTypeYearValNeq        = "year_val <> ?"
	TestAllTypeBoolValNeq        = "bool_val <> ?"
	TestAllTypeEnumValNeq        = "enum_val <> ?"
	TestAllTypeSetValNeq         = "set_val <> ?"
	TestAllTypeBinaryValNeq      = "binary_val <> ?"
	TestAllTypeVarbinaryValNeq   = "varbinary_val <> ?"
	TestAllTypeBlobValNeq        = "blob_val <> ?"
	TestAllTypeMediumblobValNeq  = "mediumblob_val <> ?"
	TestAllTypeLongblobValNeq    = "longblob_val <> ?"
	TestAllTypeJsonValNeq        = "json_val <> ?"
	TestAllTypeBitValNeq         = "bit_val <> ?"
	TestAllTypeNullableIntValNeq = "nullable_int_val <> ?"
	TestAllTypeIgnoreValNeq      = "ignore_val <> ?"
	TestAllTypeCreatedAtNeq      = "created_at <> ?"
	TestAllTypeUpdatedAtNeq      = "updated_at <> ?"
	TestAllTypeDeletedAtNeq      = "deleted_at <> ?"
)

const (
	TestAllTypeIDGt             = "id > ?"
	TestAllTypeTinyIntValGt     = "tiny_int_val > ?"
	TestAllTypeSmallIntValGt    = "small_int_val > ?"
	TestAllTypeMediumIntValGt   = "medium_int_val > ?"
	TestAllTypeIntValGt         = "int_val > ?"
	TestAllTypeBigIntValGt      = "big_int_val > ?"
	TestAllTypeDecimalValGt     = "decimal_val > ?"
	TestAllTypeFloatValGt       = "float_val > ?"
	TestAllTypeDoubleValGt      = "double_val > ?"
	TestAllTypeDateValGt        = "date_val > ?"
	TestAllTypeTimeValGt        = "time_val > ?"
	TestAllTypeDatetimeValGt    = "datetime_val > ?"
	TestAllTypeTimestampValGt   = "timestamp_val > ?"
	TestAllTypeYearValGt        = "year_val > ?"
	TestAllTypeNullableIntValGt = "nullable_int_val > ?"
	TestAllTypeCreatedAtGt      = "created_at > ?"
	TestAllTypeUpdatedAtGt      = "updated_at > ?"
	TestAllTypeDeletedAtGt      = "deleted_at > ?"
)

const (
	TestAllTypeIDGte             = "id >= ?"
	TestAllTypeTinyIntValGte     = "tiny_int_val >= ?"
	TestAllTypeSmallIntValGte    = "small_int_val >= ?"
	TestAllTypeMediumIntValGte   = "medium_int_val >= ?"
	TestAllTypeIntValGte         = "int_val >= ?"
	TestAllTypeBigIntValGte      = "big_int_val >= ?"
	TestAllTypeDecimalValGte     = "decimal_val >= ?"
	TestAllTypeFloatValGte       = "float_val >= ?"
	TestAllTypeDoubleValGte      = "double_val >= ?"
	TestAllTypeDateValGte        = "date_val >= ?"
	TestAllTypeTimeValGte        = "time_val >= ?"
	TestAllTypeDatetimeValGte    = "datetime_val >= ?"
	TestAllTypeTimestampValGte   = "timestamp_val >= ?"
	TestAllTypeYearValGte        = "year_val >= ?"
	TestAllTypeNullableIntValGte = "nullable_int_val >= ?"
	TestAllTypeCreatedAtGte      = "created_at >= ?"
	TestAllTypeUpdatedAtGte      = "updated_at >= ?"
	TestAllTypeDeletedAtGte      = "deleted_at >= ?"
)

const (
	TestAllTypeIDLt             = "id < ?"
	TestAllTypeTinyIntValLt     = "tiny_int_val < ?"
	TestAllTypeSmallIntValLt    = "small_int_val < ?"
	TestAllTypeMediumIntValLt   = "medium_int_val < ?"
	TestAllTypeIntValLt         = "int_val < ?"
	TestAllTypeBigIntValLt      = "big_int_val < ?"
	TestAllTypeDecimalValLt     = "decimal_val < ?"
	TestAllTypeFloatValLt       = "float_val < ?"
	TestAllTypeDoubleValLt      = "double_val < ?"
	TestAllTypeDateValLt        = "date_val < ?"
	TestAllTypeTimeValLt        = "time_val < ?"
	TestAllTypeDatetimeValLt    = "datetime_val < ?"
	TestAllTypeTimestampValLt   = "timestamp_val < ?"
	TestAllTypeYearValLt        = "year_val < ?"
	TestAllTypeNullableIntValLt = "nullable_int_val < ?"
	TestAllTypeCreatedAtLt      = "created_at < ?"
	TestAllTypeUpdatedAtLt      = "updated_at < ?"
	TestAllTypeDeletedAtLt      = "deleted_at < ?"
)

const (
	TestAllTypeIDLte             = "id <= ?"
	TestAllTypeTinyIntValLte     = "tiny_int_val <= ?"
	TestAllTypeSmallIntValLte    = "small_int_val <= ?"
	TestAllTypeMediumIntValLte   = "medium_int_val <= ?"
	TestAllTypeIntValLte         = "int_val <= ?"
	TestAllTypeBigIntValLte      = "big_int_val <= ?"
	TestAllTypeDecimalValLte     = "decimal_val <= ?"
	TestAllTypeFloatValLte       = "float_val <= ?"
	TestAllTypeDoubleValLte      = "double_val <= ?"
	TestAllTypeDateValLte        = "date_val <= ?"
	TestAllTypeTimeValLte        = "time_val <= ?"
	TestAllTypeDatetimeValLte    = "datetime_val <= ?"
	TestAllTypeTimestampValLte   = "timestamp_val <= ?"
	TestAllTypeYearValLte        = "year_val <= ?"
	TestAllTypeNullableIntValLte = "nullable_int_val <= ?"
	TestAllTypeCreatedAtLte      = "created_at <= ?"
	TestAllTypeUpdatedAtLte      = "updated_at <= ?"
	TestAllTypeDeletedAtLte      = "deleted_at <= ?"
)

const (
	TestAllTypeCharValLike       = "char_val LIKE ?"
	TestAllTypeVarcharValLike    = "varchar_val LIKE ?"
	TestAllTypeTextValLike       = "text_val LIKE ?"
	TestAllTypeMediumtextValLike = "mediumtext_val LIKE ?"
	TestAllTypeLongtextValLike   = "longtext_val LIKE ?"
	TestAllTypeIgnoreValLike     = "ignore_val LIKE ?"
)

const (
	TestAllTypeCharValLikePrefix       = "char_val LIKE ?%"
	TestAllTypeVarcharValLikePrefix    = "varchar_val LIKE ?%"
	TestAllTypeTextValLikePrefix       = "text_val LIKE ?%"
	TestAllTypeMediumtextValLikePrefix = "mediumtext_val LIKE ?%"
	TestAllTypeLongtextValLikePrefix   = "longtext_val LIKE ?%"
	TestAllTypeIgnoreValLikePrefix     = "ignore_val LIKE ?%"
)

const (
	TestAllTypeCharValLikeSuffix       = "char_val LIKE %?"
	TestAllTypeVarcharValLikeSuffix    = "varchar_val LIKE %?"
	TestAllTypeTextValLikeSuffix       = "text_val LIKE %?"
	TestAllTypeMediumtextValLikeSuffix = "mediumtext_val LIKE %?"
	TestAllTypeLongtextValLikeSuffix   = "longtext_val LIKE %?"
	TestAllTypeIgnoreValLikeSuffix     = "ignore_val LIKE %?"
)

const (
	TestAllTypeCharValLikeContain       = "char_val LIKE %?%"
	TestAllTypeVarcharValLikeContain    = "varchar_val LIKE %?%"
	TestAllTypeTextValLikeContain       = "text_val LIKE %?%"
	TestAllTypeMediumtextValLikeContain = "mediumtext_val LIKE %?%"
	TestAllTypeLongtextValLikeContain   = "longtext_val LIKE %?%"
	TestAllTypeIgnoreValLikeContain     = "ignore_val LIKE %?%"
)

const (
	TestAllTypeCharValConcatExpr       = "char_val = CONCAT(char_val, ?)"
	TestAllTypeVarcharValConcatExpr    = "varchar_val = CONCAT(varchar_val, ?)"
	TestAllTypeTextValConcatExpr       = "text_val = CONCAT(text_val, ?)"
	TestAllTypeMediumtextValConcatExpr = "mediumtext_val = CONCAT(mediumtext_val, ?)"
	TestAllTypeLongtextValConcatExpr   = "longtext_val = CONCAT(longtext_val, ?)"
	TestAllTypeIgnoreValConcatExpr     = "ignore_val = CONCAT(ignore_val, ?)"
)

const (
	TestAllTypeTinyIntValSUMExpr     = "SUM(tiny_int_val)"
	TestAllTypeSmallIntValSUMExpr    = "SUM(small_int_val)"
	TestAllTypeMediumIntValSUMExpr   = "SUM(medium_int_val)"
	TestAllTypeIntValSUMExpr         = "SUM(int_val)"
	TestAllTypeBigIntValSUMExpr      = "SUM(big_int_val)"
	TestAllTypeDecimalValSUMExpr     = "SUM(decimal_val)"
	TestAllTypeFloatValSUMExpr       = "SUM(float_val)"
	TestAllTypeDoubleValSUMExpr      = "SUM(double_val)"
	TestAllTypeYearValSUMExpr        = "SUM(year_val)"
	TestAllTypeNullableIntValSUMExpr = "SUM(nullable_int_val)"
)

const (
	TestAllTypeTinyIntValAVGExpr     = "AVG(tiny_int_val)"
	TestAllTypeSmallIntValAVGExpr    = "AVG(small_int_val)"
	TestAllTypeMediumIntValAVGExpr   = "AVG(medium_int_val)"
	TestAllTypeIntValAVGExpr         = "AVG(int_val)"
	TestAllTypeBigIntValAVGExpr      = "AVG(big_int_val)"
	TestAllTypeDecimalValAVGExpr     = "AVG(decimal_val)"
	TestAllTypeFloatValAVGExpr       = "AVG(float_val)"
	TestAllTypeDoubleValAVGExpr      = "AVG(double_val)"
	TestAllTypeYearValAVGExpr        = "AVG(year_val)"
	TestAllTypeNullableIntValAVGExpr = "AVG(nullable_int_val)"
)

const (
	TestAllTypeIDMINExpr             = "MIN(id)"
	TestAllTypeTinyIntValMINExpr     = "MIN(tiny_int_val)"
	TestAllTypeSmallIntValMINExpr    = "MIN(small_int_val)"
	TestAllTypeMediumIntValMINExpr   = "MIN(medium_int_val)"
	TestAllTypeIntValMINExpr         = "MIN(int_val)"
	TestAllTypeBigIntValMINExpr      = "MIN(big_int_val)"
	TestAllTypeDecimalValMINExpr     = "MIN(decimal_val)"
	TestAllTypeFloatValMINExpr       = "MIN(float_val)"
	TestAllTypeDoubleValMINExpr      = "MIN(double_val)"
	TestAllTypeDateValMINExpr        = "MIN(date_val)"
	TestAllTypeTimeValMINExpr        = "MIN(time_val)"
	TestAllTypeDatetimeValMINExpr    = "MIN(datetime_val)"
	TestAllTypeTimestampValMINExpr   = "MIN(timestamp_val)"
	TestAllTypeYearValMINExpr        = "MIN(year_val)"
	TestAllTypeNullableIntValMINExpr = "MIN(nullable_int_val)"
	TestAllTypeCreatedAtMINExpr      = "MIN(created_at)"
	TestAllTypeUpdatedAtMINExpr      = "MIN(updated_at)"
	TestAllTypeDeletedAtMINExpr      = "MIN(deleted_at)"
)

const (
	TestAllTypeIDMAXExpr             = "MAX(id)"
	TestAllTypeTinyIntValMAXExpr     = "MAX(tiny_int_val)"
	TestAllTypeSmallIntValMAXExpr    = "MAX(small_int_val)"
	TestAllTypeMediumIntValMAXExpr   = "MAX(medium_int_val)"
	TestAllTypeIntValMAXExpr         = "MAX(int_val)"
	TestAllTypeBigIntValMAXExpr      = "MAX(big_int_val)"
	TestAllTypeDecimalValMAXExpr     = "MAX(decimal_val)"
	TestAllTypeFloatValMAXExpr       = "MAX(float_val)"
	TestAllTypeDoubleValMAXExpr      = "MAX(double_val)"
	TestAllTypeDateValMAXExpr        = "MAX(date_val)"
	TestAllTypeTimeValMAXExpr        = "MAX(time_val)"
	TestAllTypeDatetimeValMAXExpr    = "MAX(datetime_val)"
	TestAllTypeTimestampValMAXExpr   = "MAX(timestamp_val)"
	TestAllTypeYearValMAXExpr        = "MAX(year_val)"
	TestAllTypeNullableIntValMAXExpr = "MAX(nullable_int_val)"
	TestAllTypeCreatedAtMAXExpr      = "MAX(created_at)"
	TestAllTypeUpdatedAtMAXExpr      = "MAX(updated_at)"
	TestAllTypeDeletedAtMAXExpr      = "MAX(deleted_at)"
)

const (
	TestAllTypeTinyIntValAddExpr     = "tiny_int_val = tiny_int_val + ?"
	TestAllTypeSmallIntValAddExpr    = "small_int_val = small_int_val + ?"
	TestAllTypeMediumIntValAddExpr   = "medium_int_val = medium_int_val + ?"
	TestAllTypeIntValAddExpr         = "int_val = int_val + ?"
	TestAllTypeBigIntValAddExpr      = "big_int_val = big_int_val + ?"
	TestAllTypeDecimalValAddExpr     = "decimal_val = decimal_val + ?"
	TestAllTypeFloatValAddExpr       = "float_val = float_val + ?"
	TestAllTypeDoubleValAddExpr      = "double_val = double_val + ?"
	TestAllTypeYearValAddExpr        = "year_val = year_val + ?"
	TestAllTypeNullableIntValAddExpr = "nullable_int_val = nullable_int_val + ?"
)

const (
	TestAllTypeTinyIntValSubExpr     = "tiny_int_val = tiny_int_val - ?"
	TestAllTypeSmallIntValSubExpr    = "small_int_val = small_int_val - ?"
	TestAllTypeMediumIntValSubExpr   = "medium_int_val = medium_int_val - ?"
	TestAllTypeIntValSubExpr         = "int_val = int_val - ?"
	TestAllTypeBigIntValSubExpr      = "big_int_val = big_int_val - ?"
	TestAllTypeDecimalValSubExpr     = "decimal_val = decimal_val - ?"
	TestAllTypeFloatValSubExpr       = "float_val = float_val - ?"
	TestAllTypeDoubleValSubExpr      = "double_val = double_val - ?"
	TestAllTypeYearValSubExpr        = "year_val = year_val - ?"
	TestAllTypeNullableIntValSubExpr = "nullable_int_val = nullable_int_val - ?"
)

const (
	TestAllTypeTinyIntValAddLeastExpr     = "tiny_int_val = LEAST(tiny_int_val + ?, ?)"
	TestAllTypeSmallIntValAddLeastExpr    = "small_int_val = LEAST(small_int_val + ?, ?)"
	TestAllTypeMediumIntValAddLeastExpr   = "medium_int_val = LEAST(medium_int_val + ?, ?)"
	TestAllTypeIntValAddLeastExpr         = "int_val = LEAST(int_val + ?, ?)"
	TestAllTypeBigIntValAddLeastExpr      = "big_int_val = LEAST(big_int_val + ?, ?)"
	TestAllTypeDecimalValAddLeastExpr     = "decimal_val = LEAST(decimal_val + ?, ?)"
	TestAllTypeFloatValAddLeastExpr       = "float_val = LEAST(float_val + ?, ?)"
	TestAllTypeDoubleValAddLeastExpr      = "double_val = LEAST(double_val + ?, ?)"
	TestAllTypeYearValAddLeastExpr        = "year_val = LEAST(year_val + ?, ?)"
	TestAllTypeNullableIntValAddLeastExpr = "nullable_int_val = LEAST(nullable_int_val + ?, ?)"
)

const (
	TestAllTypeTinyIntValSubGreatestExpr     = "tiny_int_val = GREATEST(tiny_int_val - ?, ?)"
	TestAllTypeSmallIntValSubGreatestExpr    = "small_int_val = GREATEST(small_int_val - ?, ?)"
	TestAllTypeMediumIntValSubGreatestExpr   = "medium_int_val = GREATEST(medium_int_val - ?, ?)"
	TestAllTypeIntValSubGreatestExpr         = "int_val = GREATEST(int_val - ?, ?)"
	TestAllTypeBigIntValSubGreatestExpr      = "big_int_val = GREATEST(big_int_val - ?, ?)"
	TestAllTypeDecimalValSubGreatestExpr     = "decimal_val = GREATEST(decimal_val - ?, ?)"
	TestAllTypeFloatValSubGreatestExpr       = "float_val = GREATEST(float_val - ?, ?)"
	TestAllTypeDoubleValSubGreatestExpr      = "double_val = GREATEST(double_val - ?, ?)"
	TestAllTypeYearValSubGreatestExpr        = "year_val = GREATEST(year_val - ?, ?)"
	TestAllTypeNullableIntValSubGreatestExpr = "nullable_int_val = GREATEST(nullable_int_val - ?, ?)"
)

const (
	TestAllTypeTinyIntValClampExpr     = "tiny_int_val = LEAST(GREATEST(tiny_int_val + ?, ?), ?)"
	TestAllTypeSmallIntValClampExpr    = "small_int_val = LEAST(GREATEST(small_int_val + ?, ?), ?)"
	TestAllTypeMediumIntValClampExpr   = "medium_int_val = LEAST(GREATEST(medium_int_val + ?, ?), ?)"
	TestAllTypeIntValClampExpr         = "int_val = LEAST(GREATEST(int_val + ?, ?), ?)"
	TestAllTypeBigIntValClampExpr      = "big_int_val = LEAST(GREATEST(big_int_val + ?, ?), ?)"
	TestAllTypeDecimalValClampExpr     = "decimal_val = LEAST(GREATEST(decimal_val + ?, ?), ?)"
	TestAllTypeFloatValClampExpr       = "float_val = LEAST(GREATEST(float_val + ?, ?), ?)"
	TestAllTypeDoubleValClampExpr      = "double_val = LEAST(GREATEST(double_val + ?, ?), ?)"
	TestAllTypeYearValClampExpr        = "year_val = LEAST(GREATEST(year_val + ?, ?), ?)"
	TestAllTypeNullableIntValClampExpr = "nullable_int_val = LEAST(GREATEST(nullable_int_val + ?, ?), ?)"
)

const (
	TestAllTypeIDDistinctExpr             = "DISTINCT id"
	TestAllTypeTinyIntValDistinctExpr     = "DISTINCT tiny_int_val"
	TestAllTypeSmallIntValDistinctExpr    = "DISTINCT small_int_val"
	TestAllTypeMediumIntValDistinctExpr   = "DISTINCT medium_int_val"
	TestAllTypeIntValDistinctExpr         = "DISTINCT int_val"
	TestAllTypeBigIntValDistinctExpr      = "DISTINCT big_int_val"
	TestAllTypeDecimalValDistinctExpr     = "DISTINCT decimal_val"
	TestAllTypeFloatValDistinctExpr       = "DISTINCT float_val"
	TestAllTypeDoubleValDistinctExpr      = "DISTINCT double_val"
	TestAllTypeCharValDistinctExpr        = "DISTINCT char_val"
	TestAllTypeVarcharValDistinctExpr     = "DISTINCT varchar_val"
	TestAllTypeTextValDistinctExpr        = "DISTINCT text_val"
	TestAllTypeMediumtextValDistinctExpr  = "DISTINCT mediumtext_val"
	TestAllTypeLongtextValDistinctExpr    = "DISTINCT longtext_val"
	TestAllTypeDateValDistinctExpr        = "DISTINCT date_val"
	TestAllTypeTimeValDistinctExpr        = "DISTINCT time_val"
	TestAllTypeDatetimeValDistinctExpr    = "DISTINCT datetime_val"
	TestAllTypeTimestampValDistinctExpr   = "DISTINCT timestamp_val"
	TestAllTypeYearValDistinctExpr        = "DISTINCT year_val"
	TestAllTypeBoolValDistinctExpr        = "DISTINCT bool_val"
	TestAllTypeEnumValDistinctExpr        = "DISTINCT enum_val"
	TestAllTypeSetValDistinctExpr         = "DISTINCT set_val"
	TestAllTypeBinaryValDistinctExpr      = "DISTINCT binary_val"
	TestAllTypeVarbinaryValDistinctExpr   = "DISTINCT varbinary_val"
	TestAllTypeBlobValDistinctExpr        = "DISTINCT blob_val"
	TestAllTypeMediumblobValDistinctExpr  = "DISTINCT mediumblob_val"
	TestAllTypeLongblobValDistinctExpr    = "DISTINCT longblob_val"
	TestAllTypeJsonValDistinctExpr        = "DISTINCT json_val"
	TestAllTypeBitValDistinctExpr         = "DISTINCT bit_val"
	TestAllTypeNullableIntValDistinctExpr = "DISTINCT nullable_int_val"
	TestAllTypeIgnoreValDistinctExpr      = "DISTINCT ignore_val"
	TestAllTypeCreatedAtDistinctExpr      = "DISTINCT created_at"
	TestAllTypeUpdatedAtDistinctExpr      = "DISTINCT updated_at"
	TestAllTypeDeletedAtDistinctExpr      = "DISTINCT deleted_at"
)

const (
	TestAllTypeIDCountDistinctExpr             = "COUNT(DISTINCT id)"
	TestAllTypeTinyIntValCountDistinctExpr     = "COUNT(DISTINCT tiny_int_val)"
	TestAllTypeSmallIntValCountDistinctExpr    = "COUNT(DISTINCT small_int_val)"
	TestAllTypeMediumIntValCountDistinctExpr   = "COUNT(DISTINCT medium_int_val)"
	TestAllTypeIntValCountDistinctExpr         = "COUNT(DISTINCT int_val)"
	TestAllTypeBigIntValCountDistinctExpr      = "COUNT(DISTINCT big_int_val)"
	TestAllTypeDecimalValCountDistinctExpr     = "COUNT(DISTINCT decimal_val)"
	TestAllTypeFloatValCountDistinctExpr       = "COUNT(DISTINCT float_val)"
	TestAllTypeDoubleValCountDistinctExpr      = "COUNT(DISTINCT double_val)"
	TestAllTypeCharValCountDistinctExpr        = "COUNT(DISTINCT char_val)"
	TestAllTypeVarcharValCountDistinctExpr     = "COUNT(DISTINCT varchar_val)"
	TestAllTypeTextValCountDistinctExpr        = "COUNT(DISTINCT text_val)"
	TestAllTypeMediumtextValCountDistinctExpr  = "COUNT(DISTINCT mediumtext_val)"
	TestAllTypeLongtextValCountDistinctExpr    = "COUNT(DISTINCT longtext_val)"
	TestAllTypeDateValCountDistinctExpr        = "COUNT(DISTINCT date_val)"
	TestAllTypeTimeValCountDistinctExpr        = "COUNT(DISTINCT time_val)"
	TestAllTypeDatetimeValCountDistinctExpr    = "COUNT(DISTINCT datetime_val)"
	TestAllTypeTimestampValCountDistinctExpr   = "COUNT(DISTINCT timestamp_val)"
	TestAllTypeYearValCountDistinctExpr        = "COUNT(DISTINCT year_val)"
	TestAllTypeBoolValCountDistinctExpr        = "COUNT(DISTINCT bool_val)"
	TestAllTypeEnumValCountDistinctExpr        = "COUNT(DISTINCT enum_val)"
	TestAllTypeSetValCountDistinctExpr         = "COUNT(DISTINCT set_val)"
	TestAllTypeBinaryValCountDistinctExpr      = "COUNT(DISTINCT binary_val)"
	TestAllTypeVarbinaryValCountDistinctExpr   = "COUNT(DISTINCT varbinary_val)"
	TestAllTypeBlobValCountDistinctExpr        = "COUNT(DISTINCT blob_val)"
	TestAllTypeMediumblobValCountDistinctExpr  = "COUNT(DISTINCT mediumblob_val)"
	TestAllTypeLongblobValCountDistinctExpr    = "COUNT(DISTINCT longblob_val)"
	TestAllTypeJsonValCountDistinctExpr        = "COUNT(DISTINCT json_val)"
	TestAllTypeBitValCountDistinctExpr         = "COUNT(DISTINCT bit_val)"
	TestAllTypeNullableIntValCountDistinctExpr = "COUNT(DISTINCT nullable_int_val)"
	TestAllTypeIgnoreValCountDistinctExpr      = "COUNT(DISTINCT ignore_val)"
	TestAllTypeCreatedAtCountDistinctExpr      = "COUNT(DISTINCT created_at)"
	TestAllTypeUpdatedAtCountDistinctExpr      = "COUNT(DISTINCT updated_at)"
	TestAllTypeDeletedAtCountDistinctExpr      = "COUNT(DISTINCT deleted_at)"
)

const (
	TestAllTypeIDIn             = "id IN (?)"
	TestAllTypeTinyIntValIn     = "tiny_int_val IN (?)"
	TestAllTypeSmallIntValIn    = "small_int_val IN (?)"
	TestAllTypeMediumIntValIn   = "medium_int_val IN (?)"
	TestAllTypeIntValIn         = "int_val IN (?)"
	TestAllTypeBigIntValIn      = "big_int_val IN (?)"
	TestAllTypeDecimalValIn     = "decimal_val IN (?)"
	TestAllTypeFloatValIn       = "float_val IN (?)"
	TestAllTypeDoubleValIn      = "double_val IN (?)"
	TestAllTypeCharValIn        = "char_val IN (?)"
	TestAllTypeVarcharValIn     = "varchar_val IN (?)"
	TestAllTypeTextValIn        = "text_val IN (?)"
	TestAllTypeMediumtextValIn  = "mediumtext_val IN (?)"
	TestAllTypeLongtextValIn    = "longtext_val IN (?)"
	TestAllTypeDateValIn        = "date_val IN (?)"
	TestAllTypeTimeValIn        = "time_val IN (?)"
	TestAllTypeDatetimeValIn    = "datetime_val IN (?)"
	TestAllTypeTimestampValIn   = "timestamp_val IN (?)"
	TestAllTypeYearValIn        = "year_val IN (?)"
	TestAllTypeBoolValIn        = "bool_val IN (?)"
	TestAllTypeEnumValIn        = "enum_val IN (?)"
	TestAllTypeSetValIn         = "set_val IN (?)"
	TestAllTypeNullableIntValIn = "nullable_int_val IN (?)"
	TestAllTypeIgnoreValIn      = "ignore_val IN (?)"
	TestAllTypeCreatedAtIn      = "created_at IN (?)"
	TestAllTypeUpdatedAtIn      = "updated_at IN (?)"
	TestAllTypeDeletedAtIn      = "deleted_at IN (?)"
)

const (
	TestAllTypeIDNotIn             = "id NOT IN (?)"
	TestAllTypeTinyIntValNotIn     = "tiny_int_val NOT IN (?)"
	TestAllTypeSmallIntValNotIn    = "small_int_val NOT IN (?)"
	TestAllTypeMediumIntValNotIn   = "medium_int_val NOT IN (?)"
	TestAllTypeIntValNotIn         = "int_val NOT IN (?)"
	TestAllTypeBigIntValNotIn      = "big_int_val NOT IN (?)"
	TestAllTypeDecimalValNotIn     = "decimal_val NOT IN (?)"
	TestAllTypeFloatValNotIn       = "float_val NOT IN (?)"
	TestAllTypeDoubleValNotIn      = "double_val NOT IN (?)"
	TestAllTypeCharValNotIn        = "char_val NOT IN (?)"
	TestAllTypeVarcharValNotIn     = "varchar_val NOT IN (?)"
	TestAllTypeTextValNotIn        = "text_val NOT IN (?)"
	TestAllTypeMediumtextValNotIn  = "mediumtext_val NOT IN (?)"
	TestAllTypeLongtextValNotIn    = "longtext_val NOT IN (?)"
	TestAllTypeDateValNotIn        = "date_val NOT IN (?)"
	TestAllTypeTimeValNotIn        = "time_val NOT IN (?)"
	TestAllTypeDatetimeValNotIn    = "datetime_val NOT IN (?)"
	TestAllTypeTimestampValNotIn   = "timestamp_val NOT IN (?)"
	TestAllTypeYearValNotIn        = "year_val NOT IN (?)"
	TestAllTypeBoolValNotIn        = "bool_val NOT IN (?)"
	TestAllTypeEnumValNotIn        = "enum_val NOT IN (?)"
	TestAllTypeSetValNotIn         = "set_val NOT IN (?)"
	TestAllTypeNullableIntValNotIn = "nullable_int_val NOT IN (?)"
	TestAllTypeIgnoreValNotIn      = "ignore_val NOT IN (?)"
	TestAllTypeCreatedAtNotIn      = "created_at NOT IN (?)"
	TestAllTypeUpdatedAtNotIn      = "updated_at NOT IN (?)"
	TestAllTypeDeletedAtNotIn      = "deleted_at NOT IN (?)"
)

const (
	TestAllTypeTinyIntValIsNull     = "tiny_int_val IS NULL"
	TestAllTypeMediumIntValIsNull   = "medium_int_val IS NULL"
	TestAllTypeBigIntValIsNull      = "big_int_val IS NULL"
	TestAllTypeDecimalValIsNull     = "decimal_val IS NULL"
	TestAllTypeFloatValIsNull       = "float_val IS NULL"
	TestAllTypeDoubleValIsNull      = "double_val IS NULL"
	TestAllTypeCharValIsNull        = "char_val IS NULL"
	TestAllTypeVarcharValIsNull     = "varchar_val IS NULL"
	TestAllTypeTextValIsNull        = "text_val IS NULL"
	TestAllTypeMediumtextValIsNull  = "mediumtext_val IS NULL"
	TestAllTypeLongtextValIsNull    = "longtext_val IS NULL"
	TestAllTypeDateValIsNull        = "date_val IS NULL"
	TestAllTypeTimeValIsNull        = "time_val IS NULL"
	TestAllTypeDatetimeValIsNull    = "datetime_val IS NULL"
	TestAllTypeTimestampValIsNull   = "timestamp_val IS NULL"
	TestAllTypeYearValIsNull        = "year_val IS NULL"
	TestAllTypeBoolValIsNull        = "bool_val IS NULL"
	TestAllTypeEnumValIsNull        = "enum_val IS NULL"
	TestAllTypeSetValIsNull         = "set_val IS NULL"
	TestAllTypeBinaryValIsNull      = "binary_val IS NULL"
	TestAllTypeVarbinaryValIsNull   = "varbinary_val IS NULL"
	TestAllTypeBlobValIsNull        = "blob_val IS NULL"
	TestAllTypeMediumblobValIsNull  = "mediumblob_val IS NULL"
	TestAllTypeLongblobValIsNull    = "longblob_val IS NULL"
	TestAllTypeJsonValIsNull        = "json_val IS NULL"
	TestAllTypeBitValIsNull         = "bit_val IS NULL"
	TestAllTypeNullableIntValIsNull = "nullable_int_val IS NULL"
	TestAllTypeIgnoreValIsNull      = "ignore_val IS NULL"
	TestAllTypeDeletedAtIsNull      = "deleted_at IS NULL"
)

const (
	TestAllTypeTinyIntValIsNotNull     = "tiny_int_val IS NOT NULL"
	TestAllTypeMediumIntValIsNotNull   = "medium_int_val IS NOT NULL"
	TestAllTypeBigIntValIsNotNull      = "big_int_val IS NOT NULL"
	TestAllTypeDecimalValIsNotNull     = "decimal_val IS NOT NULL"
	TestAllTypeFloatValIsNotNull       = "float_val IS NOT NULL"
	TestAllTypeDoubleValIsNotNull      = "double_val IS NOT NULL"
	TestAllTypeCharValIsNotNull        = "char_val IS NOT NULL"
	TestAllTypeVarcharValIsNotNull     = "varchar_val IS NOT NULL"
	TestAllTypeTextValIsNotNull        = "text_val IS NOT NULL"
	TestAllTypeMediumtextValIsNotNull  = "mediumtext_val IS NOT NULL"
	TestAllTypeLongtextValIsNotNull    = "longtext_val IS NOT NULL"
	TestAllTypeDateValIsNotNull        = "date_val IS NOT NULL"
	TestAllTypeTimeValIsNotNull        = "time_val IS NOT NULL"
	TestAllTypeDatetimeValIsNotNull    = "datetime_val IS NOT NULL"
	TestAllTypeTimestampValIsNotNull   = "timestamp_val IS NOT NULL"
	TestAllTypeYearValIsNotNull        = "year_val IS NOT NULL"
	TestAllTypeBoolValIsNotNull        = "bool_val IS NOT NULL"
	TestAllTypeEnumValIsNotNull        = "enum_val IS NOT NULL"
	TestAllTypeSetValIsNotNull         = "set_val IS NOT NULL"
	TestAllTypeBinaryValIsNotNull      = "binary_val IS NOT NULL"
	TestAllTypeVarbinaryValIsNotNull   = "varbinary_val IS NOT NULL"
	TestAllTypeBlobValIsNotNull        = "blob_val IS NOT NULL"
	TestAllTypeMediumblobValIsNotNull  = "mediumblob_val IS NOT NULL"
	TestAllTypeLongblobValIsNotNull    = "longblob_val IS NOT NULL"
	TestAllTypeJsonValIsNotNull        = "json_val IS NOT NULL"
	TestAllTypeBitValIsNotNull         = "bit_val IS NOT NULL"
	TestAllTypeNullableIntValIsNotNull = "nullable_int_val IS NOT NULL"
	TestAllTypeIgnoreValIsNotNull      = "ignore_val IS NOT NULL"
	TestAllTypeDeletedAtIsNotNull      = "deleted_at IS NOT NULL"
)

// COALESCE expressions (COALESCE(column, ?))
const (
	TestAllTypeTinyIntValCoalesceExpr     = "COALESCE(tiny_int_val, ?)"
	TestAllTypeMediumIntValCoalesceExpr   = "COALESCE(medium_int_val, ?)"
	TestAllTypeBigIntValCoalesceExpr      = "COALESCE(big_int_val, ?)"
	TestAllTypeDecimalValCoalesceExpr     = "COALESCE(decimal_val, ?)"
	TestAllTypeFloatValCoalesceExpr       = "COALESCE(float_val, ?)"
	TestAllTypeDoubleValCoalesceExpr      = "COALESCE(double_val, ?)"
	TestAllTypeCharValCoalesceExpr        = "COALESCE(char_val, ?)"
	TestAllTypeVarcharValCoalesceExpr     = "COALESCE(varchar_val, ?)"
	TestAllTypeTextValCoalesceExpr        = "COALESCE(text_val, ?)"
	TestAllTypeMediumtextValCoalesceExpr  = "COALESCE(mediumtext_val, ?)"
	TestAllTypeLongtextValCoalesceExpr    = "COALESCE(longtext_val, ?)"
	TestAllTypeDateValCoalesceExpr        = "COALESCE(date_val, ?)"
	TestAllTypeTimeValCoalesceExpr        = "COALESCE(time_val, ?)"
	TestAllTypeDatetimeValCoalesceExpr    = "COALESCE(datetime_val, ?)"
	TestAllTypeTimestampValCoalesceExpr   = "COALESCE(timestamp_val, ?)"
	TestAllTypeYearValCoalesceExpr        = "COALESCE(year_val, ?)"
	TestAllTypeBoolValCoalesceExpr        = "COALESCE(bool_val, ?)"
	TestAllTypeEnumValCoalesceExpr        = "COALESCE(enum_val, ?)"
	TestAllTypeSetValCoalesceExpr         = "COALESCE(set_val, ?)"
	TestAllTypeBinaryValCoalesceExpr      = "COALESCE(binary_val, ?)"
	TestAllTypeVarbinaryValCoalesceExpr   = "COALESCE(varbinary_val, ?)"
	TestAllTypeBlobValCoalesceExpr        = "COALESCE(blob_val, ?)"
	TestAllTypeMediumblobValCoalesceExpr  = "COALESCE(mediumblob_val, ?)"
	TestAllTypeLongblobValCoalesceExpr    = "COALESCE(longblob_val, ?)"
	TestAllTypeJsonValCoalesceExpr        = "COALESCE(json_val, ?)"
	TestAllTypeBitValCoalesceExpr         = "COALESCE(bit_val, ?)"
	TestAllTypeNullableIntValCoalesceExpr = "COALESCE(nullable_int_val, ?)"
	TestAllTypeIgnoreValCoalesceExpr      = "COALESCE(ignore_val, ?)"
	TestAllTypeDeletedAtCoalesceExpr      = "COALESCE(deleted_at, ?)"
)

const (
	TestAllTypeIDBetween             = "id BETWEEN ? AND ?"
	TestAllTypeTinyIntValBetween     = "tiny_int_val BETWEEN ? AND ?"
	TestAllTypeSmallIntValBetween    = "small_int_val BETWEEN ? AND ?"
	TestAllTypeMediumIntValBetween   = "medium_int_val BETWEEN ? AND ?"
	TestAllTypeIntValBetween         = "int_val BETWEEN ? AND ?"
	TestAllTypeBigIntValBetween      = "big_int_val BETWEEN ? AND ?"
	TestAllTypeDecimalValBetween     = "decimal_val BETWEEN ? AND ?"
	TestAllTypeFloatValBetween       = "float_val BETWEEN ? AND ?"
	TestAllTypeDoubleValBetween      = "double_val BETWEEN ? AND ?"
	TestAllTypeDateValBetween        = "date_val BETWEEN ? AND ?"
	TestAllTypeTimeValBetween        = "time_val BETWEEN ? AND ?"
	TestAllTypeDatetimeValBetween    = "datetime_val BETWEEN ? AND ?"
	TestAllTypeTimestampValBetween   = "timestamp_val BETWEEN ? AND ?"
	TestAllTypeYearValBetween        = "year_val BETWEEN ? AND ?"
	TestAllTypeNullableIntValBetween = "nullable_int_val BETWEEN ? AND ?"
	TestAllTypeCreatedAtBetween      = "created_at BETWEEN ? AND ?"
	TestAllTypeUpdatedAtBetween      = "updated_at BETWEEN ? AND ?"
	TestAllTypeDeletedAtBetween      = "deleted_at BETWEEN ? AND ?"
)

const (
	TestAllTypeIDNotBetween             = "id NOT BETWEEN ? AND ?"
	TestAllTypeTinyIntValNotBetween     = "tiny_int_val NOT BETWEEN ? AND ?"
	TestAllTypeSmallIntValNotBetween    = "small_int_val NOT BETWEEN ? AND ?"
	TestAllTypeMediumIntValNotBetween   = "medium_int_val NOT BETWEEN ? AND ?"
	TestAllTypeIntValNotBetween         = "int_val NOT BETWEEN ? AND ?"
	TestAllTypeBigIntValNotBetween      = "big_int_val NOT BETWEEN ? AND ?"
	TestAllTypeDecimalValNotBetween     = "decimal_val NOT BETWEEN ? AND ?"
	TestAllTypeFloatValNotBetween       = "float_val NOT BETWEEN ? AND ?"
	TestAllTypeDoubleValNotBetween      = "double_val NOT BETWEEN ? AND ?"
	TestAllTypeDateValNotBetween        = "date_val NOT BETWEEN ? AND ?"
	TestAllTypeTimeValNotBetween        = "time_val NOT BETWEEN ? AND ?"
	TestAllTypeDatetimeValNotBetween    = "datetime_val NOT BETWEEN ? AND ?"
	TestAllTypeTimestampValNotBetween   = "timestamp_val NOT BETWEEN ? AND ?"
	TestAllTypeYearValNotBetween        = "year_val NOT BETWEEN ? AND ?"
	TestAllTypeNullableIntValNotBetween = "nullable_int_val NOT BETWEEN ? AND ?"
	TestAllTypeCreatedAtNotBetween      = "created_at NOT BETWEEN ? AND ?"
	TestAllTypeUpdatedAtNotBetween      = "updated_at NOT BETWEEN ? AND ?"
	TestAllTypeDeletedAtNotBetween      = "deleted_at NOT BETWEEN ? AND ?"
)

const (
	TestAllTypeDateValDateExpr      = "DATE(date_val)"
	TestAllTypeTimeValDateExpr      = "DATE(time_val)"
	TestAllTypeDatetimeValDateExpr  = "DATE(datetime_val)"
	TestAllTypeTimestampValDateExpr = "DATE(timestamp_val)"
	TestAllTypeCreatedAtDateExpr    = "DATE(created_at)"
	TestAllTypeUpdatedAtDateExpr    = "DATE(updated_at)"
	TestAllTypeDeletedAtDateExpr    = "DATE(deleted_at)"
)

const (
	TestAllTypeDateValYearExpr      = "EXTRACT(YEAR FROM date_val)"
	TestAllTypeTimeValYearExpr      = "EXTRACT(YEAR FROM time_val)"
	TestAllTypeDatetimeValYearExpr  = "EXTRACT(YEAR FROM datetime_val)"
	TestAllTypeTimestampValYearExpr = "EXTRACT(YEAR FROM timestamp_val)"
	TestAllTypeCreatedAtYearExpr    = "EXTRACT(YEAR FROM created_at)"
	TestAllTypeUpdatedAtYearExpr    = "EXTRACT(YEAR FROM updated_at)"
	TestAllTypeDeletedAtYearExpr    = "EXTRACT(YEAR FROM deleted_at)"
)

const (
	TestAllTypeDateValMonthExpr      = "EXTRACT(MONTH FROM date_val)"
	TestAllTypeTimeValMonthExpr      = "EXTRACT(MONTH FROM time_val)"
	TestAllTypeDatetimeValMonthExpr  = "EXTRACT(MONTH FROM datetime_val)"
	TestAllTypeTimestampValMonthExpr = "EXTRACT(MONTH FROM timestamp_val)"
	TestAllTypeCreatedAtMonthExpr    = "EXTRACT(MONTH FROM created_at)"
	TestAllTypeUpdatedAtMonthExpr    = "EXTRACT(MONTH FROM updated_at)"
	TestAllTypeDeletedAtMonthExpr    = "EXTRACT(MONTH FROM deleted_at)"
)

const (
	TestAllTypeDateValDayExpr      = "EXTRACT(DAY FROM date_val)"
	TestAllTypeTimeValDayExpr      = "EXTRACT(DAY FROM time_val)"
	TestAllTypeDatetimeValDayExpr  = "EXTRACT(DAY FROM datetime_val)"
	TestAllTypeTimestampValDayExpr = "EXTRACT(DAY FROM timestamp_val)"
	TestAllTypeCreatedAtDayExpr    = "EXTRACT(DAY FROM created_at)"
	TestAllTypeUpdatedAtDayExpr    = "EXTRACT(DAY FROM updated_at)"
	TestAllTypeDeletedAtDayExpr    = "EXTRACT(DAY FROM deleted_at)"
)

const (
	TestAllTypeDateValHourExpr      = "EXTRACT(HOUR FROM date_val)"
	TestAllTypeTimeValHourExpr      = "EXTRACT(HOUR FROM time_val)"
	TestAllTypeDatetimeValHourExpr  = "EXTRACT(HOUR FROM datetime_val)"
	TestAllTypeTimestampValHourExpr = "EXTRACT(HOUR FROM timestamp_val)"
	TestAllTypeCreatedAtHourExpr    = "EXTRACT(HOUR FROM created_at)"
	TestAllTypeUpdatedAtHourExpr    = "EXTRACT(HOUR FROM updated_at)"
	TestAllTypeDeletedAtHourExpr    = "EXTRACT(HOUR FROM deleted_at)"
)

const (
	TestAllTypeDateValMinuteExpr      = "EXTRACT(MINUTE FROM date_val)"
	TestAllTypeTimeValMinuteExpr      = "EXTRACT(MINUTE FROM time_val)"
	TestAllTypeDatetimeValMinuteExpr  = "EXTRACT(MINUTE FROM datetime_val)"
	TestAllTypeTimestampValMinuteExpr = "EXTRACT(MINUTE FROM timestamp_val)"
	TestAllTypeCreatedAtMinuteExpr    = "EXTRACT(MINUTE FROM created_at)"
	TestAllTypeUpdatedAtMinuteExpr    = "EXTRACT(MINUTE FROM updated_at)"
	TestAllTypeDeletedAtMinuteExpr    = "EXTRACT(MINUTE FROM deleted_at)"
)

const (
	TestAllTypeDateValSecondExpr      = "EXTRACT(SECOND FROM date_val)"
	TestAllTypeTimeValSecondExpr      = "EXTRACT(SECOND FROM time_val)"
	TestAllTypeDatetimeValSecondExpr  = "EXTRACT(SECOND FROM datetime_val)"
	TestAllTypeTimestampValSecondExpr = "EXTRACT(SECOND FROM timestamp_val)"
	TestAllTypeCreatedAtSecondExpr    = "EXTRACT(SECOND FROM created_at)"
	TestAllTypeUpdatedAtSecondExpr    = "EXTRACT(SECOND FROM updated_at)"
	TestAllTypeDeletedAtSecondExpr    = "EXTRACT(SECOND FROM deleted_at)"
)

const (
	TestAllTypeIDAsc             = "id ASC"
	TestAllTypeTinyIntValAsc     = "tiny_int_val ASC"
	TestAllTypeSmallIntValAsc    = "small_int_val ASC"
	TestAllTypeMediumIntValAsc   = "medium_int_val ASC"
	TestAllTypeIntValAsc         = "int_val ASC"
	TestAllTypeBigIntValAsc      = "big_int_val ASC"
	TestAllTypeDecimalValAsc     = "decimal_val ASC"
	TestAllTypeFloatValAsc       = "float_val ASC"
	TestAllTypeDoubleValAsc      = "double_val ASC"
	TestAllTypeCharValAsc        = "char_val ASC"
	TestAllTypeVarcharValAsc     = "varchar_val ASC"
	TestAllTypeTextValAsc        = "text_val ASC"
	TestAllTypeMediumtextValAsc  = "mediumtext_val ASC"
	TestAllTypeLongtextValAsc    = "longtext_val ASC"
	TestAllTypeDateValAsc        = "date_val ASC"
	TestAllTypeTimeValAsc        = "time_val ASC"
	TestAllTypeDatetimeValAsc    = "datetime_val ASC"
	TestAllTypeTimestampValAsc   = "timestamp_val ASC"
	TestAllTypeYearValAsc        = "year_val ASC"
	TestAllTypeBoolValAsc        = "bool_val ASC"
	TestAllTypeEnumValAsc        = "enum_val ASC"
	TestAllTypeSetValAsc         = "set_val ASC"
	TestAllTypeNullableIntValAsc = "nullable_int_val ASC"
	TestAllTypeIgnoreValAsc      = "ignore_val ASC"
	TestAllTypeCreatedAtAsc      = "created_at ASC"
	TestAllTypeUpdatedAtAsc      = "updated_at ASC"
	TestAllTypeDeletedAtAsc      = "deleted_at ASC"
)

const (
	TestAllTypeIDDesc             = "id DESC"
	TestAllTypeTinyIntValDesc     = "tiny_int_val DESC"
	TestAllTypeSmallIntValDesc    = "small_int_val DESC"
	TestAllTypeMediumIntValDesc   = "medium_int_val DESC"
	TestAllTypeIntValDesc         = "int_val DESC"
	TestAllTypeBigIntValDesc      = "big_int_val DESC"
	TestAllTypeDecimalValDesc     = "decimal_val DESC"
	TestAllTypeFloatValDesc       = "float_val DESC"
	TestAllTypeDoubleValDesc      = "double_val DESC"
	TestAllTypeCharValDesc        = "char_val DESC"
	TestAllTypeVarcharValDesc     = "varchar_val DESC"
	TestAllTypeTextValDesc        = "text_val DESC"
	TestAllTypeMediumtextValDesc  = "mediumtext_val DESC"
	TestAllTypeLongtextValDesc    = "longtext_val DESC"
	TestAllTypeDateValDesc        = "date_val DESC"
	TestAllTypeTimeValDesc        = "time_val DESC"
	TestAllTypeDatetimeValDesc    = "datetime_val DESC"
	TestAllTypeTimestampValDesc   = "timestamp_val DESC"
	TestAllTypeYearValDesc        = "year_val DESC"
	TestAllTypeBoolValDesc        = "bool_val DESC"
	TestAllTypeEnumValDesc        = "enum_val DESC"
	TestAllTypeSetValDesc         = "set_val DESC"
	TestAllTypeNullableIntValDesc = "nullable_int_val DESC"
	TestAllTypeIgnoreValDesc      = "ignore_val DESC"
	TestAllTypeCreatedAtDesc      = "created_at DESC"
	TestAllTypeUpdatedAtDesc      = "updated_at DESC"
	TestAllTypeDeletedAtDesc      = "deleted_at DESC"
)

// TestAllType generates a model for the "test_all_types" table.
type TestAllType struct {
	bun.BaseModel `bun:"table:test_all_types,alias:test_all_types_alias"`

	ID            int32            `bun:"id,pk,autoincrement,notnull" form:"id" json:"id,omitempty" xml:"Id"`                                       //
	TinyIntVal    *int8            `bun:"tiny_int_val,nullzero" form:"tiny_int_val" json:"tiny_int_val,omitempty" xml:"TinyIntVal"`                 //
	SmallIntVal   int16            `bun:"small_int_val,notnull,default:'0'" form:"small_int_val" json:"small_int_val,omitempty" xml:"SmallIntVal"`  //
	MediumIntVal  *int32           `bun:"medium_int_val,nullzero" form:"medium_int_val" json:"medium_int_val,omitempty" xml:"MediumIntVal"`         //
	IntVal        int32            `bun:"int_val,notnull,default:'0'" form:"int_val" json:"int_val,omitempty" xml:"IntVal"`                         //
	BigIntVal     *int64           `bun:"big_int_val,nullzero" form:"big_int_val" json:"big_int_val,omitempty" xml:"BigIntVal"`                     //
	DecimalVal    *decimal.Decimal `bun:"decimal_val,type:decimal(10,2),nullzero" form:"decimal_val" json:"decimal_val,omitempty" xml:"DecimalVal"` //
	FloatVal      *float32         `bun:"float_val,nullzero" form:"float_val" json:"float_val,omitempty" xml:"FloatVal"`                            //
	DoubleVal     *float64         `bun:"double_val,nullzero" form:"double_val" json:"double_val,omitempty" xml:"DoubleVal"`                        //
	CharVal       *string          `bun:"char_val,nullzero" form:"char_val" json:"char_val,omitempty" xml:"CharVal"`                                //
	VarcharVal    *string          `bun:"varchar_val,nullzero" form:"varchar_val" json:"varchar_val,omitempty" xml:"VarcharVal"`                    //
	TextVal       *string          `bun:"text_val,nullzero" form:"text_val" json:"text_val,omitempty" xml:"TextVal"`                                //
	MediumtextVal *string          `bun:"mediumtext_val,nullzero" form:"mediumtext_val" json:"mediumtext_val,omitempty" xml:"MediumtextVal"`        //
	LongtextVal   *string          `bun:"longtext_val,nullzero" form:"longtext_val" json:"longtext_val,omitempty" xml:"LongtextVal"`                //
	DateVal       *time.Time       `bun:"date_val,nullzero" form:"date_val" json:"date_val,omitempty" xml:"DateVal"`                                //
	TimeVal       *time.Time       `bun:"time_val,nullzero" form:"time_val" json:"time_val,omitempty" xml:"TimeVal"`                                //
	DatetimeVal   *time.Time       `bun:"datetime_val,nullzero" form:"datetime_val" json:"datetime_val,omitempty" xml:"DatetimeVal"`                //
	TimestampVal  *time.Time       `bun:"timestamp_val,nullzero" form:"timestamp_val" json:"timestamp_val,omitempty" xml:"TimestampVal"`            //
	YearVal       *int             `bun:"year_val,nullzero" form:"year_val" json:"year_val,omitempty" xml:"YearVal"`                                //
	BoolVal       *bool            `bun:"bool_val,nullzero" form:"bool_val" json:"bool_val,omitempty" xml:"BoolVal"`                                //
	EnumVal       *string          `bun:"enum_val,nullzero" form:"enum_val" json:"enum_val,omitempty" xml:"EnumVal"`                                //
	SetVal        *string          `bun:"set_val,nullzero" form:"set_val" json:"set_val,omitempty" xml:"SetVal"`                                    //
	BinaryVal     []byte           `bun:"binary_val,nullzero" form:"binary_val" json:"binary_val,omitempty" xml:"BinaryVal"`                        //
	VarbinaryVal  []byte           `bun:"varbinary_val,nullzero" form:"varbinary_val" json:"varbinary_val,omitempty" xml:"VarbinaryVal"`            //
	BlobVal       []byte           `bun:"blob_val,nullzero" form:"blob_val" json:"blob_val,omitempty" xml:"BlobVal"`                                //
	MediumblobVal []byte           `bun:"mediumblob_val,nullzero" form:"mediumblob_val" json:"mediumblob_val,omitempty" xml:"MediumblobVal"`        //
	LongblobVal   []byte           `bun:"longblob_val,nullzero" form:"longblob_val" json:"longblob_val,omitempty" xml:"LongblobVal"`                //
	// This is a JSON column
	// with multiple lines of text
	// This is a JSON column
	// with multiple lines of text
	// This is a JSON column
	// with multiple lines of text
	JsonVal        json.RawMessage `bun:"json_val,nullzero" form:"json_val" json:"json_val,omitempty" xml:"JsonVal"`
	BitVal         []byte          `bun:"bit_val,nullzero" form:"bit_val" json:"bit_val,omitempty" xml:"BitVal"`                                         //
	NullableIntVal *int32          `bun:"nullable_int_val,nullzero" form:"nullable_int_val" json:"nullable_int_val,omitempty" xml:"NullableIntVal"`      //
	IgnoreVal      *string         `bun:"ignore_val,nullzero" form:"ignore_val" json:"ignore_val,omitempty" xml:"IgnoreVal"`                             //
	CreatedAt      time.Time       `bun:"created_at,notnull,default:current_timestamp(3)" form:"created_at" json:"created_at,omitempty" xml:"CreatedAt"` // created at
	UpdatedAt      time.Time       `bun:"updated_at,notnull,default:current_timestamp(3)" form:"updated_at" json:"updated_at,omitempty" xml:"UpdatedAt"` // updated at
	DeletedAt      *time.Time      `bun:"deleted_at,soft_delete,nullzero" form:"deleted_at" json:"-" xml:"DeletedAt"`                                    // deleted at
}

func (m *TestAllType) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	now := time.Now().UTC()
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}
	return nil
}
func (m *TestAllType) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	now := time.Now().UTC()
	m.UpdatedAt = now
	return nil
}
