// Code generated by bake. DO NOT EDIT.
// version: v0.1.0
// source: test_all_types

// Package model defines database models generated from schema.
package model

import (
	"context"
	"encoding/json"
	"time"

	"github.com/shopspring/decimal"
	"github.com/uptrace/bun"
)

var NilTestAllType = (*TestAllType)(nil)

var (
	_ bun.BeforeInsertHook = (*TestAllType)(nil)
	_ bun.BeforeUpdateHook = (*TestAllType)(nil)
)

const (
	TestAllTypeTableName  = "test_all_types"
	TestAllTypeTableAlias = "test_all_types_alias"
)

var (
	TestAllTypeTableNameIdent  = bun.Ident("test_all_types")
	TestAllTypeTableAliasIdent = bun.Ident("test_all_types_alias")
)

const (
	InnerJoinTestAllTypeAsAlias = "INNER JOIN test_all_types AS test_all_types_alias" // same as JOIN
	LeftJoinTestAllTypeAsAlias  = "LEFT JOIN test_all_types AS test_all_types_alias"  // same as LEFT OUTER JOIN
	RightJoinTestAllTypeAsAlias = "RIGHT JOIN test_all_types AS test_all_types_alias" // same as RIGHT OUTER JOIN
	FullJoinTestAllTypeAsAlias  = "FULL JOIN test_all_types AS test_all_types_alias"  // same as FULL OUTER JOIN
)

const (
	TestAllTypeID             = "id"
	TestAllTypeTinyIntVal     = "tiny_int_val"
	TestAllTypeSmallIntVal    = "small_int_val"
	TestAllTypeMediumIntVal   = "medium_int_val"
	TestAllTypeIntVal         = "int_val"
	TestAllTypeBigIntVal      = "big_int_val"
	TestAllTypeDecimalVal     = "decimal_val"
	TestAllTypeFloatVal       = "float_val"
	TestAllTypeDoubleVal      = "double_val"
	TestAllTypeCharVal        = "char_val"
	TestAllTypeVarcharVal     = "varchar_val"
	TestAllTypeTextVal        = "text_val"
	TestAllTypeMediumtextVal  = "mediumtext_val"
	TestAllTypeLongtextVal    = "longtext_val"
	TestAllTypeDateVal        = "date_val"
	TestAllTypeTimeVal        = "time_val"
	TestAllTypeDatetimeVal    = "datetime_val"
	TestAllTypeTimestampVal   = "timestamp_val"
	TestAllTypeYearVal        = "year_val"
	TestAllTypeBoolVal        = "bool_val"
	TestAllTypeEnumVal        = "enum_val"
	TestAllTypeSetVal         = "set_val"
	TestAllTypeBinaryVal      = "binary_val"
	TestAllTypeVarbinaryVal   = "varbinary_val"
	TestAllTypeBlobVal        = "blob_val"
	TestAllTypeMediumblobVal  = "mediumblob_val"
	TestAllTypeLongblobVal    = "longblob_val"
	TestAllTypeJsonVal        = "json_val"
	TestAllTypeBitVal         = "bit_val"
	TestAllTypeNullableIntVal = "nullable_int_val"
	TestAllTypeIgnoreVal      = "ignore_val"
	TestAllTypeCreatedAt      = "created_at"
	TestAllTypeUpdatedAt      = "updated_at"
	TestAllTypeDeletedAt      = "deleted_at"
)

const (
	TestAllTypeAliasID             = "test_all_types_alias.id"
	TestAllTypeAliasTinyIntVal     = "test_all_types_alias.tiny_int_val"
	TestAllTypeAliasSmallIntVal    = "test_all_types_alias.small_int_val"
	TestAllTypeAliasMediumIntVal   = "test_all_types_alias.medium_int_val"
	TestAllTypeAliasIntVal         = "test_all_types_alias.int_val"
	TestAllTypeAliasBigIntVal      = "test_all_types_alias.big_int_val"
	TestAllTypeAliasDecimalVal     = "test_all_types_alias.decimal_val"
	TestAllTypeAliasFloatVal       = "test_all_types_alias.float_val"
	TestAllTypeAliasDoubleVal      = "test_all_types_alias.double_val"
	TestAllTypeAliasCharVal        = "test_all_types_alias.char_val"
	TestAllTypeAliasVarcharVal     = "test_all_types_alias.varchar_val"
	TestAllTypeAliasTextVal        = "test_all_types_alias.text_val"
	TestAllTypeAliasMediumtextVal  = "test_all_types_alias.mediumtext_val"
	TestAllTypeAliasLongtextVal    = "test_all_types_alias.longtext_val"
	TestAllTypeAliasDateVal        = "test_all_types_alias.date_val"
	TestAllTypeAliasTimeVal        = "test_all_types_alias.time_val"
	TestAllTypeAliasDatetimeVal    = "test_all_types_alias.datetime_val"
	TestAllTypeAliasTimestampVal   = "test_all_types_alias.timestamp_val"
	TestAllTypeAliasYearVal        = "test_all_types_alias.year_val"
	TestAllTypeAliasBoolVal        = "test_all_types_alias.bool_val"
	TestAllTypeAliasEnumVal        = "test_all_types_alias.enum_val"
	TestAllTypeAliasSetVal         = "test_all_types_alias.set_val"
	TestAllTypeAliasBinaryVal      = "test_all_types_alias.binary_val"
	TestAllTypeAliasVarbinaryVal   = "test_all_types_alias.varbinary_val"
	TestAllTypeAliasBlobVal        = "test_all_types_alias.blob_val"
	TestAllTypeAliasMediumblobVal  = "test_all_types_alias.mediumblob_val"
	TestAllTypeAliasLongblobVal    = "test_all_types_alias.longblob_val"
	TestAllTypeAliasJsonVal        = "test_all_types_alias.json_val"
	TestAllTypeAliasBitVal         = "test_all_types_alias.bit_val"
	TestAllTypeAliasNullableIntVal = "test_all_types_alias.nullable_int_val"
	TestAllTypeAliasIgnoreVal      = "test_all_types_alias.ignore_val"
	TestAllTypeAliasCreatedAt      = "test_all_types_alias.created_at"
	TestAllTypeAliasUpdatedAt      = "test_all_types_alias.updated_at"
	TestAllTypeAliasDeletedAt      = "test_all_types_alias.deleted_at"
)

var (
	TestAllTypeIDIdent             = bun.Ident("id")
	TestAllTypeTinyIntValIdent     = bun.Ident("tiny_int_val")
	TestAllTypeSmallIntValIdent    = bun.Ident("small_int_val")
	TestAllTypeMediumIntValIdent   = bun.Ident("medium_int_val")
	TestAllTypeIntValIdent         = bun.Ident("int_val")
	TestAllTypeBigIntValIdent      = bun.Ident("big_int_val")
	TestAllTypeDecimalValIdent     = bun.Ident("decimal_val")
	TestAllTypeFloatValIdent       = bun.Ident("float_val")
	TestAllTypeDoubleValIdent      = bun.Ident("double_val")
	TestAllTypeCharValIdent        = bun.Ident("char_val")
	TestAllTypeVarcharValIdent     = bun.Ident("varchar_val")
	TestAllTypeTextValIdent        = bun.Ident("text_val")
	TestAllTypeMediumtextValIdent  = bun.Ident("mediumtext_val")
	TestAllTypeLongtextValIdent    = bun.Ident("longtext_val")
	TestAllTypeDateValIdent        = bun.Ident("date_val")
	TestAllTypeTimeValIdent        = bun.Ident("time_val")
	TestAllTypeDatetimeValIdent    = bun.Ident("datetime_val")
	TestAllTypeTimestampValIdent   = bun.Ident("timestamp_val")
	TestAllTypeYearValIdent        = bun.Ident("year_val")
	TestAllTypeBoolValIdent        = bun.Ident("bool_val")
	TestAllTypeEnumValIdent        = bun.Ident("enum_val")
	TestAllTypeSetValIdent         = bun.Ident("set_val")
	TestAllTypeBinaryValIdent      = bun.Ident("binary_val")
	TestAllTypeVarbinaryValIdent   = bun.Ident("varbinary_val")
	TestAllTypeBlobValIdent        = bun.Ident("blob_val")
	TestAllTypeMediumblobValIdent  = bun.Ident("mediumblob_val")
	TestAllTypeLongblobValIdent    = bun.Ident("longblob_val")
	TestAllTypeJsonValIdent        = bun.Ident("json_val")
	TestAllTypeBitValIdent         = bun.Ident("bit_val")
	TestAllTypeNullableIntValIdent = bun.Ident("nullable_int_val")
	TestAllTypeIgnoreValIdent      = bun.Ident("ignore_val")
	TestAllTypeCreatedAtIdent      = bun.Ident("created_at")
	TestAllTypeUpdatedAtIdent      = bun.Ident("updated_at")
	TestAllTypeDeletedAtIdent      = bun.Ident("deleted_at")
)

const (
	TestAllTypeIDEq             = "id = ?"
	TestAllTypeTinyIntValEq     = "tiny_int_val = ?"
	TestAllTypeSmallIntValEq    = "small_int_val = ?"
	TestAllTypeMediumIntValEq   = "medium_int_val = ?"
	TestAllTypeIntValEq         = "int_val = ?"
	TestAllTypeBigIntValEq      = "big_int_val = ?"
	TestAllTypeDecimalValEq     = "decimal_val = ?"
	TestAllTypeFloatValEq       = "float_val = ?"
	TestAllTypeDoubleValEq      = "double_val = ?"
	TestAllTypeCharValEq        = "char_val = ?"
	TestAllTypeVarcharValEq     = "varchar_val = ?"
	TestAllTypeTextValEq        = "text_val = ?"
	TestAllTypeMediumtextValEq  = "mediumtext_val = ?"
	TestAllTypeLongtextValEq    = "longtext_val = ?"
	TestAllTypeDateValEq        = "date_val = ?"
	TestAllTypeTimeValEq        = "time_val = ?"
	TestAllTypeDatetimeValEq    = "datetime_val = ?"
	TestAllTypeTimestampValEq   = "timestamp_val = ?"
	TestAllTypeYearValEq        = "year_val = ?"
	TestAllTypeBoolValEq        = "bool_val = ?"
	TestAllTypeEnumValEq        = "enum_val = ?"
	TestAllTypeSetValEq         = "set_val = ?"
	TestAllTypeBinaryValEq      = "binary_val = ?"
	TestAllTypeVarbinaryValEq   = "varbinary_val = ?"
	TestAllTypeBlobValEq        = "blob_val = ?"
	TestAllTypeMediumblobValEq  = "mediumblob_val = ?"
	TestAllTypeLongblobValEq    = "longblob_val = ?"
	TestAllTypeJsonValEq        = "json_val = ?"
	TestAllTypeBitValEq         = "bit_val = ?"
	TestAllTypeNullableIntValEq = "nullable_int_val = ?"
	TestAllTypeIgnoreValEq      = "ignore_val = ?"
	TestAllTypeCreatedAtEq      = "created_at = ?"
	TestAllTypeUpdatedAtEq      = "updated_at = ?"
	TestAllTypeDeletedAtEq      = "deleted_at = ?"
)

const (
	TestAllTypeAliasIDEq             = "test_all_types_alias.id = ?"
	TestAllTypeAliasTinyIntValEq     = "test_all_types_alias.tiny_int_val = ?"
	TestAllTypeAliasSmallIntValEq    = "test_all_types_alias.small_int_val = ?"
	TestAllTypeAliasMediumIntValEq   = "test_all_types_alias.medium_int_val = ?"
	TestAllTypeAliasIntValEq         = "test_all_types_alias.int_val = ?"
	TestAllTypeAliasBigIntValEq      = "test_all_types_alias.big_int_val = ?"
	TestAllTypeAliasDecimalValEq     = "test_all_types_alias.decimal_val = ?"
	TestAllTypeAliasFloatValEq       = "test_all_types_alias.float_val = ?"
	TestAllTypeAliasDoubleValEq      = "test_all_types_alias.double_val = ?"
	TestAllTypeAliasCharValEq        = "test_all_types_alias.char_val = ?"
	TestAllTypeAliasVarcharValEq     = "test_all_types_alias.varchar_val = ?"
	TestAllTypeAliasTextValEq        = "test_all_types_alias.text_val = ?"
	TestAllTypeAliasMediumtextValEq  = "test_all_types_alias.mediumtext_val = ?"
	TestAllTypeAliasLongtextValEq    = "test_all_types_alias.longtext_val = ?"
	TestAllTypeAliasDateValEq        = "test_all_types_alias.date_val = ?"
	TestAllTypeAliasTimeValEq        = "test_all_types_alias.time_val = ?"
	TestAllTypeAliasDatetimeValEq    = "test_all_types_alias.datetime_val = ?"
	TestAllTypeAliasTimestampValEq   = "test_all_types_alias.timestamp_val = ?"
	TestAllTypeAliasYearValEq        = "test_all_types_alias.year_val = ?"
	TestAllTypeAliasBoolValEq        = "test_all_types_alias.bool_val = ?"
	TestAllTypeAliasEnumValEq        = "test_all_types_alias.enum_val = ?"
	TestAllTypeAliasSetValEq         = "test_all_types_alias.set_val = ?"
	TestAllTypeAliasBinaryValEq      = "test_all_types_alias.binary_val = ?"
	TestAllTypeAliasVarbinaryValEq   = "test_all_types_alias.varbinary_val = ?"
	TestAllTypeAliasBlobValEq        = "test_all_types_alias.blob_val = ?"
	TestAllTypeAliasMediumblobValEq  = "test_all_types_alias.mediumblob_val = ?"
	TestAllTypeAliasLongblobValEq    = "test_all_types_alias.longblob_val = ?"
	TestAllTypeAliasJsonValEq        = "test_all_types_alias.json_val = ?"
	TestAllTypeAliasBitValEq         = "test_all_types_alias.bit_val = ?"
	TestAllTypeAliasNullableIntValEq = "test_all_types_alias.nullable_int_val = ?"
	TestAllTypeAliasIgnoreValEq      = "test_all_types_alias.ignore_val = ?"
	TestAllTypeAliasCreatedAtEq      = "test_all_types_alias.created_at = ?"
	TestAllTypeAliasUpdatedAtEq      = "test_all_types_alias.updated_at = ?"
	TestAllTypeAliasDeletedAtEq      = "test_all_types_alias.deleted_at = ?"
)

const (
	TestAllTypeIDNeq             = "id <> ?"
	TestAllTypeTinyIntValNeq     = "tiny_int_val <> ?"
	TestAllTypeSmallIntValNeq    = "small_int_val <> ?"
	TestAllTypeMediumIntValNeq   = "medium_int_val <> ?"
	TestAllTypeIntValNeq         = "int_val <> ?"
	TestAllTypeBigIntValNeq      = "big_int_val <> ?"
	TestAllTypeDecimalValNeq     = "decimal_val <> ?"
	TestAllTypeFloatValNeq       = "float_val <> ?"
	TestAllTypeDoubleValNeq      = "double_val <> ?"
	TestAllTypeCharValNeq        = "char_val <> ?"
	TestAllTypeVarcharValNeq     = "varchar_val <> ?"
	TestAllTypeTextValNeq        = "text_val <> ?"
	TestAllTypeMediumtextValNeq  = "mediumtext_val <> ?"
	TestAllTypeLongtextValNeq    = "longtext_val <> ?"
	TestAllTypeDateValNeq        = "date_val <> ?"
	TestAllTypeTimeValNeq        = "time_val <> ?"
	TestAllTypeDatetimeValNeq    = "datetime_val <> ?"
	TestAllTypeTimestampValNeq   = "timestamp_val <> ?"
	TestAllTypeYearValNeq        = "year_val <> ?"
	TestAllTypeBoolValNeq        = "bool_val <> ?"
	TestAllTypeEnumValNeq        = "enum_val <> ?"
	TestAllTypeSetValNeq         = "set_val <> ?"
	TestAllTypeBinaryValNeq      = "binary_val <> ?"
	TestAllTypeVarbinaryValNeq   = "varbinary_val <> ?"
	TestAllTypeBlobValNeq        = "blob_val <> ?"
	TestAllTypeMediumblobValNeq  = "mediumblob_val <> ?"
	TestAllTypeLongblobValNeq    = "longblob_val <> ?"
	TestAllTypeJsonValNeq        = "json_val <> ?"
	TestAllTypeBitValNeq         = "bit_val <> ?"
	TestAllTypeNullableIntValNeq = "nullable_int_val <> ?"
	TestAllTypeIgnoreValNeq      = "ignore_val <> ?"
	TestAllTypeCreatedAtNeq      = "created_at <> ?"
	TestAllTypeUpdatedAtNeq      = "updated_at <> ?"
	TestAllTypeDeletedAtNeq      = "deleted_at <> ?"
)

const (
	TestAllTypeAliasIDNeq             = "test_all_types_alias.id <> ?"
	TestAllTypeAliasTinyIntValNeq     = "test_all_types_alias.tiny_int_val <> ?"
	TestAllTypeAliasSmallIntValNeq    = "test_all_types_alias.small_int_val <> ?"
	TestAllTypeAliasMediumIntValNeq   = "test_all_types_alias.medium_int_val <> ?"
	TestAllTypeAliasIntValNeq         = "test_all_types_alias.int_val <> ?"
	TestAllTypeAliasBigIntValNeq      = "test_all_types_alias.big_int_val <> ?"
	TestAllTypeAliasDecimalValNeq     = "test_all_types_alias.decimal_val <> ?"
	TestAllTypeAliasFloatValNeq       = "test_all_types_alias.float_val <> ?"
	TestAllTypeAliasDoubleValNeq      = "test_all_types_alias.double_val <> ?"
	TestAllTypeAliasCharValNeq        = "test_all_types_alias.char_val <> ?"
	TestAllTypeAliasVarcharValNeq     = "test_all_types_alias.varchar_val <> ?"
	TestAllTypeAliasTextValNeq        = "test_all_types_alias.text_val <> ?"
	TestAllTypeAliasMediumtextValNeq  = "test_all_types_alias.mediumtext_val <> ?"
	TestAllTypeAliasLongtextValNeq    = "test_all_types_alias.longtext_val <> ?"
	TestAllTypeAliasDateValNeq        = "test_all_types_alias.date_val <> ?"
	TestAllTypeAliasTimeValNeq        = "test_all_types_alias.time_val <> ?"
	TestAllTypeAliasDatetimeValNeq    = "test_all_types_alias.datetime_val <> ?"
	TestAllTypeAliasTimestampValNeq   = "test_all_types_alias.timestamp_val <> ?"
	TestAllTypeAliasYearValNeq        = "test_all_types_alias.year_val <> ?"
	TestAllTypeAliasBoolValNeq        = "test_all_types_alias.bool_val <> ?"
	TestAllTypeAliasEnumValNeq        = "test_all_types_alias.enum_val <> ?"
	TestAllTypeAliasSetValNeq         = "test_all_types_alias.set_val <> ?"
	TestAllTypeAliasBinaryValNeq      = "test_all_types_alias.binary_val <> ?"
	TestAllTypeAliasVarbinaryValNeq   = "test_all_types_alias.varbinary_val <> ?"
	TestAllTypeAliasBlobValNeq        = "test_all_types_alias.blob_val <> ?"
	TestAllTypeAliasMediumblobValNeq  = "test_all_types_alias.mediumblob_val <> ?"
	TestAllTypeAliasLongblobValNeq    = "test_all_types_alias.longblob_val <> ?"
	TestAllTypeAliasJsonValNeq        = "test_all_types_alias.json_val <> ?"
	TestAllTypeAliasBitValNeq         = "test_all_types_alias.bit_val <> ?"
	TestAllTypeAliasNullableIntValNeq = "test_all_types_alias.nullable_int_val <> ?"
	TestAllTypeAliasIgnoreValNeq      = "test_all_types_alias.ignore_val <> ?"
	TestAllTypeAliasCreatedAtNeq      = "test_all_types_alias.created_at <> ?"
	TestAllTypeAliasUpdatedAtNeq      = "test_all_types_alias.updated_at <> ?"
	TestAllTypeAliasDeletedAtNeq      = "test_all_types_alias.deleted_at <> ?"
)

const (
	TestAllTypeIDGt             = "id > ?"
	TestAllTypeTinyIntValGt     = "tiny_int_val > ?"
	TestAllTypeSmallIntValGt    = "small_int_val > ?"
	TestAllTypeMediumIntValGt   = "medium_int_val > ?"
	TestAllTypeIntValGt         = "int_val > ?"
	TestAllTypeBigIntValGt      = "big_int_val > ?"
	TestAllTypeDecimalValGt     = "decimal_val > ?"
	TestAllTypeFloatValGt       = "float_val > ?"
	TestAllTypeDoubleValGt      = "double_val > ?"
	TestAllTypeDateValGt        = "date_val > ?"
	TestAllTypeTimeValGt        = "time_val > ?"
	TestAllTypeDatetimeValGt    = "datetime_val > ?"
	TestAllTypeTimestampValGt   = "timestamp_val > ?"
	TestAllTypeYearValGt        = "year_val > ?"
	TestAllTypeNullableIntValGt = "nullable_int_val > ?"
	TestAllTypeCreatedAtGt      = "created_at > ?"
	TestAllTypeUpdatedAtGt      = "updated_at > ?"
	TestAllTypeDeletedAtGt      = "deleted_at > ?"
)

const (
	TestAllTypeAliasIDGt             = "test_all_types_alias.id > ?"
	TestAllTypeAliasTinyIntValGt     = "test_all_types_alias.tiny_int_val > ?"
	TestAllTypeAliasSmallIntValGt    = "test_all_types_alias.small_int_val > ?"
	TestAllTypeAliasMediumIntValGt   = "test_all_types_alias.medium_int_val > ?"
	TestAllTypeAliasIntValGt         = "test_all_types_alias.int_val > ?"
	TestAllTypeAliasBigIntValGt      = "test_all_types_alias.big_int_val > ?"
	TestAllTypeAliasDecimalValGt     = "test_all_types_alias.decimal_val > ?"
	TestAllTypeAliasFloatValGt       = "test_all_types_alias.float_val > ?"
	TestAllTypeAliasDoubleValGt      = "test_all_types_alias.double_val > ?"
	TestAllTypeAliasDateValGt        = "test_all_types_alias.date_val > ?"
	TestAllTypeAliasTimeValGt        = "test_all_types_alias.time_val > ?"
	TestAllTypeAliasDatetimeValGt    = "test_all_types_alias.datetime_val > ?"
	TestAllTypeAliasTimestampValGt   = "test_all_types_alias.timestamp_val > ?"
	TestAllTypeAliasYearValGt        = "test_all_types_alias.year_val > ?"
	TestAllTypeAliasNullableIntValGt = "test_all_types_alias.nullable_int_val > ?"
	TestAllTypeAliasCreatedAtGt      = "test_all_types_alias.created_at > ?"
	TestAllTypeAliasUpdatedAtGt      = "test_all_types_alias.updated_at > ?"
	TestAllTypeAliasDeletedAtGt      = "test_all_types_alias.deleted_at > ?"
)

const (
	TestAllTypeIDGte             = "id >= ?"
	TestAllTypeTinyIntValGte     = "tiny_int_val >= ?"
	TestAllTypeSmallIntValGte    = "small_int_val >= ?"
	TestAllTypeMediumIntValGte   = "medium_int_val >= ?"
	TestAllTypeIntValGte         = "int_val >= ?"
	TestAllTypeBigIntValGte      = "big_int_val >= ?"
	TestAllTypeDecimalValGte     = "decimal_val >= ?"
	TestAllTypeFloatValGte       = "float_val >= ?"
	TestAllTypeDoubleValGte      = "double_val >= ?"
	TestAllTypeDateValGte        = "date_val >= ?"
	TestAllTypeTimeValGte        = "time_val >= ?"
	TestAllTypeDatetimeValGte    = "datetime_val >= ?"
	TestAllTypeTimestampValGte   = "timestamp_val >= ?"
	TestAllTypeYearValGte        = "year_val >= ?"
	TestAllTypeNullableIntValGte = "nullable_int_val >= ?"
	TestAllTypeCreatedAtGte      = "created_at >= ?"
	TestAllTypeUpdatedAtGte      = "updated_at >= ?"
	TestAllTypeDeletedAtGte      = "deleted_at >= ?"
)

const (
	TestAllTypeAliasIDGte             = "test_all_types_alias.id >= ?"
	TestAllTypeAliasTinyIntValGte     = "test_all_types_alias.tiny_int_val >= ?"
	TestAllTypeAliasSmallIntValGte    = "test_all_types_alias.small_int_val >= ?"
	TestAllTypeAliasMediumIntValGte   = "test_all_types_alias.medium_int_val >= ?"
	TestAllTypeAliasIntValGte         = "test_all_types_alias.int_val >= ?"
	TestAllTypeAliasBigIntValGte      = "test_all_types_alias.big_int_val >= ?"
	TestAllTypeAliasDecimalValGte     = "test_all_types_alias.decimal_val >= ?"
	TestAllTypeAliasFloatValGte       = "test_all_types_alias.float_val >= ?"
	TestAllTypeAliasDoubleValGte      = "test_all_types_alias.double_val >= ?"
	TestAllTypeAliasDateValGte        = "test_all_types_alias.date_val >= ?"
	TestAllTypeAliasTimeValGte        = "test_all_types_alias.time_val >= ?"
	TestAllTypeAliasDatetimeValGte    = "test_all_types_alias.datetime_val >= ?"
	TestAllTypeAliasTimestampValGte   = "test_all_types_alias.timestamp_val >= ?"
	TestAllTypeAliasYearValGte        = "test_all_types_alias.year_val >= ?"
	TestAllTypeAliasNullableIntValGte = "test_all_types_alias.nullable_int_val >= ?"
	TestAllTypeAliasCreatedAtGte      = "test_all_types_alias.created_at >= ?"
	TestAllTypeAliasUpdatedAtGte      = "test_all_types_alias.updated_at >= ?"
	TestAllTypeAliasDeletedAtGte      = "test_all_types_alias.deleted_at >= ?"
)

const (
	TestAllTypeIDLt             = "id < ?"
	TestAllTypeTinyIntValLt     = "tiny_int_val < ?"
	TestAllTypeSmallIntValLt    = "small_int_val < ?"
	TestAllTypeMediumIntValLt   = "medium_int_val < ?"
	TestAllTypeIntValLt         = "int_val < ?"
	TestAllTypeBigIntValLt      = "big_int_val < ?"
	TestAllTypeDecimalValLt     = "decimal_val < ?"
	TestAllTypeFloatValLt       = "float_val < ?"
	TestAllTypeDoubleValLt      = "double_val < ?"
	TestAllTypeDateValLt        = "date_val < ?"
	TestAllTypeTimeValLt        = "time_val < ?"
	TestAllTypeDatetimeValLt    = "datetime_val < ?"
	TestAllTypeTimestampValLt   = "timestamp_val < ?"
	TestAllTypeYearValLt        = "year_val < ?"
	TestAllTypeNullableIntValLt = "nullable_int_val < ?"
	TestAllTypeCreatedAtLt      = "created_at < ?"
	TestAllTypeUpdatedAtLt      = "updated_at < ?"
	TestAllTypeDeletedAtLt      = "deleted_at < ?"
)

const (
	TestAllTypeAliasIDLt             = "test_all_types_alias.id < ?"
	TestAllTypeAliasTinyIntValLt     = "test_all_types_alias.tiny_int_val < ?"
	TestAllTypeAliasSmallIntValLt    = "test_all_types_alias.small_int_val < ?"
	TestAllTypeAliasMediumIntValLt   = "test_all_types_alias.medium_int_val < ?"
	TestAllTypeAliasIntValLt         = "test_all_types_alias.int_val < ?"
	TestAllTypeAliasBigIntValLt      = "test_all_types_alias.big_int_val < ?"
	TestAllTypeAliasDecimalValLt     = "test_all_types_alias.decimal_val < ?"
	TestAllTypeAliasFloatValLt       = "test_all_types_alias.float_val < ?"
	TestAllTypeAliasDoubleValLt      = "test_all_types_alias.double_val < ?"
	TestAllTypeAliasDateValLt        = "test_all_types_alias.date_val < ?"
	TestAllTypeAliasTimeValLt        = "test_all_types_alias.time_val < ?"
	TestAllTypeAliasDatetimeValLt    = "test_all_types_alias.datetime_val < ?"
	TestAllTypeAliasTimestampValLt   = "test_all_types_alias.timestamp_val < ?"
	TestAllTypeAliasYearValLt        = "test_all_types_alias.year_val < ?"
	TestAllTypeAliasNullableIntValLt = "test_all_types_alias.nullable_int_val < ?"
	TestAllTypeAliasCreatedAtLt      = "test_all_types_alias.created_at < ?"
	TestAllTypeAliasUpdatedAtLt      = "test_all_types_alias.updated_at < ?"
	TestAllTypeAliasDeletedAtLt      = "test_all_types_alias.deleted_at < ?"
)

const (
	TestAllTypeIDLte             = "id <= ?"
	TestAllTypeTinyIntValLte     = "tiny_int_val <= ?"
	TestAllTypeSmallIntValLte    = "small_int_val <= ?"
	TestAllTypeMediumIntValLte   = "medium_int_val <= ?"
	TestAllTypeIntValLte         = "int_val <= ?"
	TestAllTypeBigIntValLte      = "big_int_val <= ?"
	TestAllTypeDecimalValLte     = "decimal_val <= ?"
	TestAllTypeFloatValLte       = "float_val <= ?"
	TestAllTypeDoubleValLte      = "double_val <= ?"
	TestAllTypeDateValLte        = "date_val <= ?"
	TestAllTypeTimeValLte        = "time_val <= ?"
	TestAllTypeDatetimeValLte    = "datetime_val <= ?"
	TestAllTypeTimestampValLte   = "timestamp_val <= ?"
	TestAllTypeYearValLte        = "year_val <= ?"
	TestAllTypeNullableIntValLte = "nullable_int_val <= ?"
	TestAllTypeCreatedAtLte      = "created_at <= ?"
	TestAllTypeUpdatedAtLte      = "updated_at <= ?"
	TestAllTypeDeletedAtLte      = "deleted_at <= ?"
)

const (
	TestAllTypeAliasIDLte             = "test_all_types_alias.id <= ?"
	TestAllTypeAliasTinyIntValLte     = "test_all_types_alias.tiny_int_val <= ?"
	TestAllTypeAliasSmallIntValLte    = "test_all_types_alias.small_int_val <= ?"
	TestAllTypeAliasMediumIntValLte   = "test_all_types_alias.medium_int_val <= ?"
	TestAllTypeAliasIntValLte         = "test_all_types_alias.int_val <= ?"
	TestAllTypeAliasBigIntValLte      = "test_all_types_alias.big_int_val <= ?"
	TestAllTypeAliasDecimalValLte     = "test_all_types_alias.decimal_val <= ?"
	TestAllTypeAliasFloatValLte       = "test_all_types_alias.float_val <= ?"
	TestAllTypeAliasDoubleValLte      = "test_all_types_alias.double_val <= ?"
	TestAllTypeAliasDateValLte        = "test_all_types_alias.date_val <= ?"
	TestAllTypeAliasTimeValLte        = "test_all_types_alias.time_val <= ?"
	TestAllTypeAliasDatetimeValLte    = "test_all_types_alias.datetime_val <= ?"
	TestAllTypeAliasTimestampValLte   = "test_all_types_alias.timestamp_val <= ?"
	TestAllTypeAliasYearValLte        = "test_all_types_alias.year_val <= ?"
	TestAllTypeAliasNullableIntValLte = "test_all_types_alias.nullable_int_val <= ?"
	TestAllTypeAliasCreatedAtLte      = "test_all_types_alias.created_at <= ?"
	TestAllTypeAliasUpdatedAtLte      = "test_all_types_alias.updated_at <= ?"
	TestAllTypeAliasDeletedAtLte      = "test_all_types_alias.deleted_at <= ?"
)

const (
	TestAllTypeCharValLike       = "char_val LIKE ?"
	TestAllTypeVarcharValLike    = "varchar_val LIKE ?"
	TestAllTypeTextValLike       = "text_val LIKE ?"
	TestAllTypeMediumtextValLike = "mediumtext_val LIKE ?"
	TestAllTypeLongtextValLike   = "longtext_val LIKE ?"
	TestAllTypeIgnoreValLike     = "ignore_val LIKE ?"
)

const (
	TestAllTypeAliasCharValLike       = "test_all_types_alias.char_val LIKE ?"
	TestAllTypeAliasVarcharValLike    = "test_all_types_alias.varchar_val LIKE ?"
	TestAllTypeAliasTextValLike       = "test_all_types_alias.text_val LIKE ?"
	TestAllTypeAliasMediumtextValLike = "test_all_types_alias.mediumtext_val LIKE ?"
	TestAllTypeAliasLongtextValLike   = "test_all_types_alias.longtext_val LIKE ?"
	TestAllTypeAliasIgnoreValLike     = "test_all_types_alias.ignore_val LIKE ?"
)

const (
	TestAllTypeCharValLikePrefix       = "char_val LIKE ?%"
	TestAllTypeVarcharValLikePrefix    = "varchar_val LIKE ?%"
	TestAllTypeTextValLikePrefix       = "text_val LIKE ?%"
	TestAllTypeMediumtextValLikePrefix = "mediumtext_val LIKE ?%"
	TestAllTypeLongtextValLikePrefix   = "longtext_val LIKE ?%"
	TestAllTypeIgnoreValLikePrefix     = "ignore_val LIKE ?%"
)

const (
	TestAllTypeAliasCharValLikePrefix       = "test_all_types_alias.char_val LIKE ?%"
	TestAllTypeAliasVarcharValLikePrefix    = "test_all_types_alias.varchar_val LIKE ?%"
	TestAllTypeAliasTextValLikePrefix       = "test_all_types_alias.text_val LIKE ?%"
	TestAllTypeAliasMediumtextValLikePrefix = "test_all_types_alias.mediumtext_val LIKE ?%"
	TestAllTypeAliasLongtextValLikePrefix   = "test_all_types_alias.longtext_val LIKE ?%"
	TestAllTypeAliasIgnoreValLikePrefix     = "test_all_types_alias.ignore_val LIKE ?%"
)

const (
	TestAllTypeCharValLikeSuffix       = "char_val LIKE %?"
	TestAllTypeVarcharValLikeSuffix    = "varchar_val LIKE %?"
	TestAllTypeTextValLikeSuffix       = "text_val LIKE %?"
	TestAllTypeMediumtextValLikeSuffix = "mediumtext_val LIKE %?"
	TestAllTypeLongtextValLikeSuffix   = "longtext_val LIKE %?"
	TestAllTypeIgnoreValLikeSuffix     = "ignore_val LIKE %?"
)

const (
	TestAllTypeAliasCharValLikeSuffix       = "test_all_types_alias.char_val LIKE %?"
	TestAllTypeAliasVarcharValLikeSuffix    = "test_all_types_alias.varchar_val LIKE %?"
	TestAllTypeAliasTextValLikeSuffix       = "test_all_types_alias.text_val LIKE %?"
	TestAllTypeAliasMediumtextValLikeSuffix = "test_all_types_alias.mediumtext_val LIKE %?"
	TestAllTypeAliasLongtextValLikeSuffix   = "test_all_types_alias.longtext_val LIKE %?"
	TestAllTypeAliasIgnoreValLikeSuffix     = "test_all_types_alias.ignore_val LIKE %?"
)

const (
	TestAllTypeCharValLikeContain       = "char_val LIKE %?%"
	TestAllTypeVarcharValLikeContain    = "varchar_val LIKE %?%"
	TestAllTypeTextValLikeContain       = "text_val LIKE %?%"
	TestAllTypeMediumtextValLikeContain = "mediumtext_val LIKE %?%"
	TestAllTypeLongtextValLikeContain   = "longtext_val LIKE %?%"
	TestAllTypeIgnoreValLikeContain     = "ignore_val LIKE %?%"
)

const (
	TestAllTypeAliasCharValLikeContain       = "test_all_types_alias.char_val LIKE %?%"
	TestAllTypeAliasVarcharValLikeContain    = "test_all_types_alias.varchar_val LIKE %?%"
	TestAllTypeAliasTextValLikeContain       = "test_all_types_alias.text_val LIKE %?%"
	TestAllTypeAliasMediumtextValLikeContain = "test_all_types_alias.mediumtext_val LIKE %?%"
	TestAllTypeAliasLongtextValLikeContain   = "test_all_types_alias.longtext_val LIKE %?%"
	TestAllTypeAliasIgnoreValLikeContain     = "test_all_types_alias.ignore_val LIKE %?%"
)

const (
	TestAllTypeTinyIntValSUMExpr     = "SUM(tiny_int_val)"
	TestAllTypeSmallIntValSUMExpr    = "SUM(small_int_val)"
	TestAllTypeMediumIntValSUMExpr   = "SUM(medium_int_val)"
	TestAllTypeIntValSUMExpr         = "SUM(int_val)"
	TestAllTypeBigIntValSUMExpr      = "SUM(big_int_val)"
	TestAllTypeDecimalValSUMExpr     = "SUM(decimal_val)"
	TestAllTypeFloatValSUMExpr       = "SUM(float_val)"
	TestAllTypeDoubleValSUMExpr      = "SUM(double_val)"
	TestAllTypeYearValSUMExpr        = "SUM(year_val)"
	TestAllTypeNullableIntValSUMExpr = "SUM(nullable_int_val)"
)

const (
	TestAllTypeAliasTinyIntValSUMExpr     = "SUM(test_all_types_alias.tiny_int_val)"
	TestAllTypeAliasSmallIntValSUMExpr    = "SUM(test_all_types_alias.small_int_val)"
	TestAllTypeAliasMediumIntValSUMExpr   = "SUM(test_all_types_alias.medium_int_val)"
	TestAllTypeAliasIntValSUMExpr         = "SUM(test_all_types_alias.int_val)"
	TestAllTypeAliasBigIntValSUMExpr      = "SUM(test_all_types_alias.big_int_val)"
	TestAllTypeAliasDecimalValSUMExpr     = "SUM(test_all_types_alias.decimal_val)"
	TestAllTypeAliasFloatValSUMExpr       = "SUM(test_all_types_alias.float_val)"
	TestAllTypeAliasDoubleValSUMExpr      = "SUM(test_all_types_alias.double_val)"
	TestAllTypeAliasYearValSUMExpr        = "SUM(test_all_types_alias.year_val)"
	TestAllTypeAliasNullableIntValSUMExpr = "SUM(test_all_types_alias.nullable_int_val)"
)

const (
	TestAllTypeTinyIntValAVGExpr     = "AVG(tiny_int_val)"
	TestAllTypeSmallIntValAVGExpr    = "AVG(small_int_val)"
	TestAllTypeMediumIntValAVGExpr   = "AVG(medium_int_val)"
	TestAllTypeIntValAVGExpr         = "AVG(int_val)"
	TestAllTypeBigIntValAVGExpr      = "AVG(big_int_val)"
	TestAllTypeDecimalValAVGExpr     = "AVG(decimal_val)"
	TestAllTypeFloatValAVGExpr       = "AVG(float_val)"
	TestAllTypeDoubleValAVGExpr      = "AVG(double_val)"
	TestAllTypeYearValAVGExpr        = "AVG(year_val)"
	TestAllTypeNullableIntValAVGExpr = "AVG(nullable_int_val)"
)

const (
	TestAllTypeAliasTinyIntValAVGExpr     = "AVG(test_all_types_alias.tiny_int_val)"
	TestAllTypeAliasSmallIntValAVGExpr    = "AVG(test_all_types_alias.small_int_val)"
	TestAllTypeAliasMediumIntValAVGExpr   = "AVG(test_all_types_alias.medium_int_val)"
	TestAllTypeAliasIntValAVGExpr         = "AVG(test_all_types_alias.int_val)"
	TestAllTypeAliasBigIntValAVGExpr      = "AVG(test_all_types_alias.big_int_val)"
	TestAllTypeAliasDecimalValAVGExpr     = "AVG(test_all_types_alias.decimal_val)"
	TestAllTypeAliasFloatValAVGExpr       = "AVG(test_all_types_alias.float_val)"
	TestAllTypeAliasDoubleValAVGExpr      = "AVG(test_all_types_alias.double_val)"
	TestAllTypeAliasYearValAVGExpr        = "AVG(test_all_types_alias.year_val)"
	TestAllTypeAliasNullableIntValAVGExpr = "AVG(test_all_types_alias.nullable_int_val)"
)

const (
	TestAllTypeIDMINExpr             = "MIN(id)"
	TestAllTypeTinyIntValMINExpr     = "MIN(tiny_int_val)"
	TestAllTypeSmallIntValMINExpr    = "MIN(small_int_val)"
	TestAllTypeMediumIntValMINExpr   = "MIN(medium_int_val)"
	TestAllTypeIntValMINExpr         = "MIN(int_val)"
	TestAllTypeBigIntValMINExpr      = "MIN(big_int_val)"
	TestAllTypeDecimalValMINExpr     = "MIN(decimal_val)"
	TestAllTypeFloatValMINExpr       = "MIN(float_val)"
	TestAllTypeDoubleValMINExpr      = "MIN(double_val)"
	TestAllTypeDateValMINExpr        = "MIN(date_val)"
	TestAllTypeTimeValMINExpr        = "MIN(time_val)"
	TestAllTypeDatetimeValMINExpr    = "MIN(datetime_val)"
	TestAllTypeTimestampValMINExpr   = "MIN(timestamp_val)"
	TestAllTypeYearValMINExpr        = "MIN(year_val)"
	TestAllTypeNullableIntValMINExpr = "MIN(nullable_int_val)"
	TestAllTypeCreatedAtMINExpr      = "MIN(created_at)"
	TestAllTypeUpdatedAtMINExpr      = "MIN(updated_at)"
	TestAllTypeDeletedAtMINExpr      = "MIN(deleted_at)"
)

const (
	TestAllTypeAliasIDMINExpr             = "MIN(test_all_types_alias.id)"
	TestAllTypeAliasTinyIntValMINExpr     = "MIN(test_all_types_alias.tiny_int_val)"
	TestAllTypeAliasSmallIntValMINExpr    = "MIN(test_all_types_alias.small_int_val)"
	TestAllTypeAliasMediumIntValMINExpr   = "MIN(test_all_types_alias.medium_int_val)"
	TestAllTypeAliasIntValMINExpr         = "MIN(test_all_types_alias.int_val)"
	TestAllTypeAliasBigIntValMINExpr      = "MIN(test_all_types_alias.big_int_val)"
	TestAllTypeAliasDecimalValMINExpr     = "MIN(test_all_types_alias.decimal_val)"
	TestAllTypeAliasFloatValMINExpr       = "MIN(test_all_types_alias.float_val)"
	TestAllTypeAliasDoubleValMINExpr      = "MIN(test_all_types_alias.double_val)"
	TestAllTypeAliasDateValMINExpr        = "MIN(test_all_types_alias.date_val)"
	TestAllTypeAliasTimeValMINExpr        = "MIN(test_all_types_alias.time_val)"
	TestAllTypeAliasDatetimeValMINExpr    = "MIN(test_all_types_alias.datetime_val)"
	TestAllTypeAliasTimestampValMINExpr   = "MIN(test_all_types_alias.timestamp_val)"
	TestAllTypeAliasYearValMINExpr        = "MIN(test_all_types_alias.year_val)"
	TestAllTypeAliasNullableIntValMINExpr = "MIN(test_all_types_alias.nullable_int_val)"
	TestAllTypeAliasCreatedAtMINExpr      = "MIN(test_all_types_alias.created_at)"
	TestAllTypeAliasUpdatedAtMINExpr      = "MIN(test_all_types_alias.updated_at)"
	TestAllTypeAliasDeletedAtMINExpr      = "MIN(test_all_types_alias.deleted_at)"
)

const (
	TestAllTypeIDMAXExpr             = "MAX(id)"
	TestAllTypeTinyIntValMAXExpr     = "MAX(tiny_int_val)"
	TestAllTypeSmallIntValMAXExpr    = "MAX(small_int_val)"
	TestAllTypeMediumIntValMAXExpr   = "MAX(medium_int_val)"
	TestAllTypeIntValMAXExpr         = "MAX(int_val)"
	TestAllTypeBigIntValMAXExpr      = "MAX(big_int_val)"
	TestAllTypeDecimalValMAXExpr     = "MAX(decimal_val)"
	TestAllTypeFloatValMAXExpr       = "MAX(float_val)"
	TestAllTypeDoubleValMAXExpr      = "MAX(double_val)"
	TestAllTypeDateValMAXExpr        = "MAX(date_val)"
	TestAllTypeTimeValMAXExpr        = "MAX(time_val)"
	TestAllTypeDatetimeValMAXExpr    = "MAX(datetime_val)"
	TestAllTypeTimestampValMAXExpr   = "MAX(timestamp_val)"
	TestAllTypeYearValMAXExpr        = "MAX(year_val)"
	TestAllTypeNullableIntValMAXExpr = "MAX(nullable_int_val)"
	TestAllTypeCreatedAtMAXExpr      = "MAX(created_at)"
	TestAllTypeUpdatedAtMAXExpr      = "MAX(updated_at)"
	TestAllTypeDeletedAtMAXExpr      = "MAX(deleted_at)"
)

const (
	TestAllTypeAliasIDMAXExpr             = "MAX(test_all_types_alias.id)"
	TestAllTypeAliasTinyIntValMAXExpr     = "MAX(test_all_types_alias.tiny_int_val)"
	TestAllTypeAliasSmallIntValMAXExpr    = "MAX(test_all_types_alias.small_int_val)"
	TestAllTypeAliasMediumIntValMAXExpr   = "MAX(test_all_types_alias.medium_int_val)"
	TestAllTypeAliasIntValMAXExpr         = "MAX(test_all_types_alias.int_val)"
	TestAllTypeAliasBigIntValMAXExpr      = "MAX(test_all_types_alias.big_int_val)"
	TestAllTypeAliasDecimalValMAXExpr     = "MAX(test_all_types_alias.decimal_val)"
	TestAllTypeAliasFloatValMAXExpr       = "MAX(test_all_types_alias.float_val)"
	TestAllTypeAliasDoubleValMAXExpr      = "MAX(test_all_types_alias.double_val)"
	TestAllTypeAliasDateValMAXExpr        = "MAX(test_all_types_alias.date_val)"
	TestAllTypeAliasTimeValMAXExpr        = "MAX(test_all_types_alias.time_val)"
	TestAllTypeAliasDatetimeValMAXExpr    = "MAX(test_all_types_alias.datetime_val)"
	TestAllTypeAliasTimestampValMAXExpr   = "MAX(test_all_types_alias.timestamp_val)"
	TestAllTypeAliasYearValMAXExpr        = "MAX(test_all_types_alias.year_val)"
	TestAllTypeAliasNullableIntValMAXExpr = "MAX(test_all_types_alias.nullable_int_val)"
	TestAllTypeAliasCreatedAtMAXExpr      = "MAX(test_all_types_alias.created_at)"
	TestAllTypeAliasUpdatedAtMAXExpr      = "MAX(test_all_types_alias.updated_at)"
	TestAllTypeAliasDeletedAtMAXExpr      = "MAX(test_all_types_alias.deleted_at)"
)

const (
	TestAllTypeTinyIntValAddExpr     = "tiny_int_val = tiny_int_val + ?"
	TestAllTypeSmallIntValAddExpr    = "small_int_val = small_int_val + ?"
	TestAllTypeMediumIntValAddExpr   = "medium_int_val = medium_int_val + ?"
	TestAllTypeIntValAddExpr         = "int_val = int_val + ?"
	TestAllTypeBigIntValAddExpr      = "big_int_val = big_int_val + ?"
	TestAllTypeDecimalValAddExpr     = "decimal_val = decimal_val + ?"
	TestAllTypeFloatValAddExpr       = "float_val = float_val + ?"
	TestAllTypeDoubleValAddExpr      = "double_val = double_val + ?"
	TestAllTypeYearValAddExpr        = "year_val = year_val + ?"
	TestAllTypeNullableIntValAddExpr = "nullable_int_val = nullable_int_val + ?"
)

const (
	TestAllTypeAliasTinyIntValAddExpr     = "test_all_types_alias.tiny_int_val = test_all_types_alias.tiny_int_val + ?"
	TestAllTypeAliasSmallIntValAddExpr    = "test_all_types_alias.small_int_val = test_all_types_alias.small_int_val + ?"
	TestAllTypeAliasMediumIntValAddExpr   = "test_all_types_alias.medium_int_val = test_all_types_alias.medium_int_val + ?"
	TestAllTypeAliasIntValAddExpr         = "test_all_types_alias.int_val = test_all_types_alias.int_val + ?"
	TestAllTypeAliasBigIntValAddExpr      = "test_all_types_alias.big_int_val = test_all_types_alias.big_int_val + ?"
	TestAllTypeAliasDecimalValAddExpr     = "test_all_types_alias.decimal_val = test_all_types_alias.decimal_val + ?"
	TestAllTypeAliasFloatValAddExpr       = "test_all_types_alias.float_val = test_all_types_alias.float_val + ?"
	TestAllTypeAliasDoubleValAddExpr      = "test_all_types_alias.double_val = test_all_types_alias.double_val + ?"
	TestAllTypeAliasYearValAddExpr        = "test_all_types_alias.year_val = test_all_types_alias.year_val + ?"
	TestAllTypeAliasNullableIntValAddExpr = "test_all_types_alias.nullable_int_val = test_all_types_alias.nullable_int_val + ?"
)

const (
	TestAllTypeTinyIntValSubExpr     = "tiny_int_val = tiny_int_val - ?"
	TestAllTypeSmallIntValSubExpr    = "small_int_val = small_int_val - ?"
	TestAllTypeMediumIntValSubExpr   = "medium_int_val = medium_int_val - ?"
	TestAllTypeIntValSubExpr         = "int_val = int_val - ?"
	TestAllTypeBigIntValSubExpr      = "big_int_val = big_int_val - ?"
	TestAllTypeDecimalValSubExpr     = "decimal_val = decimal_val - ?"
	TestAllTypeFloatValSubExpr       = "float_val = float_val - ?"
	TestAllTypeDoubleValSubExpr      = "double_val = double_val - ?"
	TestAllTypeYearValSubExpr        = "year_val = year_val - ?"
	TestAllTypeNullableIntValSubExpr = "nullable_int_val = nullable_int_val - ?"
)

const (
	TestAllTypeAliasTinyIntValSubExpr     = "test_all_types_alias.tiny_int_val = test_all_types_alias.tiny_int_val - ?"
	TestAllTypeAliasSmallIntValSubExpr    = "test_all_types_alias.small_int_val = test_all_types_alias.small_int_val - ?"
	TestAllTypeAliasMediumIntValSubExpr   = "test_all_types_alias.medium_int_val = test_all_types_alias.medium_int_val - ?"
	TestAllTypeAliasIntValSubExpr         = "test_all_types_alias.int_val = test_all_types_alias.int_val - ?"
	TestAllTypeAliasBigIntValSubExpr      = "test_all_types_alias.big_int_val = test_all_types_alias.big_int_val - ?"
	TestAllTypeAliasDecimalValSubExpr     = "test_all_types_alias.decimal_val = test_all_types_alias.decimal_val - ?"
	TestAllTypeAliasFloatValSubExpr       = "test_all_types_alias.float_val = test_all_types_alias.float_val - ?"
	TestAllTypeAliasDoubleValSubExpr      = "test_all_types_alias.double_val = test_all_types_alias.double_val - ?"
	TestAllTypeAliasYearValSubExpr        = "test_all_types_alias.year_val = test_all_types_alias.year_val - ?"
	TestAllTypeAliasNullableIntValSubExpr = "test_all_types_alias.nullable_int_val = test_all_types_alias.nullable_int_val - ?"
)

const (
	TestAllTypeTinyIntValAddLeastExpr     = "tiny_int_val = LEAST(tiny_int_val + ?, ?)"
	TestAllTypeSmallIntValAddLeastExpr    = "small_int_val = LEAST(small_int_val + ?, ?)"
	TestAllTypeMediumIntValAddLeastExpr   = "medium_int_val = LEAST(medium_int_val + ?, ?)"
	TestAllTypeIntValAddLeastExpr         = "int_val = LEAST(int_val + ?, ?)"
	TestAllTypeBigIntValAddLeastExpr      = "big_int_val = LEAST(big_int_val + ?, ?)"
	TestAllTypeDecimalValAddLeastExpr     = "decimal_val = LEAST(decimal_val + ?, ?)"
	TestAllTypeFloatValAddLeastExpr       = "float_val = LEAST(float_val + ?, ?)"
	TestAllTypeDoubleValAddLeastExpr      = "double_val = LEAST(double_val + ?, ?)"
	TestAllTypeYearValAddLeastExpr        = "year_val = LEAST(year_val + ?, ?)"
	TestAllTypeNullableIntValAddLeastExpr = "nullable_int_val = LEAST(nullable_int_val + ?, ?)"
)

const (
	TestAllTypeAliasTinyIntValAddLeastExpr     = "test_all_types_alias.tiny_int_val = LEAST(test_all_types_alias.tiny_int_val + ?, ?)"
	TestAllTypeAliasSmallIntValAddLeastExpr    = "test_all_types_alias.small_int_val = LEAST(test_all_types_alias.small_int_val + ?, ?)"
	TestAllTypeAliasMediumIntValAddLeastExpr   = "test_all_types_alias.medium_int_val = LEAST(test_all_types_alias.medium_int_val + ?, ?)"
	TestAllTypeAliasIntValAddLeastExpr         = "test_all_types_alias.int_val = LEAST(test_all_types_alias.int_val + ?, ?)"
	TestAllTypeAliasBigIntValAddLeastExpr      = "test_all_types_alias.big_int_val = LEAST(test_all_types_alias.big_int_val + ?, ?)"
	TestAllTypeAliasDecimalValAddLeastExpr     = "test_all_types_alias.decimal_val = LEAST(test_all_types_alias.decimal_val + ?, ?)"
	TestAllTypeAliasFloatValAddLeastExpr       = "test_all_types_alias.float_val = LEAST(test_all_types_alias.float_val + ?, ?)"
	TestAllTypeAliasDoubleValAddLeastExpr      = "test_all_types_alias.double_val = LEAST(test_all_types_alias.double_val + ?, ?)"
	TestAllTypeAliasYearValAddLeastExpr        = "test_all_types_alias.year_val = LEAST(test_all_types_alias.year_val + ?, ?)"
	TestAllTypeAliasNullableIntValAddLeastExpr = "test_all_types_alias.nullable_int_val = LEAST(test_all_types_alias.nullable_int_val + ?, ?)"
)

const (
	TestAllTypeTinyIntValSubGreatestExpr     = "tiny_int_val = GREATEST(tiny_int_val - ?, ?)"
	TestAllTypeSmallIntValSubGreatestExpr    = "small_int_val = GREATEST(small_int_val - ?, ?)"
	TestAllTypeMediumIntValSubGreatestExpr   = "medium_int_val = GREATEST(medium_int_val - ?, ?)"
	TestAllTypeIntValSubGreatestExpr         = "int_val = GREATEST(int_val - ?, ?)"
	TestAllTypeBigIntValSubGreatestExpr      = "big_int_val = GREATEST(big_int_val - ?, ?)"
	TestAllTypeDecimalValSubGreatestExpr     = "decimal_val = GREATEST(decimal_val - ?, ?)"
	TestAllTypeFloatValSubGreatestExpr       = "float_val = GREATEST(float_val - ?, ?)"
	TestAllTypeDoubleValSubGreatestExpr      = "double_val = GREATEST(double_val - ?, ?)"
	TestAllTypeYearValSubGreatestExpr        = "year_val = GREATEST(year_val - ?, ?)"
	TestAllTypeNullableIntValSubGreatestExpr = "nullable_int_val = GREATEST(nullable_int_val - ?, ?)"
)

const (
	TestAllTypeAliasTinyIntValSubGreatestExpr     = "test_all_types_alias.tiny_int_val = GREATEST(test_all_types_alias.tiny_int_val - ?, ?)"
	TestAllTypeAliasSmallIntValSubGreatestExpr    = "test_all_types_alias.small_int_val = GREATEST(test_all_types_alias.small_int_val - ?, ?)"
	TestAllTypeAliasMediumIntValSubGreatestExpr   = "test_all_types_alias.medium_int_val = GREATEST(test_all_types_alias.medium_int_val - ?, ?)"
	TestAllTypeAliasIntValSubGreatestExpr         = "test_all_types_alias.int_val = GREATEST(test_all_types_alias.int_val - ?, ?)"
	TestAllTypeAliasBigIntValSubGreatestExpr      = "test_all_types_alias.big_int_val = GREATEST(test_all_types_alias.big_int_val - ?, ?)"
	TestAllTypeAliasDecimalValSubGreatestExpr     = "test_all_types_alias.decimal_val = GREATEST(test_all_types_alias.decimal_val - ?, ?)"
	TestAllTypeAliasFloatValSubGreatestExpr       = "test_all_types_alias.float_val = GREATEST(test_all_types_alias.float_val - ?, ?)"
	TestAllTypeAliasDoubleValSubGreatestExpr      = "test_all_types_alias.double_val = GREATEST(test_all_types_alias.double_val - ?, ?)"
	TestAllTypeAliasYearValSubGreatestExpr        = "test_all_types_alias.year_val = GREATEST(test_all_types_alias.year_val - ?, ?)"
	TestAllTypeAliasNullableIntValSubGreatestExpr = "test_all_types_alias.nullable_int_val = GREATEST(test_all_types_alias.nullable_int_val - ?, ?)"
)

const (
	TestAllTypeTinyIntValClampExpr     = "tiny_int_val = LEAST(GREATEST(tiny_int_val + ?, ?), ?)"
	TestAllTypeSmallIntValClampExpr    = "small_int_val = LEAST(GREATEST(small_int_val + ?, ?), ?)"
	TestAllTypeMediumIntValClampExpr   = "medium_int_val = LEAST(GREATEST(medium_int_val + ?, ?), ?)"
	TestAllTypeIntValClampExpr         = "int_val = LEAST(GREATEST(int_val + ?, ?), ?)"
	TestAllTypeBigIntValClampExpr      = "big_int_val = LEAST(GREATEST(big_int_val + ?, ?), ?)"
	TestAllTypeDecimalValClampExpr     = "decimal_val = LEAST(GREATEST(decimal_val + ?, ?), ?)"
	TestAllTypeFloatValClampExpr       = "float_val = LEAST(GREATEST(float_val + ?, ?), ?)"
	TestAllTypeDoubleValClampExpr      = "double_val = LEAST(GREATEST(double_val + ?, ?), ?)"
	TestAllTypeYearValClampExpr        = "year_val = LEAST(GREATEST(year_val + ?, ?), ?)"
	TestAllTypeNullableIntValClampExpr = "nullable_int_val = LEAST(GREATEST(nullable_int_val + ?, ?), ?)"
)

const (
	TestAllTypeAliasTinyIntValClampExpr     = "test_all_types_alias.tiny_int_val = LEAST(GREATEST(test_all_types_alias.tiny_int_val + ?, ?), ?)"
	TestAllTypeAliasSmallIntValClampExpr    = "test_all_types_alias.small_int_val = LEAST(GREATEST(test_all_types_alias.small_int_val + ?, ?), ?)"
	TestAllTypeAliasMediumIntValClampExpr   = "test_all_types_alias.medium_int_val = LEAST(GREATEST(test_all_types_alias.medium_int_val + ?, ?), ?)"
	TestAllTypeAliasIntValClampExpr         = "test_all_types_alias.int_val = LEAST(GREATEST(test_all_types_alias.int_val + ?, ?), ?)"
	TestAllTypeAliasBigIntValClampExpr      = "test_all_types_alias.big_int_val = LEAST(GREATEST(test_all_types_alias.big_int_val + ?, ?), ?)"
	TestAllTypeAliasDecimalValClampExpr     = "test_all_types_alias.decimal_val = LEAST(GREATEST(test_all_types_alias.decimal_val + ?, ?), ?)"
	TestAllTypeAliasFloatValClampExpr       = "test_all_types_alias.float_val = LEAST(GREATEST(test_all_types_alias.float_val + ?, ?), ?)"
	TestAllTypeAliasDoubleValClampExpr      = "test_all_types_alias.double_val = LEAST(GREATEST(test_all_types_alias.double_val + ?, ?), ?)"
	TestAllTypeAliasYearValClampExpr        = "test_all_types_alias.year_val = LEAST(GREATEST(test_all_types_alias.year_val + ?, ?), ?)"
	TestAllTypeAliasNullableIntValClampExpr = "test_all_types_alias.nullable_int_val = LEAST(GREATEST(test_all_types_alias.nullable_int_val + ?, ?), ?)"
)

const (
	TestAllTypeIDIn             = "id IN (?)"
	TestAllTypeTinyIntValIn     = "tiny_int_val IN (?)"
	TestAllTypeSmallIntValIn    = "small_int_val IN (?)"
	TestAllTypeMediumIntValIn   = "medium_int_val IN (?)"
	TestAllTypeIntValIn         = "int_val IN (?)"
	TestAllTypeBigIntValIn      = "big_int_val IN (?)"
	TestAllTypeDecimalValIn     = "decimal_val IN (?)"
	TestAllTypeFloatValIn       = "float_val IN (?)"
	TestAllTypeDoubleValIn      = "double_val IN (?)"
	TestAllTypeCharValIn        = "char_val IN (?)"
	TestAllTypeVarcharValIn     = "varchar_val IN (?)"
	TestAllTypeTextValIn        = "text_val IN (?)"
	TestAllTypeMediumtextValIn  = "mediumtext_val IN (?)"
	TestAllTypeLongtextValIn    = "longtext_val IN (?)"
	TestAllTypeDateValIn        = "date_val IN (?)"
	TestAllTypeTimeValIn        = "time_val IN (?)"
	TestAllTypeDatetimeValIn    = "datetime_val IN (?)"
	TestAllTypeTimestampValIn   = "timestamp_val IN (?)"
	TestAllTypeYearValIn        = "year_val IN (?)"
	TestAllTypeBoolValIn        = "bool_val IN (?)"
	TestAllTypeEnumValIn        = "enum_val IN (?)"
	TestAllTypeSetValIn         = "set_val IN (?)"
	TestAllTypeNullableIntValIn = "nullable_int_val IN (?)"
	TestAllTypeIgnoreValIn      = "ignore_val IN (?)"
	TestAllTypeCreatedAtIn      = "created_at IN (?)"
	TestAllTypeUpdatedAtIn      = "updated_at IN (?)"
	TestAllTypeDeletedAtIn      = "deleted_at IN (?)"
)

const (
	TestAllTypeAliasIDIn             = "test_all_types_alias.id IN (?)"
	TestAllTypeAliasTinyIntValIn     = "test_all_types_alias.tiny_int_val IN (?)"
	TestAllTypeAliasSmallIntValIn    = "test_all_types_alias.small_int_val IN (?)"
	TestAllTypeAliasMediumIntValIn   = "test_all_types_alias.medium_int_val IN (?)"
	TestAllTypeAliasIntValIn         = "test_all_types_alias.int_val IN (?)"
	TestAllTypeAliasBigIntValIn      = "test_all_types_alias.big_int_val IN (?)"
	TestAllTypeAliasDecimalValIn     = "test_all_types_alias.decimal_val IN (?)"
	TestAllTypeAliasFloatValIn       = "test_all_types_alias.float_val IN (?)"
	TestAllTypeAliasDoubleValIn      = "test_all_types_alias.double_val IN (?)"
	TestAllTypeAliasCharValIn        = "test_all_types_alias.char_val IN (?)"
	TestAllTypeAliasVarcharValIn     = "test_all_types_alias.varchar_val IN (?)"
	TestAllTypeAliasTextValIn        = "test_all_types_alias.text_val IN (?)"
	TestAllTypeAliasMediumtextValIn  = "test_all_types_alias.mediumtext_val IN (?)"
	TestAllTypeAliasLongtextValIn    = "test_all_types_alias.longtext_val IN (?)"
	TestAllTypeAliasDateValIn        = "test_all_types_alias.date_val IN (?)"
	TestAllTypeAliasTimeValIn        = "test_all_types_alias.time_val IN (?)"
	TestAllTypeAliasDatetimeValIn    = "test_all_types_alias.datetime_val IN (?)"
	TestAllTypeAliasTimestampValIn   = "test_all_types_alias.timestamp_val IN (?)"
	TestAllTypeAliasYearValIn        = "test_all_types_alias.year_val IN (?)"
	TestAllTypeAliasBoolValIn        = "test_all_types_alias.bool_val IN (?)"
	TestAllTypeAliasEnumValIn        = "test_all_types_alias.enum_val IN (?)"
	TestAllTypeAliasSetValIn         = "test_all_types_alias.set_val IN (?)"
	TestAllTypeAliasNullableIntValIn = "test_all_types_alias.nullable_int_val IN (?)"
	TestAllTypeAliasIgnoreValIn      = "test_all_types_alias.ignore_val IN (?)"
	TestAllTypeAliasCreatedAtIn      = "test_all_types_alias.created_at IN (?)"
	TestAllTypeAliasUpdatedAtIn      = "test_all_types_alias.updated_at IN (?)"
	TestAllTypeAliasDeletedAtIn      = "test_all_types_alias.deleted_at IN (?)"
)

const (
	TestAllTypeIDNotIn             = "id NOT IN (?)"
	TestAllTypeTinyIntValNotIn     = "tiny_int_val NOT IN (?)"
	TestAllTypeSmallIntValNotIn    = "small_int_val NOT IN (?)"
	TestAllTypeMediumIntValNotIn   = "medium_int_val NOT IN (?)"
	TestAllTypeIntValNotIn         = "int_val NOT IN (?)"
	TestAllTypeBigIntValNotIn      = "big_int_val NOT IN (?)"
	TestAllTypeDecimalValNotIn     = "decimal_val NOT IN (?)"
	TestAllTypeFloatValNotIn       = "float_val NOT IN (?)"
	TestAllTypeDoubleValNotIn      = "double_val NOT IN (?)"
	TestAllTypeCharValNotIn        = "char_val NOT IN (?)"
	TestAllTypeVarcharValNotIn     = "varchar_val NOT IN (?)"
	TestAllTypeTextValNotIn        = "text_val NOT IN (?)"
	TestAllTypeMediumtextValNotIn  = "mediumtext_val NOT IN (?)"
	TestAllTypeLongtextValNotIn    = "longtext_val NOT IN (?)"
	TestAllTypeDateValNotIn        = "date_val NOT IN (?)"
	TestAllTypeTimeValNotIn        = "time_val NOT IN (?)"
	TestAllTypeDatetimeValNotIn    = "datetime_val NOT IN (?)"
	TestAllTypeTimestampValNotIn   = "timestamp_val NOT IN (?)"
	TestAllTypeYearValNotIn        = "year_val NOT IN (?)"
	TestAllTypeBoolValNotIn        = "bool_val NOT IN (?)"
	TestAllTypeEnumValNotIn        = "enum_val NOT IN (?)"
	TestAllTypeSetValNotIn         = "set_val NOT IN (?)"
	TestAllTypeNullableIntValNotIn = "nullable_int_val NOT IN (?)"
	TestAllTypeIgnoreValNotIn      = "ignore_val NOT IN (?)"
	TestAllTypeCreatedAtNotIn      = "created_at NOT IN (?)"
	TestAllTypeUpdatedAtNotIn      = "updated_at NOT IN (?)"
	TestAllTypeDeletedAtNotIn      = "deleted_at NOT IN (?)"
)

const (
	TestAllTypeAliasIDNotIn             = "test_all_types_alias.id NOT IN (?)"
	TestAllTypeAliasTinyIntValNotIn     = "test_all_types_alias.tiny_int_val NOT IN (?)"
	TestAllTypeAliasSmallIntValNotIn    = "test_all_types_alias.small_int_val NOT IN (?)"
	TestAllTypeAliasMediumIntValNotIn   = "test_all_types_alias.medium_int_val NOT IN (?)"
	TestAllTypeAliasIntValNotIn         = "test_all_types_alias.int_val NOT IN (?)"
	TestAllTypeAliasBigIntValNotIn      = "test_all_types_alias.big_int_val NOT IN (?)"
	TestAllTypeAliasDecimalValNotIn     = "test_all_types_alias.decimal_val NOT IN (?)"
	TestAllTypeAliasFloatValNotIn       = "test_all_types_alias.float_val NOT IN (?)"
	TestAllTypeAliasDoubleValNotIn      = "test_all_types_alias.double_val NOT IN (?)"
	TestAllTypeAliasCharValNotIn        = "test_all_types_alias.char_val NOT IN (?)"
	TestAllTypeAliasVarcharValNotIn     = "test_all_types_alias.varchar_val NOT IN (?)"
	TestAllTypeAliasTextValNotIn        = "test_all_types_alias.text_val NOT IN (?)"
	TestAllTypeAliasMediumtextValNotIn  = "test_all_types_alias.mediumtext_val NOT IN (?)"
	TestAllTypeAliasLongtextValNotIn    = "test_all_types_alias.longtext_val NOT IN (?)"
	TestAllTypeAliasDateValNotIn        = "test_all_types_alias.date_val NOT IN (?)"
	TestAllTypeAliasTimeValNotIn        = "test_all_types_alias.time_val NOT IN (?)"
	TestAllTypeAliasDatetimeValNotIn    = "test_all_types_alias.datetime_val NOT IN (?)"
	TestAllTypeAliasTimestampValNotIn   = "test_all_types_alias.timestamp_val NOT IN (?)"
	TestAllTypeAliasYearValNotIn        = "test_all_types_alias.year_val NOT IN (?)"
	TestAllTypeAliasBoolValNotIn        = "test_all_types_alias.bool_val NOT IN (?)"
	TestAllTypeAliasEnumValNotIn        = "test_all_types_alias.enum_val NOT IN (?)"
	TestAllTypeAliasSetValNotIn         = "test_all_types_alias.set_val NOT IN (?)"
	TestAllTypeAliasNullableIntValNotIn = "test_all_types_alias.nullable_int_val NOT IN (?)"
	TestAllTypeAliasIgnoreValNotIn      = "test_all_types_alias.ignore_val NOT IN (?)"
	TestAllTypeAliasCreatedAtNotIn      = "test_all_types_alias.created_at NOT IN (?)"
	TestAllTypeAliasUpdatedAtNotIn      = "test_all_types_alias.updated_at NOT IN (?)"
	TestAllTypeAliasDeletedAtNotIn      = "test_all_types_alias.deleted_at NOT IN (?)"
)

const (
	TestAllTypeTinyIntValIsNull     = "tiny_int_val IS NULL"
	TestAllTypeMediumIntValIsNull   = "medium_int_val IS NULL"
	TestAllTypeBigIntValIsNull      = "big_int_val IS NULL"
	TestAllTypeDecimalValIsNull     = "decimal_val IS NULL"
	TestAllTypeFloatValIsNull       = "float_val IS NULL"
	TestAllTypeDoubleValIsNull      = "double_val IS NULL"
	TestAllTypeCharValIsNull        = "char_val IS NULL"
	TestAllTypeVarcharValIsNull     = "varchar_val IS NULL"
	TestAllTypeTextValIsNull        = "text_val IS NULL"
	TestAllTypeMediumtextValIsNull  = "mediumtext_val IS NULL"
	TestAllTypeLongtextValIsNull    = "longtext_val IS NULL"
	TestAllTypeDateValIsNull        = "date_val IS NULL"
	TestAllTypeTimeValIsNull        = "time_val IS NULL"
	TestAllTypeDatetimeValIsNull    = "datetime_val IS NULL"
	TestAllTypeTimestampValIsNull   = "timestamp_val IS NULL"
	TestAllTypeYearValIsNull        = "year_val IS NULL"
	TestAllTypeBoolValIsNull        = "bool_val IS NULL"
	TestAllTypeEnumValIsNull        = "enum_val IS NULL"
	TestAllTypeSetValIsNull         = "set_val IS NULL"
	TestAllTypeBinaryValIsNull      = "binary_val IS NULL"
	TestAllTypeVarbinaryValIsNull   = "varbinary_val IS NULL"
	TestAllTypeBlobValIsNull        = "blob_val IS NULL"
	TestAllTypeMediumblobValIsNull  = "mediumblob_val IS NULL"
	TestAllTypeLongblobValIsNull    = "longblob_val IS NULL"
	TestAllTypeJsonValIsNull        = "json_val IS NULL"
	TestAllTypeBitValIsNull         = "bit_val IS NULL"
	TestAllTypeNullableIntValIsNull = "nullable_int_val IS NULL"
	TestAllTypeIgnoreValIsNull      = "ignore_val IS NULL"
	TestAllTypeDeletedAtIsNull      = "deleted_at IS NULL"
)

const (
	TestAllTypeAliasTinyIntValIsNull     = "test_all_types_alias.tiny_int_val IS NULL"
	TestAllTypeAliasMediumIntValIsNull   = "test_all_types_alias.medium_int_val IS NULL"
	TestAllTypeAliasBigIntValIsNull      = "test_all_types_alias.big_int_val IS NULL"
	TestAllTypeAliasDecimalValIsNull     = "test_all_types_alias.decimal_val IS NULL"
	TestAllTypeAliasFloatValIsNull       = "test_all_types_alias.float_val IS NULL"
	TestAllTypeAliasDoubleValIsNull      = "test_all_types_alias.double_val IS NULL"
	TestAllTypeAliasCharValIsNull        = "test_all_types_alias.char_val IS NULL"
	TestAllTypeAliasVarcharValIsNull     = "test_all_types_alias.varchar_val IS NULL"
	TestAllTypeAliasTextValIsNull        = "test_all_types_alias.text_val IS NULL"
	TestAllTypeAliasMediumtextValIsNull  = "test_all_types_alias.mediumtext_val IS NULL"
	TestAllTypeAliasLongtextValIsNull    = "test_all_types_alias.longtext_val IS NULL"
	TestAllTypeAliasDateValIsNull        = "test_all_types_alias.date_val IS NULL"
	TestAllTypeAliasTimeValIsNull        = "test_all_types_alias.time_val IS NULL"
	TestAllTypeAliasDatetimeValIsNull    = "test_all_types_alias.datetime_val IS NULL"
	TestAllTypeAliasTimestampValIsNull   = "test_all_types_alias.timestamp_val IS NULL"
	TestAllTypeAliasYearValIsNull        = "test_all_types_alias.year_val IS NULL"
	TestAllTypeAliasBoolValIsNull        = "test_all_types_alias.bool_val IS NULL"
	TestAllTypeAliasEnumValIsNull        = "test_all_types_alias.enum_val IS NULL"
	TestAllTypeAliasSetValIsNull         = "test_all_types_alias.set_val IS NULL"
	TestAllTypeAliasBinaryValIsNull      = "test_all_types_alias.binary_val IS NULL"
	TestAllTypeAliasVarbinaryValIsNull   = "test_all_types_alias.varbinary_val IS NULL"
	TestAllTypeAliasBlobValIsNull        = "test_all_types_alias.blob_val IS NULL"
	TestAllTypeAliasMediumblobValIsNull  = "test_all_types_alias.mediumblob_val IS NULL"
	TestAllTypeAliasLongblobValIsNull    = "test_all_types_alias.longblob_val IS NULL"
	TestAllTypeAliasJsonValIsNull        = "test_all_types_alias.json_val IS NULL"
	TestAllTypeAliasBitValIsNull         = "test_all_types_alias.bit_val IS NULL"
	TestAllTypeAliasNullableIntValIsNull = "test_all_types_alias.nullable_int_val IS NULL"
	TestAllTypeAliasIgnoreValIsNull      = "test_all_types_alias.ignore_val IS NULL"
	TestAllTypeAliasDeletedAtIsNull      = "test_all_types_alias.deleted_at IS NULL"
)

const (
	TestAllTypeTinyIntValIsNotNull     = "tiny_int_val IS NOT NULL"
	TestAllTypeMediumIntValIsNotNull   = "medium_int_val IS NOT NULL"
	TestAllTypeBigIntValIsNotNull      = "big_int_val IS NOT NULL"
	TestAllTypeDecimalValIsNotNull     = "decimal_val IS NOT NULL"
	TestAllTypeFloatValIsNotNull       = "float_val IS NOT NULL"
	TestAllTypeDoubleValIsNotNull      = "double_val IS NOT NULL"
	TestAllTypeCharValIsNotNull        = "char_val IS NOT NULL"
	TestAllTypeVarcharValIsNotNull     = "varchar_val IS NOT NULL"
	TestAllTypeTextValIsNotNull        = "text_val IS NOT NULL"
	TestAllTypeMediumtextValIsNotNull  = "mediumtext_val IS NOT NULL"
	TestAllTypeLongtextValIsNotNull    = "longtext_val IS NOT NULL"
	TestAllTypeDateValIsNotNull        = "date_val IS NOT NULL"
	TestAllTypeTimeValIsNotNull        = "time_val IS NOT NULL"
	TestAllTypeDatetimeValIsNotNull    = "datetime_val IS NOT NULL"
	TestAllTypeTimestampValIsNotNull   = "timestamp_val IS NOT NULL"
	TestAllTypeYearValIsNotNull        = "year_val IS NOT NULL"
	TestAllTypeBoolValIsNotNull        = "bool_val IS NOT NULL"
	TestAllTypeEnumValIsNotNull        = "enum_val IS NOT NULL"
	TestAllTypeSetValIsNotNull         = "set_val IS NOT NULL"
	TestAllTypeBinaryValIsNotNull      = "binary_val IS NOT NULL"
	TestAllTypeVarbinaryValIsNotNull   = "varbinary_val IS NOT NULL"
	TestAllTypeBlobValIsNotNull        = "blob_val IS NOT NULL"
	TestAllTypeMediumblobValIsNotNull  = "mediumblob_val IS NOT NULL"
	TestAllTypeLongblobValIsNotNull    = "longblob_val IS NOT NULL"
	TestAllTypeJsonValIsNotNull        = "json_val IS NOT NULL"
	TestAllTypeBitValIsNotNull         = "bit_val IS NOT NULL"
	TestAllTypeNullableIntValIsNotNull = "nullable_int_val IS NOT NULL"
	TestAllTypeIgnoreValIsNotNull      = "ignore_val IS NOT NULL"
	TestAllTypeDeletedAtIsNotNull      = "deleted_at IS NOT NULL"
)

const (
	TestAllTypeAliasTinyIntValIsNotNull     = "test_all_types_alias.tiny_int_val IS NOT NULL"
	TestAllTypeAliasMediumIntValIsNotNull   = "test_all_types_alias.medium_int_val IS NOT NULL"
	TestAllTypeAliasBigIntValIsNotNull      = "test_all_types_alias.big_int_val IS NOT NULL"
	TestAllTypeAliasDecimalValIsNotNull     = "test_all_types_alias.decimal_val IS NOT NULL"
	TestAllTypeAliasFloatValIsNotNull       = "test_all_types_alias.float_val IS NOT NULL"
	TestAllTypeAliasDoubleValIsNotNull      = "test_all_types_alias.double_val IS NOT NULL"
	TestAllTypeAliasCharValIsNotNull        = "test_all_types_alias.char_val IS NOT NULL"
	TestAllTypeAliasVarcharValIsNotNull     = "test_all_types_alias.varchar_val IS NOT NULL"
	TestAllTypeAliasTextValIsNotNull        = "test_all_types_alias.text_val IS NOT NULL"
	TestAllTypeAliasMediumtextValIsNotNull  = "test_all_types_alias.mediumtext_val IS NOT NULL"
	TestAllTypeAliasLongtextValIsNotNull    = "test_all_types_alias.longtext_val IS NOT NULL"
	TestAllTypeAliasDateValIsNotNull        = "test_all_types_alias.date_val IS NOT NULL"
	TestAllTypeAliasTimeValIsNotNull        = "test_all_types_alias.time_val IS NOT NULL"
	TestAllTypeAliasDatetimeValIsNotNull    = "test_all_types_alias.datetime_val IS NOT NULL"
	TestAllTypeAliasTimestampValIsNotNull   = "test_all_types_alias.timestamp_val IS NOT NULL"
	TestAllTypeAliasYearValIsNotNull        = "test_all_types_alias.year_val IS NOT NULL"
	TestAllTypeAliasBoolValIsNotNull        = "test_all_types_alias.bool_val IS NOT NULL"
	TestAllTypeAliasEnumValIsNotNull        = "test_all_types_alias.enum_val IS NOT NULL"
	TestAllTypeAliasSetValIsNotNull         = "test_all_types_alias.set_val IS NOT NULL"
	TestAllTypeAliasBinaryValIsNotNull      = "test_all_types_alias.binary_val IS NOT NULL"
	TestAllTypeAliasVarbinaryValIsNotNull   = "test_all_types_alias.varbinary_val IS NOT NULL"
	TestAllTypeAliasBlobValIsNotNull        = "test_all_types_alias.blob_val IS NOT NULL"
	TestAllTypeAliasMediumblobValIsNotNull  = "test_all_types_alias.mediumblob_val IS NOT NULL"
	TestAllTypeAliasLongblobValIsNotNull    = "test_all_types_alias.longblob_val IS NOT NULL"
	TestAllTypeAliasJsonValIsNotNull        = "test_all_types_alias.json_val IS NOT NULL"
	TestAllTypeAliasBitValIsNotNull         = "test_all_types_alias.bit_val IS NOT NULL"
	TestAllTypeAliasNullableIntValIsNotNull = "test_all_types_alias.nullable_int_val IS NOT NULL"
	TestAllTypeAliasIgnoreValIsNotNull      = "test_all_types_alias.ignore_val IS NOT NULL"
	TestAllTypeAliasDeletedAtIsNotNull      = "test_all_types_alias.deleted_at IS NOT NULL"
)

// COALESCE expressions (COALESCE(column, ?))
const (
	TestAllTypeTinyIntValCoalesceExpr     = "COALESCE(tiny_int_val, ?)"
	TestAllTypeMediumIntValCoalesceExpr   = "COALESCE(medium_int_val, ?)"
	TestAllTypeBigIntValCoalesceExpr      = "COALESCE(big_int_val, ?)"
	TestAllTypeDecimalValCoalesceExpr     = "COALESCE(decimal_val, ?)"
	TestAllTypeFloatValCoalesceExpr       = "COALESCE(float_val, ?)"
	TestAllTypeDoubleValCoalesceExpr      = "COALESCE(double_val, ?)"
	TestAllTypeCharValCoalesceExpr        = "COALESCE(char_val, ?)"
	TestAllTypeVarcharValCoalesceExpr     = "COALESCE(varchar_val, ?)"
	TestAllTypeTextValCoalesceExpr        = "COALESCE(text_val, ?)"
	TestAllTypeMediumtextValCoalesceExpr  = "COALESCE(mediumtext_val, ?)"
	TestAllTypeLongtextValCoalesceExpr    = "COALESCE(longtext_val, ?)"
	TestAllTypeDateValCoalesceExpr        = "COALESCE(date_val, ?)"
	TestAllTypeTimeValCoalesceExpr        = "COALESCE(time_val, ?)"
	TestAllTypeDatetimeValCoalesceExpr    = "COALESCE(datetime_val, ?)"
	TestAllTypeTimestampValCoalesceExpr   = "COALESCE(timestamp_val, ?)"
	TestAllTypeYearValCoalesceExpr        = "COALESCE(year_val, ?)"
	TestAllTypeBoolValCoalesceExpr        = "COALESCE(bool_val, ?)"
	TestAllTypeEnumValCoalesceExpr        = "COALESCE(enum_val, ?)"
	TestAllTypeSetValCoalesceExpr         = "COALESCE(set_val, ?)"
	TestAllTypeBinaryValCoalesceExpr      = "COALESCE(binary_val, ?)"
	TestAllTypeVarbinaryValCoalesceExpr   = "COALESCE(varbinary_val, ?)"
	TestAllTypeBlobValCoalesceExpr        = "COALESCE(blob_val, ?)"
	TestAllTypeMediumblobValCoalesceExpr  = "COALESCE(mediumblob_val, ?)"
	TestAllTypeLongblobValCoalesceExpr    = "COALESCE(longblob_val, ?)"
	TestAllTypeJsonValCoalesceExpr        = "COALESCE(json_val, ?)"
	TestAllTypeBitValCoalesceExpr         = "COALESCE(bit_val, ?)"
	TestAllTypeNullableIntValCoalesceExpr = "COALESCE(nullable_int_val, ?)"
	TestAllTypeIgnoreValCoalesceExpr      = "COALESCE(ignore_val, ?)"
	TestAllTypeDeletedAtCoalesceExpr      = "COALESCE(deleted_at, ?)"
)

const (
	TestAllTypeAliasTinyIntValCoalesceExpr     = "COALESCE(test_all_types_alias.tiny_int_val, ?)"
	TestAllTypeAliasMediumIntValCoalesceExpr   = "COALESCE(test_all_types_alias.medium_int_val, ?)"
	TestAllTypeAliasBigIntValCoalesceExpr      = "COALESCE(test_all_types_alias.big_int_val, ?)"
	TestAllTypeAliasDecimalValCoalesceExpr     = "COALESCE(test_all_types_alias.decimal_val, ?)"
	TestAllTypeAliasFloatValCoalesceExpr       = "COALESCE(test_all_types_alias.float_val, ?)"
	TestAllTypeAliasDoubleValCoalesceExpr      = "COALESCE(test_all_types_alias.double_val, ?)"
	TestAllTypeAliasCharValCoalesceExpr        = "COALESCE(test_all_types_alias.char_val, ?)"
	TestAllTypeAliasVarcharValCoalesceExpr     = "COALESCE(test_all_types_alias.varchar_val, ?)"
	TestAllTypeAliasTextValCoalesceExpr        = "COALESCE(test_all_types_alias.text_val, ?)"
	TestAllTypeAliasMediumtextValCoalesceExpr  = "COALESCE(test_all_types_alias.mediumtext_val, ?)"
	TestAllTypeAliasLongtextValCoalesceExpr    = "COALESCE(test_all_types_alias.longtext_val, ?)"
	TestAllTypeAliasDateValCoalesceExpr        = "COALESCE(test_all_types_alias.date_val, ?)"
	TestAllTypeAliasTimeValCoalesceExpr        = "COALESCE(test_all_types_alias.time_val, ?)"
	TestAllTypeAliasDatetimeValCoalesceExpr    = "COALESCE(test_all_types_alias.datetime_val, ?)"
	TestAllTypeAliasTimestampValCoalesceExpr   = "COALESCE(test_all_types_alias.timestamp_val, ?)"
	TestAllTypeAliasYearValCoalesceExpr        = "COALESCE(test_all_types_alias.year_val, ?)"
	TestAllTypeAliasBoolValCoalesceExpr        = "COALESCE(test_all_types_alias.bool_val, ?)"
	TestAllTypeAliasEnumValCoalesceExpr        = "COALESCE(test_all_types_alias.enum_val, ?)"
	TestAllTypeAliasSetValCoalesceExpr         = "COALESCE(test_all_types_alias.set_val, ?)"
	TestAllTypeAliasBinaryValCoalesceExpr      = "COALESCE(test_all_types_alias.binary_val, ?)"
	TestAllTypeAliasVarbinaryValCoalesceExpr   = "COALESCE(test_all_types_alias.varbinary_val, ?)"
	TestAllTypeAliasBlobValCoalesceExpr        = "COALESCE(test_all_types_alias.blob_val, ?)"
	TestAllTypeAliasMediumblobValCoalesceExpr  = "COALESCE(test_all_types_alias.mediumblob_val, ?)"
	TestAllTypeAliasLongblobValCoalesceExpr    = "COALESCE(test_all_types_alias.longblob_val, ?)"
	TestAllTypeAliasJsonValCoalesceExpr        = "COALESCE(test_all_types_alias.json_val, ?)"
	TestAllTypeAliasBitValCoalesceExpr         = "COALESCE(test_all_types_alias.bit_val, ?)"
	TestAllTypeAliasNullableIntValCoalesceExpr = "COALESCE(test_all_types_alias.nullable_int_val, ?)"
	TestAllTypeAliasIgnoreValCoalesceExpr      = "COALESCE(test_all_types_alias.ignore_val, ?)"
	TestAllTypeAliasDeletedAtCoalesceExpr      = "COALESCE(test_all_types_alias.deleted_at, ?)"
)

const (
	TestAllTypeIDBetween             = "id BETWEEN ? AND ?"
	TestAllTypeTinyIntValBetween     = "tiny_int_val BETWEEN ? AND ?"
	TestAllTypeSmallIntValBetween    = "small_int_val BETWEEN ? AND ?"
	TestAllTypeMediumIntValBetween   = "medium_int_val BETWEEN ? AND ?"
	TestAllTypeIntValBetween         = "int_val BETWEEN ? AND ?"
	TestAllTypeBigIntValBetween      = "big_int_val BETWEEN ? AND ?"
	TestAllTypeDecimalValBetween     = "decimal_val BETWEEN ? AND ?"
	TestAllTypeFloatValBetween       = "float_val BETWEEN ? AND ?"
	TestAllTypeDoubleValBetween      = "double_val BETWEEN ? AND ?"
	TestAllTypeDateValBetween        = "date_val BETWEEN ? AND ?"
	TestAllTypeTimeValBetween        = "time_val BETWEEN ? AND ?"
	TestAllTypeDatetimeValBetween    = "datetime_val BETWEEN ? AND ?"
	TestAllTypeTimestampValBetween   = "timestamp_val BETWEEN ? AND ?"
	TestAllTypeYearValBetween        = "year_val BETWEEN ? AND ?"
	TestAllTypeNullableIntValBetween = "nullable_int_val BETWEEN ? AND ?"
	TestAllTypeCreatedAtBetween      = "created_at BETWEEN ? AND ?"
	TestAllTypeUpdatedAtBetween      = "updated_at BETWEEN ? AND ?"
	TestAllTypeDeletedAtBetween      = "deleted_at BETWEEN ? AND ?"
)

const (
	TestAllTypeAliasIDBetween             = "test_all_types_alias.id BETWEEN ? AND ?"
	TestAllTypeAliasTinyIntValBetween     = "test_all_types_alias.tiny_int_val BETWEEN ? AND ?"
	TestAllTypeAliasSmallIntValBetween    = "test_all_types_alias.small_int_val BETWEEN ? AND ?"
	TestAllTypeAliasMediumIntValBetween   = "test_all_types_alias.medium_int_val BETWEEN ? AND ?"
	TestAllTypeAliasIntValBetween         = "test_all_types_alias.int_val BETWEEN ? AND ?"
	TestAllTypeAliasBigIntValBetween      = "test_all_types_alias.big_int_val BETWEEN ? AND ?"
	TestAllTypeAliasDecimalValBetween     = "test_all_types_alias.decimal_val BETWEEN ? AND ?"
	TestAllTypeAliasFloatValBetween       = "test_all_types_alias.float_val BETWEEN ? AND ?"
	TestAllTypeAliasDoubleValBetween      = "test_all_types_alias.double_val BETWEEN ? AND ?"
	TestAllTypeAliasDateValBetween        = "test_all_types_alias.date_val BETWEEN ? AND ?"
	TestAllTypeAliasTimeValBetween        = "test_all_types_alias.time_val BETWEEN ? AND ?"
	TestAllTypeAliasDatetimeValBetween    = "test_all_types_alias.datetime_val BETWEEN ? AND ?"
	TestAllTypeAliasTimestampValBetween   = "test_all_types_alias.timestamp_val BETWEEN ? AND ?"
	TestAllTypeAliasYearValBetween        = "test_all_types_alias.year_val BETWEEN ? AND ?"
	TestAllTypeAliasNullableIntValBetween = "test_all_types_alias.nullable_int_val BETWEEN ? AND ?"
	TestAllTypeAliasCreatedAtBetween      = "test_all_types_alias.created_at BETWEEN ? AND ?"
	TestAllTypeAliasUpdatedAtBetween      = "test_all_types_alias.updated_at BETWEEN ? AND ?"
	TestAllTypeAliasDeletedAtBetween      = "test_all_types_alias.deleted_at BETWEEN ? AND ?"
)

const (
	TestAllTypeIDNotBetween             = "id NOT BETWEEN ? AND ?"
	TestAllTypeTinyIntValNotBetween     = "tiny_int_val NOT BETWEEN ? AND ?"
	TestAllTypeSmallIntValNotBetween    = "small_int_val NOT BETWEEN ? AND ?"
	TestAllTypeMediumIntValNotBetween   = "medium_int_val NOT BETWEEN ? AND ?"
	TestAllTypeIntValNotBetween         = "int_val NOT BETWEEN ? AND ?"
	TestAllTypeBigIntValNotBetween      = "big_int_val NOT BETWEEN ? AND ?"
	TestAllTypeDecimalValNotBetween     = "decimal_val NOT BETWEEN ? AND ?"
	TestAllTypeFloatValNotBetween       = "float_val NOT BETWEEN ? AND ?"
	TestAllTypeDoubleValNotBetween      = "double_val NOT BETWEEN ? AND ?"
	TestAllTypeDateValNotBetween        = "date_val NOT BETWEEN ? AND ?"
	TestAllTypeTimeValNotBetween        = "time_val NOT BETWEEN ? AND ?"
	TestAllTypeDatetimeValNotBetween    = "datetime_val NOT BETWEEN ? AND ?"
	TestAllTypeTimestampValNotBetween   = "timestamp_val NOT BETWEEN ? AND ?"
	TestAllTypeYearValNotBetween        = "year_val NOT BETWEEN ? AND ?"
	TestAllTypeNullableIntValNotBetween = "nullable_int_val NOT BETWEEN ? AND ?"
	TestAllTypeCreatedAtNotBetween      = "created_at NOT BETWEEN ? AND ?"
	TestAllTypeUpdatedAtNotBetween      = "updated_at NOT BETWEEN ? AND ?"
	TestAllTypeDeletedAtNotBetween      = "deleted_at NOT BETWEEN ? AND ?"
)

const (
	TestAllTypeAliasIDNotBetween             = "test_all_types_alias.id NOT BETWEEN ? AND ?"
	TestAllTypeAliasTinyIntValNotBetween     = "test_all_types_alias.tiny_int_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasSmallIntValNotBetween    = "test_all_types_alias.small_int_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasMediumIntValNotBetween   = "test_all_types_alias.medium_int_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasIntValNotBetween         = "test_all_types_alias.int_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasBigIntValNotBetween      = "test_all_types_alias.big_int_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasDecimalValNotBetween     = "test_all_types_alias.decimal_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasFloatValNotBetween       = "test_all_types_alias.float_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasDoubleValNotBetween      = "test_all_types_alias.double_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasDateValNotBetween        = "test_all_types_alias.date_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasTimeValNotBetween        = "test_all_types_alias.time_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasDatetimeValNotBetween    = "test_all_types_alias.datetime_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasTimestampValNotBetween   = "test_all_types_alias.timestamp_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasYearValNotBetween        = "test_all_types_alias.year_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasNullableIntValNotBetween = "test_all_types_alias.nullable_int_val NOT BETWEEN ? AND ?"
	TestAllTypeAliasCreatedAtNotBetween      = "test_all_types_alias.created_at NOT BETWEEN ? AND ?"
	TestAllTypeAliasUpdatedAtNotBetween      = "test_all_types_alias.updated_at NOT BETWEEN ? AND ?"
	TestAllTypeAliasDeletedAtNotBetween      = "test_all_types_alias.deleted_at NOT BETWEEN ? AND ?"
)

const (
	TestAllTypeDateValDateExpr      = "DATE(date_val)"
	TestAllTypeTimeValDateExpr      = "DATE(time_val)"
	TestAllTypeDatetimeValDateExpr  = "DATE(datetime_val)"
	TestAllTypeTimestampValDateExpr = "DATE(timestamp_val)"
	TestAllTypeCreatedAtDateExpr    = "DATE(created_at)"
	TestAllTypeUpdatedAtDateExpr    = "DATE(updated_at)"
	TestAllTypeDeletedAtDateExpr    = "DATE(deleted_at)"
)

const (
	TestAllTypeAliasDateValDateExpr      = "DATE(test_all_types_alias.date_val)"
	TestAllTypeAliasTimeValDateExpr      = "DATE(test_all_types_alias.time_val)"
	TestAllTypeAliasDatetimeValDateExpr  = "DATE(test_all_types_alias.datetime_val)"
	TestAllTypeAliasTimestampValDateExpr = "DATE(test_all_types_alias.timestamp_val)"
	TestAllTypeAliasCreatedAtDateExpr    = "DATE(test_all_types_alias.created_at)"
	TestAllTypeAliasUpdatedAtDateExpr    = "DATE(test_all_types_alias.updated_at)"
	TestAllTypeAliasDeletedAtDateExpr    = "DATE(test_all_types_alias.deleted_at)"
)

const (
	TestAllTypeDateValYearExpr      = "EXTRACT(YEAR FROM date_val)"
	TestAllTypeTimeValYearExpr      = "EXTRACT(YEAR FROM time_val)"
	TestAllTypeDatetimeValYearExpr  = "EXTRACT(YEAR FROM datetime_val)"
	TestAllTypeTimestampValYearExpr = "EXTRACT(YEAR FROM timestamp_val)"
	TestAllTypeCreatedAtYearExpr    = "EXTRACT(YEAR FROM created_at)"
	TestAllTypeUpdatedAtYearExpr    = "EXTRACT(YEAR FROM updated_at)"
	TestAllTypeDeletedAtYearExpr    = "EXTRACT(YEAR FROM deleted_at)"
)

const (
	TestAllTypeAliasDateValYearExpr      = "EXTRACT(YEAR FROM test_all_types_alias.date_val)"
	TestAllTypeAliasTimeValYearExpr      = "EXTRACT(YEAR FROM test_all_types_alias.time_val)"
	TestAllTypeAliasDatetimeValYearExpr  = "EXTRACT(YEAR FROM test_all_types_alias.datetime_val)"
	TestAllTypeAliasTimestampValYearExpr = "EXTRACT(YEAR FROM test_all_types_alias.timestamp_val)"
	TestAllTypeAliasCreatedAtYearExpr    = "EXTRACT(YEAR FROM test_all_types_alias.created_at)"
	TestAllTypeAliasUpdatedAtYearExpr    = "EXTRACT(YEAR FROM test_all_types_alias.updated_at)"
	TestAllTypeAliasDeletedAtYearExpr    = "EXTRACT(YEAR FROM test_all_types_alias.deleted_at)"
)

const (
	TestAllTypeDateValMonthExpr      = "EXTRACT(MONTH FROM date_val)"
	TestAllTypeTimeValMonthExpr      = "EXTRACT(MONTH FROM time_val)"
	TestAllTypeDatetimeValMonthExpr  = "EXTRACT(MONTH FROM datetime_val)"
	TestAllTypeTimestampValMonthExpr = "EXTRACT(MONTH FROM timestamp_val)"
	TestAllTypeCreatedAtMonthExpr    = "EXTRACT(MONTH FROM created_at)"
	TestAllTypeUpdatedAtMonthExpr    = "EXTRACT(MONTH FROM updated_at)"
	TestAllTypeDeletedAtMonthExpr    = "EXTRACT(MONTH FROM deleted_at)"
)

const (
	TestAllTypeAliasDateValMonthExpr      = "EXTRACT(MONTH FROM test_all_types_alias.date_val)"
	TestAllTypeAliasTimeValMonthExpr      = "EXTRACT(MONTH FROM test_all_types_alias.time_val)"
	TestAllTypeAliasDatetimeValMonthExpr  = "EXTRACT(MONTH FROM test_all_types_alias.datetime_val)"
	TestAllTypeAliasTimestampValMonthExpr = "EXTRACT(MONTH FROM test_all_types_alias.timestamp_val)"
	TestAllTypeAliasCreatedAtMonthExpr    = "EXTRACT(MONTH FROM test_all_types_alias.created_at)"
	TestAllTypeAliasUpdatedAtMonthExpr    = "EXTRACT(MONTH FROM test_all_types_alias.updated_at)"
	TestAllTypeAliasDeletedAtMonthExpr    = "EXTRACT(MONTH FROM test_all_types_alias.deleted_at)"
)

const (
	TestAllTypeDateValDayExpr      = "EXTRACT(DAY FROM date_val)"
	TestAllTypeTimeValDayExpr      = "EXTRACT(DAY FROM time_val)"
	TestAllTypeDatetimeValDayExpr  = "EXTRACT(DAY FROM datetime_val)"
	TestAllTypeTimestampValDayExpr = "EXTRACT(DAY FROM timestamp_val)"
	TestAllTypeCreatedAtDayExpr    = "EXTRACT(DAY FROM created_at)"
	TestAllTypeUpdatedAtDayExpr    = "EXTRACT(DAY FROM updated_at)"
	TestAllTypeDeletedAtDayExpr    = "EXTRACT(DAY FROM deleted_at)"
)

const (
	TestAllTypeAliasDateValDayExpr      = "EXTRACT(DAY FROM test_all_types_alias.date_val)"
	TestAllTypeAliasTimeValDayExpr      = "EXTRACT(DAY FROM test_all_types_alias.time_val)"
	TestAllTypeAliasDatetimeValDayExpr  = "EXTRACT(DAY FROM test_all_types_alias.datetime_val)"
	TestAllTypeAliasTimestampValDayExpr = "EXTRACT(DAY FROM test_all_types_alias.timestamp_val)"
	TestAllTypeAliasCreatedAtDayExpr    = "EXTRACT(DAY FROM test_all_types_alias.created_at)"
	TestAllTypeAliasUpdatedAtDayExpr    = "EXTRACT(DAY FROM test_all_types_alias.updated_at)"
	TestAllTypeAliasDeletedAtDayExpr    = "EXTRACT(DAY FROM test_all_types_alias.deleted_at)"
)

const (
	TestAllTypeDateValHourExpr      = "EXTRACT(HOUR FROM date_val)"
	TestAllTypeTimeValHourExpr      = "EXTRACT(HOUR FROM time_val)"
	TestAllTypeDatetimeValHourExpr  = "EXTRACT(HOUR FROM datetime_val)"
	TestAllTypeTimestampValHourExpr = "EXTRACT(HOUR FROM timestamp_val)"
	TestAllTypeCreatedAtHourExpr    = "EXTRACT(HOUR FROM created_at)"
	TestAllTypeUpdatedAtHourExpr    = "EXTRACT(HOUR FROM updated_at)"
	TestAllTypeDeletedAtHourExpr    = "EXTRACT(HOUR FROM deleted_at)"
)

const (
	TestAllTypeAliasDateValHourExpr      = "EXTRACT(HOUR FROM test_all_types_alias.date_val)"
	TestAllTypeAliasTimeValHourExpr      = "EXTRACT(HOUR FROM test_all_types_alias.time_val)"
	TestAllTypeAliasDatetimeValHourExpr  = "EXTRACT(HOUR FROM test_all_types_alias.datetime_val)"
	TestAllTypeAliasTimestampValHourExpr = "EXTRACT(HOUR FROM test_all_types_alias.timestamp_val)"
	TestAllTypeAliasCreatedAtHourExpr    = "EXTRACT(HOUR FROM test_all_types_alias.created_at)"
	TestAllTypeAliasUpdatedAtHourExpr    = "EXTRACT(HOUR FROM test_all_types_alias.updated_at)"
	TestAllTypeAliasDeletedAtHourExpr    = "EXTRACT(HOUR FROM test_all_types_alias.deleted_at)"
)

const (
	TestAllTypeDateValMinuteExpr      = "EXTRACT(MINUTE FROM date_val)"
	TestAllTypeTimeValMinuteExpr      = "EXTRACT(MINUTE FROM time_val)"
	TestAllTypeDatetimeValMinuteExpr  = "EXTRACT(MINUTE FROM datetime_val)"
	TestAllTypeTimestampValMinuteExpr = "EXTRACT(MINUTE FROM timestamp_val)"
	TestAllTypeCreatedAtMinuteExpr    = "EXTRACT(MINUTE FROM created_at)"
	TestAllTypeUpdatedAtMinuteExpr    = "EXTRACT(MINUTE FROM updated_at)"
	TestAllTypeDeletedAtMinuteExpr    = "EXTRACT(MINUTE FROM deleted_at)"
)

const (
	TestAllTypeAliasDateValMinuteExpr      = "EXTRACT(MINUTE FROM test_all_types_alias.date_val)"
	TestAllTypeAliasTimeValMinuteExpr      = "EXTRACT(MINUTE FROM test_all_types_alias.time_val)"
	TestAllTypeAliasDatetimeValMinuteExpr  = "EXTRACT(MINUTE FROM test_all_types_alias.datetime_val)"
	TestAllTypeAliasTimestampValMinuteExpr = "EXTRACT(MINUTE FROM test_all_types_alias.timestamp_val)"
	TestAllTypeAliasCreatedAtMinuteExpr    = "EXTRACT(MINUTE FROM test_all_types_alias.created_at)"
	TestAllTypeAliasUpdatedAtMinuteExpr    = "EXTRACT(MINUTE FROM test_all_types_alias.updated_at)"
	TestAllTypeAliasDeletedAtMinuteExpr    = "EXTRACT(MINUTE FROM test_all_types_alias.deleted_at)"
)

const (
	TestAllTypeDateValSecondExpr      = "EXTRACT(SECOND FROM date_val)"
	TestAllTypeTimeValSecondExpr      = "EXTRACT(SECOND FROM time_val)"
	TestAllTypeDatetimeValSecondExpr  = "EXTRACT(SECOND FROM datetime_val)"
	TestAllTypeTimestampValSecondExpr = "EXTRACT(SECOND FROM timestamp_val)"
	TestAllTypeCreatedAtSecondExpr    = "EXTRACT(SECOND FROM created_at)"
	TestAllTypeUpdatedAtSecondExpr    = "EXTRACT(SECOND FROM updated_at)"
	TestAllTypeDeletedAtSecondExpr    = "EXTRACT(SECOND FROM deleted_at)"
)

const (
	TestAllTypeAliasDateValSecondExpr      = "EXTRACT(SECOND FROM test_all_types_alias.date_val)"
	TestAllTypeAliasTimeValSecondExpr      = "EXTRACT(SECOND FROM test_all_types_alias.time_val)"
	TestAllTypeAliasDatetimeValSecondExpr  = "EXTRACT(SECOND FROM test_all_types_alias.datetime_val)"
	TestAllTypeAliasTimestampValSecondExpr = "EXTRACT(SECOND FROM test_all_types_alias.timestamp_val)"
	TestAllTypeAliasCreatedAtSecondExpr    = "EXTRACT(SECOND FROM test_all_types_alias.created_at)"
	TestAllTypeAliasUpdatedAtSecondExpr    = "EXTRACT(SECOND FROM test_all_types_alias.updated_at)"
	TestAllTypeAliasDeletedAtSecondExpr    = "EXTRACT(SECOND FROM test_all_types_alias.deleted_at)"
)

const (
	TestAllTypeIDAsc             = "id ASC"
	TestAllTypeTinyIntValAsc     = "tiny_int_val ASC"
	TestAllTypeSmallIntValAsc    = "small_int_val ASC"
	TestAllTypeMediumIntValAsc   = "medium_int_val ASC"
	TestAllTypeIntValAsc         = "int_val ASC"
	TestAllTypeBigIntValAsc      = "big_int_val ASC"
	TestAllTypeDecimalValAsc     = "decimal_val ASC"
	TestAllTypeFloatValAsc       = "float_val ASC"
	TestAllTypeDoubleValAsc      = "double_val ASC"
	TestAllTypeCharValAsc        = "char_val ASC"
	TestAllTypeVarcharValAsc     = "varchar_val ASC"
	TestAllTypeTextValAsc        = "text_val ASC"
	TestAllTypeMediumtextValAsc  = "mediumtext_val ASC"
	TestAllTypeLongtextValAsc    = "longtext_val ASC"
	TestAllTypeDateValAsc        = "date_val ASC"
	TestAllTypeTimeValAsc        = "time_val ASC"
	TestAllTypeDatetimeValAsc    = "datetime_val ASC"
	TestAllTypeTimestampValAsc   = "timestamp_val ASC"
	TestAllTypeYearValAsc        = "year_val ASC"
	TestAllTypeBoolValAsc        = "bool_val ASC"
	TestAllTypeEnumValAsc        = "enum_val ASC"
	TestAllTypeSetValAsc         = "set_val ASC"
	TestAllTypeNullableIntValAsc = "nullable_int_val ASC"
	TestAllTypeIgnoreValAsc      = "ignore_val ASC"
	TestAllTypeCreatedAtAsc      = "created_at ASC"
	TestAllTypeUpdatedAtAsc      = "updated_at ASC"
	TestAllTypeDeletedAtAsc      = "deleted_at ASC"
)

const (
	TestAllTypeAliasIDAsc             = "test_all_types_alias.id ASC"
	TestAllTypeAliasTinyIntValAsc     = "test_all_types_alias.tiny_int_val ASC"
	TestAllTypeAliasSmallIntValAsc    = "test_all_types_alias.small_int_val ASC"
	TestAllTypeAliasMediumIntValAsc   = "test_all_types_alias.medium_int_val ASC"
	TestAllTypeAliasIntValAsc         = "test_all_types_alias.int_val ASC"
	TestAllTypeAliasBigIntValAsc      = "test_all_types_alias.big_int_val ASC"
	TestAllTypeAliasDecimalValAsc     = "test_all_types_alias.decimal_val ASC"
	TestAllTypeAliasFloatValAsc       = "test_all_types_alias.float_val ASC"
	TestAllTypeAliasDoubleValAsc      = "test_all_types_alias.double_val ASC"
	TestAllTypeAliasCharValAsc        = "test_all_types_alias.char_val ASC"
	TestAllTypeAliasVarcharValAsc     = "test_all_types_alias.varchar_val ASC"
	TestAllTypeAliasTextValAsc        = "test_all_types_alias.text_val ASC"
	TestAllTypeAliasMediumtextValAsc  = "test_all_types_alias.mediumtext_val ASC"
	TestAllTypeAliasLongtextValAsc    = "test_all_types_alias.longtext_val ASC"
	TestAllTypeAliasDateValAsc        = "test_all_types_alias.date_val ASC"
	TestAllTypeAliasTimeValAsc        = "test_all_types_alias.time_val ASC"
	TestAllTypeAliasDatetimeValAsc    = "test_all_types_alias.datetime_val ASC"
	TestAllTypeAliasTimestampValAsc   = "test_all_types_alias.timestamp_val ASC"
	TestAllTypeAliasYearValAsc        = "test_all_types_alias.year_val ASC"
	TestAllTypeAliasBoolValAsc        = "test_all_types_alias.bool_val ASC"
	TestAllTypeAliasEnumValAsc        = "test_all_types_alias.enum_val ASC"
	TestAllTypeAliasSetValAsc         = "test_all_types_alias.set_val ASC"
	TestAllTypeAliasNullableIntValAsc = "test_all_types_alias.nullable_int_val ASC"
	TestAllTypeAliasIgnoreValAsc      = "test_all_types_alias.ignore_val ASC"
	TestAllTypeAliasCreatedAtAsc      = "test_all_types_alias.created_at ASC"
	TestAllTypeAliasUpdatedAtAsc      = "test_all_types_alias.updated_at ASC"
	TestAllTypeAliasDeletedAtAsc      = "test_all_types_alias.deleted_at ASC"
)

const (
	TestAllTypeIDDesc             = "id DESC"
	TestAllTypeTinyIntValDesc     = "tiny_int_val DESC"
	TestAllTypeSmallIntValDesc    = "small_int_val DESC"
	TestAllTypeMediumIntValDesc   = "medium_int_val DESC"
	TestAllTypeIntValDesc         = "int_val DESC"
	TestAllTypeBigIntValDesc      = "big_int_val DESC"
	TestAllTypeDecimalValDesc     = "decimal_val DESC"
	TestAllTypeFloatValDesc       = "float_val DESC"
	TestAllTypeDoubleValDesc      = "double_val DESC"
	TestAllTypeCharValDesc        = "char_val DESC"
	TestAllTypeVarcharValDesc     = "varchar_val DESC"
	TestAllTypeTextValDesc        = "text_val DESC"
	TestAllTypeMediumtextValDesc  = "mediumtext_val DESC"
	TestAllTypeLongtextValDesc    = "longtext_val DESC"
	TestAllTypeDateValDesc        = "date_val DESC"
	TestAllTypeTimeValDesc        = "time_val DESC"
	TestAllTypeDatetimeValDesc    = "datetime_val DESC"
	TestAllTypeTimestampValDesc   = "timestamp_val DESC"
	TestAllTypeYearValDesc        = "year_val DESC"
	TestAllTypeBoolValDesc        = "bool_val DESC"
	TestAllTypeEnumValDesc        = "enum_val DESC"
	TestAllTypeSetValDesc         = "set_val DESC"
	TestAllTypeNullableIntValDesc = "nullable_int_val DESC"
	TestAllTypeIgnoreValDesc      = "ignore_val DESC"
	TestAllTypeCreatedAtDesc      = "created_at DESC"
	TestAllTypeUpdatedAtDesc      = "updated_at DESC"
	TestAllTypeDeletedAtDesc      = "deleted_at DESC"
)

const (
	TestAllTypeAliasIDDesc             = "test_all_types_alias.id DESC"
	TestAllTypeAliasTinyIntValDesc     = "test_all_types_alias.tiny_int_val DESC"
	TestAllTypeAliasSmallIntValDesc    = "test_all_types_alias.small_int_val DESC"
	TestAllTypeAliasMediumIntValDesc   = "test_all_types_alias.medium_int_val DESC"
	TestAllTypeAliasIntValDesc         = "test_all_types_alias.int_val DESC"
	TestAllTypeAliasBigIntValDesc      = "test_all_types_alias.big_int_val DESC"
	TestAllTypeAliasDecimalValDesc     = "test_all_types_alias.decimal_val DESC"
	TestAllTypeAliasFloatValDesc       = "test_all_types_alias.float_val DESC"
	TestAllTypeAliasDoubleValDesc      = "test_all_types_alias.double_val DESC"
	TestAllTypeAliasCharValDesc        = "test_all_types_alias.char_val DESC"
	TestAllTypeAliasVarcharValDesc     = "test_all_types_alias.varchar_val DESC"
	TestAllTypeAliasTextValDesc        = "test_all_types_alias.text_val DESC"
	TestAllTypeAliasMediumtextValDesc  = "test_all_types_alias.mediumtext_val DESC"
	TestAllTypeAliasLongtextValDesc    = "test_all_types_alias.longtext_val DESC"
	TestAllTypeAliasDateValDesc        = "test_all_types_alias.date_val DESC"
	TestAllTypeAliasTimeValDesc        = "test_all_types_alias.time_val DESC"
	TestAllTypeAliasDatetimeValDesc    = "test_all_types_alias.datetime_val DESC"
	TestAllTypeAliasTimestampValDesc   = "test_all_types_alias.timestamp_val DESC"
	TestAllTypeAliasYearValDesc        = "test_all_types_alias.year_val DESC"
	TestAllTypeAliasBoolValDesc        = "test_all_types_alias.bool_val DESC"
	TestAllTypeAliasEnumValDesc        = "test_all_types_alias.enum_val DESC"
	TestAllTypeAliasSetValDesc         = "test_all_types_alias.set_val DESC"
	TestAllTypeAliasNullableIntValDesc = "test_all_types_alias.nullable_int_val DESC"
	TestAllTypeAliasIgnoreValDesc      = "test_all_types_alias.ignore_val DESC"
	TestAllTypeAliasCreatedAtDesc      = "test_all_types_alias.created_at DESC"
	TestAllTypeAliasUpdatedAtDesc      = "test_all_types_alias.updated_at DESC"
	TestAllTypeAliasDeletedAtDesc      = "test_all_types_alias.deleted_at DESC"
)

// TestAllType generates a model for the "test_all_types" table.
type TestAllType struct {
	bun.BaseModel `bun:"table:test_all_types,alias:test_all_types_alias"`

	ID            int32            `bun:"id,pk,autoincrement,notnull" form:"id" json:"id,omitempty" xml:"Id"`                                       //
	TinyIntVal    *int8            `bun:"tiny_int_val,nullzero" form:"tiny_int_val" json:"tiny_int_val,omitempty" xml:"TinyIntVal"`                 //
	SmallIntVal   int16            `bun:"small_int_val,notnull,default:'0'" form:"small_int_val" json:"small_int_val,omitempty" xml:"SmallIntVal"`  //
	MediumIntVal  *int32           `bun:"medium_int_val,nullzero" form:"medium_int_val" json:"medium_int_val,omitempty" xml:"MediumIntVal"`         //
	IntVal        int32            `bun:"int_val,notnull,default:'0'" form:"int_val" json:"int_val,omitempty" xml:"IntVal"`                         //
	BigIntVal     *int64           `bun:"big_int_val,nullzero" form:"big_int_val" json:"big_int_val,omitempty" xml:"BigIntVal"`                     //
	DecimalVal    *decimal.Decimal `bun:"decimal_val,type:decimal(10,2),nullzero" form:"decimal_val" json:"decimal_val,omitempty" xml:"DecimalVal"` //
	FloatVal      *float32         `bun:"float_val,nullzero" form:"float_val" json:"float_val,omitempty" xml:"FloatVal"`                            //
	DoubleVal     *float64         `bun:"double_val,nullzero" form:"double_val" json:"double_val,omitempty" xml:"DoubleVal"`                        //
	CharVal       *string          `bun:"char_val,nullzero" form:"char_val" json:"char_val,omitempty" xml:"CharVal"`                                //
	VarcharVal    *string          `bun:"varchar_val,nullzero" form:"varchar_val" json:"varchar_val,omitempty" xml:"VarcharVal"`                    //
	TextVal       *string          `bun:"text_val,nullzero" form:"text_val" json:"text_val,omitempty" xml:"TextVal"`                                //
	MediumtextVal *string          `bun:"mediumtext_val,nullzero" form:"mediumtext_val" json:"mediumtext_val,omitempty" xml:"MediumtextVal"`        //
	LongtextVal   *string          `bun:"longtext_val,nullzero" form:"longtext_val" json:"longtext_val,omitempty" xml:"LongtextVal"`                //
	DateVal       *time.Time       `bun:"date_val,nullzero" form:"date_val" json:"date_val,omitempty" xml:"DateVal"`                                //
	TimeVal       *time.Time       `bun:"time_val,nullzero" form:"time_val" json:"time_val,omitempty" xml:"TimeVal"`                                //
	DatetimeVal   *time.Time       `bun:"datetime_val,nullzero" form:"datetime_val" json:"datetime_val,omitempty" xml:"DatetimeVal"`                //
	TimestampVal  *time.Time       `bun:"timestamp_val,nullzero" form:"timestamp_val" json:"timestamp_val,omitempty" xml:"TimestampVal"`            //
	YearVal       *int             `bun:"year_val,nullzero" form:"year_val" json:"year_val,omitempty" xml:"YearVal"`                                //
	BoolVal       *bool            `bun:"bool_val,nullzero" form:"bool_val" json:"bool_val,omitempty" xml:"BoolVal"`                                //
	EnumVal       *string          `bun:"enum_val,nullzero" form:"enum_val" json:"enum_val,omitempty" xml:"EnumVal"`                                //
	SetVal        *string          `bun:"set_val,nullzero" form:"set_val" json:"set_val,omitempty" xml:"SetVal"`                                    //
	BinaryVal     []byte           `bun:"binary_val,nullzero" form:"binary_val" json:"binary_val,omitempty" xml:"BinaryVal"`                        //
	VarbinaryVal  []byte           `bun:"varbinary_val,nullzero" form:"varbinary_val" json:"varbinary_val,omitempty" xml:"VarbinaryVal"`            //
	BlobVal       []byte           `bun:"blob_val,nullzero" form:"blob_val" json:"blob_val,omitempty" xml:"BlobVal"`                                //
	MediumblobVal []byte           `bun:"mediumblob_val,nullzero" form:"mediumblob_val" json:"mediumblob_val,omitempty" xml:"MediumblobVal"`        //
	LongblobVal   []byte           `bun:"longblob_val,nullzero" form:"longblob_val" json:"longblob_val,omitempty" xml:"LongblobVal"`                //
	// This is a JSON column
	// with multiple lines of text
	// This is a JSON column
	// with multiple lines of text
	// This is a JSON column
	// with multiple lines of text
	JsonVal        json.RawMessage `bun:"json_val,nullzero" form:"json_val" json:"json_val,omitempty" xml:"JsonVal"`
	BitVal         []byte          `bun:"bit_val,nullzero" form:"bit_val" json:"bit_val,omitempty" xml:"BitVal"`                                         //
	NullableIntVal *int32          `bun:"nullable_int_val,nullzero" form:"nullable_int_val" json:"nullable_int_val,omitempty" xml:"NullableIntVal"`      //
	IgnoreVal      *string         `bun:"ignore_val,nullzero" form:"ignore_val" json:"ignore_val,omitempty" xml:"IgnoreVal"`                             //
	CreatedAt      time.Time       `bun:"created_at,notnull,default:current_timestamp(3)" form:"created_at" json:"created_at,omitempty" xml:"CreatedAt"` // created at
	UpdatedAt      time.Time       `bun:"updated_at,notnull,default:current_timestamp(3)" form:"updated_at" json:"updated_at,omitempty" xml:"UpdatedAt"` // updated at
	DeletedAt      *time.Time      `bun:"deleted_at,nullzero,soft_delete" form:"deleted_at" json:"-" xml:"DeletedAt"`                                    // deleted at
}

func (m *TestAllType) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	now := time.Now()
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}
	return nil
}

func (m *TestAllType) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	now := time.Now()
	if m.UpdatedAt.IsZero() {
		m.UpdatedAt = now
	}
	return nil
}
