// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: test_index

// Package model defines database models generated from schema.
package model

import (
	"github.com/uptrace/bun"
)

const TestIndexTableAlias = "test_index_alias"

const TestIndexTableNameAsAlias = "test_index AS test_index_alias"

var TestIndexTableAliasIdent = bun.Ident("test_index_alias")

const (
	InnerJoinTestIndexAsAlias = "INNER JOIN test_index AS test_index_alias" // same as JOIN
	LeftJoinTestIndexAsAlias  = "LEFT JOIN test_index AS test_index_alias"  // same as LEFT OUTER JOIN
	RightJoinTestIndexAsAlias = "RIGHT JOIN test_index AS test_index_alias" // same as RIGHT OUTER JOIN
)

const (
	TestIndexAliasID      = "test_index_alias.id"
	TestIndexAliasStartAt = "test_index_alias.start_at"
	TestIndexAliasEndAt   = "test_index_alias.end_at"
	TestIndexAliasSeq     = "test_index_alias.seq"
)

var (
	TestIndexIDAliasIdent      = bun.Ident("test_index_alias.id")
	TestIndexStartAtAliasIdent = bun.Ident("test_index_alias.start_at")
	TestIndexEndAtAliasIdent   = bun.Ident("test_index_alias.end_at")
	TestIndexSeqAliasIdent     = bun.Ident("test_index_alias.seq")
)

const (
	TestIndexAliasIDEq      = "test_index_alias.id = ?"
	TestIndexAliasStartAtEq = "test_index_alias.start_at = ?"
	TestIndexAliasEndAtEq   = "test_index_alias.end_at = ?"
	TestIndexAliasSeqEq     = "test_index_alias.seq = ?"
)

const (
	TestIndexAliasIDNeq      = "test_index_alias.id <> ?"
	TestIndexAliasStartAtNeq = "test_index_alias.start_at <> ?"
	TestIndexAliasEndAtNeq   = "test_index_alias.end_at <> ?"
	TestIndexAliasSeqNeq     = "test_index_alias.seq <> ?"
)

const (
	TestIndexAliasIDGt      = "test_index_alias.id > ?"
	TestIndexAliasStartAtGt = "test_index_alias.start_at > ?"
	TestIndexAliasEndAtGt   = "test_index_alias.end_at > ?"
	TestIndexAliasSeqGt     = "test_index_alias.seq > ?"
)

const (
	TestIndexAliasIDGte      = "test_index_alias.id >= ?"
	TestIndexAliasStartAtGte = "test_index_alias.start_at >= ?"
	TestIndexAliasEndAtGte   = "test_index_alias.end_at >= ?"
	TestIndexAliasSeqGte     = "test_index_alias.seq >= ?"
)

const (
	TestIndexAliasIDLt      = "test_index_alias.id < ?"
	TestIndexAliasStartAtLt = "test_index_alias.start_at < ?"
	TestIndexAliasEndAtLt   = "test_index_alias.end_at < ?"
	TestIndexAliasSeqLt     = "test_index_alias.seq < ?"
)

const (
	TestIndexAliasIDLte      = "test_index_alias.id <= ?"
	TestIndexAliasStartAtLte = "test_index_alias.start_at <= ?"
	TestIndexAliasEndAtLte   = "test_index_alias.end_at <= ?"
	TestIndexAliasSeqLte     = "test_index_alias.seq <= ?"
)

const (
	TestIndexAliasSeqSUMExpr = "SUM(test_index_alias.seq)"
)

const (
	TestIndexAliasSeqAVGExpr = "AVG(test_index_alias.seq)"
)

const (
	TestIndexAliasIDMINExpr      = "MIN(test_index_alias.id)"
	TestIndexAliasStartAtMINExpr = "MIN(test_index_alias.start_at)"
	TestIndexAliasEndAtMINExpr   = "MIN(test_index_alias.end_at)"
	TestIndexAliasSeqMINExpr     = "MIN(test_index_alias.seq)"
)

const (
	TestIndexAliasIDMAXExpr      = "MAX(test_index_alias.id)"
	TestIndexAliasStartAtMAXExpr = "MAX(test_index_alias.start_at)"
	TestIndexAliasEndAtMAXExpr   = "MAX(test_index_alias.end_at)"
	TestIndexAliasSeqMAXExpr     = "MAX(test_index_alias.seq)"
)

const (
	TestIndexAliasSeqAddExpr = "test_index_alias.seq = test_index_alias.seq + ?"
)

const (
	TestIndexAliasSeqSubExpr = "test_index_alias.seq = test_index_alias.seq - ?"
)

const (
	TestIndexAliasSeqAddLeastExpr = "test_index_alias.seq = LEAST(test_index_alias.seq + ?, ?)"
)

const (
	TestIndexAliasSeqSubGreatestExpr = "test_index_alias.seq = GREATEST(test_index_alias.seq - ?, ?)"
)

const (
	TestIndexAliasSeqClampExpr = "test_index_alias.seq = LEAST(GREATEST(test_index_alias.seq + ?, ?), ?)"
)

const (
	TestIndexAliasIDDistinctExpr      = "DISTINCT test_index_alias.id"
	TestIndexAliasStartAtDistinctExpr = "DISTINCT test_index_alias.start_at"
	TestIndexAliasEndAtDistinctExpr   = "DISTINCT test_index_alias.end_at"
	TestIndexAliasSeqDistinctExpr     = "DISTINCT test_index_alias.seq"
)

const (
	TestIndexAliasIDCountDistinctExpr      = "COUNT(DISTINCT test_index_alias.id)"
	TestIndexAliasStartAtCountDistinctExpr = "COUNT(DISTINCT test_index_alias.start_at)"
	TestIndexAliasEndAtCountDistinctExpr   = "COUNT(DISTINCT test_index_alias.end_at)"
	TestIndexAliasSeqCountDistinctExpr     = "COUNT(DISTINCT test_index_alias.seq)"
)

const (
	TestIndexAliasIDIn      = "test_index_alias.id IN (?)"
	TestIndexAliasStartAtIn = "test_index_alias.start_at IN (?)"
	TestIndexAliasEndAtIn   = "test_index_alias.end_at IN (?)"
	TestIndexAliasSeqIn     = "test_index_alias.seq IN (?)"
)

const (
	TestIndexAliasIDNotIn      = "test_index_alias.id NOT IN (?)"
	TestIndexAliasStartAtNotIn = "test_index_alias.start_at NOT IN (?)"
	TestIndexAliasEndAtNotIn   = "test_index_alias.end_at NOT IN (?)"
	TestIndexAliasSeqNotIn     = "test_index_alias.seq NOT IN (?)"
)

const (
	TestIndexAliasIDBetween      = "test_index_alias.id BETWEEN ? AND ?"
	TestIndexAliasStartAtBetween = "test_index_alias.start_at BETWEEN ? AND ?"
	TestIndexAliasEndAtBetween   = "test_index_alias.end_at BETWEEN ? AND ?"
	TestIndexAliasSeqBetween     = "test_index_alias.seq BETWEEN ? AND ?"
)

const (
	TestIndexAliasIDNotBetween      = "test_index_alias.id NOT BETWEEN ? AND ?"
	TestIndexAliasStartAtNotBetween = "test_index_alias.start_at NOT BETWEEN ? AND ?"
	TestIndexAliasEndAtNotBetween   = "test_index_alias.end_at NOT BETWEEN ? AND ?"
	TestIndexAliasSeqNotBetween     = "test_index_alias.seq NOT BETWEEN ? AND ?"
)

const (
	TestIndexAliasStartAtDateExpr = "DATE(test_index_alias.start_at)"
	TestIndexAliasEndAtDateExpr   = "DATE(test_index_alias.end_at)"
)

const (
	TestIndexAliasStartAtYearExpr = "EXTRACT(YEAR FROM test_index_alias.start_at)"
	TestIndexAliasEndAtYearExpr   = "EXTRACT(YEAR FROM test_index_alias.end_at)"
)

const (
	TestIndexAliasStartAtMonthExpr = "EXTRACT(MONTH FROM test_index_alias.start_at)"
	TestIndexAliasEndAtMonthExpr   = "EXTRACT(MONTH FROM test_index_alias.end_at)"
)

const (
	TestIndexAliasStartAtDayExpr = "EXTRACT(DAY FROM test_index_alias.start_at)"
	TestIndexAliasEndAtDayExpr   = "EXTRACT(DAY FROM test_index_alias.end_at)"
)

const (
	TestIndexAliasStartAtHourExpr = "EXTRACT(HOUR FROM test_index_alias.start_at)"
	TestIndexAliasEndAtHourExpr   = "EXTRACT(HOUR FROM test_index_alias.end_at)"
)

const (
	TestIndexAliasStartAtMinuteExpr = "EXTRACT(MINUTE FROM test_index_alias.start_at)"
	TestIndexAliasEndAtMinuteExpr   = "EXTRACT(MINUTE FROM test_index_alias.end_at)"
)

const (
	TestIndexAliasStartAtSecondExpr = "EXTRACT(SECOND FROM test_index_alias.start_at)"
	TestIndexAliasEndAtSecondExpr   = "EXTRACT(SECOND FROM test_index_alias.end_at)"
)

const (
	TestIndexAliasIDAsc      = "test_index_alias.id ASC"
	TestIndexAliasStartAtAsc = "test_index_alias.start_at ASC"
	TestIndexAliasEndAtAsc   = "test_index_alias.end_at ASC"
	TestIndexAliasSeqAsc     = "test_index_alias.seq ASC"
)

const (
	TestIndexAliasIDDesc      = "test_index_alias.id DESC"
	TestIndexAliasStartAtDesc = "test_index_alias.start_at DESC"
	TestIndexAliasEndAtDesc   = "test_index_alias.end_at DESC"
	TestIndexAliasSeqDesc     = "test_index_alias.seq DESC"
)
