// Code generated by bake. DO NOT EDIT.
// version: v0.1.1
// source: users

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilUser = (*User)(nil)

var (
	_ bun.BeforeInsertHook = (*User)(nil)
	_ bun.BeforeUpdateHook = (*User)(nil)
)

const (
	UserTableName  = "users"
	UserTableAlias = "users_alias"
)

const UserTableNameAsAlias = "users AS users_alias"

var (
	UserTableNameIdent  = bun.Ident("users")
	UserTableAliasIdent = bun.Ident("users_alias")
)

const (
	InnerJoinUserAsAlias = "INNER JOIN users AS users_alias" // same as JOIN
	LeftJoinUserAsAlias  = "LEFT JOIN users AS users_alias"  // same as LEFT OUTER JOIN
	RightJoinUserAsAlias = "RIGHT JOIN users AS users_alias" // same as RIGHT OUTER JOIN
	FullJoinUserAsAlias  = "FULL JOIN users AS users_alias"  // same as FULL OUTER JOIN
)

const (
	UserID        = "id"
	UserName      = "name"
	UserEmail     = "email"
	UserCreatedAt = "created_at"
)

const (
	UserRelationPosts = "Posts"
)

const (
	UserAliasID        = "users_alias.id"
	UserAliasName      = "users_alias.name"
	UserAliasEmail     = "users_alias.email"
	UserAliasCreatedAt = "users_alias.created_at"
)

var (
	UserIDIdent        = bun.Ident("id")
	UserNameIdent      = bun.Ident("name")
	UserEmailIdent     = bun.Ident("email")
	UserCreatedAtIdent = bun.Ident("created_at")
)

const (
	UserIDEq        = "id = ?"
	UserNameEq      = "name = ?"
	UserEmailEq     = "email = ?"
	UserCreatedAtEq = "created_at = ?"
)

const (
	UserAliasIDEq        = "users_alias.id = ?"
	UserAliasNameEq      = "users_alias.name = ?"
	UserAliasEmailEq     = "users_alias.email = ?"
	UserAliasCreatedAtEq = "users_alias.created_at = ?"
)

const (
	UserIDNeq        = "id <> ?"
	UserNameNeq      = "name <> ?"
	UserEmailNeq     = "email <> ?"
	UserCreatedAtNeq = "created_at <> ?"
)

const (
	UserAliasIDNeq        = "users_alias.id <> ?"
	UserAliasNameNeq      = "users_alias.name <> ?"
	UserAliasEmailNeq     = "users_alias.email <> ?"
	UserAliasCreatedAtNeq = "users_alias.created_at <> ?"
)

const (
	UserIDGt        = "id > ?"
	UserCreatedAtGt = "created_at > ?"
)

const (
	UserAliasIDGt        = "users_alias.id > ?"
	UserAliasCreatedAtGt = "users_alias.created_at > ?"
)

const (
	UserIDGte        = "id >= ?"
	UserCreatedAtGte = "created_at >= ?"
)

const (
	UserAliasIDGte        = "users_alias.id >= ?"
	UserAliasCreatedAtGte = "users_alias.created_at >= ?"
)

const (
	UserIDLt        = "id < ?"
	UserCreatedAtLt = "created_at < ?"
)

const (
	UserAliasIDLt        = "users_alias.id < ?"
	UserAliasCreatedAtLt = "users_alias.created_at < ?"
)

const (
	UserIDLte        = "id <= ?"
	UserCreatedAtLte = "created_at <= ?"
)

const (
	UserAliasIDLte        = "users_alias.id <= ?"
	UserAliasCreatedAtLte = "users_alias.created_at <= ?"
)

const (
	UserNameLike  = "name LIKE ?"
	UserEmailLike = "email LIKE ?"
)

const (
	UserAliasNameLike  = "users_alias.name LIKE ?"
	UserAliasEmailLike = "users_alias.email LIKE ?"
)

const (
	UserNameLikePrefix  = "name LIKE ?%"
	UserEmailLikePrefix = "email LIKE ?%"
)

const (
	UserAliasNameLikePrefix  = "users_alias.name LIKE ?%"
	UserAliasEmailLikePrefix = "users_alias.email LIKE ?%"
)

const (
	UserNameLikeSuffix  = "name LIKE %?"
	UserEmailLikeSuffix = "email LIKE %?"
)

const (
	UserAliasNameLikeSuffix  = "users_alias.name LIKE %?"
	UserAliasEmailLikeSuffix = "users_alias.email LIKE %?"
)

const (
	UserNameLikeContain  = "name LIKE %?%"
	UserEmailLikeContain = "email LIKE %?%"
)

const (
	UserAliasNameLikeContain  = "users_alias.name LIKE %?%"
	UserAliasEmailLikeContain = "users_alias.email LIKE %?%"
)

const (
	UserIDMINExpr        = "MIN(id)"
	UserCreatedAtMINExpr = "MIN(created_at)"
)

const (
	UserAliasIDMINExpr        = "MIN(users_alias.id)"
	UserAliasCreatedAtMINExpr = "MIN(users_alias.created_at)"
)

const (
	UserIDMAXExpr        = "MAX(id)"
	UserCreatedAtMAXExpr = "MAX(created_at)"
)

const (
	UserAliasIDMAXExpr        = "MAX(users_alias.id)"
	UserAliasCreatedAtMAXExpr = "MAX(users_alias.created_at)"
)

const (
	UserIDIn        = "id IN (?)"
	UserNameIn      = "name IN (?)"
	UserEmailIn     = "email IN (?)"
	UserCreatedAtIn = "created_at IN (?)"
)

const (
	UserAliasIDIn        = "users_alias.id IN (?)"
	UserAliasNameIn      = "users_alias.name IN (?)"
	UserAliasEmailIn     = "users_alias.email IN (?)"
	UserAliasCreatedAtIn = "users_alias.created_at IN (?)"
)

const (
	UserIDNotIn        = "id NOT IN (?)"
	UserNameNotIn      = "name NOT IN (?)"
	UserEmailNotIn     = "email NOT IN (?)"
	UserCreatedAtNotIn = "created_at NOT IN (?)"
)

const (
	UserAliasIDNotIn        = "users_alias.id NOT IN (?)"
	UserAliasNameNotIn      = "users_alias.name NOT IN (?)"
	UserAliasEmailNotIn     = "users_alias.email NOT IN (?)"
	UserAliasCreatedAtNotIn = "users_alias.created_at NOT IN (?)"
)

const (
	UserIDBetween        = "id BETWEEN ? AND ?"
	UserCreatedAtBetween = "created_at BETWEEN ? AND ?"
)

const (
	UserAliasIDBetween        = "users_alias.id BETWEEN ? AND ?"
	UserAliasCreatedAtBetween = "users_alias.created_at BETWEEN ? AND ?"
)

const (
	UserIDNotBetween        = "id NOT BETWEEN ? AND ?"
	UserCreatedAtNotBetween = "created_at NOT BETWEEN ? AND ?"
)

const (
	UserAliasIDNotBetween        = "users_alias.id NOT BETWEEN ? AND ?"
	UserAliasCreatedAtNotBetween = "users_alias.created_at NOT BETWEEN ? AND ?"
)

const (
	UserCreatedAtDateExpr = "DATE(created_at)"
)

const (
	UserAliasCreatedAtDateExpr = "DATE(users_alias.created_at)"
)

const (
	UserCreatedAtYearExpr = "EXTRACT(YEAR FROM created_at)"
)

const (
	UserAliasCreatedAtYearExpr = "EXTRACT(YEAR FROM users_alias.created_at)"
)

const (
	UserCreatedAtMonthExpr = "EXTRACT(MONTH FROM created_at)"
)

const (
	UserAliasCreatedAtMonthExpr = "EXTRACT(MONTH FROM users_alias.created_at)"
)

const (
	UserCreatedAtDayExpr = "EXTRACT(DAY FROM created_at)"
)

const (
	UserAliasCreatedAtDayExpr = "EXTRACT(DAY FROM users_alias.created_at)"
)

const (
	UserCreatedAtHourExpr = "EXTRACT(HOUR FROM created_at)"
)

const (
	UserAliasCreatedAtHourExpr = "EXTRACT(HOUR FROM users_alias.created_at)"
)

const (
	UserCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM created_at)"
)

const (
	UserAliasCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM users_alias.created_at)"
)

const (
	UserCreatedAtSecondExpr = "EXTRACT(SECOND FROM created_at)"
)

const (
	UserAliasCreatedAtSecondExpr = "EXTRACT(SECOND FROM users_alias.created_at)"
)

const (
	UserIDAsc        = "id ASC"
	UserNameAsc      = "name ASC"
	UserEmailAsc     = "email ASC"
	UserCreatedAtAsc = "created_at ASC"
)

const (
	UserAliasIDAsc        = "users_alias.id ASC"
	UserAliasNameAsc      = "users_alias.name ASC"
	UserAliasEmailAsc     = "users_alias.email ASC"
	UserAliasCreatedAtAsc = "users_alias.created_at ASC"
)

const (
	UserIDDesc        = "id DESC"
	UserNameDesc      = "name DESC"
	UserEmailDesc     = "email DESC"
	UserCreatedAtDesc = "created_at DESC"
)

const (
	UserAliasIDDesc        = "users_alias.id DESC"
	UserAliasNameDesc      = "users_alias.name DESC"
	UserAliasEmailDesc     = "users_alias.email DESC"
	UserAliasCreatedAtDesc = "users_alias.created_at DESC"
)

// User generates a model for the "users" table.
// 用户表
type User struct {
	bun.BaseModel `bun:"table:users,alias:users_alias"`

	ID        int64     `bun:"id,pk,autoincrement,notnull" form:"id" json:"id,omitempty"`                                     //
	Name      string    `bun:"name,notnull" form:"name" json:"name,omitempty"`                                                // 用户名
	Email     string    `bun:"email,notnull" form:"email" json:"email,omitempty"`                                             // 邮箱
	CreatedAt time.Time `bun:"created_at,notnull,default:current_timestamp(3)" form:"created_at" json:"created_at,omitempty"` // 创建时间
	Posts     []*Post   `bun:"posts,join:id=user_id,rel:has-many" form:"posts" json:"posts,omitempty"`                        //
}

func (m *User) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	now := time.Now()
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	return nil
}

func (m *User) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	return nil
}
