// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: users

// Package model defines database models generated from schema.
package model

import (
	"github.com/uptrace/bun"
)

const UserTableAlias = "users_alias"

const UserTableNameAsAlias = "users AS users_alias"

var UserTableAliasIdent = bun.Ident("users_alias")

const (
	InnerJoinUserAsAlias = "INNER JOIN users AS users_alias" // same as JOIN
	LeftJoinUserAsAlias  = "LEFT JOIN users AS users_alias"  // same as LEFT OUTER JOIN
	RightJoinUserAsAlias = "RIGHT JOIN users AS users_alias" // same as RIGHT OUTER JOIN
)

const (
	UserAliasID        = "users_alias.id"
	UserAliasName      = "users_alias.name"
	UserAliasEmail     = "users_alias.email"
	UserAliasStartAt   = "users_alias.start_at"
	UserAliasEndAt     = "users_alias.end_at"
	UserAliasSeq       = "users_alias.seq"
	UserAliasCreatedAt = "users_alias.created_at"
)

var (
	UserIDAliasIdent        = bun.Ident("users_alias.id")
	UserNameAliasIdent      = bun.Ident("users_alias.name")
	UserEmailAliasIdent     = bun.Ident("users_alias.email")
	UserStartAtAliasIdent   = bun.Ident("users_alias.start_at")
	UserEndAtAliasIdent     = bun.Ident("users_alias.end_at")
	UserSeqAliasIdent       = bun.Ident("users_alias.seq")
	UserCreatedAtAliasIdent = bun.Ident("users_alias.created_at")
)

const (
	UserAliasIDEq        = "users_alias.id = ?"
	UserAliasNameEq      = "users_alias.name = ?"
	UserAliasEmailEq     = "users_alias.email = ?"
	UserAliasStartAtEq   = "users_alias.start_at = ?"
	UserAliasEndAtEq     = "users_alias.end_at = ?"
	UserAliasSeqEq       = "users_alias.seq = ?"
	UserAliasCreatedAtEq = "users_alias.created_at = ?"
)

const (
	UserAliasIDNeq        = "users_alias.id <> ?"
	UserAliasNameNeq      = "users_alias.name <> ?"
	UserAliasEmailNeq     = "users_alias.email <> ?"
	UserAliasStartAtNeq   = "users_alias.start_at <> ?"
	UserAliasEndAtNeq     = "users_alias.end_at <> ?"
	UserAliasSeqNeq       = "users_alias.seq <> ?"
	UserAliasCreatedAtNeq = "users_alias.created_at <> ?"
)

const (
	UserAliasIDGt        = "users_alias.id > ?"
	UserAliasStartAtGt   = "users_alias.start_at > ?"
	UserAliasEndAtGt     = "users_alias.end_at > ?"
	UserAliasSeqGt       = "users_alias.seq > ?"
	UserAliasCreatedAtGt = "users_alias.created_at > ?"
)

const (
	UserAliasIDGte        = "users_alias.id >= ?"
	UserAliasStartAtGte   = "users_alias.start_at >= ?"
	UserAliasEndAtGte     = "users_alias.end_at >= ?"
	UserAliasSeqGte       = "users_alias.seq >= ?"
	UserAliasCreatedAtGte = "users_alias.created_at >= ?"
)

const (
	UserAliasIDLt        = "users_alias.id < ?"
	UserAliasStartAtLt   = "users_alias.start_at < ?"
	UserAliasEndAtLt     = "users_alias.end_at < ?"
	UserAliasSeqLt       = "users_alias.seq < ?"
	UserAliasCreatedAtLt = "users_alias.created_at < ?"
)

const (
	UserAliasIDLte        = "users_alias.id <= ?"
	UserAliasStartAtLte   = "users_alias.start_at <= ?"
	UserAliasEndAtLte     = "users_alias.end_at <= ?"
	UserAliasSeqLte       = "users_alias.seq <= ?"
	UserAliasCreatedAtLte = "users_alias.created_at <= ?"
)

const (
	UserAliasNameLike  = "users_alias.name LIKE ?"
	UserAliasEmailLike = "users_alias.email LIKE ?"
)

const (
	UserAliasNameLikePrefix  = "users_alias.name LIKE ?%"
	UserAliasEmailLikePrefix = "users_alias.email LIKE ?%"
)

const (
	UserAliasNameLikeSuffix  = "users_alias.name LIKE %?"
	UserAliasEmailLikeSuffix = "users_alias.email LIKE %?"
)

const (
	UserAliasNameLikeContain  = "users_alias.name LIKE %?%"
	UserAliasEmailLikeContain = "users_alias.email LIKE %?%"
)

const (
	UserAliasNameConcatExpr  = "users_alias.name = CONCAT(users_alias.name, ?)"
	UserAliasEmailConcatExpr = "users_alias.email = CONCAT(users_alias.email, ?)"
)

const (
	UserAliasSeqSUMExpr = "SUM(users_alias.seq)"
)

const (
	UserAliasSeqAVGExpr = "AVG(users_alias.seq)"
)

const (
	UserAliasIDMINExpr        = "MIN(users_alias.id)"
	UserAliasStartAtMINExpr   = "MIN(users_alias.start_at)"
	UserAliasEndAtMINExpr     = "MIN(users_alias.end_at)"
	UserAliasSeqMINExpr       = "MIN(users_alias.seq)"
	UserAliasCreatedAtMINExpr = "MIN(users_alias.created_at)"
)

const (
	UserAliasIDMAXExpr        = "MAX(users_alias.id)"
	UserAliasStartAtMAXExpr   = "MAX(users_alias.start_at)"
	UserAliasEndAtMAXExpr     = "MAX(users_alias.end_at)"
	UserAliasSeqMAXExpr       = "MAX(users_alias.seq)"
	UserAliasCreatedAtMAXExpr = "MAX(users_alias.created_at)"
)

const (
	UserAliasSeqAddExpr = "users_alias.seq = users_alias.seq + ?"
)

const (
	UserAliasSeqSubExpr = "users_alias.seq = users_alias.seq - ?"
)

const (
	UserAliasSeqAddLeastExpr = "users_alias.seq = LEAST(users_alias.seq + ?, ?)"
)

const (
	UserAliasSeqSubGreatestExpr = "users_alias.seq = GREATEST(users_alias.seq - ?, ?)"
)

const (
	UserAliasSeqClampExpr = "users_alias.seq = LEAST(GREATEST(users_alias.seq + ?, ?), ?)"
)

const (
	UserAliasIDDistinctExpr        = "DISTINCT users_alias.id"
	UserAliasNameDistinctExpr      = "DISTINCT users_alias.name"
	UserAliasEmailDistinctExpr     = "DISTINCT users_alias.email"
	UserAliasStartAtDistinctExpr   = "DISTINCT users_alias.start_at"
	UserAliasEndAtDistinctExpr     = "DISTINCT users_alias.end_at"
	UserAliasSeqDistinctExpr       = "DISTINCT users_alias.seq"
	UserAliasCreatedAtDistinctExpr = "DISTINCT users_alias.created_at"
)

const (
	UserAliasIDCountDistinctExpr        = "COUNT(DISTINCT users_alias.id)"
	UserAliasNameCountDistinctExpr      = "COUNT(DISTINCT users_alias.name)"
	UserAliasEmailCountDistinctExpr     = "COUNT(DISTINCT users_alias.email)"
	UserAliasStartAtCountDistinctExpr   = "COUNT(DISTINCT users_alias.start_at)"
	UserAliasEndAtCountDistinctExpr     = "COUNT(DISTINCT users_alias.end_at)"
	UserAliasSeqCountDistinctExpr       = "COUNT(DISTINCT users_alias.seq)"
	UserAliasCreatedAtCountDistinctExpr = "COUNT(DISTINCT users_alias.created_at)"
)

const (
	UserAliasIDIn        = "users_alias.id IN (?)"
	UserAliasNameIn      = "users_alias.name IN (?)"
	UserAliasEmailIn     = "users_alias.email IN (?)"
	UserAliasStartAtIn   = "users_alias.start_at IN (?)"
	UserAliasEndAtIn     = "users_alias.end_at IN (?)"
	UserAliasSeqIn       = "users_alias.seq IN (?)"
	UserAliasCreatedAtIn = "users_alias.created_at IN (?)"
)

const (
	UserAliasIDNotIn        = "users_alias.id NOT IN (?)"
	UserAliasNameNotIn      = "users_alias.name NOT IN (?)"
	UserAliasEmailNotIn     = "users_alias.email NOT IN (?)"
	UserAliasStartAtNotIn   = "users_alias.start_at NOT IN (?)"
	UserAliasEndAtNotIn     = "users_alias.end_at NOT IN (?)"
	UserAliasSeqNotIn       = "users_alias.seq NOT IN (?)"
	UserAliasCreatedAtNotIn = "users_alias.created_at NOT IN (?)"
)

const (
	UserAliasIDBetween        = "users_alias.id BETWEEN ? AND ?"
	UserAliasStartAtBetween   = "users_alias.start_at BETWEEN ? AND ?"
	UserAliasEndAtBetween     = "users_alias.end_at BETWEEN ? AND ?"
	UserAliasSeqBetween       = "users_alias.seq BETWEEN ? AND ?"
	UserAliasCreatedAtBetween = "users_alias.created_at BETWEEN ? AND ?"
)

const (
	UserAliasIDNotBetween        = "users_alias.id NOT BETWEEN ? AND ?"
	UserAliasStartAtNotBetween   = "users_alias.start_at NOT BETWEEN ? AND ?"
	UserAliasEndAtNotBetween     = "users_alias.end_at NOT BETWEEN ? AND ?"
	UserAliasSeqNotBetween       = "users_alias.seq NOT BETWEEN ? AND ?"
	UserAliasCreatedAtNotBetween = "users_alias.created_at NOT BETWEEN ? AND ?"
)

const (
	UserAliasStartAtDateExpr   = "DATE(users_alias.start_at)"
	UserAliasEndAtDateExpr     = "DATE(users_alias.end_at)"
	UserAliasCreatedAtDateExpr = "DATE(users_alias.created_at)"
)

const (
	UserAliasStartAtYearExpr   = "EXTRACT(YEAR FROM users_alias.start_at)"
	UserAliasEndAtYearExpr     = "EXTRACT(YEAR FROM users_alias.end_at)"
	UserAliasCreatedAtYearExpr = "EXTRACT(YEAR FROM users_alias.created_at)"
)

const (
	UserAliasStartAtMonthExpr   = "EXTRACT(MONTH FROM users_alias.start_at)"
	UserAliasEndAtMonthExpr     = "EXTRACT(MONTH FROM users_alias.end_at)"
	UserAliasCreatedAtMonthExpr = "EXTRACT(MONTH FROM users_alias.created_at)"
)

const (
	UserAliasStartAtDayExpr   = "EXTRACT(DAY FROM users_alias.start_at)"
	UserAliasEndAtDayExpr     = "EXTRACT(DAY FROM users_alias.end_at)"
	UserAliasCreatedAtDayExpr = "EXTRACT(DAY FROM users_alias.created_at)"
)

const (
	UserAliasStartAtHourExpr   = "EXTRACT(HOUR FROM users_alias.start_at)"
	UserAliasEndAtHourExpr     = "EXTRACT(HOUR FROM users_alias.end_at)"
	UserAliasCreatedAtHourExpr = "EXTRACT(HOUR FROM users_alias.created_at)"
)

const (
	UserAliasStartAtMinuteExpr   = "EXTRACT(MINUTE FROM users_alias.start_at)"
	UserAliasEndAtMinuteExpr     = "EXTRACT(MINUTE FROM users_alias.end_at)"
	UserAliasCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM users_alias.created_at)"
)

const (
	UserAliasStartAtSecondExpr   = "EXTRACT(SECOND FROM users_alias.start_at)"
	UserAliasEndAtSecondExpr     = "EXTRACT(SECOND FROM users_alias.end_at)"
	UserAliasCreatedAtSecondExpr = "EXTRACT(SECOND FROM users_alias.created_at)"
)

const (
	UserAliasIDAsc        = "users_alias.id ASC"
	UserAliasNameAsc      = "users_alias.name ASC"
	UserAliasEmailAsc     = "users_alias.email ASC"
	UserAliasStartAtAsc   = "users_alias.start_at ASC"
	UserAliasEndAtAsc     = "users_alias.end_at ASC"
	UserAliasSeqAsc       = "users_alias.seq ASC"
	UserAliasCreatedAtAsc = "users_alias.created_at ASC"
)

const (
	UserAliasIDDesc        = "users_alias.id DESC"
	UserAliasNameDesc      = "users_alias.name DESC"
	UserAliasEmailDesc     = "users_alias.email DESC"
	UserAliasStartAtDesc   = "users_alias.start_at DESC"
	UserAliasEndAtDesc     = "users_alias.end_at DESC"
	UserAliasSeqDesc       = "users_alias.seq DESC"
	UserAliasCreatedAtDesc = "users_alias.created_at DESC"
)
