// Code generated by bake. DO NOT EDIT.
// version: v0.3.0
// source: users

// Package model defines database models generated from schema.
package model

import (
	"context"
	"time"

	"github.com/uptrace/bun"
)

var NilUser = (*User)(nil)

var (
	_ bun.BeforeInsertHook = (*User)(nil)
	_ bun.BeforeUpdateHook = (*User)(nil)
)

const UserTableName = "users"

var UserTableNameIdent  = bun.Ident("users")

const (
	UserID        = "id"
	UserName      = "name"
	UserEmail     = "email"
	UserStartAt   = "start_at"
	UserEndAt     = "end_at"
	UserSeq       = "seq"
	UserCreatedAt = "created_at"
)

const (
	UserRelationPosts = "Posts"
)

var (
	UserIDIdent        = bun.Ident("id")
	UserNameIdent      = bun.Ident("name")
	UserEmailIdent     = bun.Ident("email")
	UserStartAtIdent   = bun.Ident("start_at")
	UserEndAtIdent     = bun.Ident("end_at")
	UserSeqIdent       = bun.Ident("seq")
	UserCreatedAtIdent = bun.Ident("created_at")
)

const (
	UserIDEq        = "id = ?"
	UserNameEq      = "name = ?"
	UserEmailEq     = "email = ?"
	UserStartAtEq   = "start_at = ?"
	UserEndAtEq     = "end_at = ?"
	UserSeqEq       = "seq = ?"
	UserCreatedAtEq = "created_at = ?"
)

const (
	UserIDNeq        = "id <> ?"
	UserNameNeq      = "name <> ?"
	UserEmailNeq     = "email <> ?"
	UserStartAtNeq   = "start_at <> ?"
	UserEndAtNeq     = "end_at <> ?"
	UserSeqNeq       = "seq <> ?"
	UserCreatedAtNeq = "created_at <> ?"
)

const (
	UserIDGt        = "id > ?"
	UserStartAtGt   = "start_at > ?"
	UserEndAtGt     = "end_at > ?"
	UserSeqGt       = "seq > ?"
	UserCreatedAtGt = "created_at > ?"
)

const (
	UserIDGte        = "id >= ?"
	UserStartAtGte   = "start_at >= ?"
	UserEndAtGte     = "end_at >= ?"
	UserSeqGte       = "seq >= ?"
	UserCreatedAtGte = "created_at >= ?"
)

const (
	UserIDLt        = "id < ?"
	UserStartAtLt   = "start_at < ?"
	UserEndAtLt     = "end_at < ?"
	UserSeqLt       = "seq < ?"
	UserCreatedAtLt = "created_at < ?"
)

const (
	UserIDLte        = "id <= ?"
	UserStartAtLte   = "start_at <= ?"
	UserEndAtLte     = "end_at <= ?"
	UserSeqLte       = "seq <= ?"
	UserCreatedAtLte = "created_at <= ?"
)

const (
	UserNameLike  = "name LIKE ?"
	UserEmailLike = "email LIKE ?"
)

const (
	UserNameLikePrefix  = "name LIKE ?%"
	UserEmailLikePrefix = "email LIKE ?%"
)

const (
	UserNameLikeSuffix  = "name LIKE %?"
	UserEmailLikeSuffix = "email LIKE %?"
)

const (
	UserNameLikeContain  = "name LIKE %?%"
	UserEmailLikeContain = "email LIKE %?%"
)

const (
	UserNameConcatExpr  = "name = CONCAT(name, ?)"
	UserEmailConcatExpr = "email = CONCAT(email, ?)"
)

const (
	UserSeqSUMExpr = "SUM(seq)"
)

const (
	UserSeqAVGExpr = "AVG(seq)"
)

const (
	UserIDMINExpr        = "MIN(id)"
	UserStartAtMINExpr   = "MIN(start_at)"
	UserEndAtMINExpr     = "MIN(end_at)"
	UserSeqMINExpr       = "MIN(seq)"
	UserCreatedAtMINExpr = "MIN(created_at)"
)

const (
	UserIDMAXExpr        = "MAX(id)"
	UserStartAtMAXExpr   = "MAX(start_at)"
	UserEndAtMAXExpr     = "MAX(end_at)"
	UserSeqMAXExpr       = "MAX(seq)"
	UserCreatedAtMAXExpr = "MAX(created_at)"
)

const (
	UserSeqAddExpr = "seq = seq + ?"
)

const (
	UserSeqSubExpr = "seq = seq - ?"
)

const (
	UserSeqAddLeastExpr = "seq = LEAST(seq + ?, ?)"
)

const (
	UserSeqSubGreatestExpr = "seq = GREATEST(seq - ?, ?)"
)

const (
	UserSeqClampExpr = "seq = LEAST(GREATEST(seq + ?, ?), ?)"
)

const (
	UserIDDistinctExpr        = "DISTINCT id"
	UserNameDistinctExpr      = "DISTINCT name"
	UserEmailDistinctExpr     = "DISTINCT email"
	UserStartAtDistinctExpr   = "DISTINCT start_at"
	UserEndAtDistinctExpr     = "DISTINCT end_at"
	UserSeqDistinctExpr       = "DISTINCT seq"
	UserCreatedAtDistinctExpr = "DISTINCT created_at"
)

const (
	UserIDCountDistinctExpr        = "COUNT(DISTINCT id)"
	UserNameCountDistinctExpr      = "COUNT(DISTINCT name)"
	UserEmailCountDistinctExpr     = "COUNT(DISTINCT email)"
	UserStartAtCountDistinctExpr   = "COUNT(DISTINCT start_at)"
	UserEndAtCountDistinctExpr     = "COUNT(DISTINCT end_at)"
	UserSeqCountDistinctExpr       = "COUNT(DISTINCT seq)"
	UserCreatedAtCountDistinctExpr = "COUNT(DISTINCT created_at)"
)

const (
	UserIDIn        = "id IN (?)"
	UserNameIn      = "name IN (?)"
	UserEmailIn     = "email IN (?)"
	UserStartAtIn   = "start_at IN (?)"
	UserEndAtIn     = "end_at IN (?)"
	UserSeqIn       = "seq IN (?)"
	UserCreatedAtIn = "created_at IN (?)"
)

const (
	UserIDNotIn        = "id NOT IN (?)"
	UserNameNotIn      = "name NOT IN (?)"
	UserEmailNotIn     = "email NOT IN (?)"
	UserStartAtNotIn   = "start_at NOT IN (?)"
	UserEndAtNotIn     = "end_at NOT IN (?)"
	UserSeqNotIn       = "seq NOT IN (?)"
	UserCreatedAtNotIn = "created_at NOT IN (?)"
)

const (
	UserIDBetween        = "id BETWEEN ? AND ?"
	UserStartAtBetween   = "start_at BETWEEN ? AND ?"
	UserEndAtBetween     = "end_at BETWEEN ? AND ?"
	UserSeqBetween       = "seq BETWEEN ? AND ?"
	UserCreatedAtBetween = "created_at BETWEEN ? AND ?"
)

const (
	UserIDNotBetween        = "id NOT BETWEEN ? AND ?"
	UserStartAtNotBetween   = "start_at NOT BETWEEN ? AND ?"
	UserEndAtNotBetween     = "end_at NOT BETWEEN ? AND ?"
	UserSeqNotBetween       = "seq NOT BETWEEN ? AND ?"
	UserCreatedAtNotBetween = "created_at NOT BETWEEN ? AND ?"
)

const (
	UserStartAtDateExpr   = "DATE(start_at)"
	UserEndAtDateExpr     = "DATE(end_at)"
	UserCreatedAtDateExpr = "DATE(created_at)"
)

const (
	UserStartAtYearExpr   = "EXTRACT(YEAR FROM start_at)"
	UserEndAtYearExpr     = "EXTRACT(YEAR FROM end_at)"
	UserCreatedAtYearExpr = "EXTRACT(YEAR FROM created_at)"
)

const (
	UserStartAtMonthExpr   = "EXTRACT(MONTH FROM start_at)"
	UserEndAtMonthExpr     = "EXTRACT(MONTH FROM end_at)"
	UserCreatedAtMonthExpr = "EXTRACT(MONTH FROM created_at)"
)

const (
	UserStartAtDayExpr   = "EXTRACT(DAY FROM start_at)"
	UserEndAtDayExpr     = "EXTRACT(DAY FROM end_at)"
	UserCreatedAtDayExpr = "EXTRACT(DAY FROM created_at)"
)

const (
	UserStartAtHourExpr   = "EXTRACT(HOUR FROM start_at)"
	UserEndAtHourExpr     = "EXTRACT(HOUR FROM end_at)"
	UserCreatedAtHourExpr = "EXTRACT(HOUR FROM created_at)"
)

const (
	UserStartAtMinuteExpr   = "EXTRACT(MINUTE FROM start_at)"
	UserEndAtMinuteExpr     = "EXTRACT(MINUTE FROM end_at)"
	UserCreatedAtMinuteExpr = "EXTRACT(MINUTE FROM created_at)"
)

const (
	UserStartAtSecondExpr   = "EXTRACT(SECOND FROM start_at)"
	UserEndAtSecondExpr     = "EXTRACT(SECOND FROM end_at)"
	UserCreatedAtSecondExpr = "EXTRACT(SECOND FROM created_at)"
)

const (
	UserIDAsc        = "id ASC"
	UserNameAsc      = "name ASC"
	UserEmailAsc     = "email ASC"
	UserStartAtAsc   = "start_at ASC"
	UserEndAtAsc     = "end_at ASC"
	UserSeqAsc       = "seq ASC"
	UserCreatedAtAsc = "created_at ASC"
)

const (
	UserIDDesc        = "id DESC"
	UserNameDesc      = "name DESC"
	UserEmailDesc     = "email DESC"
	UserStartAtDesc   = "start_at DESC"
	UserEndAtDesc     = "end_at DESC"
	UserSeqDesc       = "seq DESC"
	UserCreatedAtDesc = "created_at DESC"
)

// User generates a model for the "users" table.
// 用户表
type User struct {
	bun.BaseModel `bun:"table:users,alias:users_alias"`

	ID        int64     `bun:"id,pk,autoincrement,notnull" form:"id" json:"id,omitempty"`                                     //
	Name      string    `bun:"name,notnull" form:"name" json:"name,omitempty"`                                                // 用户名
	Email     string    `bun:"email,unique,notnull" form:"email" json:"email,omitempty"`                                      // 邮箱
	StartAt   time.Time `bun:"start_at,notnull" form:"start_at" json:"start_at,omitempty"`                                    //
	EndAt     time.Time `bun:"end_at,notnull" form:"end_at" json:"end_at,omitempty"`                                          //
	Seq       int64     `bun:"seq,notnull" form:"seq" json:"seq,omitempty"`                                                   //
	CreatedAt time.Time `bun:"created_at,notnull,default:current_timestamp(3)" form:"created_at" json:"created_at,omitempty"` // 创建时间
	Posts     []*Post   `bun:"posts,join:id=user_id,rel:has-many" form:"posts" json:"posts,omitempty"`                        //
}

func (m *User) BeforeInsert(ctx context.Context, query *bun.InsertQuery) error {
	now := time.Now().UTC()
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	return nil
}
func (m *User) BeforeUpdate(ctx context.Context, query *bun.UpdateQuery) error {
	return nil
}
